### ISSUE TITLE
Procedural Macro Expansion Fails With `IOException`

### ISSUE THREAD

**Issue by HTG-YT** [intellij-rust/intellij-rust#10544]
## Environment

* **IntelliJ Rust plugin version:** 0.4.196.5401-232-nightly
* **Rust toolchain version:** 1.72.0-nightly (b2b34bd83 2023-06-06)
* **IDE name and version:** InteliJ IDEA 2023.2 EAP (Build IU-232.6734.9)
* **Operating system:** Windows 11 22H2 (Build 22621.1702)

## Problem description

The expansion of procedural macros completely fails, resulting in the following code losing syntax highlighting altogether (for attribute procedural macros):
![image](https://github.com/intellij-rust/intellij-rust/assets/39023054/f005b467-3fdb-4cb4-b6b9-e407570c9396)

## Steps to reproduce

1. Try adding code involving the usage of a procedural macro.
2. Observe that an/some IDE error(s) occurs.

A copy of the exception backtrace is attached below (1 of 9, but all are similar errors anyway):
`````
Error communicating with `intellij-rust-native-helper` process
  
  java.io.IOException: The pipe has been ended
at java.base/java.io.FileOutputStream.writeBytes(Native Method)
at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349)
at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:123)
at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:304)
at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:132)
at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:205)
at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._writeString2(WriterBasedJsonGenerator.java:1125)
at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._writeString(WriterBasedJsonGenerator.java:1094)
at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeString(WriterBasedJsonGenerator.java:430)
at org.rust.lang.core.macros.tt.FlatTreeJsonSerializer.serialize(FlatTreeJsonSerializer.kt:20)
at org.rust.lang.core.macros.proc.RequestJsonSerializer.serialize(Request.kt:32)
at org.rust.lang.core.macros.proc.RequestJsonSerializer.serialize(Request.kt:27)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719)
at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3947)
at org.rust.lang.core.macros.proc.ProcMacroServerProcess.writeAndRead(ProcMacroServerPool.kt:284)
at org.rust.lang.core.macros.proc.ProcMacroServerProcess.run(ProcMacroServerPool.kt:249)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by HTG-YT** [comment]
A similar issue has also been encountered for `rust-analyzer`: https://github.com/rust-lang/rust-analyzer/issues/15001

**Comment by HTG-YT** [comment]
After deeper investigation, this seems to be related to https://github.com/rust-lang/rust-analyzer/issues/14991.
A PR has been opened on rust-lang/rust on solving this issue: https://github.com/rust-lang/rust/pull/112339.

**Comment by HTG-YT** [comment]
Closed as of the merge of https://github.com/rust-lang/rust/pull/112339.
