### ISSUE TITLE
NPE on Intellij startup

### ISSUE THREAD

**Issue by CodeSandwich** [intellij-rust/intellij-rust#1063]
On every start up Intellij reports an NPE, but everything works fine. I know, that this issue was already closed three times and the solution is to upgrade Cargo, but I have Cargo 0.18.0-nightly and there is nothing to upgrade to yet.
```
null
kotlin.KotlinNullPointerException
	at org.rust.cargo.toolchain.impl.CargoMetadata.clean(CargoMetadata.kt:123)
	at org.rust.cargo.toolchain.Cargo.fullProjectDescription(Cargo.kt:56)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceServiceImpl$UpdateTask.run(CargoProjectWorkspaceServiceImpl.kt:209)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by matklad** [comment]
Hm, this is another error! Could you execute `cargo metadata` in the project directory in the console, and send the output here?

**Comment by CodeSandwich** [comment]
It outputted JSON with project name and path, list of packages, their resolutions, and version, which is "1", nothing special,  I'm sorry, but I can't share this output, there are some details about a company project. Are you looking for anything specific?

**Comment by alygin** [comment]
@CodeSandwich, is it possible to share only the part of the output that relates to packages and their dependencies? That would be the the list of `packages.id`'s and the `resolve.nodes` block. All paths can be removed. For instance, below is "cleaned" and shortened metadata from one of my projects.

The idea is to check if there're dependencies from the `resolve.nodes` block that point to unknown items from the `packages` block?

```json
{
    "packages": [
        { "id": "traitobject 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "staticfile 0.3.1 (path+file:///Users/andrew/Development/Workspaces/External/staticfile)" },
        { "id": "lazy_static 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "core-foundation-sys 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "mime 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "hyper 0.10.4 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "iron 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "language-tags 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "toml 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "time 0.1.36 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "matches 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "security-framework-sys 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "pkg-config 0.3.9 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "rustc_version 0.1.7 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "libc 0.2.20 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "security-framework 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "openssl 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "sequence_trie 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "idna 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "gdi32-sys 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "user32-sys 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" },
        { "id": "healthmon 0.1.0 (path+file:///bla-bla-bla)" },
        { "id": "crypt32-sys 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" },
        ...
    ],
    "resolve": {
        "nodes": [
            {
                "dependencies": [],
                "id": "traitobject 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)"
            },
            {
                "dependencies": [
                    "url 1.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
                    "mount 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)",
                    "iron 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)",
                    "time 0.1.36 (registry+https://github.com/rust-lang/crates.io-index)"
                ],
                "id": "staticfile 0.3.1 (path+file:///Users/andrew/Development/Workspaces/External/staticfile)"
            },
            {
                "dependencies": [],
                "id": "lazy_static 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)"
            },
            {
                "dependencies": [
                    "libc 0.2.20 (registry+https://github.com/rust-lang/crates.io-index)"
                ],
                "id": "core-foundation-sys 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)"
            },
            {
                "dependencies": [
                    "log 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)"
                ],
                "id": "mime 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)"
            },
            {
                "dependencies": [
                    "time 0.1.36 (registry+https://github.com/rust-lang/crates.io-index)",
                    "unicase 1.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
                    "language-tags 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)",
                    "typeable 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
                    "mime 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)"
                ],
                "id": "hyper 0.10.4 (registry+https://github.com/rust-lang/crates.io-index)"
            },
            {
                "dependencies": [
                    "url 1.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
                    "modifier 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
                    "lazy_static 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)",
                    "log 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)",
                    "num_cpus 1.2.1 (registry+https://github.com/rust-lang/crates.io-index)"
                ],
                "id": "iron 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)"
            },
            ...
        ]
    }
}
```

**Comment by matklad** [comment]
>All paths can be removed

But there's a possibility that there's something wrong with paths: for example, cargo could theoretically use relative path in one case and absolute in another one.

@CodeSandwich does the same happen with stable cargo? If it doesn't you can try to diff `cargo metadata` output from both versions. 

You can always share more info privately, my email is aleksey.kladov@gmail.com.

**Comment by CodeSandwich** [comment]
I'll check it on Monday :)

**Comment by matklad** [comment]
This should be easier to track down with https://github.com/intellij-rust/intellij-rust/commit/97a86fe76020b242778721724bfd60483ed1d456

**Comment by matklad** [comment]
(you can get a build with this commit via TeamCity: https://teamcity.jetbrains.com/repository/download/IntellijIdeaPlugins_Rust_CurrentIdea_TestsRust/.lastSuccessful/intellij-rust-0.1.0.%7Bbuild.number%7D.zip)

**Comment by CodeSandwich** [comment]
I'm sorry, but it stopped happening on Monday and didn't come back since then. I don't know, what I did, but i definitely did not touch Cargo.toml or Cago.lock. Should I close the issue?

**Comment by matklad** [comment]
Yep, let's close the issue!

There's a better error handling logic there now, which should have been implemented from the start, so there's a high change that we'll get a bug report with more information if IntelliJ Rust or Cargo are buggy.

Thanks for the the report!
