### ISSUE TITLE
No error message when failing to create project with some invalid project names

### ISSUE THREAD

**Issue by ljchen1** [intellij-rust/intellij-rust#10771]
## Environment

* **IntelliJ Rust plugin version:**
0.4.18
* **IDE name and version:**
IDEA 2023.2
* **Operating system:**
Linux

## Problem description
When I create a Rust project named `match` in IDEA's project wizard, IDEA fails to create it and doesn't open it.

## Steps to reproduce
Create a Rust project with `match` name.

Result:
The project wizard dialog disappears but the IDEA doesn't open this project. Also, it shows the below exception in the log.

Expected:
The project wizard shows an error advising the name is wrong.

```
2023-08-01 12:30:49,090 [  10164] SEVERE - #org.rust.ide.module.RsModuleBuilder - Execution failed (exit code 101).
/usr/bin/cargo init --bin --name match --vcs none /home/username/IdeaProjects/match
stdout : error: the name `match` cannot be used as a package name, it is a Rust keyword
If you need a binary with the name "match", use a valid package name, and set the binary name to be different from the package. This can be done by setting the binary filename to `src/bin/match.rs` or change the name in Cargo.toml with:

    [[bin]]
    name = "match"
    path = "src/main.rs"


stderr : 
org.rust.openapiext.RsProcessExecutionException$ProcessAborted: Execution failed (exit code 101).
/usr/bin/cargo init --bin --name match --vcs none /home/username/IdeaProjects/match
stdout : error: the name `match` cannot be used as a package name, it is a Rust keyword
If you need a binary with the name "match", use a valid package name, and set the binary name to be different from the package. This can be done by setting the binary filename to `src/bin/match.rs` or change the name in Cargo.toml with:

    [[bin]]
    name = "match"
    path = "src/main.rs"


stderr : 
	at org.rust.openapiext.CommandLineExtKt.execute(CommandLineExt.kt:112)
	at org.rust.openapiext.CommandLineExtKt.execute$default(CommandLineExt.kt:55)
	at org.rust.cargo.toolchain.tools.Cargo.execute(Cargo.kt:551)
	at org.rust.cargo.toolchain.tools.Cargo.execute$default(Cargo.kt:545)
	at org.rust.cargo.toolchain.tools.Cargo.init(Cargo.kt:410)
	at org.rust.ide.newProject.UtilsKt.makeProject(Utils.kt:36)
	at org.rust.ide.module.RsModuleBuilder.createProject(RsModuleBuilder.kt:63)
	at org.rust.ide.newProject.RsNewProjectWizard$Step$setupProject$1.invoke(RsNewProjectWizard.kt:50)
	at org.rust.ide.newProject.RsNewProjectWizard$Step$setupProject$1.invoke(RsNewProjectWizard.kt:48)
	at org.rust.ide.newProject.RsNewProjectWizard$Step.setupProject$lambda$1(RsNewProjectWizard.kt:48)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.lambda$updateModel$9(ModuleRootModificationUtil.java:152)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.modifyModel(ModuleRootModificationUtil.java:160)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:151)
	at org.rust.ide.newProject.RsNewProjectWizard$Step.setupProject(RsNewProjectWizard.kt:48)
	at com.intellij.ide.wizard.AbstractNewProjectWizardMultiStepBase.setupProject(AbstractNewProjectWizardMultiStepBase.kt:75)
	at com.intellij.ide.wizard.NewProjectWizardLanguageStep.setupProject(NewProjectWizardLanguageStep.kt:93)
	at com.intellij.ide.wizard.NewProjectWizardChainStep.setupProject(NewProjectWizardChainStep.kt:44)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$commitModule$1.invoke(AbstractNewProjectWizardBuilder.kt:44)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$commitModule$1.invoke(AbstractNewProjectWizardBuilder.kt:43)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$Companion.detectCreatedModule(AbstractNewProjectWizardBuilder.kt:80)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$Companion.detectCreatedModule(AbstractNewProjectWizardBuilder.kt:68)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder$Companion.access$detectCreatedModule(AbstractNewProjectWizardBuilder.kt:65)
	at com.intellij.ide.wizard.AbstractNewProjectWizardBuilder.commitModule(AbstractNewProjectWizardBuilder.kt:43)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commit(ModuleBuilder.java:342)
	at com.intellij.ide.impl.NewProjectUtil.doCreate(NewProjectUtil.kt:155)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.kt:84)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard$default(NewProjectUtil.kt:82)
	at com.intellij.ide.impl.NewProjectUtil.createNewProject(NewProjectUtil.kt:69)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:24)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:300)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:293)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:68)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:115)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:115)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:791)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:762)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-08-01 12:30:49,093 [  10167] SEVERE - #org.rust.ide.module.RsModuleBuilder - IntelliJ IDEA 2023.2  Build #IU-232.8660.185
2023-08-01 12:30:49,093 [  10167] SEVERE - #org.rust.ide.module.RsModuleBuilder - JDK: 17.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-08-01 12:30:49,093 [  10167] SEVERE - #org.rust.ide.module.RsModuleBuilder - OS: Linux
2023-08-01 12:30:49,093 [  10167] SEVERE - #org.rust.ide.module.RsModuleBuilder - Plugin to blame: Rust version: 0.4.199.5415-232
```

**Comment by Maksim20023** [comment]
Hi! Thank you for your report.
I opened your project and observed the same behavior as in the description. And not only code completion but also the rest of IDE functions like syntax highlighting or line commenting were slow.
I forwarded this issue to our development team for investigating. However, at the moment, we don’t have an estimated time for when the issue will be completely resolved. When we have any new information about this issue, we will add a reply to this ticket. If you have any further suggestions, please feel free to reach out.
