### ISSUE TITLE
Syntax highlighting broken in 2023.3 nightly version of IDEs

### ISSUE THREAD

**Issue by ChristianIvicevic** [intellij-rust/intellij-rust#10803]
## Environment

* **IntelliJ Rust plugin version:** 0.4.200.5421-232
* **Rust toolchain version:** 1.72.0-nightly (839e9a6e1 2023-07-02) aarch64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2023.3 EAP Ultimate Edition (IU-233.3589)
* **Operating system:** macOS 13.5
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.macros.proc.attr

## Problem description

Using the current nightly versions of our IDEs causes the syntax highlighting to break and not highlighting anything but a few basic keywords.

![CleanShot 2023-08-10 at 09 03 48](https://github.com/intellij-rust/intellij-rust/assets/45569997/a445164a-b95f-48f1-be98-3c82b7638204)

The stacktrace for the error is the following:

```
java.lang.ClassCastException: class com.intellij.lang.annotation.AnnotationSession cannot be cast to class com.intellij.openapi.util.UserDataHolderEx (com.intellij.lang.annotation.AnnotationSession and com.intellij.openapi.util.UserDataHolderEx are in unnamed module of loader com.intellij.util.lang.PathClassLoader @5f150435)
	at org.rust.ide.annotator.AnnotationSessionExKt.currentCrate(AnnotationSessionEx.kt:23)
	at org.rust.ide.annotator.AnnotationSessionExKt.currentCrate(AnnotationSessionEx.kt:32)
	at org.rust.ide.annotator.RsCfgDisabledCodeAnnotator$Companion.shouldHighlightAsCfsDisabled(RsCfgDisabledCodeAnnotator.kt:36)
	at org.rust.ide.annotator.RsMacroExpansionHighlightingPass.doCollectInformation(RsMacroExpansionHighlightingPass.kt:123)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:395)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:76)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:390)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1073)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:381)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:380)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:356)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:354)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

## Steps to reproduce

```toml
[package]
name = "reproduction"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
```

```rust
// lib.rs
use wasm_bindgen::prelude::wasm_bindgen;

#[wasm_bindgen]
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[wasm_bindgen]
pub fn sub(left: isize, right: isize) -> isize {
    left - right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
```

**Comment by Maksim20023** [comment]
Hi! Thank you for the report.
The Rust plugin 0.4.200.5421.232 version is incompatible with the 2023.3 version of IDE's. Please see the Compatibility Range on this page https://plugins.jetbrains.com/plugin/8182-rust/versions/stable. You can use this version only with the 2023.2 version of IDE (edited)
