### ISSUE TITLE
The bundled debugger crashes when trying to run it on library tests

### ISSUE THREAD

**Issue by lilianmoraru** [intellij-rust/intellij-rust#1098]
CLion: Build #CL-171.3780.103, built on March 21, 2017
JRE: 1.8.0_112-release-736-b13 amd64
IntelliJ Rust: 0.1.0.1773

I am trying to run the debugger and it crashes with the same issue, however I try to run it.
```
The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 11,4,main]
java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 11,4,main]
	at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2086)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1245)
	at com.intellij.openapi.ui.Messages$MessageDialog._init(Messages.java:1388)
	at com.intellij.openapi.ui.Messages$MessageDialog.<init>(Messages.java:1313)
	at com.intellij.openapi.ui.Messages.showIdeaMessageDialog(Messages.java:187)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:174)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:143)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:691)
	at org.rust.debugger.runconfig.RsDebugRunnerKt.showErrorDialog(RsDebugRunner.kt:176)
	at org.rust.debugger.runconfig.RsDebugRunnerKt.access$showErrorDialog(RsDebugRunner.kt:1)
	at org.rust.debugger.runconfig.RsDebugRunnerKt$buildProjectAndGetBinaryArtifactPath$1$1$1.run(RsDebugRunner.kt:145)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

If this doesn't help, the project is on Github, I can point to it.

**Comment by lilianmoraru** [comment]
Seems to me like it is failing here(I have not looked through the code, just stacktraces):
```
at org.rust.debugger.runconfig.RsDebugRunnerKt$buildProjectAndGetBinaryArtifactPath$1$1$1.run(RsDebugRunner.kt:145)
```
It might be relevant: I have a library and I try to run it on a test.

**Comment by matklad** [comment]
The crux of the problem is that when you run `cargo test`, cargo will potentially a whole bunch of binaries, and we can't attach debugger to more than one binary. 

Originally, I've implemented a dialog which would ask which of the binaries to debug (and I've obviously messed up action system along the way :) ), but now I think it was a bad solution: it's better just to rise an error and to ask the user to provide `--bin`, `--test` or `--lib` argument (we should do this automatically if you run "configuration from context").
