### ISSUE TITLE
Exception in plugin Rust. . .NoSuchFieldError: Companion

### ISSUE THREAD

**Issue by hgallagher1993** [intellij-rust/intellij-rust#1101]
I'm on the latest release and this appears consistently in the event window even if I so much as click in the editor window. The full message is:

Companion
java.lang.NoSuchFieldError: Companion
	at org.rust.cargo.runconfig.test.CargoTestRunLineMarkerContributor.getInfo(CargoTestRunLineMarkerContributor.kt:18)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:50)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.addLineMarkers(LineMarkersPass.java:178)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:111)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:427)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by hgallagher1993** [comment]
Not sure if it's related or if I should open another issue but the performance has seriously regressed in the last release or 2. Code completetion has started taking a very long to...complete, even just code highlighting like the `#[test]`s in my current file could take upwards of a minute to highlight yellow from when I first open Intellij.

**Comment by matklad** [comment]
>I'm on the latest release and this appears consistently in the event window even if I so much as click in the editor window. 

Yep, unfortunately a binary incompatibility issue has slipped into the last alpha release. I've scheduled another alpha which should not not have this issue, it should be ready soon. Alternatively, you can upgrade to 2017.1 version of the IDE.

>Not sure if it's related or if I should open another issue but the performance has seriously regressed in the last release or 2. Code completetion has started taking a very long to...complete, even just code highlighting like the #[test]s in my current file could take upwards of a minute to highlight yellow from when I first open Intellij.

Hm, that is most likely not related. It would be helpful to open another issue. Does this happen with all projects? Is there some specific code pattern that causes slowness?

**Comment by hgallagher1993** [comment]
Probably should have done it before I made this issue but I went ahead and uninstalled the plugin and then reinstalled and the performance is back to normal. It was only a tiny project I was working on so I went and tried it with something bigger as well and opened Webrender and auto completion and everything (apart from the original NoSuchFieldError: Companion ) is perfect again.

I am actually on an older version of Intellij so I'll use this as a reason to finally upgrade to 2017.1

**Comment by matklad** [comment]
Alpha is out, so you can update just the plugin instead of upgrading the whole IDE :) 

>Probably should have done it before I made this issue but I went ahead and uninstalled the plugin and then reinstalled and the performance is back to normal. 

Glad to here that! Although probably there was some problem on our side. If you see something suspicions again, please create an issue ;) 

By the way, you can always downgrade the plugin, previous releases are here: https://plugins.jetbrains.com/plugin/8182-rust

Closing!

**Comment by matklad** [comment]
>instead of upgrading the whole IDE :)

But we are dropping support for 2016.2 next week!

**Comment by hgallagher1993** [comment]
Upgraded to 2017.1 and everything is working fine now, thanks for the help :smile:
