### ISSUE TITLE
Exception / Fatal Error

### ISSUE THREAD

**Issue by seeekr** [intellij-rust/intellij-rust#1322]
Just reporting this in here real quick in case it is helpful. Not sure what other info to add. (Latest plugin version.)

```
Index: 2, Size: 2
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at com.intellij.util.SmartList.get(SmartList.java:66)
	at org.rust.lang.core.types.infer.DeclarationsKt.inferTypeForLambdaExpr(Declarations.kt:74)
	at org.rust.lang.core.types.infer.DeclarationsKt.inferTypeForLambdaParameter(Declarations.kt:95)
	at org.rust.lang.core.types.infer.DeclarationsKt.inferDeclarationType(Declarations.kt:38)
	at org.rust.lang.core.types.infer.ExpressionsKt.inferExpressionType(Expressions.kt:16)
	at org.rust.lang.core.types.ExtensionsKt$type$3$type$1.compute(Extensions.kt:43)
	at org.rust.lang.core.types.ExtensionsKt$type$3$type$1.compute(Extensions.kt)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at org.rust.ide.utils.PlatformUtilsKt.recursionGuard(PlatformUtils.kt:11)
	at org.rust.ide.utils.PlatformUtilsKt.recursionGuard$default(PlatformUtils.kt:10)
	at org.rust.lang.core.types.ExtensionsKt$type$3.compute(Extensions.kt:43)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at org.rust.lang.core.types.ExtensionsKt.getType(Extensions.kt:42)
	at org.rust.lang.core.types.infer.ExpressionsKt.addTypeMapping(Expressions.kt:322)
	at org.rust.lang.core.types.infer.ExpressionsKt.mapTypeParameters(Expressions.kt:317)
	at org.rust.lang.core.types.infer.ExpressionsKt.inferExpressionType(Expressions.kt:54)
	at org.rust.lang.core.types.ExtensionsKt$type$3$type$1.compute(Extensions.kt:43)
	at org.rust.lang.core.types.ExtensionsKt$type$3$type$1.compute(Extensions.kt)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at org.rust.ide.utils.PlatformUtilsKt.recursionGuard(PlatformUtils.kt:11)
	at org.rust.ide.utils.PlatformUtilsKt.recursionGuard$default(PlatformUtils.kt:10)
	at org.rust.lang.core.types.ExtensionsKt$type$3.compute(Extensions.kt:43)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at org.rust.lang.core.types.ExtensionsKt.getType(Extensions.kt:42)
	at org.rust.lang.core.resolve.NameResolutionKt.processMethodCallExprResolveVariants(NameResolution.kt:76)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImpl$resolveInner$1.invoke(RsMethodCallReferenceImpl.kt:20)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImpl$resolveInner$1.invoke(RsMethodCallReferenceImpl.kt:9)
	at org.rust.lang.core.resolve.ProcessorsKt.collectResolveVariants(Processors.kt:46)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImpl.resolveInner(RsMethodCallReferenceImpl.kt:20)
	at org.rust.lang.core.resolve.ref.RsReferenceBase$Resolver.resolve(RsReferenceBase.kt:63)
	at org.rust.lang.core.resolve.ref.RsReferenceBase$Resolver.resolve(RsReferenceBase.kt:61)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:220)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.advancedCachedMultiResolve(RsReferenceBase.kt:37)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.multiResolve(RsReferenceBase.kt:30)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.resolve(RsReferenceBase.kt:24)
	at org.rust.ide.annotator.RsRecursiveCallLineMarkerProvider.isRecursive(RsRecursiveCallLineMarkerProvider.kt:53)
	at org.rust.ide.annotator.RsRecursiveCallLineMarkerProvider.collectSlowLineMarkers(RsRecursiveCallLineMarkerProvider.kt:30)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:212)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:250)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by farodin91** [comment]
I'm working on lambda expr. Could you give a code sample?

**Comment by burjui** [comment]
Got this error when typing "r" at the end of a lambda:
```
fn f() -> u8 {
    f(|left, right| left + r
}
```
It's the whole test case, nothing else in the file except this function.

**Comment by seeekr** [comment]
(Forgot to comment, but I couldn't find the code in question any more, so I don't have another sample to add, sorry. Will come back if I find another issue here.)
