### ISSUE TITLE
Cargo check annotation NPE

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1341]
```
null
java.lang.NullPointerException
	at org.rust.cargo.toolchain.CargoTopMessage$Companion.fromJson(CargoMessage.kt:15)
	at org.rust.ide.annotator.CargoCheckAnnotationResult.<init>(RsCargoCheckAnnotator.kt:47)
	at org.rust.ide.annotator.RsCargoCheckAnnotator.checkProject(RsCargoCheckAnnotator.kt:202)
	at org.rust.ide.annotator.RsCargoCheckAnnotator$getCachedResult$1.compute(RsCargoCheckAnnotator.kt:55)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at org.rust.ide.annotator.RsCargoCheckAnnotator.doAnnotate(RsCargoCheckAnnotator.kt:66)
	at org.rust.ide.annotator.RsCargoCheckAnnotator.doAnnotate(RsCargoCheckAnnotator.kt:51)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:224)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:48)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:172)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.util.Alarm$Request.run(Alarm.java:396)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by matklad** [comment]
Should be worked around by https://github.com/intellij-rust/intellij-rust/pull/1345 and fixed by https://github.com/intellij-rust/intellij-rust/pull/1348.

Thanks for the report!
