### ISSUE TITLE
java.lang.NumberFormatException: For input string: "1departure_code"

### ISSUE THREAD

**Issue by LooMaclin** [intellij-rust/intellij-rust#1423]
```
For input string: "1departure_code"
java.lang.NumberFormatException: For input string: "1departure_code"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.rust.lang.core.types.infer.ExpressionsKt.inferFieldExprType(Expressions.kt:91)
	at org.rust.lang.core.types.infer.ExpressionsKt.inferExpressionType(Expressions.kt:24)
	at org.rust.lang.core.types.ExtensionsKt$type$3$type$1.compute(Extensions.kt:48)
	at org.rust.lang.core.types.ExtensionsKt$type$3$type$1.compute(Extensions.kt)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at org.rust.ide.utils.PlatformUtilsKt.recursionGuard(PlatformUtils.kt:16)
	at org.rust.ide.utils.PlatformUtilsKt.recursionGuard$default(PlatformUtils.kt:15)
	at org.rust.lang.core.types.ExtensionsKt$type$3.compute(Extensions.kt:48)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:141)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:87)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:140)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at org.rust.lang.core.types.ExtensionsKt.getType(Extensions.kt:47)
	at org.rust.ide.template.postfix.UtilsKt.isBool(utils.kt:65)
	at org.rust.ide.template.postfix.AssertPostfixTemplateBase$1.invoke(stringBasedPostfixTemplates.kt:20)
	at org.rust.ide.template.postfix.AssertPostfixTemplateBase$1.invoke(stringBasedPostfixTemplates.kt:17)
	at org.rust.ide.template.postfix.RsTopMostInScopeSelector.hasExpression(utils.kt:47)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateWithExpressionSelector.isApplicable(PostfixTemplateWithExpressionSelector.java:54)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.lambda$createIsApplicationTemplateFunction$4(PostfixLiveTemplate.java:273)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.getLookupElements(PostfixLiveTemplate.java:212)
	at com.intellij.codeInsight.template.CustomLiveTemplateBase.addCompletions(CustomLiveTemplateBase.java:53)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.showCustomLiveTemplates(LiveTemplateCompletionContributor.java:155)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.access$200(LiveTemplateCompletionContributor.java:48)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:96)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:831)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$600(CompletionProgressIndicator.java:93)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:813)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Undin** [comment]
@matklad I'll fix it
