### ISSUE TITLE
IOOBE: RsCargoCheckAnnotator

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1425]
```
Wrong line: 155. Available lines count: 140
java.lang.IndexOutOfBoundsException: Wrong line: 155. Available lines count: 140
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:200)
	at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:185)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:909)
	at org.rust.ide.annotator.RsCargoCheckAnnotator$createAnnotation$1.invoke(RsCargoCheckAnnotator.kt:161)
	at org.rust.ide.annotator.RsCargoCheckAnnotator.createAnnotation(RsCargoCheckAnnotator.kt:166)
	at org.rust.ide.annotator.RsCargoCheckAnnotator.apply(RsCargoCheckAnnotator.kt:116)
	at org.rust.ide.annotator.RsCargoCheckAnnotator.apply(RsCargoCheckAnnotator.kt:60)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.applyRelevant(ExternalToolPass.java:204)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$700(ExternalToolPass.java:48)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:178)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:174)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.util.Alarm$Request.run(Alarm.java:396)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by matklad** [comment]
Thanks for the report! closed by #1426
