### ISSUE TITLE
SOE

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1523]
```null
java.lang.StackOverflowError
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.handleError(FSRecords.java)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.access$000(FSRecords.java:163)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getParents(FSRecords.java:1151)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:951)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileByIdIfCached(PersistentFSImpl.java:943)
	at com.intellij.util.indexing.IndexInfrastructure.findFileByIdIfCached(IndexInfrastructure.java:145)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:327)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:615)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:603)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:62)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:360)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at org.rust.lang.core.resolve.indexes.RsImplIndex$Companion.findImpls(RsImplIndex.kt:56)
	at org.rust.lang.core.resolve.ImplLookup.findSimpleImpls(ImplLookup.kt:124)
	at org.rust.lang.core.resolve.ImplLookup.rawFindImplsAndTraits(ImplLookup.kt:86)
	at org.rust.lang.core.resolve.ImplLookup.findImplsAndTraits(ImplLookup.kt:63)
	at org.rust.lang.core.types.ty.TyTypeParameter.canUnifyWith(TyTypeParameter.kt:29)
	at org.rust.lang.core.types.ty.TyTypeParameter.canUnifyWith(TyTypeParameter.kt:34)
	at org.rust.lang.core.types.ty.TyStructOrEnumBase$DefaultImpls.canUnifyWith(TyStructOrEnum.kt:31)
	at org.rust.lang.core.types.ty.TyStruct.canUnifyWith(TyStructOrEnum.kt:35)
	at org.rust.lang.core.resolve.ImplLookup.remapTypeParameters(ImplLookup.kt:143)
	at org.rust.lang.core.resolve.ImplLookup.findSimpleImpls(ImplLookup.kt:125)
	at org.rust.lang.core.resolve.ImplLookup.rawFindImplsAndTraits(ImplLookup.kt:86)
	at org.rust.lang.core.resolve.ImplLookup.findImplsAndTraits(ImplLookup.kt:63)
	at org.rust.lang.core.types.ty.TyTypeParameter.canUnifyWith(TyTypeParameter.kt:29)
	at org.rust.lang.core.types.ty.TyTypeParameter.canUnifyWith(TyTypeParameter.kt:34)
	at org.rust.lang.core.types.ty.TyStructOrEnumBase$DefaultImpls.canUnifyWith(TyStructOrEnum.kt:31)
	at org.rust.lang.core.types.ty.TyStruct.canUnifyWith(TyStructOrEnum.kt:35)
	at org.rust.lang.core.resolve.ImplLookup.remapTypeParameters(ImplLookup.kt:143)
	at org.rust.lang.core.resolve.ImplLookup.findSimpleImpls(ImplLookup.kt:125)
	at org.rust.lang.core.resolve.ImplLookup.rawFindImplsAndTraits(ImplLookup.kt:86)
	at org.rust.lang.core.resolve.ImplLookup.findImplsAndTraits(ImplLookup.kt:63)
	at org.rust.lang.core.types.ty.TyTypeParameter.canUnifyWith(TyTypeParameter.kt:29)
	at org.rust.lang.core.types.ty.TyTypeParameter.canUnifyWith(TyTypeParameter.kt:34)
	at 
```

**Comment by farodin91** [comment]
@vlad20012 I think we need to limit the recursive type interference.

**Comment by farodin91** [comment]
I'm not sure. Getting the same error on the latest master.
```
null
java.lang.StackOverflowError
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findViewProvider(FileManagerImpl.java:210)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:396)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:188)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:64)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:53)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:331)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:615)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:603)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:62)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:360)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at org.rust.lang.core.resolve.indexes.RsImplIndex$Companion.findImpls(RsImplIndex.kt:56)
	at org.rust.lang.core.resolve.ImplLookup.findSimpleImpls(ImplLookup.kt:126)
	at org.rust.lang.core.resolve.ImplLookup.rawFindImplsAndTraits(ImplLookup.kt:88)
	at org.rust.lang.core.resolve.ImplLookup.findImplsAndTraits(ImplLookup.kt:65)
	at org.rust.lang.core.types.ty.TyTypeParameter.canUnifyWith(TyTypeParameter.kt:29)
	at org.rust.lang.core.types.ty.TyTypeParameter.canUnifyWith(TyTypeParameter.kt:35)
	at org.rust.lang.core.types.ty.TyStructOrEnumBase$DefaultImpls.canUnifyWith(TyStructOrEnum.kt:31)
	at org.rust.lang.core.types.ty.TyStruct.canUnifyWith(TyStructOrEnum.kt:35)
	at org.rust.lang.core.resolve.ImplLookup.remapTypeParameters(ImplLookup.kt:145)
	at org.rust.lang.core.resolve.ImplLookup.findSimpleImpls(ImplLookup.kt:127)
	at org.rust.lang.core.resolve.ImplLookup.rawFindImplsAndTraits(ImplLookup.kt:88)
	at org.rust.lang.core.resolve.ImplLookup.findImplsAndTraits(ImplLookup.kt:65)
	at org.rust.lang.core.types.ty.TyTypeParameter.canUnifyWith(TyTypeParameter.kt:29)
	at org.rust.lang.core.types.ty.TyTypeParameter.canUnifyWith(TyTypeParameter.kt:35)
	at org.rust.lang.core.types.ty.TyStructOrEnumBase$DefaultImpls.canUnifyWith(TyStructOrEnum.kt:31)
	at org.rust.lang.core.types.ty.TyStruct.canUnifyWith(TyStructOrEnum.kt:35)
	at org.rust.lang.core.resolve.ImplLookup.remapTypeParameters(ImplLookup.kt:145)
	at org.rust.lang.core.resolve.ImplLookup.findSimpleImpls(ImplLookup.kt:127)
	at org.rust.lang.core.resolve.ImplLookup.rawFindImplsAndTraits(ImplLookup.kt:88)
	at org.rust.lang.core.resolve.ImplLookup.findImplsAndTraits(ImplLookup.kt:65)
	at org.rust.lang.core.types.ty.TyTypeParameter.canUnifyWith(TyTypeParameter.kt:29)
	at org.rust.lang.core.types.ty.TyTypeParameter.canUnifyWith(TyTypeParameter.kt:35)
	at 
```

**Comment by vlad20012** [comment]
Hmm, can't reproduce anywhere. Could you please tell the Rust project in which the error occurs?

**Comment by farodin91** [comment]
ruma/ruma

**Comment by vlad20012** [comment]
Ok, I've reproduced it. Thanks :)

**Comment by vlad20012** [comment]
I've tested it with ruma, and it seems to work now.

**Comment by farodin91** [comment]
Thank you. It seems to work for me to.
