### ISSUE TITLE
Intellij sometimes starts doing a huge amount of work spinning the cpu at 400% for ~30seconds

### ISSUE THREAD

**Issue by jrmuizel** [intellij-rust/intellij-rust#1659]
This perhaps a sample of the work that's being done:
<details>
	at java.util.AbstractList$Itr.next(AbstractList.java:358)
	at com.intellij.psi.util.PsiTreeUtil.getStubChildOfType(PsiTreeUtil.java:420)
	at org.rust.lang.core.psi.impl.RsUseItemImpl.getUseGlobList(RsUseItemImpl.java:56)
	at org.rust.lang.core.resolve.NameResolutionKt.processItemDeclarations(NameResolution.kt:582)
	at org.rust.lang.core.resolve.NameResolutionKt.processNestedScopesUpwards(NameResolution.kt:749)
	at org.rust.lang.core.resolve.NameResolutionKt.processPathResolveVariants(NameResolution.kt:238)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$resolveInner$result$1.invoke(RsPathReferenceImpl.kt:33)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$resolveInner$result$1.invoke(RsPathReferenceImpl.kt:23)
	at org.rust.lang.core.resolve.ProcessorsKt.collectResolveVariants(Processors.kt:51)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.resolveInner(RsPathReferenceImpl.kt:32)
	at org.rust.lang.core.resolve.ref.RsReferenceBase$Resolver.resolve(RsReferenceBase.kt:69)
	at org.rust.lang.core.resolve.ref.RsReferenceBase$Resolver.resolve(RsReferenceBase.kt:67)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:142)
	at com.intellij.psi.impl.source.resolve.ResolveCache$$Lambda$1091/1902370573.compute(Unknown Source)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:220)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.advancedCachedMultiResolve(RsReferenceBase.kt:43)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.advancedResolve(RsReferenceBase.kt:33)
	at org.rust.lang.core.psi.ext.RsTraitRefKt.getResolveToBoundTrait(RsTraitRef.kt:16)
	at org.rust.lang.core.psi.ext.RsImplItemImplMixin.getImplementedTrait(RsImplItem.kt:32)
	at org.rust.lang.core.resolve.ImplLookup.remapTypeParameters(ImplLookup.kt:162)
	at org.rust.lang.core.resolve.ImplLookup.findSimpleImpls(ImplLookup.kt:144)
	at org.rust.lang.core.resolve.ImplLookup.rawFindImplsAndTraits(ImplLookup.kt:80)
	at org.rust.lang.core.resolve.ImplLookup.findImplsAndTraits(ImplLookup.kt:62)
	at org.rust.lang.core.types.ty.TyTypeParameter.unifyWith(TyTypeParameter.kt:31)
	at org.rust.lang.core.types.ty.TyStructOrEnumBase$DefaultImpls.unifyWith(TyStructOrEnum.kt:25)
	at org.rust.lang.core.types.ty.TyStruct.unifyWith(TyStructOrEnum.kt:32)
	at org.rust.lang.core.resolve.ImplLookup.remapTypeParameters(ImplLookup.kt:161)
	at org.rust.lang.core.resolve.ImplLookup.findSimpleImpls(ImplLookup.kt:144)
	at org.rust.lang.core.resolve.ImplLookup.rawFindImplsAndTraits(ImplLookup.kt:80)
	at org.rust.lang.core.resolve.ImplLookup.findImplsAndTraits(ImplLookup.kt:62)
	at org.rust.lang.core.resolve.ImplLookup.findImplOfTrait(ImplLookup.kt:190)
	at org.rust.lang.core.resolve.ImplLookup.findDerefTarget(ImplLookup.kt:194)
	at org.rust.lang.core.resolve.ImplLookup.derefTransitively(ImplLookup.kt:181)
	at org.rust.lang.core.resolve.NameResolutionKt.processMethodDeclarationsWithDeref(NameResolution.kt:423)
	at org.rust.lang.core.resolve.NameResolutionKt.processMethodCallExprResolveVariants(NameResolution.kt:85)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImplKt$resolveMethodCallReferenceWithReceiverType$result$1.invoke(RsMethodCallReferenceImpl.kt:72)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImplKt$resolveMethodCallReferenceWithReceiverType$result$1.invoke(RsMethodCallReferenceImpl.kt)
	at org.rust.lang.core.resolve.ProcessorsKt.collectResolveVariants(Processors.kt:51)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImplKt.resolveMethodCallReferenceWithReceiverType(RsMethodCallReferenceImpl.kt:71)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferMethodCallExprType(TypeInference.kt:220)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferDotExprType(TypeInference.kt:260)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType(TypeInference.kt:110)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType$default(TypeInference.kt:99)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferDotExprType(TypeInference.kt:256)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType(TypeInference.kt:110)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType$default(TypeInference.kt:99)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferDotExprType(TypeInference.kt:256)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType(TypeInference.kt:110)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType$default(TypeInference.kt:99)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferBinaryExprType(TypeInference.kt:372)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType(TypeInference.kt:119)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType$default(TypeInference.kt:99)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.processStatement(TypeInference.kt:95)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType(TypeInference.kt:82)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType$default(TypeInference.kt:80)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferBlockType(TypeInference.kt:78)
	at org.rust.lang.core.types.infer.RsInferenceContext.infer(TypeInference.kt:35)
	at org.rust.lang.core.types.infer.TypeInferenceKt.inferTypesIn(TypeInference.kt:23)
	at org.rust.lang.core.types.ExtensionsKt$inferenceContext$1.compute(Extensions.kt:40)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.util.CachedValuesManager$$Lambda$1082/1502762013.compute(Unknown Source)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at org.rust.lang.core.types.ExtensionsKt.getInferenceContext(Extensions.kt:39)
	at org.rust.lang.core.types.ExtensionsKt.getInferenceContext(Extensions.kt:87)
	at org.rust.lang.core.types.ExtensionsKt.getType(Extensions.kt:47)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImpl.resolveInner(RsMethodCallReferenceImpl.kt:35)
	at org.rust.lang.core.resolve.ref.RsReferenceBase$Resolver.resolve(RsReferenceBase.kt:69)
	at org.rust.lang.core.resolve.ref.RsReferenceBase$Resolver.resolve(RsReferenceBase.kt:67)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:142)
	at com.intellij.psi.impl.source.resolve.ResolveCache$$Lambda$1091/1902370573.compute(Unknown Source)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:220)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.advancedCachedMultiResolve(RsReferenceBase.kt:43)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.multiResolve(RsReferenceBase.kt:36)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.resolve(RsReferenceBase.kt:30)
	at org.rust.ide.utils.CallInfo$Companion.resolve(CallInfo.kt:32)
	at org.rust.ide.hints.RsArgumentsDescription$Companion.findDescription(RsParameterInfoHandler.kt:140)
	at org.rust.ide.hints.RsParameterInfoHandler.showParameterInfo(RsParameterInfoHandler.kt:52)
	at org.rust.ide.hints.RsParameterInfoHandler.showParameterInfo(RsParameterInfoHandler.kt:22)
	at com.intellij.codeInsight.hint.ShowParameterInfoHandler.invoke(ShowParameterInfoHandler.java:125)
	at com.intellij.codeInsight.AutoPopupController.lambda$autoPopupParameterInfo$3(AutoPopupController.java:191)
	at com.intellij.codeInsight.AutoPopupController$$Lambda$1702/2080252129.run(Unknown Source)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$null$5(PsiDocumentManagerBase.java:574)
	at com.intellij.psi.impl.PsiDocumentManagerBase$$Lambda$790/91317889.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</details>

Is there a better way to profile intellij during these situations?

**Comment by matklad** [comment]
>Is there a better way to profile intellij during these situations?

Yep, a CPU snapshot (Tools menu > Start CPU Usage Profiling) will be useful!

**Comment by vlad20012** [comment]
Is it fixed now?

**Comment by jrmuizel** [comment]
I haven't noticed it recently but haven't been using intellij as much recently.

**Comment by vlad20012** [comment]
Ok, really I think it's foxed, so I close the issue for now. Reopen it if it will happen again.
