### ISSUE TITLE
StackOverflow in name resolution

### ISSUE THREAD

**Issue by josephDunne** [intellij-rust/intellij-rust#1669]
Hi, is there a way to get logs from the rust plugin? I am trying to debug an issue where plugin seems to only half analyse some files - syntax highlighting only part of a file, no code completion in file, not clearing any error highlights that have been fixed, and jump to declaration doesn't work if the target function is in one of this half analysed files. What is the typical debug flow? I know you can dump memory/thread data from java etc but I'm not setup to analyse those but I am hopping there might be error logs :-)

**Comment by matklad** [comment]
Hi!

There's an action called "Show Log in File Manager" to get IDE logs (more docs here https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files). But we log only our interaction with external stuff like Cargo and rustup, and "partially highlighed" file does not seem like a Cargo problem...

>What is the typical debug flow?

Usually it's better just to create a reproducible example and share it, because there are a lot of different subsystems in the plugin, and it's pretty hard to guess what exactly when wrong. 

>I am trying to debug an issue where plugin seems to only half analyse some files - syntax highlighting only part of a file, no code completion in file, not clearing any error highlights that have been fixed, and jump to declaration doesn't work if the target function is in one of this half analysed files. 

And that seems puzzling! Is CPU at 100% for those half-analysed files? Off the top of my head, the only reason the analysis could break half-way is if it enters an infinite loop. If analysis is missing from a file almost completely, that probably means that we don't know project structure well enough for some reason, and running "refresh cargo project" action usually helps to find a problem in this case.

**Comment by josephDunne** [comment]
thanks will take a look.

> Is CPU at 100% for those half-analysed files?

Nope

foudn this in the logs:

```
java.lang.StackOverflowError
	at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:164)
	at org.rust.lang.core.resolve.ProcessorsKt$collectResolveVariants$1.invoke(Processors.kt:52)
	at org.rust.lang.core.resolve.ProcessorsKt$collectResolveVariants$1.invoke(Processors.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processNestedScopesUpwards$2$shadowingProcessor$1.invoke(NameResolution.kt:749)
	at org.rust.lang.core.resolve.NameResolutionKt$processNestedScopesUpwards$2$shadowingProcessor$1.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt:618)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt:618)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt:618)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt:618)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt:618)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt:618)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt:618)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt:618)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt:618)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt:618)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt:618)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt$processItemDeclarations$found$1.invoke(NameResolution.kt:618)

```

**Comment by josephDunne** [comment]
Yip thats the error. It occurs whenever I interact with the broken file

**Comment by josephDunne** [comment]
I'll try make some reproducible but the file in question is very very basic so not expecting to have much luck.

**Comment by josephDunne** [comment]
ah ok...quick scan of `NameResolutionKt$processItemDeclarations` suggested it could be this line in my module:

```
use super::*;
```

I dont think `NameResolutionKt$processItemDeclarations` can handle recursion (I call `use super::*` in a `mod a` and `use self::a::*` in super module

**Comment by josephDunne** [comment]
should i create new issue or rename this one?

**Comment by matklad** [comment]
@josephDunne could you create an example rust file where the problem happens? We do intend to handle recursion, and there are some existing tests for it, but looks like they are not sufficient :)

**Comment by josephDunne** [comment]
I will. I just tried no to create one but the simple case works. Seems its more complicated than just using `use super::*` . My project is quiet big so its going to take time to recreate

**Comment by josephDunne** [comment]
Any chance you can explain `processNestedScopesUpwards` to me? That might give me some clues

**Comment by matklad** [comment]
>Any chance you can explain processNestedScopesUpwards to me? That might give me some clues

Sure! The general idea is that code completion and name resolution share the same code, which just collects the set of visible name at a certain point of code. Instead of literally creating a list of visible elements, they are fed one by one into a `processor` sink: this allows to bail early from the search.

`processNestedScopesUpwards` task in particular is to walk the code upwards, visiting larger and larger scopes: current block, containing block, function, impl, and, finally, module. Basically, this is handled by `walkUp` function, which visits ancestors of the current elemnt until it hits the `mod`. There are some complications regarding shadowing (names at the same level must conflict, but names at different levels must use shadowing) and the `cameFrom` helps to with situations like `for x in expr`, where `x` should not be visible inside `expr` despite the fact that `expr` is a descendant of a for loop.

It is unlikelly

**Comment by josephDunne** [comment]
I have not had this problem again So I recommend closing.
