### ISSUE TITLE
IndexNotReadyException when starting with the Structure viewer open

### ISSUE THREAD

**Issue by kumbayo** [intellij-rust/intellij-rust#1688]
When IntelliJ IDEA is restarted while the "Structure" viewer is open, an IndexNotReadyException is triggered.

Bisecting shows this was introduced with 2df2b35885fcbc4aff40b1c4aaf10a62da09dfdc
CC @matklad 

**How to reproduce:**

- Crate a new project
- Paste the following code into main.rs
```rust
struct MyStruct {}

trait Foo {}

impl Foo for MyStruct {}
```
- Open the Structure view using Alt-7
- Exit IntelliJ IDEA
- Start IntelliJ IDEA
-> An exception happens
```
Tree is not dumb-mode-aware; treeBuilder=com.intellij.ide.structureView.newStructureView.StructureViewComponent$2@71c4ead5 treeStructure=structure view tree structure(model=org.rust.ide.structure.RsStructureViewModel@15a53c82)
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:730)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:679)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:662)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:346)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:312)
	at org.rust.lang.core.stubs.index.RsModulesIndex$Companion.getSuperFor(RsModulesIndex.kt:33)
	at org.rust.lang.core.psi.RsFile$super$1.compute(RsFile.kt:57)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:87)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:139)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at org.rust.lang.core.psi.RsFile.getSuper(RsFile.kt:55)
	at org.rust.lang.core.psi.ext.RsModKt$superMods$1.invoke(RsMod.kt:45)
	at org.rust.lang.core.psi.ext.RsModKt$superMods$1.invoke(RsMod.kt)
	at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:517)
	at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:535)
	at kotlin.sequences.TakeWhileSequence$iterator$1.calcNext(Sequences.kt:368)
	at kotlin.sequences.TakeWhileSequence$iterator$1.hasNext(Sequences.kt:395)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:632)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:662)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:653)
	at org.rust.lang.core.psi.ext.RsModKt.getSuperMods(RsMod.kt:47)
	at org.rust.lang.core.psi.ext.RsCompositeElementKt.getCrateRoot(RsCompositeElement.kt:46)
	at org.rust.lang.core.psi.ext.RsCompositeElementKt.getCrateRoot(RsCompositeElement.kt:52)
	at org.rust.lang.core.psi.ext.RsCompositeElementKt.getCrateRoot(RsCompositeElement.kt:52)
	at org.rust.lang.core.psi.ext.RsCompositeElementKt.getCrateRoot(RsCompositeElement.kt:52)
	at org.rust.lang.core.psi.ext.RsCompositeElementKt.getCrateRoot(RsCompositeElement.kt:52)
	at org.rust.lang.core.resolve.StdKnownItems$Companion.relativeTo(StdKnownItems.kt:83)
	at org.rust.lang.core.resolve.ImplLookup$Companion.relativeTo(ImplLookup.kt:264)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.resolveInner(RsPathReferenceImpl.kt:31)
	at org.rust.lang.core.resolve.ref.RsReferenceBase$Resolver.resolve(RsReferenceBase.kt:69)
	at org.rust.lang.core.resolve.ref.RsReferenceBase$Resolver.resolve(RsReferenceBase.kt:67)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:220)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.advancedCachedMultiResolve(RsReferenceBase.kt:43)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.advancedResolve(RsReferenceBase.kt:33)
	at org.rust.lang.core.types.infer.DeclarationsKt.inferTypeReferenceType(Declarations.kt:41)
	at org.rust.lang.core.types.ExtensionsKt$type$1.compute(Extensions.kt:22)
	at org.rust.lang.core.types.ExtensionsKt$type$1.compute(Extensions.kt)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at org.rust.ide.utils.PlatformUtilsKt.recursionGuard(PlatformUtils.kt:16)
	at org.rust.ide.utils.PlatformUtilsKt.recursionGuard$default(PlatformUtils.kt:15)
	at org.rust.lang.core.types.ExtensionsKt.getType(Extensions.kt:22)
	at org.rust.ide.presentation.UtilsKt.presentableName(Utils.kt:61)
	at org.rust.ide.presentation.UtilsKt.getPresentationForStructure(Utils.kt:33)
	at org.rust.ide.structure.RsStructureViewElement.getPresentation(RsStructureViewModel.kt:51)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.update(TreeElementWrapper.java:41)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.updateNodeDescriptor(AbstractTreeBuilder.java:577)
	at com.intellij.ide.util.treeView.AbstractTreeUi$22.perform(AbstractTreeUi.java:935)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1856)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:931)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:852)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$1600(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$43$1.perform(AbstractTreeUi.java:2702)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1856)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$43.perform(AbstractTreeUi.java:2699)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1856)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$54$1.perform(AbstractTreeUi.java:3385)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$2.perform(AbstractTreeBuilder.java:467)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:939)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runBackgroundLoading(AbstractTreeBuilder.java:464)
	at com.intellij.ide.util.treeView.AbstractTreeUi$54.perform(AbstractTreeUi.java:3376)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.ide.util.treeView.AbstractTreeUi$55.perform(AbstractTreeUi.java:3438)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.lambda$new$0(AbstractTreeUi.java:98)
	at com.intellij.util.concurrency.QueueProcessor.lambda$null$0(QueueProcessor.java:93)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.concurrency.QueueProcessor.lambda$wrappingProcessor$1(QueueProcessor.java:93)
	at com.intellij.util.concurrency.QueueProcessor.lambda$null$3(QueueProcessor.java:226)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.concurrency.QueueProcessor.lambda$startProcessing$4(QueueProcessor.java:226)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
**IntelliJ also wants to attach indexingStart.trace**
```
java.lang.Throwable
	at com.intellij.openapi.project.DumbServiceImpl.queueAsynchronousTask(DumbServiceImpl.java:201)
	at com.intellij.openapi.project.DumbServiceImpl.queueTask(DumbServiceImpl.java:181)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.doSynchronizeRoots(ProjectRootManagerComponent.java:283)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:409)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$100(ProjectRootManagerImpl.java:53)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.fireChange(ProjectRootManagerImpl.java:104)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:117)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:349)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceServiceImpl$workspaceMerger$1.invoke(CargoProjectWorkspaceServiceImpl.kt:99)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceServiceImpl$workspaceMerger$1.invoke(CargoProjectWorkspaceServiceImpl.kt:91)
	at org.rust.cargo.project.workspace.impl.WorkspaceMerger.update(CargoProjectWorkspaceServiceImpl.kt:86)
	at org.rust.cargo.project.workspace.impl.WorkspaceMerger.setRawWorkspace(CargoProjectWorkspaceServiceImpl.kt:67)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceServiceImpl$commitUpdate$$inlined$runWriteAction$1.compute(actions.kt:57)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1043)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceServiceImpl.commitUpdate(CargoProjectWorkspaceServiceImpl.kt:300)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceServiceImpl.access$commitUpdate(CargoProjectWorkspaceServiceImpl.kt:91)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceServiceImpl$UpdateTask.onSuccess(CargoProjectWorkspaceServiceImpl.kt:254)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:462)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.lambda$run$0(ProgressManagerImpl.java:189)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Line numbers in this exceptions were captured with 2df2b35885fcbc4aff40b1c4aaf10a62da09dfdc

**Comment by kumbayo** [comment]
This is possibly also related to a different exception: PsiInvalidElementAccessException.
But this error only happens with some enhancements applied so the Structure tree is properly updated when a file changes.
(This exception also does not happen before 2df2b35885fcbc4aff40b1c4aaf10a62da09dfdc even with my patches applied)

**Reproduction:**
- Apply my patch series from https://github.com/kumbayo/intellij-rust/commits/structure-view-improvements
- Use the same example source code for main.rs from above
- Close Structure viewer (to avoid the problem above on startup)
- Restart IntelliJ IDEA
- Show the Structure view using Alt-7
- Ctrl-A to select the whole contents of main.rs file
- Ctrl-Shift-/ (Comment with block comment)
-> Structure viewer strangely displays "Foo for MyStruct" (which was just commented out) under main.rs  and Exception happens

```
Element class com.intellij.psi.impl.source.tree.CompositeElement of type PATH (class org.rust.lang.core.stubs.RsPathStub$Type)
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type PATH (class org.rust.lang.core.stubs.RsPathStub$Type)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:96)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:275)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.isPhysical(StubBasedPsiElementBase.java:317)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:220)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.advancedCachedMultiResolve(RsReferenceBase.kt:43)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.advancedResolve(RsReferenceBase.kt:33)
	at org.rust.lang.core.types.infer.DeclarationsKt.inferTypeReferenceType(Declarations.kt:27)
	at org.rust.lang.core.types.ExtensionsKt$type$1.compute(Extensions.kt:23)
	at org.rust.lang.core.types.ExtensionsKt$type$1.compute(Extensions.kt)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at org.rust.ide.utils.PlatformUtilsKt.recursionGuard(PlatformUtils.kt:16)
	at org.rust.ide.utils.PlatformUtilsKt.recursionGuard$default(PlatformUtils.kt:15)
	at org.rust.lang.core.types.ExtensionsKt.getType(Extensions.kt:23)
	at org.rust.ide.presentation.UtilsKt.presentableName(Utils.kt:61)
	at org.rust.ide.presentation.UtilsKt.getPresentationForStructure(Utils.kt:33)
	at org.rust.ide.structure.RsStructureViewElement.getPresentation(RsStructureViewModel.kt:51)
	at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.update(TreeElementWrapper.java:41)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.updateNodeDescriptor(AbstractTreeBuilder.java:577)
	at com.intellij.ide.util.treeView.AbstractTreeUi$22.perform(AbstractTreeUi.java:935)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1856)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:931)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:883)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExistingNode(AbstractTreeUi.java:3004)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$4900(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$32$1.run(AbstractTreeUi.java:1718)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1835)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5200(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$33.perform(AbstractTreeUi.java:1801)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2090)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5800(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$36$1.perform(AbstractTreeUi.java:2002)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:433)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2185)
	at com.intellij.ide.util.treeView.AbstractTreeUi$36.perform(AbstractTreeUi.java:1997)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.lambda$new$0(AbstractTreeBuilder.java:51)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:102)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:57)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by matklad** [comment]
Yeah, project structure should not depend on indexes ideally. IIRC, Kotlin has some explicit "is dumb mode" checks in project structure.

**Comment by kumbayo** [comment]
This disappeared by updating IDEA to 2017.3 (#2090)
No more exceptions when the structure viewer is open during startup.
Also the structure viewer immediately reacts to changes in the file.
(Even when https://youtrack.jetbrains.com/issue/IDEA-177231 is not marked as fixed...)
