### ISSUE TITLE
Indexing an impl tries to launch resolve

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1759]
For indexing, we can only touch the current file (otherwise there'll be invalid data in the index), but looks like this is not the case:

```
Error while indexing C:\Users\matklad\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\convert.rs
To reindex this file IDEA has to be restarted
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:730)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:679)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:662)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:346)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:312)
	at org.rust.lang.core.stubs.index.RsModulesIndex$Companion.getSuperFor(RsModulesIndex.kt:33)
	at org.rust.lang.core.psi.RsFile$super$1.compute(RsFile.kt:58)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:87)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:139)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at org.rust.lang.core.psi.RsFile.getSuper(RsFile.kt:56)
	at org.rust.lang.core.psi.ext.RsModKt$superMods$1.invoke(RsMod.kt:45)
	at org.rust.lang.core.psi.ext.RsModKt$superMods$1.invoke(RsMod.kt)
	at kotlin.sequences.GeneratorSequence$iterator$1.calcNext(Sequences.kt:517)
	at kotlin.sequences.GeneratorSequence$iterator$1.hasNext(Sequences.kt:535)
	at kotlin.sequences.TakeWhileSequence$iterator$1.calcNext(Sequences.kt:368)
	at kotlin.sequences.TakeWhileSequence$iterator$1.hasNext(Sequences.kt:395)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:632)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:662)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:653)
	at org.rust.lang.core.psi.ext.RsModKt.getSuperMods(RsMod.kt:47)
	at org.rust.lang.core.psi.ext.RsCompositeElementKt.getCrateRoot(RsCompositeElement.kt:46)
	at org.rust.lang.core.psi.ext.RsCompositeElementKt.getCrateRoot(RsCompositeElement.kt:52)
	at org.rust.lang.core.psi.ext.RsCompositeElementKt.getCrateRoot(RsCompositeElement.kt:52)
	at org.rust.lang.core.psi.ext.RsCompositeElementKt.getCrateRoot(RsCompositeElement.kt:52)
	at org.rust.lang.core.psi.ext.RsCompositeElementKt.getCrateRoot(RsCompositeElement.kt:52)
	at org.rust.lang.core.psi.ext.RsCompositeElementKt.getCrateRoot(RsCompositeElement.kt:52)
	at org.rust.lang.core.psi.ext.RsCompositeElementKt.getCrateRoot(RsCompositeElement.kt:52)
	at org.rust.lang.core.resolve.StdKnownItems$Companion.relativeTo(StdKnownItems.kt:90)
	at org.rust.lang.core.resolve.ImplLookup$Companion.relativeTo(ImplLookup.kt:265)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.resolveInner(RsPathReferenceImpl.kt:31)
	at org.rust.lang.core.resolve.ref.RsReferenceBase$Resolver.resolve(RsReferenceBase.kt:69)
	at org.rust.lang.core.resolve.ref.RsReferenceBase$Resolver.resolve(RsReferenceBase.kt:67)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:220)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.advancedCachedMultiResolve(RsReferenceBase.kt:43)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.multiResolve(RsReferenceBase.kt:36)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.resolve(RsReferenceBase.kt:30)
	at org.rust.lang.core.psi.ext.RsTypeParameterKt.getBounds(RsTypeParameter.kt:21)
	at org.rust.lang.core.resolve.indexes.RsImplIndex$Companion.index(RsImplIndex.kt:63)
	at org.rust.lang.core.stubs.StubIndexingKt.indexImplItem(StubIndexing.kt:47)
	at org.rust.lang.core.stubs.RsImplItemStub$Type.indexStub(StubImplementations.kt:430)
	at org.rust.lang.core.stubs.RsImplItemStub$Type.indexStub(StubImplementations.kt:416)
	at com.intellij.psi.stubs.ObjectStubTree.indexStubTree(ObjectStubTree.java:70)
	at com.intellij.psi.stubs.StubUpdatingIndex.a(StubUpdatingIndex.java:375)
	at com.intellij.psi.stubs.StubUpdatingIndex.access$300(StubUpdatingIndex.java:50)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.a(StubUpdatingIndex.java:243)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:934)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:211)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:194)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:272)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:99)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:215)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1615)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1551)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:518)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1510)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1498)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:242)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by matklad** [comment]
I think this might have been introduced in https://github.com/intellij-rust/intellij-rust/pull/1749 so cc @Undin  :-)

**Comment by vlad20012** [comment]
Oh, using of `RsTypeParameter.bounds` was a bad idea. We should manually check check that there are no bound and where clauses

**Comment by Undin** [comment]
Ok, yes
I'll fix it:)

**Comment by matklad** [comment]
The main problem is that the invariant of "no touchy other files!" is not checked in any way :( 

Unfortunately, I don't really know how to improve the situation here, other than carefully think when writing indexing stuff :( Luckly, indexing itself is usually pretty simple and changes rarely!
