### ISSUE TITLE
ClassCastException in CLion debugger with Swift plugin enabled

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#1765]
Originally reported at https://youtrack.jetbrains.com/issue/CPP-10593#comment=27-2434646

```
java.lang.ClassCastException: org.rust.lang.core.psi.RsFile cannot be cast to com.jetbrains.cidr.lang.psi.OCFile
	at com.jetbrains.cidr.lang.symbols.cpp.OCThisSelfSuperSymbol.processThisSelfSuperInContext(OCThisSelfSuperSymbol.java:90)
	at com.jetbrains.cidr.lang.symbols.cpp.OCThisSelfSuperSymbol.tryResolveThisSelfSuper(OCThisSelfSuperSymbol.java:74)
	at com.jetbrains.cidr.execution.debugger.OCDebuggerTypesHelper.isImplicitContextVariable(OCDebuggerTypesHelper.java:75)
	at com.jetbrains.swift.execution.debugger.SwiftDebuggerTypesHelper.isImplicitContextVariable(SwiftDebuggerTypesHelper.java:62)
	at com.jetbrains.cidr.execution.debugger.CidrStackFrame.a(CidrStackFrame.java:230)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.jetbrains.cidr.execution.debugger.CidrStackFrame.a(CidrStackFrame.java:225)
	at com.intellij.util.containers.ContainerUtil.findAll(ContainerUtil.java:1041)
	at com.intellij.util.containers.ContainerUtil.filter(ContainerUtil.java:1020)
	at com.jetbrains.cidr.execution.debugger.CidrStackFrame.a(CidrStackFrame.java:215)
	at com.jetbrains.cidr.execution.debugger.CidrStackFrame.a(CidrStackFrame.java:173)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$MyCommandProcessor.consume(CidrDebugProcess.java:695)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$MyCommandProcessor.consume(CidrDebugProcess.java:685)
	at com.intellij.util.concurrency.QueueProcessor.lambda$null$0(QueueProcessor.java:93)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.concurrency.QueueProcessor.lambda$wrappingProcessor$1(QueueProcessor.java:93)
	at com.intellij.util.concurrency.QueueProcessor.lambda$null$3(QueueProcessor.java:226)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.concurrency.QueueProcessor.lambda$startProcessing$4(QueueProcessor.java:226)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:342)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

**Comment by Undin** [comment]
Works with the latest CLion 2018.1 EAP
fixed in #2356
