### ISSUE TITLE
Run Clippy command fails

### ISSUE THREAD

**Issue by vasily-kirichenko** [intellij-rust/intellij-rust#1941]
Latest EAP IDEA, latest Rust nightly, latest intellij-rust.
Create a exe project, build it.
Execute "Run Clippy" command:

![image](https://user-images.githubusercontent.com/873919/32122209-47172e16-bb68-11e7-9631-6510111e8c37.png)

Result:

```
C:/Users/vaski/.cargo/bin/cargo.exe +nightly clippy
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `C:\Users\vaski\.cargo\bin\clippy-driver C:\Users\vaski\.cargo\bin\rustc.exe - --crate-name ___ --print=file-names --target x86_64-pc-windows-msvc --crate-type bin --crate-type rlib` (exit code: 101)
--- stderr
error: multiple input filenames provided

thread 'rustc' panicked at 'Box<Any>', src\librustc\session\mod.rs:877:4
stack backtrace:
   0:     0x7ffc79284931 - _rdl_shrink_in_place
   1:     0x7ffc7929709c - std::panicking::Location::column::hf90f67c89a7651f4
   2:     0x7ffc79296d85 - std::panicking::Location::column::hf90f67c89a7651f4
   3:     0x7ffc79297705 - std::panicking::rust_panic_with_hook::h3a1712df1695e81b
   4:     0x7ffc763db61a - rustc::ty::maps::<impl rustc::ty::maps::queries::erase_regions_ty<'tcx>>::try_get::hfc893a3823ff1753
   5:     0x7ffc76143dfe - rustc::session::early_error::h185cdf29f6a83bcc
   6:     0x7ffc823bf3d6 - <rustc_driver::RustcDefaultCalls as rustc_driver::CompilerCalls<'a>>::no_input::hb35093ad5f7744e1
   7:     0x7ff6d0ae8f7d - <unknown>
   8:     0x7ffc823bb373 - rustc_driver::run_compiler::h2f36b49c15eb7b0a
   9:     0x7ff6d0ae2520 - <unknown>
  10:     0x7ff6d0ae350e - <unknown>
  11:     0x7ffc7929a671 - _rust_maybe_catch_panic
  12:     0x7ff6d0ae8bd2 - <unknown>
  13:     0x7ffc7929502b - std::sys::imp::thread::Thread::new::hb5d165aa7198c0ba
  14:     0x7ffcc4b72773 - BaseThreadInitThunk
thread 'main' panicked at 'rustc_thread failed: Any', src\libcore\result.rs:906:4
stack backtrace:
   0:     0x7ffc79284931 - _rdl_shrink_in_place
   1:     0x7ffc7929709c - std::panicking::Location::column::hf90f67c89a7651f4
   2:     0x7ffc79296d85 - std::panicking::Location::column::hf90f67c89a7651f4
   3:     0x7ffc79297705 - std::panicking::rust_panic_with_hook::h3a1712df1695e81b
   4:     0x7ffc79297528 - std::panicking::begin_panic_fmt::h677bfb217306a405
   5:     0x7ffc79297471 - std::panicking::begin_panic_fmt::h677bfb217306a405
   6:     0x7ffc792973df - rust_begin_unwind
   7:     0x7ffc792a980e - core::panicking::panic_fmt::h38934701a995b8c0
   8:     0x7ff6d0ae8983 - <unknown>
   9:     0x7ff6d0aea67c - <unknown>
  10:     0x7ffc7929a671 - _rust_maybe_catch_panic
  11:     0x7ffc79298171 - std::rt::lang_start::hba0280a1c20115bb
  12:     0x7ff6d0c89868 - <unknown>
  13:     0x7ffcc4b72773 - BaseThreadInitThunk


Process finished with exit code 101
```

**Comment by sanmai-NL** [comment]
I have the same issue. It also fails with custom Cargo commands. Clippy and custom Cargo commands do work properly from the terminal in IntelliJ IDEA.

**Comment by vadixidav** [comment]
Same issue for me as well. It runs from the command line just fine (including cmd.exe).
