### ISSUE TITLE
Exception in CargoTestRunLineMarkerContributor

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#1945]
After first opening file with test function(s) (looks like file must be outside of our project, in my case, it was `src/libstd/collections/hash/map.rs`), we get exception.

<details><summary>stacktrace</summary>
<p>

```
kotlin.UninitializedPropertyAccessException: lateinit property myWorkspace has not been initialized
	at org.rust.cargo.project.workspace.PackageImpl.getWorkspace(CargoWorkspace.kt:225)
	at org.rust.cargo.toolchain.CargoCommandLine$Companion.forTarget(CargoCommandLine.kt:58)
	at org.rust.cargo.runconfig.test.TestConfig.<init>(CargoTestRunConfigurationProducer.kt:88)
	at org.rust.cargo.runconfig.test.CargoTestRunConfigurationProducer$Companion.findTestFunction(CargoTestRunConfigurationProducer.kt:56)
	at org.rust.cargo.runconfig.test.CargoTestRunConfigurationProducer$Companion.findTest(CargoTestRunConfigurationProducer.kt:50)
	at org.rust.ide.lineMarkers.CargoTestRunLineMarkerContributor.getInfo(CargoTestRunLineMarkerContributor.kt:21)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:58)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:189)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:119)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1148)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:237)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

</p>
</details>

**Comment by matklad** [comment]
Wow, this is **spectacularly** broken at the moment. I think this is my favorite bug in IntelliJ Rust so far.

**Comment by matklad** [comment]
Oh welll, this is even more broken then I've thought initially...
