### ISSUE TITLE
NPE while building RustModulesIndex

### ISSUE THREAD

**Issue by himikof** [intellij-rust/intellij-rust#199]
When opening cargo repository project (at rust-lang/cargo@7f21e73) an NPE occurs consistently:

```
[   5516]  ERROR - napi.project.CacheUpdateRunner - Error while indexing /home/nikita/.cargo/registry/src/github.com-88ac128001ac3a9a/term-0.2.11/src/terminfo/mod.rs
To reindex this file IDEA has to be restarted 
kotlin.KotlinNullPointerException
	at org.rust.lang.core.psi.util.RustPsiExtensionsKt.getCrate(RustPsiExtensions.kt:58)
	at org.rust.lang.core.resolve.indexes.RustModulesIndex$Companion.getSuperFor(RustModulesIndex.kt:21)
	at org.rust.lang.core.psi.util.RustModExtensionsKt.getSuper(RustModExtensions.kt:61)
	at org.rust.lang.core.psi.util.RustModExtensionsKt.getCanonicalName(RustModExtensions.kt:33)
	at org.rust.lang.core.psi.util.RustModExtensionsKt.getCanonicalNameInFile(RustModExtensions.kt:41)
	at org.rust.lang.core.resolve.indexes.RustModulesIndexExtension$Companion$process$1.visitModItem(RustModulesIndexExtension.kt:118)
	at org.rust.lang.core.psi.impl.RustModItemImpl.accept(RustModItemImpl.java:26)
	at org.rust.lang.core.psi.impl.RustModItemImpl.accept(RustModItemImpl.java:30)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at org.rust.lang.core.resolve.indexes.RustModulesIndexExtension$Companion$process$1.visitModItem(RustModulesIndexExtension.kt:120)
	at org.rust.lang.core.psi.RustVisitor.visitFileModItem(RustVisitor.java:151)
	at org.rust.lang.core.psi.impl.RustFileModItemImpl.accept(RustFileModItemImpl.java:26)
	at org.rust.lang.core.psi.impl.RustFileModItemImpl.accept(RustFileModItemImpl.java:30)
	at org.rust.lang.core.resolve.indexes.RustModulesIndexExtension$Companion$process$1.visitFile(RustModulesIndexExtension.kt:102)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at org.rust.lang.core.resolve.indexes.RustModulesIndexExtension$Companion.process(RustModulesIndexExtension.kt:95)
	at org.rust.lang.core.resolve.indexes.RustModulesIndexExtension$Companion.access$process(RustModulesIndexExtension.kt:37)
	at org.rust.lang.core.resolve.indexes.RustModulesIndexExtension$Companion$dataIndexer$1.map(RustModulesIndexExtension.kt:81)
	at org.rust.lang.core.resolve.indexes.RustModulesIndexExtension$Companion$dataIndexer$1.map(RustModulesIndexExtension.kt:37)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1744)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1671)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1616)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:109)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:225)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:239)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
[   5521]  ERROR - napi.project.CacheUpdateRunner - IntelliJ IDEA 15.0  Build #IC-143.381.42 
[   5521]  ERROR - napi.project.CacheUpdateRunner - JDK: 1.8.0_60 
[   5521]  ERROR - napi.project.CacheUpdateRunner - VM: OpenJDK 64-Bit Server VM 
[   5521]  ERROR - napi.project.CacheUpdateRunner - Vendor: Oracle Corporation 
[   5522]  ERROR - napi.project.CacheUpdateRunner - OS: Linux 
[   5522]  ERROR - napi.project.CacheUpdateRunner - Last Action:  
```

Unfortunately, I'm not sure how to debug cache update process, so I was unable to catch the exception in the debugger.

May be related to https://github.com/intellij-rust/intellij-rust/commit/146a17d697474226bbaf1567258f6039cd4ee5d9#commitcomment-15153257.

**Comment by alexeykudinkin** [comment]
Will take a look tomorrow.

**Comment by schmitch** [comment]
I get this NPE's even without a Cargo project.

**Comment by alexeykudinkin** [comment]
Would be fixed alongside the #218 merge.

**Comment by ryandbair** [comment]
I'm still seeing this on a fresh build from master this morning. 

I tried debugging a few days ago and didn't get anywhere. I may spend a little more time this evening.

**Comment by alexeykudinkin** [comment]
Should be fixed by now.
