### ISSUE TITLE
Cannot build plugin on Mac OS X

### ISSUE THREAD

**Issue by govlas** [intellij-rust/intellij-rust#220]
```
FAILURE: Build failed with an exception.

* What went wrong:
(class: org/gradle/internal/UncheckedException, method: unwrapAndRethrow signature: (Ljava/lang/reflect/InvocationTargetException;)Ljava/lang/RuntimeException;) Illegal constant pool index

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.VerifyError: (class: org/gradle/internal/UncheckedException, method: unwrapAndRethrow signature: (Ljava/lang/reflect/InvocationTargetException;)Ljava/lang/RuntimeException;) Illegal constant pool index
	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:112)
	at org.gradle.initialization.DefaultGradleLauncher.stop(DefaultGradleLauncher.java:195)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by alexeykudinkin** [comment]
Hi, @govlas! Could you please re-run it wiht `--debug` option?

**Comment by govlas** [comment]
[log.txt](https://github.com/intellij-rust/intellij-rust/files/109405/log.txt)

**Comment by Turbo87** [comment]
The current master works fine for me on OSX. This is most likely not OS-related.

**Comment by ukstv** [comment]
Works for me too on El Capitan.

**Comment by schmitch** [comment]
btw for me i couldn't build it a while back, too. however currently it works again just fine.

**Comment by Leviathan1995** [comment]
how to solve it ?

**Comment by alexeykudinkin** [comment]
@Leviathan1995 have you checked it out with the `--recursive`?

**Comment by Leviathan1995** [comment]
i use `git clone https://github.com/intellij-rust/intellij-rust --recursive`  then `./gradlew buildPlugin`
but `* What went wrong:
A problem occurred configuring root project 'intellij-rust'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve gradle.plugin.org.jetbrains:gradle-intellij-plugin:0.0.39.
     Required by:
         :intellij-rust:0.0.1
      > Could not resolve gradle.plugin.org.jetbrains:gradle-intellij-plugin:0.0.39.
         > Could not get resource 'https://plugins.gradle.org/m2/gradle/plugin/org/jetbrains/gradle-intellij-plugin/0.0.39/gradle-intellij-plugin-0.0.39.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/gradle/plugin/org/jetbrains/gradle-intellij-plugin/0.0.39/gradle-intellij-plugin-0.0.39.pom'.
               > Connection to https://gradleware-plugins.s3.amazonaws.com refused

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

**Comment by vsuharnikov** [comment]
@Leviathan1995 It seems to be another problem: you can't download https://plugins.gradle.org/m2/gradle/plugin/org/jetbrains/gradle-intellij-plugin/0.0.39/gradle-intellij-plugin-0.0.39.pom , so it may be internet connection problems. Try to open this URL in a browser.

**Comment by alexeykudinkin** [comment]
Checked the latest trunk revision: works from my side.
