### ISSUE TITLE
NPE in RustPsiExtensionsKt.getCrate

### ISSUE THREAD

**Issue by daschl** [intellij-rust/intellij-rust#228]
Hi folks,

I'm running on `b4889642a4de115d00fa7817996429cf0a2579de` (current master, 31 jan) and I got the following error reported by IJ:

```
null
kotlin.KotlinNullPointerException
	at org.rust.lang.core.psi.util.RustPsiExtensionsKt.getCrate(RustPsiExtensions.kt:64)
	at org.rust.lang.core.resolve.indexes.RustModulesIndex$Companion.getSuperFor(RustModulesIndex.kt:21)
	at org.rust.lang.core.psi.util.RustModExtensionsKt.getSuper(RustModExtensions.kt:61)
	at org.rust.lang.core.resolve.util.RustResolveUtil.getCrateRootModFor(RustResolveUtil.kt:35)
	at org.rust.lang.core.resolve.RustResolveEngineKt.enumerateScopesFor(RustResolveEngine.kt:373)
	at org.rust.lang.core.resolve.Resolver.resolve(RustResolveEngine.kt:117)
	at org.rust.lang.core.resolve.RustResolveEngine.resolve(RustResolveEngine.kt:56)
	at org.rust.lang.core.resolve.ref.RustQualifiedReferenceImpl.resolve(RustQualifiedReferenceImpl.kt:19)
	at org.rust.ide.annotator.RustAnnotator.annotate(RustAnnotator.kt:37)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:162)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:354)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:65)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:283)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:65)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

Not sure if it helps, but I was trying out the new "goto class" with "cmd N" feature and browsing along in a dependency (but that could be coincidence, I tried doing the same a few times but it did not show up again).

**Comment by alexeykudinkin** [comment]
Hey @daschl! Thanks for the report! 
Could you try to see whether it's fixed for you now with `68a3cc1`?

**Comment by daschl** [comment]
yes I can try - is there a specific way it should not fail like before? Since when browsing around it did not show up after the first error.

**Comment by matklad** [comment]
Yes, this is indeed fixed.
