### ISSUE TITLE
Attach to process

### ISSUE THREAD

**Issue by russelltg** [intellij-rust/intellij-rust#2302]
Currently, the debugger only supports creating a new process (afaik). 

Is attach support possible?

**Comment by x1tan** [comment]
Also interested in this feature. Currently if I am trying to attach to a local process nothing happens.

But "idea.log" seems to contain the exception:

`ERROR - llij.ide.plugins.PluginManager - Parameter specified as non-null is null: method org.rust.debugger.lang.RsDebuggerLanguageSupportFactory.createEditor, parameter profile 
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method org.rust.debugger.lang.RsDebuggerLanguageSupportFactory.createEditor, parameter profile
	at org.rust.debugger.lang.RsDebuggerLanguageSupportFactory.createEditor(RsDebuggerLanguageSupportFactory.kt)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess.a(CidrDebugProcess.java:226)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess.<init>(CidrDebugProcess.java:186)
	at com.jetbrains.cidr.execution.debugger.CidrAttachedDebugProcess.<init>(CidrAttachedDebugProcess.java:14)
	at com.jetbrains.cidr.execution.debugger.CidrLocalAttachedDebugProcess.<init>(CidrLocalAttachedDebugProcess.java:22)
	at com.jetbrains.cidr.execution.debugger.CidrLocalAttachDebugger$1.start(CidrLocalAttachDebugger.java:50)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.a(XDebuggerManagerImpl.java:223)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSessionAndShowTab(XDebuggerManagerImpl.java:209)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSessionAndShowTab(XDebuggerManagerImpl.java:199)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSessionAndShowTab(XDebuggerManagerImpl.java:191)
	at com.jetbrains.cidr.execution.debugger.CidrLocalAttachDebugger.doAttachDebugSession(CidrLocalAttachDebugger.java:41)
	at com.jetbrains.cidr.execution.debugger.CidrLocalAttachDebugger.attachDebugSession(CidrLocalAttachDebugger.java:33)
	at com.intellij.xdebugger.impl.actions.AttachToLocalProcessAction$AttachItem.startDebugSession(AttachToLocalProcessAction.java:362)
	at com.intellij.xdebugger.impl.actions.AttachToLocalProcessAction$MyBasePopupStep.a(AttachToLocalProcessAction.java:398)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1431)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by Undin** [comment]
Works in CLion 2020.3.1 with 0.3.139.3615-203

**Comment by amircodota** [comment]
What about intellij IDEA ultimate? Any plans to support it there?

**Comment by Undin** [comment]
@amircodota see #6727
