### ISSUE TITLE
Watch creation

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#2372]
Currently action `New Watch` throws the following exception
<details><summary>stacktrace</summary>
<p>

```
CidrDebuggerEditorsExtensionBase.createExpressionCodeFragment must not return null 
java.lang.IllegalStateException: @NotNull method com/jetbrains/cidr/execution/debugger/CidrDebuggerEditorsExtensionBase.createExpressionCodeFragment must not return null
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerEditorsExtensionBase.a(CidrDebuggerEditorsExtensionBase.java)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerEditorsExtensionBase.createExpressionCodeFragment(CidrDebuggerEditorsExtensionBase.java:31)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerEditorsProvider$1.run(CidrDebuggerEditorsProvider.java:70)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.application.WriteAction.execute(WriteAction.java:37)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerEditorsProvider.createDocument(CidrDebuggerEditorsProvider.java:74)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:348)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.createDocument(XDebuggerExpressionComboBox.java:123)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.doSetText(XDebuggerExpressionComboBox.java:112)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setExpression(XDebuggerEditorBase.java:280)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.<init>(XDebuggerExpressionComboBox.java:55)
	at com.intellij.xdebugger.impl.ui.tree.XDebuggerTreeInplaceEditor.<init>(XDebuggerTreeInplaceEditor.java:47)
	at com.intellij.xdebugger.impl.frame.WatchInplaceEditor.<init>(WatchInplaceEditor.java:42)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.editWatch(WatchesRootNode.java:188)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.addNewWatch(WatchesRootNode.java:171)
	at com.intellij.xdebugger.impl.frame.actions.XNewWatchAction.perform(XNewWatchAction.java:34)
	at com.intellij.xdebugger.impl.frame.actions.XWatchesTreeActionBase.actionPerformed(XWatchesTreeActionBase.java:61)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:193)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:153)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:357)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:762)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

</p>
</details>

It's because of we don't implement `CidrDebuggerEditorsExtension.createExpressionCodeFragment` in `RsDebuggerEditorsExtension`
It would be great to support this feature (at least not to throw an exception)

**Comment by Undin** [comment]
Fixed by #3753
