### ISSUE TITLE
NPE in CargoExecutionSettings

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#248]
This double bang throws: https://github.com/intellij-rust/intellij-rust/blob/4c2675f426c4c266edaac72be328763873e923b8/src/main/kotlin/org/rust/cargo/project/settings/CargoExecutionSettings.kt#L35

It does not affect the user in any way, because we don't use cargo execution settings, but it is a shame anyway.

**Comment by jkozlowski** [comment]
I am getting that exception while trying to import a project (setting the path to cargo as ~/.multirust/toolchains/nightly on Mac OSX):
```
2016-02-20 13:18:14,118 [1375086]   WARN - nal.AbstractExternalSystemTask -  
kotlin.KotlinNullPointerException
	at org.rust.cargo.project.settings.CargoExecutionSettings$Companion.from(CargoExecutionSettings.kt:31)
	at org.rust.cargo.project.CargoExternalSystemManager$Companion.executionSettingsFor$intellij_rust_compileKotlin(CargoExternalSystemManager.kt:71)
	at org.rust.cargo.project.CargoExternalSystemManager$getExecutionSettingsProvider$1.fun(CargoExternalSystemManager.kt:40)
	at org.rust.cargo.project.CargoExternalSystemManager$getExecutionSettingsProvider$1.fun(CargoExternalSystemManager.kt:22)
	at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.getExecutionSettings(ExternalSystemApiUtil.java:776)
	at com.intellij.openapi.externalSystem.service.ExternalSystemFacadeManager.doCreateFacade(ExternalSystemFacadeManager.java:202)
	at com.intellij.openapi.externalSystem.service.ExternalSystemFacadeManager.doGetFacade(ExternalSystemFacadeManager.java:178)
	at com.intellij.openapi.externalSystem.service.ExternalSystemFacadeManager.doInvoke(ExternalSystemFacadeManager.java:133)
	at com.intellij.openapi.externalSystem.service.ExternalSystemFacadeManager$MyHandler.invoke(ExternalSystemFacadeManager.java:270)
	at com.sun.proxy.$Proxy123.getResolver(Unknown Source)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:48)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:124)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:419)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4$1.run(ExternalSystemUtil.java:491)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$14$1.run(ApplicationImpl.java:634)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
2016-02-20 13:18:23,812 [1384780]   WARN - nal.AbstractExternalSystemTask -  
kotlin.KotlinNullPointerException
	at org.rust.cargo.project.settings.CargoExecutionSettings$Companion.from(CargoExecutionSettings.kt:31)
	at org.rust.cargo.project.CargoExternalSystemManager$Companion.executionSettingsFor$intellij_rust_compileKotlin(CargoExternalSystemManager.kt:71)
	at org.rust.cargo.project.CargoExternalSystemManager$getExecutionSettingsProvider$1.fun(CargoExternalSystemManager.kt:40)
	at org.rust.cargo.project.CargoExternalSystemManager$getExecutionSettingsProvider$1.fun(CargoExternalSystemManager.kt:22)
	at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.getExecutionSettings(ExternalSystemApiUtil.java:776)
	at com.intellij.openapi.externalSystem.service.ExternalSystemFacadeManager.doCreateFacade(ExternalSystemFacadeManager.java:202)
	at com.intellij.openapi.externalSystem.service.ExternalSystemFacadeManager.doGetFacade(ExternalSystemFacadeManager.java:178)
	at com.intellij.openapi.externalSystem.service.ExternalSystemFacadeManager.doInvoke(ExternalSystemFacadeManager.java:133)
	at com.intellij.openapi.externalSystem.service.ExternalSystemFacadeManager$MyHandler.invoke(ExternalSystemFacadeManager.java:270)
	at com.sun.proxy.$Proxy123.getResolver(Unknown Source)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:48)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:138)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:124)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:419)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4$1.run(ExternalSystemUtil.java:491)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$14$1.run(ApplicationImpl.java:634)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by matklad** [comment]
@jkozlowski but is the project import successful?

**Comment by jkozlowski** [comment]
Saddly not :( Maybe I shouldn't be importing it as module in another project?

![image](https://cloud.githubusercontent.com/assets/690973/13196965/eed2fcc4-d7d6-11e5-9125-c8d04e55fab9.png)

**Comment by matklad** [comment]
>Maybe I shouldn't be importing it as module in another project?

Well, maybe. I've always imported the whole project, and this NPE was benign in that case.

I'm working on this very issue right now, but I can't give any ETA yet.

**Comment by jkozlowski** [comment]
Yeah it worked in a new window as per the user guide, so that works :)

> I'm working on this very issue right now, but I can't give any ETA yet.

No worries, just thought I'd add another data point that it could be user facing :)
