### ISSUE TITLE
Exception while macro expansion

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#2548]
**Environment**:
IntelliJ IDEA 2018.2 EAP (Ultimate Edition)
Build #IU-182.2574.2, built on May 22, 2018
JRE: 1.8.0_152-release-1226-b7 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

**Project**: https://github.com/recombinant/PetzoldPW5e-rs
<details><summary>stacktrace</summary>
<p>

```
2018-05-24 11:56:26,542 [1671926]  ERROR - n.impl.GeneralHighlightingPass - In file: file:///Users/warrior/Programming/PetzoldPW5e-rs/Chapter 01 - Getting Started/hello_msg/src/main.rs 
java.lang.NullPointerException
	at com.intellij.lang.parser.GeneratedParserUtilBase.addVariantInner(GeneratedParserUtilBase.java:388)
	at com.intellij.lang.parser.GeneratedParserUtilBase.addVariant(GeneratedParserUtilBase.java:376)
	at com.intellij.lang.parser.GeneratedParserUtilBase.addVariant(GeneratedParserUtilBase.java:371)
	at org.rust.lang.core.parser.RustParser.Expr(RustParser.java:7064)
	at org.rust.lang.core.macros.MacroPattern.matchPartial(MacroExpander.kt:228)
	at org.rust.lang.core.macros.MacroPattern.match(MacroExpander.kt:198)
	at org.rust.lang.core.macros.MacroExpander$findMatchingPattern$1.invoke(MacroExpander.kt:132)
	at org.rust.lang.core.macros.MacroExpander$findMatchingPattern$1.invoke(MacroExpander.kt:89)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:149)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:109)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:133)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:120)
	at org.rust.lang.core.macros.MacroExpander.findMatchingPattern(MacroExpander.kt:141)
	at org.rust.lang.core.macros.MacroExpander.expandMacroAsText(MacroExpander.kt:106)
	at org.rust.lang.core.macros.MacroExpander.expandMacro(MacroExpander.kt:98)
	at org.rust.lang.core.macros.MacroExpansionKt.expandMacro(MacroExpansion.kt:32)
	at org.rust.lang.core.psi.ext.RsMacroCallKt$expansion$1.compute(RsMacroCall.kt:53)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at org.rust.lang.core.psi.ext.RsMacroCallKt.getExpansion(RsMacroCall.kt:52)
	at org.rust.lang.core.psi.ext.RsItemsOwnerKt.processMacroCall(RsItemsOwner.kt:60)
	at org.rust.lang.core.psi.ext.RsItemsOwnerKt.processExpandedItems(RsItemsOwner.kt:48)
	at org.rust.lang.core.resolve.ItemResolutionKt.processItemDeclarations(ItemResolution.kt:86)
	at org.rust.lang.core.resolve.ItemResolutionKt.processItemOrEnumVariantDeclarations(ItemResolution.kt:25)
	at org.rust.lang.core.resolve.NameResolutionKt.processPathResolveVariants(NameResolution.kt:221)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt$resolvePath$result$1.invoke(RsPathReferenceImpl.kt:72)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt$resolvePath$result$1.invoke(RsPathReferenceImpl.kt)
	at org.rust.lang.core.resolve.ProcessorsKt.collectPathResolveVariants(Processors.kt:58)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt.resolvePath(RsPathReferenceImpl.kt:71)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt.resolvePath$default(RsPathReferenceImpl.kt:70)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$Resolver.resolve(RsPathReferenceImpl.kt:65)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$Resolver.resolve(RsPathReferenceImpl.kt:63)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:153)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:152)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:242)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.advancedCachedMultiResolve(RsPathReferenceImpl.kt:54)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.advancedMultiResolve(RsPathReferenceImpl.kt:43)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.multiResolve(RsPathReferenceImpl.kt:46)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.resolve(RsReferenceBase.kt:26)
	at org.rust.ide.annotator.RsHighlightingAnnotator.highlightReference(RsHighlightingAnnotator.kt:41)
	at org.rust.ide.annotator.RsHighlightingAnnotator.annotate(RsHighlightingAnnotator.kt:25)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:366)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:328)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:295)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

</p>
</details>

**Comment by kitsuneninetails** [comment]
Same here, exact same stack trace.  Plugin completely borken and unusable.

Using IntelliJ Community Edition (latest early access):

IntelliJ IDEA 2018.2 EAP (Community Edition)
Build #IC-182.2757.3, built on May 29, 2018
JRE: 1.8.0_152-release-1226-b7 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-43-generic

**Comment by kitsuneninetails** [comment]
Some more info.  When I backtrack to stable IntelliJ and install the 181 version of the plugin (Rust (0.2.0.2342-181-nightly)), it looks to be stable (no NPEs):

IntelliJ IDEA 2018.1.4 (Community Edition)
Build #IC-181.5087.20, built on May 17, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-43-generic

**Comment by amesgen** [comment]
can confirm @ downgrading to intellij 2018.1
