### ISSUE TITLE
Exception in plugin Javascript Support- Webstorm

### ISSUE THREAD

**Issue by guillermodv** [intellij-rust/intellij-rust#2895]
### **Fatal IDE Error on:**

WebStorm 2018.3 EAP
Build #WS-183.3283.12, built on October 3, 2018
WebStorm EAP User
Expiration date: November 2, 2018
JRE: 1.8.0_152-release-1343-b3 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-8-generic

### **trace:**

Uncaught exception from [com.intellij.openapi.application.impl.AsyncExecutionSupport$myCoroutineDispatchingContext$2$$special$$inlined$CoroutineExceptionHandler$1@3641109c, CoroutineName(AppUIExecutorImpl(later::withDocumentsCommitted::inTransaction)), CoroutineId(1), com.intellij.openapi.application.impl.AsyncExecutionSupport$createExpirableJobContinuationInterceptor$1@77295a85]

java.lang.NoClassDefFoundError: Could not initialize class com.intellij.icons.AllIcons$Javaee
	at com.intellij.lang.typescript.compiler.TypeScriptToolWindowProvider.<init>(TypeScriptToolWindowProvider.java:33)
	at sun.reflect.GeneratedConstructorAccessor59.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:85)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:209)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:52)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:30)
	at com.intellij.lang.typescript.compiler.TypeScriptToolWindowProvider.getToolWindow(TypeScriptToolWindowProvider.java:25)
	at com.intellij.lang.typescript.compiler.languageService.TypeScriptServerServiceImpl.createToolWindow(TypeScriptServerServiceImpl.java:662)
	at com.intellij.lang.javascript.service.JSAsyncLanguageServiceBase.<init>(JSAsyncLanguageServiceBase.java:43)
	at com.intellij.lang.javascript.service.JSLanguageServiceBase.<init>(JSLanguageServiceBase.java:23)
	at com.intellij.lang.typescript.compiler.TypeScriptCompilerService.<init>(TypeScriptCompilerService.java:132)
	at com.intellij.lang.typescript.compiler.languageService.TypeScriptServerServiceImpl.<init>(TypeScriptServerServiceImpl.java:143)
	at org.angular2.service.Angular2LanguageService.<init>(Angular2LanguageService.java:70)
	at org.angular2.service.Angular2LanguageServiceProvider.lambda$new$0(Angular2LanguageServiceProvider.java:26)
	at com.intellij.openapi.util.AtomicNotNullLazyValue$1.compute(AtomicNotNullLazyValue.java:60)
	at com.intellij.openapi.util.AtomicNotNullLazyValue.getValue(AtomicNotNullLazyValue.java:38)
	at org.angular2.service.Angular2LanguageServiceProvider.getAllServices(Angular2LanguageServiceProvider.java:36)
	at org.angular2.service.Angular2LanguageServiceProvider.getService(Angular2LanguageServiceProvider.java:42)
	at org.angular2.service.Angular2HighlightingPassFactory.getService(Angular2HighlightingPassFactory.java:36)
	at com.intellij.lang.javascript.service.highlighting.JSLanguageServiceHighlightingPassFactory.createHighlightingPass(JSLanguageServiceHighlightingPassFactory.java:38)
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.lambda$instantiatePasses$0(TextEditorHighlightingPassRegistrarImpl.java:111)
	at gnu.trove.TIntObjectHashMap.forEach(TIntObjectHashMap.java:179)
	at gnu.trove.TIntObjectHashMap.forEachKey(TIntObjectHashMap.java:554)
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.instantiatePasses(TextEditorHighlightingPassRegistrarImpl.java:104)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.java:81)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.createPassesForEditor(TextEditorBackgroundHighlighter.java:93)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.createPassesForEditor(TextEditorBackgroundHighlighter.java:22)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl$UpdateRunnable.run(DaemonCodeAnalyzerImpl.java:812)
	at com.intellij.openapi.application.impl.AppUIExecutorEx$execute$1.doResume(AppUIExecutorEx.kt:30)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$ChainedDispatcher.dispatchChain(AsyncExecutionSupport.kt:125)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$ChainedDispatcher.access$dispatchChain(AsyncExecutionSupport.kt:100)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$ChainedDispatcher.dispatch(AsyncExecutionSupport.kt:112)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$RescheduleAttemptLimitAwareDispatcher.retryDispatch(AsyncExecutionSupport.kt:200)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$ChainedDispatcher$dispatchChain$$inlined$Runnable$1.run(Runnable.kt:20)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.impl.AppUIExecutorImpl$inTransaction$1.schedule(AppUIExecutorImpl.kt:104)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$SimpleConstraintDispatcher.doSchedule(AsyncExecutionSupport.kt:146)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$ChainedDispatcher.dispatchChain(AsyncExecutionSupport.kt:119)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$ChainedDispatcher.access$dispatchChain(AsyncExecutionSupport.kt:100)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$ChainedDispatcher.dispatch(AsyncExecutionSupport.kt:112)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$RescheduleAttemptLimitAwareDispatcher.retryDispatch(AsyncExecutionSupport.kt:200)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$ChainedDispatcher$dispatchChain$$inlined$Runnable$1.run(Runnable.kt:20)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$ExpirableConstraintDispatcher$doSchedule$1.invoke(AsyncExecutionSupport.kt:173)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$ExpirableConstraintDispatcher$doSchedule$1.invoke(AsyncExecutionSupport.kt:151)
	at com.intellij.openapi.application.impl.AsyncExecutionSupport$Companion$RunOnce$runnable$$inlined$Runnable$1.run(Runnable.kt:19)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$null$7(PsiDocumentManagerBase.java:562)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Undin** [comment]
Looks like it's not related to IntelliJ Rust at all
Please, file issue in WebStorm issue [tracker](https://youtrack.jetbrains.com/issues/WEB)
