### ISSUE TITLE
Error:Internal error: (java.lang.NoClassDefFoundError) Could not initialize class com.intellij.util.io.PagedFileStorage

### ISSUE THREAD

**Issue by xlh006** [intellij-rust/intellij-rust#2959]
Error:Internal error: (java.lang.NoClassDefFoundError) Could not initialize class com.intellij.util.io.PagedFileStorage
java.lang.NoClassDefFoundError: Could not initialize class com.intellij.util.io.PagedFileStorage
	at com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:48)
	at com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:82)
	at com.intellij.util.io.PersistentEnumeratorDelegate.<init>(PersistentEnumeratorDelegate.java:38)
	at com.intellij.util.io.PersistentEnumeratorDelegate.<init>(PersistentEnumeratorDelegate.java:31)
	at com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:130)
	at com.intellij.util.io.PersistentHashMap.<init>(PersistentHashMap.java:126)
	at org.jetbrains.jps.incremental.storage.AbstractStateStorage.createMap(AbstractStateStorage.java:136)
	at org.jetbrains.jps.incremental.storage.AbstractStateStorage.<init>(AbstractStateStorage.java:41)
	at org.jetbrains.jps.incremental.storage.TimestampStorage.<init>(TimestampStorage.java:36)
	at org.jetbrains.jps.incremental.storage.ProjectTimestamps.<init>(ProjectTimestamps.java:36)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:90)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:266)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by Undin** [comment]
@xlh006 How is it related to IntelliJ Rust?

**Comment by Undin** [comment]
@xlh006 Looks like it's not related to IntelliJ Rust.
Please, file issue in IDEA issue [tracker](https://youtrack.jetbrains.com/issues/IDEA)
