### ISSUE TITLE
Unable to save settings. Failed to save settings, Please restart Intellij IDEA

### ISSUE THREAD

**Issue by coderplay** [intellij-rust/intellij-rust#297]
```
String index out of range: 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.intellij.configurationStore.ProjectStateStorageManager.expandMacros(ProjectStateStorageManager.kt:33)
	at com.intellij.configurationStore.StateStorageManagerImpl.createStateStorage(StateStorageManagerImpl.kt:194)
	at com.intellij.configurationStore.StateStorageManagerImpl.getOrCreateStorage(StateStorageManagerImpl.kt:150)
	at com.intellij.configurationStore.StateStorageManagerImpl.getStateStorage(StateStorageManagerImpl.kt:133)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:269)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:237)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:41)
	at org.rust.cargo.project.settings.CargoSettings$Companion.getInstance(CargoSettings.kt:60)
	at org.rust.cargo.project.CargoExternalSystemManager$getSettingsProvider$1.fun(CargoExternalSystemManager.kt:32)
	at org.rust.cargo.project.CargoExternalSystemManager$getSettingsProvider$1.fun(CargoExternalSystemManager.kt:21)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil.refreshProjects(ExternalSystemUtil.java:239)
	at com.intellij.openapi.externalSystem.service.ExternalSystemStartupActivity$1.run(ExternalSystemStartupActivity.java:64)
	at com.intellij.util.DisposeAwareRunnable.run(DisposeAwareRunnable.java:82)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:150)
	at com.intellij.openapi.externalSystem.service.ExternalSystemStartupActivity.runActivity(ExternalSystemStartupActivity.java:78)
	at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:147)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:342)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$700(StartupManagerImpl.java:58)
	at com.intellij.ide.startup.impl.StartupManagerImpl$3.run(StartupManagerImpl.java:165)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:318)
	at com.intellij.openapi.project.DumbServiceImpl.access$1100(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$10.run(DumbServiceImpl.java:503)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:158)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.intellij.configurationStore.ProjectStateStorageManager.expandMacros(ProjectStateStorageManager.kt:33)
	at com.intellij.configurationStore.StateStorageManagerImpl.createStateStorage(StateStorageManagerImpl.kt:194)
	at com.intellij.configurationStore.StateStorageManagerImpl.getOrCreateStorage(StateStorageManagerImpl.kt:150)
	at com.intellij.configurationStore.StateStorageManagerImpl.getStateStorage(StateStorageManagerImpl.kt:133)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:269)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:237)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:41)
	at org.rust.cargo.project.settings.CargoSettings$Companion.getInstance(CargoSettings.kt:60)
	at org.rust.cargo.project.CargoExternalSystemManager$getSettingsProvider$1.fun(CargoExternalSystemManager.kt:32)
	at org.rust.cargo.project.CargoExternalSystemManager$getSettingsProvider$1.fun(CargoExternalSystemManager.kt:21)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil.refreshProjects(ExternalSystemUtil.java:239)
	at com.intellij.openapi.externalSystem.service.ExternalSystemStartupActivity$1.run(ExternalSystemStartupActivity.java:64)
	at com.intellij.util.DisposeAwareRunnable.run(DisposeAwareRunnable.java:82)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:150)
	at com.intellij.openapi.externalSystem.service.ExternalSystemStartupActivity.runActivity(ExternalSystemStartupActivity.java:78)
	at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:147)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:342)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$700(StartupManagerImpl.java:58)
	at com.intellij.ide.startup.impl.StartupManagerImpl$3.run(StartupManagerImpl.java:165)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:318)
	at com.intellij.openapi.project.DumbServiceImpl.access$1100(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$10.run(DumbServiceImpl.java:503)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:158)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
IntelliJ version  15.0.4 ultimate

**Comment by matklad** [comment]
Hm, I did check https://github.com/intellij-rust/intellij-rust/commit/6708de402763ac99817087b35b6cc479158363ea yesterday with IDEA 15, and it worked. I must have messed up something =(

Sorry for the inconvenience and thanks for the report!

**Comment by matklad** [comment]
The next nightly is up, so you can update the plugin to fix the problem
