### ISSUE TITLE
New version of intellij-rust breaks syntax hinglight

### ISSUE THREAD

**Issue by richerarc** [intellij-rust/intellij-rust#2977]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2108-182
* **Rust toolchain version:** stable-x86_64-apple-darwin (default)
                                               rustc 1.29.1 (b801ae664 2018-09-20)
* **IDE name and version:** Clion CLion 2018.2.5 Build #CL-182.4892.24, built on October 16, 2018
* **Operating system:** macOS 10.14

## Problem description
I  installed the newest version of the rust plugin on CLion this morning. Since then, the plugin is very unstable, and does not provide syntax highlighting. It seems you are aware of the problem since the version changelog is not online anymore and de version does not appear to be on github, but it sure is broken for the poeple who did the update this morning.

**Comment by amakeev** [comment]
Workaround: manually install 2107 plugin version from https://plugins.jetbrains.com/plugin/8182-rust 
(`IDE | Settings | Plugins | install plugin from disk`).

**Comment by Undin** [comment]
@richerarc thanks for the report!
Could you provide code where syntax highlighting is broken to reproduce the issue?
Also, it would be great if you attach the corresponding logs. `Cmd + shift + A > Show Log in Finder` should help you to find them.
> It seems you are aware of the problem since the version changelog is not online anymore

Changelog page is unavailable because GitHub temporarily turned off GitHub Pages builds.

**Comment by amakeev** [comment]
For me reproduces on this code (works fine with 2107, hangs with 2108):
```fn main() {
    let vec1 = vec![1, 2, 3];
    let vec2 = vec![4, 5, 6];

    // `iter()` for vecs yields `&i32`.
    let mut iter = vec1.iter();
    // `into_iter()` for vecs yields `i32`.
    let mut into_iter = vec2.into_iter();

    // A reference to what is yielded is `&&i32`. Destructure to `i32`.
    println!("Find 2 in vec1: {:?}", iter     .find(|&&x| x == 2));
    // A reference to what is yielded is `&i32`. Destructure to `i32`.
    println!("Find 2 in vec2: {:?}", into_iter.find(| &x| x == 2));

    let array1 = [1, 2, 3];
    let array2 = [4, 5, 6];

    // `iter()` for arrays yields `&i32`
    println!("Find 2 in array1: {:?}", array1.iter()     .find(|&&x| x == 2));
    // `into_iter()` for arrays unusually yields `&i32`
    println!("Find 2 in array2: {:?}", array2.into_iter().find(|&&x| x == 2));
}```

Exception in the log:
```
java.lang.NoClassDefFoundError: com/intellij/util/CollectionsKt
	at org.rust.ide.presentation.TypeRenderingKt.getShortPresentableText(TypeRendering.kt:22)
	at org.rust.ide.hints.RsInlayParameterHintsProviderKt$inlayInfo$4.invoke(RsInlayParameterHintsProvider.kt:33)
	at org.rust.ide.hints.RsInlayParameterHintsProviderKt$inlayInfo$4.invoke(RsInlayParameterHintsProvider.kt)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:149)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:647)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:677)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:668)
	at org.rust.ide.hints.RsInlayParameterHintsProviderKt.getInlayInfo(RsInlayParameterHintsProvider.kt:34)
	at org.rust.ide.hints.RsInlayParameterHintsProviderKt.access$getInlayInfo$p(RsInlayParameterHintsProvider.kt:1)
	at org.rust.ide.hints.HintType$LET_BINDING_HINT.provideHints(RsInlayParameterHintsProvider.kt:47)
	at org.rust.ide.hints.RsInlayParameterHintsProvider.getParameterHints(RsInlayParameterHintsProvider.kt:142)
	at com.intellij.codeInsight.hints.ParameterHintsPass.a(ParameterHintsPass.java:84)
	at com.intellij.codeInsight.hints.ParameterHintsPass.a(ParameterHintsPass.java:76)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPass.doCollectInformation(ParameterHintsPass.java:76)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.e(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```[
[idea.log](https://github.com/intellij-rust/intellij-rust/files/2502602/idea.log)
](url)

**Comment by Undin** [comment]
@richerarc We fixed this issue and upload new plugin version to plugin repo.
Sorry for inconvenience

**Comment by richerarc** [comment]
@Undin Thanks for your quick fix of the issue!
