### ISSUE TITLE
Mimic cargo test standard behavior for stdout and error

### ISSUE THREAD

**Issue by la10736** [intellij-rust/intellij-rust#3030]
## Environment

* **Intellij-Rust plugin version:** v0.2.0.2110-182
* **Rust toolchain version:** 1.30
* **IDE name and version:** Intellij 2018.2.5
* **Operating system:** Linux

## Problem description

Test runner should show stderr and stdout for failed test like `cargo test` command do.

## Steps to reproduce
```rust
#[test]
fn it_works() {
    println!("it_works stdout");
    eprintln!("it_works stderr");
    assert_eq!(2 + 2, 4);
}

#[test]
fn it_fail() {
    println!("it_fail stdout");
    eprintln!("it_fail stderr");
    assert_eq!(2 + 2, 5);
}
```
Create a test runner and run it. Select `it_fail` test should show stdout and stderr like `cargo test` do.

Now, cargo json output contains the stdout and stderr:

```none

michele@DartVader:~/learning/rust/cargo_test_json_out$ cargo test --color=always --no-fail-fast --all-features -- -Z unstable-options --format=json
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s                                                                                                                         
     Running target/debug/deps/cargo_test_json_out-4851566aeccea52d
{ "type": "suite", "event": "started", "test_count": 2 }
{ "type": "test", "event": "started", "name": "it_fail" }
{ "type": "test", "event": "started", "name": "it_works" }
{ "type": "test", "name": "it_works", "event": "ok" }
{ "type": "test", "name": "it_fail", "event": "failed", "stdout": "it_fail stdout\nit_fail stderr\nthread 'it_fail' panicked at 'assertion failed: `(left == right)`\n  left: `4`,\n right: `5`', src/lib.rs:12:5\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\nstack backtrace:\n   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace\n             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49\n   1: std::sys_common::backtrace::_print\n             at libstd/sys_common/backtrace.rs:71\n   2: std::panicking::default_hook::{{closure}}\n             at libstd/sys_common/backtrace.rs:59\n             at libstd/panicking.rs:211\n   3: std::panicking::default_hook\n             at libstd/panicking.rs:221\n   4: std::panicking::rust_panic_with_hook\n             at libstd/panicking.rs:476\n   5: std::panicking::continue_panic_fmt\n             at libstd/panicking.rs:390\n   6: std::panicking::begin_panic_fmt\n             at libstd/panicking.rs:345\n   7: cargo_test_json_out::it_fail\n             at src/lib.rs:12\n   8: cargo_test_json_out::it_fail::{{closure}}\n             at src/lib.rs:9\n   9: core::ops::function::FnOnce::call_once\n             at /rustc/3e6f30ec3e6bda159063fcd126dcb14725fef92d/src/libcore/ops/function.rs:238\n  10: <F as alloc::boxed::FnBox<A>>::call_box\n             at libtest/lib.rs:1468\n             at /rustc/3e6f30ec3e6bda159063fcd126dcb14725fef92d/src/libcore/ops/function.rs:238\n             at /rustc/3e6f30ec3e6bda159063fcd126dcb14725fef92d/src/liballoc/boxed.rs:672\n  11: __rust_maybe_catch_panic\n             at libpanic_unwind/lib.rs:102\n" }
{ "type": "suite", "event": "failed", "passed": 1, "failed": 1, "allowed_fail": 0, "ignored": 0, "measured": 0, "filtered_out": 0 }
   Doc-tests cargo_test_json_out
{ "type": "suite", "event": "started", "test_count": 0 }
{ "type": "suite", "event": "ok", "passed": 0, "failed": 0, "allowed_fail": 0, "ignored": 0, "measured": 0, "filtered_out": 0 }
error: test failed, to rerun pass '--lib'
```

But UI filter it out.

![no_out_and_err](https://user-images.githubusercontent.com/3902961/48315637-fe7b7300-e5d8-11e8-8f7d-49ef6d520ef7.png)

I think that `cargo test` behavior should be recovered by default independently from rust-lang/rust#54669 . Use `--no-caputure` is useful for debugging (see output and error also for not failed tests) but for failed tests should be the normal behavior.

**Comment by la10736** [comment]
The real question is: Why cut stdout in `createServiceMessagesFor()`.

```kotlin
"failed" -> {
                messages.add(createTestFailedMessage(testMessage.name, getTestResult(testMessage.stdout)))
                messages.add(createTestFinishedMessage(testMessage.name, getTestDuration(testMessage.name)))
                recordSuiteChildFinished(testMessage.name)
                processFinishedSuites(messages)
            }
```

Should use just `messages.add(createTestFailedMessage(testMessage.name, testMessage.stdout))`

**Comment by mchernyavsky** [comment]
@la10736 Because we can't get stdout for successful tests. Look at the json messages for the test2 from https://github.com/rust-lang/rust/issues/54669.

**Comment by mchernyavsky** [comment]
Oh. Thanks, now I get it.
