### ISSUE TITLE
Fatal Error Null Pointer Exception

### ISSUE THREAD

**Issue by LooMaclin** [intellij-rust/intellij-rust#3445]
```
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at org.rust.openapiext.AsyncTasksKt$runAsyncTask$1.run(AsyncTasks.kt:34)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:680)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:685)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:144)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt.setupProjectRoots(CargoProjectImpl.kt:411)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt.access$setupProjectRoots(CargoProjectImpl.kt:1)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$doRefresh$2.apply(CargoProjectImpl.kt:396)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$doRefresh$2.apply(CargoProjectImpl.kt)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 17 more
Caused by: java.lang.NullPointerException
	at com.intellij.openapi.roots.LanguageLevelModuleExtensionImpl.isChanged(LanguageLevelModuleExtensionImpl.java:81)
	at com.intellij.openapi.roots.impl.RootModelImpl.isChanged(RootModelImpl.java:562)
	at com.intellij.openapi.roots.impl.ModuleRootManagerImpl.commitModel(ModuleRootManagerImpl.java:158)
	at com.intellij.openapi.roots.impl.RootModelImpl.commit(RootModelImpl.java:375)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:92)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.lambda$updateModel$9(ModuleRootModificationUtil.java:144)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:156)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:723)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:672)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:367)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Environment:
```
IntelliJ IDEA 2019.1 EAP (Community Edition)
Build #IC-191.5701.16, built on February 20, 2019
JRE: 1.8.0_202-release-1483-b4 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.20.12-arch1-1-ARCH
```

```
[loomaclin@loomaclin magnus]$ rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2019-01-17-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.34.0-nightly (00aae71f5 2019-02-25)
```

```
[loomaclin@loomaclin magnus]$ archey3

               +                OS: Arch Linux x86_64
               #                Hostname: loomaclin
              ###               Kernel Release: 4.20.12-arch1-1-ARCH
             #####              Uptime: 0:41
             ######             WM: Openbox
            ; #####;            DE: None
           +##.#####            Packages: 450
          +##########           RAM: 2545 MB / 15741 MB
         #############;         Processor Type: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
        ###############+        $EDITOR: None
       #######   #######        Root: 14G / 117G (11%) (ext4)
     .######;     ;###;`".      
    .#######;     ;#####.       
    #########.   .########`     
   ######'           '######    
  ;####                 ####;   
  ##'                     '##   
 #'                         `#  
```

**Comment by amakeev** [comment]
@LooMaclin I can only imagine one scenario when this could have happen: when a project was being closed or already closed.
Is it reproducible? what were the circumstances?

**Comment by amakeev** [comment]
Should be fixed in the next IntelliJ IDEA 2019.1 EAP: https://youtrack.jetbrains.com/issue/IDEA-208045

**Comment by LooMaclin** [comment]
> @LooMaclin I can only imagine one scenario when this could have happen: when a project was being closed or already closed.
> Is it reproducible? what were the circumstances?

I cannot reproduce this.

**Comment by amakeev** [comment]
@LooMaclin OK, thanks, let's consider closed then.
