### ISSUE TITLE
Clippy checker throws exception

### ISSUE THREAD

**Issue by ice1000** [intellij-rust/intellij-rust#3539]
## Environment

* **Intellij-Rust plugin version:** Unrelated
* **Rust toolchain version:** intellij-rust-0.2.94.2579-191-nightly
* **IDE name and version:** CL-191.6183.6
* **Operating system:** Ubuntu Linux 18.04

## Problem description

```
java.lang.Throwable: Incorrect CachedValue use: same CV with different captured context, this can cause unstable results and invalid PSI access.
Field $owner in class org.rust.ide.annotator.RsExternalLinterUtils$checkLazily$1 has non-equivalent values:
  Dispose on PSI change (com.intellij.openapi.util.Disposer$2) and
  Dispose on PSI change (com.intellij.openapi.util.Disposer$2)
Either make `equals()` hold for these values, or avoid this dependency, e.g. by extracting CV provider into a static method.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.util.CachedValueStabilityChecker.complain(CachedValueStabilityChecker.java:163)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:134)
	at com.intellij.util.CachedValueStabilityChecker.checkProvidersEquivalent(CachedValueStabilityChecker.java:87)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:60)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:119)
	at org.rust.ide.annotator.RsExternalLinterUtils.checkLazily(RsExternalLinterUtils.kt:71)
	at org.rust.ide.annotator.RsExternalLinterPass.doCollectInformation(RsExternalLinterPass.kt:57)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

## Steps to reproduce

Cannot reproduce, but I get the stack trace.

This happens after:

+ I changed checker from "cargo check" to "clippy" and enabled "run cargo check on the fly"
+ ij-rs said I don't have clippy, I clicked "install"
+ I triggered a build, get error

**Comment by mili-l** [comment]
I've caught it too on the latest version of plugin
## Environment

* **IntelliJ Rust plugin version:** 0.4.180.4886-222-nightly
* **Rust toolchain version:** 1.63.0 (4b91a6ea7 2022-08-08) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.2.3 (CL-222.4167.35)
* **Operating system:** macOS 11.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts


[idea.log](https://github.com/intellij-rust/intellij-rust/files/9605410/idea.log)


<details> 

<summary> Exeptions </summary >

```
com.intellij.diagnostic.PluginException: Incorrect CachedValue use: same CV with different captured context, this can cause unstable results and invalid PSI access.
Field arg$1 in class org.rust.lang.core.macros.MacroExpansionServiceImplInner$$Lambda$3856/0x0000000801ea52b0 has non-equivalent values:
  org.rust.lang.core.macros.MacroExpansionServiceImplInner@4b6d7e97 (org.rust.lang.core.macros.MacroExpansionServiceImplInner) and
  org.rust.lang.core.macros.MacroExpansionServiceImplInner@2b48ac14 (org.rust.lang.core.macros.MacroExpansionServiceImplInner)
Either make `equals()` hold for these values, or avoid this dependency, e.g. by extracting CV provider into a static method. [Plugin: org.rust.lang]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.logPluginError(PluginException.java:100)
	at com.intellij.util.CachedValueStabilityChecker.complain(CachedValueStabilityChecker.java:164)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:131)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:127)
	at com.intellij.util.CachedValueStabilityChecker.checkProvidersEquivalent(CachedValueStabilityChecker.java:83)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:67)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.getContextOfMacroCallExpandedFrom(MacroExpansionManager.kt:749)
	at org.rust.lang.core.macros.MacroExpansionManagerImpl.getContextOfMacroCallExpandedFrom(MacroExpansionManager.kt:240)
	at org.rust.lang.core.macros.RsExpandedElement$Companion.getContextImpl(RsExpandedElement.kt:35)
	at org.rust.lang.core.macros.RsExpandedElement$Companion.getContextImpl$default(RsExpandedElement.kt:29)
	at org.rust.lang.core.psi.ext.RsFunctionImplMixin.getContext(RsFunction.kt:324)
	at org.rust.lang.core.psi.ext.RsAbstractableKt.getOwner(RsAbstractable.kt:36)
	at org.rust.ide.annotator.RsHighlightingAnnotatorKt.colorFor(RsHighlightingAnnotator.kt:176)
	at org.rust.ide.annotator.RsHighlightingAnnotatorKt.access$colorFor(RsHighlightingAnnotator.kt:1)
	at org.rust.ide.annotator.RsHighlightingAnnotator.highlightIdentifier(RsHighlightingAnnotator.kt:96)
	at org.rust.ide.annotator.RsHighlightingAnnotator.highlightLeaf(RsHighlightingAnnotator.kt:55)
	at org.rust.ide.annotator.RsHighlightingAnnotator.annotateInternal(RsHighlightingAnnotator.kt:32)
	at org.rust.ide.annotator.AnnotatorBase.annotate(AnnotatorBase.kt:21)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:347)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:279)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:276)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:221)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


Following exceptions happened soon after this one, most probably they are induced.


2022-09-20T10:05:56.148
com.intellij.diagnostic.PluginException: Incorrect CachedValue use: same CV with different captured context, this can cause unstable results and invalid PSI access.
Field arg$1 in class org.rust.lang.core.macros.MacroExpansionServiceImplInner$$Lambda$4398/0x0000000802497520 has non-equivalent values:
  org.rust.lang.core.macros.MacroExpansionServiceImplInner@4b6d7e97 (org.rust.lang.core.macros.MacroExpansionServiceImplInner) and
  org.rust.lang.core.macros.MacroExpansionServiceImplInner@2b48ac14 (org.rust.lang.core.macros.MacroExpansionServiceImplInner)
Either make `equals()` hold for these values, or avoid this dependency, e.g. by extracting CV provider into a static method. [Plugin: org.rust.lang]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.logPluginError(PluginException.java:100)
	at com.intellij.util.CachedValueStabilityChecker.complain(CachedValueStabilityChecker.java:164)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:131)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:127)
	at com.intellij.util.CachedValueStabilityChecker.checkProvidersEquivalent(CachedValueStabilityChecker.java:83)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:67)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.getExpandedFrom(MacroExpansionManager.kt:730)
	at org.rust.lang.core.macros.MacroExpansionManagerImpl.getExpandedFrom(MacroExpansionManager.kt:231)
	at org.rust.lang.core.macros.RsExpandedElementKt.getExpandedFrom(RsExpandedElement.kt:70)
	at org.rust.lang.core.macros.RsExpandedElementKt$findMacroCallExpandedFromNonRecursive$1.invoke(RsExpandedElement.kt:116)
	at org.rust.lang.core.macros.RsExpandedElementKt$findMacroCallExpandedFromNonRecursive$1.invoke(RsExpandedElement.kt:116)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:167)
	at org.rust.lang.core.macros.RsExpandedElementKt.findMacroCallExpandedFromNonRecursive(RsExpandedElement.kt:117)
	at org.rust.lang.core.resolve2.FacadeResolveKt.getPathSegmentsAdjusted(FacadeResolve.kt:375)
	at org.rust.lang.core.resolve2.FacadeResolveKt.access$getPathSegmentsAdjusted(FacadeResolve.kt:1)
	at org.rust.lang.core.resolve2.FacadeResolveKt$resolveToMacroDefInfo$1.invoke(FacadeResolve.kt:267)
	at org.rust.lang.core.resolve2.FacadeResolveKt$resolveToMacroDefInfo$1.invoke(FacadeResolve.kt:266)
	at org.rust.lang.core.resolve.ref.RsResolveCache.resolveWithCaching$lambda-1$lambda-0(RsResolveCache.kt:96)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at org.rust.lang.core.resolve.ref.RsResolveCache.resolveWithCaching(RsResolveCache.kt:96)
	at org.rust.lang.core.resolve2.FacadeResolveKt.resolveToMacroDefInfo(FacadeResolve.kt:266)
	at org.rust.lang.core.resolve2.FacadeResolveKt.resolveToMacroInfo(FacadeResolve.kt:228)
	at org.rust.lang.core.resolve2.FacadeResolveKt.resolveToMacroWithoutPsi(FacadeResolve.kt:199)
	at org.rust.lang.core.psi.ext.RsPossibleMacroCallKt.resolveToMacroWithoutPsiWithErr(RsPossibleMacroCall.kt:409)
	at org.rust.lang.core.macros.MacroExpansionManagerKt.expandMacroToMemoryFile(MacroExpansionManager.kt:922)
	at org.rust.lang.core.macros.MacroExpansionManagerKt.access$expandMacroToMemoryFile(MacroExpansionManager.kt:1)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.getExpansionFor(MacroExpansionManager.kt:710)
	at org.rust.lang.core.macros.MacroExpansionManagerImpl.getExpansionFor(MacroExpansionManager.kt:206)
	at org.rust.lang.core.psi.ext.RsPossibleMacroCallKt._get_expansionResult_$lambda-16(RsPossibleMacroCall.kt:431)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.rust.lang.core.psi.ext.RsPossibleMacroCallKt.getExpansionResult(RsPossibleMacroCall.kt:425)
	at org.rust.lang.core.psi.ext.RsPossibleMacroCallKt.getExpansion(RsPossibleMacroCall.kt:421)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferMacroAsExpr(TypeInferenceWalker.kt:1325)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferFormatMacro(TypeInferenceWalker.kt:1328)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferMacroExprType0(TypeInferenceWalker.kt:1302)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferMacroExprType(TypeInferenceWalker.kt:1256)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:202)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType$default(TypeInferenceWalker.kt:170)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.processStatement(TypeInferenceWalker.kt:163)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:117)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferTypeCoercableTo(TypeInferenceWalker.kt:111)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferFnBody(TypeInferenceWalker.kt:106)
	at org.rust.lang.core.types.infer.RsInferenceContext.infer(TypeInference.kt:214)
	at org.rust.lang.core.types.infer.TypeInferenceKt.inferTypesIn$lambda-0(TypeInference.kt:40)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at org.rust.openapiext.UtilsKt.recursionGuard(utils.kt:94)
	at org.rust.lang.core.types.infer.TypeInferenceKt.inferTypesIn(TypeInference.kt:40)
	at org.rust.lang.core.types.ExtensionsKt._get_inference_$lambda-0(Extensions.kt:111)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:110)
	at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:117)
	at org.rust.lang.core.types.ExtensionsKt.getType(Extensions.kt:123)
	at org.rust.ide.hints.type.RsInlayTypeHintsProvider$getCollectorFor$1.presentTypePlaceholders(RsInlayTypeHintsProvider.kt:128)
	at org.rust.ide.hints.type.RsInlayTypeHintsProvider$getCollectorFor$1.presentVariable(RsInlayTypeHintsProvider.kt:106)
	at org.rust.ide.hints.type.RsInlayTypeHintsProvider$getCollectorFor$1.collect(RsInlayTypeHintsProvider.kt:90)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:91)
	at com.intellij.codeInsight.hints.InlayHintsPass$doCollectInformation$1.process(InlayHintsPass.kt:47)
	at com.intellij.codeInsight.hints.InlayHintsPass$doCollectInformation$1.process(InlayHintsPass.kt:27)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:63)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation(InlayHintsPass.kt:38)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

</details>

**Comment by vlad20012** [comment]
@mili-l Your exception is very different. And, to be honest, I have no idea how it ever possible :D
let's close it for now and open a new issue if such an exception will occur again
