### ISSUE TITLE
Type inference throws exception

### ISSUE THREAD

**Issue by ice1000** [intellij-rust/intellij-rust#3544]
## Environment

Rust toolchain version: Unrelated
Intellij-Rust plugin version: intellij-rust-0.2.94.2580-191-nightly
IDE name and version: CL-191.6183.6
Operating system: Ubuntu Linux 18.04

## Problem description

```
In file: LightVirtualFile: /tcm.rs

java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at org.rust.lang.core.resolve.ImplLookup.confirmCandidate(ImplLookup.kt:1042)
	at org.rust.lang.core.resolve.ImplLookup.select(ImplLookup.kt:367)
	at org.rust.lang.core.types.infer.FulfillmentContext.processPredicate(Fulfillment.kt:190)
	at org.rust.lang.core.types.infer.FulfillmentContext.access$processPredicate(Fulfillment.kt:146)
	at org.rust.lang.core.types.infer.FulfillmentContext$selectWherePossible$1.invoke(Fulfillment.kt:161)
	at org.rust.lang.core.types.infer.FulfillmentContext$selectWherePossible$1.invoke(Fulfillment.kt:146)
	at org.rust.lang.core.types.infer.ObligationForest.processObligations(Fulfillment.kt:119)
	at org.rust.lang.core.types.infer.ObligationForest.processObligations$default(Fulfillment.kt:110)
	at org.rust.lang.core.types.infer.FulfillmentContext.selectWherePossible(Fulfillment.kt:161)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.selectObligationsWherePossible(TypeInference.kt:643)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferArgumentTypes(TypeInference.kt:1299)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferMethodCallExprType(TypeInference.kt:1206)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferDotExprType(TypeInference.kt:1340)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType(TypeInference.kt:746)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType$default(TypeInference.kt:734)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferTryExprType(TypeInference.kt:1546)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType(TypeInference.kt:756)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType$default(TypeInference.kt:734)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.processStatement(TypeInference.kt:730)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType(TypeInference.kt:702)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType$default(TypeInference.kt:699)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferBlockExprType(TypeInference.kt:650)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType(TypeInference.kt:748)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferMatchExprType(TypeInference.kt:1393)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType(TypeInference.kt:753)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferTypeCoercableTo(TypeInference.kt:774)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferType(TypeInference.kt:704)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferTypeCoercableTo(TypeInference.kt:697)
	at org.rust.lang.core.types.infer.RsFnInferenceContext.inferFnBody(TypeInference.kt:685)
	at org.rust.lang.core.types.infer.RsInferenceContext.infer(TypeInference.kt:153)
	at org.rust.lang.core.types.infer.TypeInferenceKt$inferTypesIn$1.compute(TypeInference.kt:44)
	at org.rust.lang.core.types.infer.TypeInferenceKt$inferTypesIn$1.compute(TypeInference.kt)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:116)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at org.rust.openapiext.UtilsKt.recursionGuard(utils.kt:54)
	at org.rust.openapiext.UtilsKt.recursionGuard$default(utils.kt:53)
	at org.rust.lang.core.types.infer.TypeInferenceKt.inferTypesIn(TypeInference.kt:44)
	at org.rust.lang.core.types.ExtensionsKt$inference$1.compute(Extensions.kt:66)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$0(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:116)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:65)
	at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:120)
	at org.rust.lang.core.types.ExtensionsKt.getType(Extensions.kt:75)
	at org.rust.ide.annotator.RsHighlightingMutableAnnotatorKt.isMut(RsHighlightingMutableAnnotator.kt:75)
	at org.rust.ide.annotator.RsHighlightingMutableAnnotator.distinctAnnotation(RsHighlightingMutableAnnotator.kt:47)
	at org.rust.ide.annotator.RsHighlightingMutableAnnotator.annotateInternal(RsHighlightingMutableAnnotator.kt:32)
	at org.rust.ide.annotator.RsAnnotatorBase.annotate(RsAnnotatorBase.kt:21)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:120)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:290)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.RainbowVisitor.analyze(RainbowVisitor.java:50)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:71)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

## Steps to reproduce

Cannot reproduce but I got stack trace. This happened when I was:

+ Open vcs log
+ Click on one diff file

(maybe it's trying to do type inference on the psi elements in the old revision?

**Comment by lancelote** [comment]
Managed to reproduce it reliably:

1. Get the sample project:

```
git clone https://gitlab.com/lancelote/rust-book.git
cd rust-book
git reset --hard ad1c0044e05b38a1253867f1c670302f9008243a
```

2. Open `chapter02/src/bin/guessing_game.rs` in the editor
3. Right click in the editor -> git -> Compare with the Same Repository Version
4. Exception is raised

## Environment

* **Intellij-Rust plugin version:** 0.2.100.2128-192
* **Rust toolchain version:** rustc 1.35.0 (3c235d560 2019-05-20)
* **IDE name and version:** CLion 2019.2 Nightly 192.5631
* **Operating system:** macOS 10.14.4

**Comment by vlad20012** [comment]
Thank you so much @lancelote! Without your help, I could not reproduce it.
