### ISSUE TITLE
Assertion failed: Intention Description Dir URL is null

### ISSUE THREAD

**Issue by jajakobyly** [intellij-rust/intellij-rust#376]
```
Throwable: Assertion failed: Intention Description Dir URL is null: Expand module structure; ExpandModuleIntention, PluginClassLoader[org.rust.lang, 0.0.1.SNAPSHOT]
```

Stack trace:
```
Assertion failed: Intention Description Dir URL is null: Expand module structure; ExpandModuleIntention, PluginClassLoader[org.rust.lang, 0.0.1.SNAPSHOT]
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:156)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getDirURL(IntentionActionMetaData.java:112)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:155)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.processMetaData(IntentionManagerSettings.java:166)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerMetaData(IntentionManagerSettings.java:157)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerIntentionMetaData(IntentionManagerSettings.java:75)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.registerIntentionAndMetaData(IntentionManagerImpl.java:142)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl.registerIntentionAndMetaData(IntentionManagerImpl.java:119)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerImpl$2.run(IntentionManagerImpl.java:96)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by matklad** [comment]
ouch, it was https://github.com/intellij-rust/intellij-rust/commit/d1e6b968cc414dfbbf82182558effdcb9b95a633

**Comment by matklad** [comment]
Cleaned up intentions a bit more: https://github.com/intellij-rust/intellij-rust/commit/f475ed62a35ae471d7d7ebbcd82baea27e9a59a9.

Noticed an important gotcha: if you override a Java method without nullability annotations, Kotlin will use `?` types for parameters, though they might not be necessary.
