### ISSUE TITLE
NoSuchMethodError thrown when opening project preferences (or selecting a toolchain)

### ISSUE THREAD

**Issue by Others** [intellij-rust/intellij-rust#378]
Since updating to the latest version of the intellij-rust plugin, I've been experiencing a strange bug. When I open a preexisting rust project, the plugin notifies me that I have to set up a Rust toolchain. (Which makes sense.) But when I click on the message to setup the toolchain, nothing happens, except for an error message popping up. The displayed error is a NoSuchMethodError, with the following stack trace:
```
com.intellij.openapi.util.Disposer.newDisposable(Ljava/lang/String;)Lcom/intellij/openapi/Disposable;
java.lang.NoSuchMethodError: com.intellij.openapi.util.Disposer.newDisposable(Ljava/lang/String;)Lcom/intellij/openapi/Disposable;
	at org.rust.cargo.project.settings.ui.RustProjectSettingsPanel.<init>(RustProjectSettingsPanel.kt:30)
	at org.rust.cargo.project.configurable.RustProjectConfigurable.<init>(RustProjectConfigurable.kt:16)
	at org.rust.cargo.project.settings.impl.RustProjectSettingsServiceImpl.configureToolchain(RustProjectSettingsServiceImpl.kt:37)
	at org.rust.ide.notifications.MissingToolchainNotificationProvider$createBadToolchainPanel$$inlined$apply$lambda$1.run(MissingToolchainNotificationProvider.kt:87)
	at com.intellij.ui.EditorNotificationPanel$2.hyperlinkActivated(EditorNotificationPanel.java:93)
	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:28)
	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:196)
	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:129)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This error also occurs when attempting to open preferences in Intelliji, which is frustrating, as it prevents any preferences at all from being changed. As far as versions go, I'm on version 0.0.1.461 of the plugin, and version 15.0.5 of Intellij IDEA. I can reproduce this issue with both `rustc 1.10.0-nightly (8da2bcac5 2016-04-28)` +  `cargo 0.11.0-nightly (afac7fc 2016-04-27)` and `rustc 1.9.0-beta.2 (87cb73304 2016-05-04)` + `cargo 0.10.0-nightly (10ddd7d 2016-04-08)`. My laptop is a Mac running OSX 10.11.1.

**Comment by matklad** [comment]
Ouch, looks like we use some API which appeard only in IDEA 2016, and have not covered it with tests, so CI for IDEA 15 passes.

**Comment by matklad** [comment]
>CI for IDEA 15 passes.

Of course `IDEA15` TeamCity configuration actually uses IDEA2016.1! :frowning:

**Comment by matklad** [comment]
published new nightly, should be OK now, thanks for the report!

**Comment by matklad** [comment]
>published new nightly,

Not yet published the nightly build :)
