### ISSUE TITLE
Synchronous execution on EDT: cargo.exe init

### ISSUE THREAD

**Issue by maxim-banaev** [intellij-rust/intellij-rust#4147]
## Environment

* **IntelliJ Rust plugin version:** 0.2.101.2129-192
* **Rust toolchain version:** 1.33.0
* **IDE name and version:**  CLion 2019.2 Beta
* **Operating system:** Windows 10

## Problem description

Exception on project opening 

## Steps
1. Open Hello World Rust project

exception:
java.lang.Throwable: Synchronous execution on EDT: C:/Users/maxim.banaev/.cargo/bin/cargo.exe init --bin --name untitled6 C:\Users\maxim.banaev\CLionProjects\untitled6
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:117)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:55)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:31)
	at com.intellij.execution.process.CapturingProcessHandler.runProcess(CapturingProcessHandler.java:50)
	at org.rust.openapiext.CommandLineExtKt.execute(CommandLineExt.kt:95)
	at org.rust.cargo.toolchain.Cargo.execute(Cargo.kt:206)
	at org.rust.cargo.toolchain.Cargo.execute$default(Cargo.kt:205)
	at org.rust.cargo.toolchain.Cargo.init(Cargo.kt:137)
	at org.rust.cargo.toolchain.Cargo.init$default(Cargo.kt:123)
	at org.rust.ide.newProject.RsDirectoryProjectGenerator.generateProject(RsDirectoryProjectGenerator.kt:44)
	at org.rust.ide.newProject.RsDirectoryProjectGenerator.generateProject(RsDirectoryProjectGenerator.kt:26)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.lambda$doGenerateProject$2(AbstractNewProjectStep.java:204)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:215)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.doGenerateProject(AbstractNewProjectStep.java:209)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$AbstractCallback.consume(AbstractNewProjectStep.java:163)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase$1.lambda$actionPerformed$0(ProjectSettingsStepBase.java:137)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:148)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase$1.actionPerformed(ProjectSettingsStepBase.java:137)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:762)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:405)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:404)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by maxim-banaev** [comment]
Any chance to fix it before 2019.3 released?

**Comment by mili-l** [comment]
## Environment

* **IntelliJ Rust plugin version:** **0.4.169.4542-221-nightly**
* **Rust toolchain version:** 1.62.0-nightly (60e50fc1c 2022-04-04) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA **2022.1** Beta Ultimate Edition (IU-221.5080.93)
* **Operating system:** macOS 11.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

Sometimes the exception occurs when creating a new project 
<details>
  <summary>Exception</summary>

```
2022-04-06 11:09:04,597 [1458797]   INFO - o.r.o.CommandLineExt - Executing `/Users/jamilya.shurukhova/.cargo/bin/cargo init --bin --name pr_8629_2 --vcs none /Users/jamilya.shurukhova/IdeaProjects/pr_verify_projects/pr_7816/src/pr_8629_2`
2022-04-06 11:09:04,607 [1458807] SEVERE - #c.i.e.p.OSProcessHandler - Synchronous execution on EDT: /Users/jamilya.shurukhova/.cargo/bin/cargo init --bin --name pr_8629_2 --vcs none /Users/jamilya.shurukhova/IdeaProjects/pr_verify_projects/pr_7816/src/pr_8629_2, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions
java.lang.Throwable: Synchronous execution on EDT: /Users/jamilya.shurukhova/.cargo/bin/cargo init --bin --name pr_8629_2 --vcs none /Users/jamilya.shurukhova/IdeaProjects/pr_verify_projects/pr_7816/src/pr_8629_2, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:171)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:102)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:39)
	at com.intellij.execution.process.CapturingProcessHandler.runProcess(CapturingProcessHandler.java:43)
	at org.rust.openapiext.CommandLineExtKt.runProcess(CommandLineExt.kt:131)
	at org.rust.openapiext.CommandLineExtKt.runProcessWithGlobalProgress(CommandLineExt.kt:118)
	at org.rust.openapiext.CommandLineExtKt.access$runProcessWithGlobalProgress(CommandLineExt.kt:1)
	at org.rust.openapiext.CommandLineExtKt$execute$1.invoke(CommandLineExt.kt:58)
	at org.rust.openapiext.CommandLineExtKt$execute$1.invoke(CommandLineExt.kt:58)
	at org.rust.openapiext.CommandLineExtKt.execute(CommandLineExt.kt:104)
	at org.rust.openapiext.CommandLineExtKt.execute$default(CommandLineExt.kt:55)
	at org.rust.cargo.toolchain.tools.Cargo.execute(Cargo.kt:428)
	at org.rust.cargo.toolchain.tools.Cargo.execute$default(Cargo.kt:422)
	at org.rust.cargo.toolchain.tools.Cargo.init(Cargo.kt:304)
	at org.rust.ide.actions.RsCreateCrateAction.createProject(RsCreateCrateAction.kt:58)
	at org.rust.ide.actions.RsCreateCrateAction.actionPerformed(RsCreateCrateAction.kt:34)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:235)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:235)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$performAction$0(ActionMenuItem.java:289)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.performAction(ActionMenuItem.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:296)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$2(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:540)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:570)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2022-04-06 11:09:04,612 [1458812] SEVERE - #c.i.e.p.OSProcessHandler - IntelliJ IDEA 2022.1 Beta  Build #IU-221.5080.93
2022-04-06 11:09:04,615 [1458815] SEVERE - #c.i.e.p.OSProcessHandler - JDK: 11.0.14.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-04-06 11:09:04,616 [1458816] SEVERE - #c.i.e.p.OSProcessHandler - OS: Mac OS X
2022-04-06 11:09:04,618 [1458818] SEVERE - #c.i.e.p.OSProcessHandler - Plugin to blame: Rust version: 0.4.169.4542-221-nightly
```
</details>
