### ISSUE TITLE
Make ModuleIndex compatible with 162.xxx branch

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust#415]
https://github.com/intellij-rust/intellij-rust/issues/372#issuecomment-220829152

Not actually sure if it is indeed a bug in `ModuleIndex` or in idea itself.

**Comment by alexeykudinkin** [comment]
Does it still throw?

**Comment by alexeykudinkin** [comment]
All tests pass on TC against the `162.*` branch.

**Comment by matklad** [comment]
>Does it still throw?

Yes it does. 

>All tests pass on TC against the 162.* branch.

Then something's wrong with the CI, until build is 145 :) 
https://github.com/intellij-rust/intellij-rust/blob/master/src/main/resources/META-INF/plugin.xml#L18

**Comment by matklad** [comment]
Enable 162 and enable stderr for gradle tests:

```
diff --git a/build.gradle b/build.gradle
index ab958ec..abee390 100644
--- a/build.gradle
+++ b/build.gradle
@@ -63,6 +63,7 @@ allprojects {
 
     test {
         testLogging {
+            showStandardStreams = true
             events "passed", "skipped", "failed"
             exceptionFormat = 'full'
         }
diff --git a/gradle.properties b/gradle.properties
index 95a3e8d..db19f50 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -3,7 +3,7 @@ name = "intellij-rust"
 # ideaVersion = 145.184.1
 # javaVersion = 1.8
 
-ideaVersion = 2016.1.2
+ideaVersion = LATEST-EAP-SNAPSHOT
 javaVersion = 1.6
 
 kotlinVersion = 1.0.2
diff --git a/src/main/resources/META-INF/plugin.xml b/src/main/resources/META-INF/plugin.xml
index 31982f0..9e8621a 100644
--- a/src/main/resources/META-INF/plugin.xml
+++ b/src/main/resources/META-INF/plugin.xml
@@ -15,7 +15,7 @@
     <!--</change-notes>-->
 
     <!-- please see https://confluence.jetbrains.com/display/IDEADEV/Build+Number+Ranges for description -->
-    <idea-version since-build="143.381.42" until-build="145.9999"/>
+    <idea-version since-build="143.381.42" until-build="162.9999"/>
 
     <!-- please see https://confluence.jetbrains.com/display/IDEADEV/Plugin+Compatibility+with+IntelliJ+Platform+Products
          on how to target different products -->
```

run the test:

```
> % ./gradlew test -Dtest.single=CargoProjectResolveTestCase                                                                                 ~/projects/intellij-rust
:generateRustLexer UP-TO-DATE
:generateRustPsiAndParser UP-TO-DATE
:generate UP-TO-DATE
:compileKotlin
w: /home/matklad/projects/intellij-rust/src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt: (18, 57): 'PROJECT_FILE: String' is deprecated. Deprecated in Java
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:processResources UP-TO-DATE
:classes
:downloadRustSources UP-TO-DATE
:processTestResources UP-TO-DATE
:compileTestKotlin
:compileTestJava UP-TO-DATE
:testClasses
:prepareTestsSandbox UP-TO-DATE
:test
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=250m; support was removed in 8.0

org.rust.cargo.toolchain.CargoProjectResolveTestCase > testResolveExternalLibrary PASSED

org.rust.cargo.toolchain.CargoProjectResolveTestCase > testResolveLocalPackage PASSED

org.rust.cargo.toolchain.CargoProjectResolveTestCase > testModuleRelations STANDARD_ERROR
    ERROR: Index org.rust.lang.indexes.RustModulesIndex violates equals / hashCode contract for Value parameter
    java.lang.Throwable
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
        at com.intellij.util.indexing.MapReduceIndex.checkValuesHaveProperEqualsAndHashCode(MapReduceIndex.java:755)
        at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:456)
        at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1656)
        at com.intellij.util.indexing.FileBasedIndexImpl$19.run(FileBasedIndexImpl.java:1586)
        at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:510)
        at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1541)
        at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1526)
        at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:108)
        at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
        at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:226)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1063)
        at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:246)
        at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:472)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:421)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
        at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:240)
        at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:472)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:421)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
        at com.intellij.openapi.project.CacheUpdateRunner.processSomeFilesWhileUserIsInactive(CacheUpdateRunner.java:125)
        at com.intellij.openapi.project.CacheUpdateRunner.processFiles(CacheUpdateRunner.java:84)
        at com.intellij.util.indexing.UnindexedFilesUpdater.indexFiles(UnindexedFilesUpdater.java:105)
        at com.intellij.util.indexing.UnindexedFilesUpdater.updateUnindexedFiles(UnindexedFilesUpdater.java:99)
        at com.intellij.util.indexing.UnindexedFilesUpdater.performInDumbMode(UnindexedFilesUpdater.java:117)
        at com.intellij.openapi.project.DumbServiceImpl.queueTask(DumbServiceImpl.java:176)
        at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.doSynchronizeRoots(ProjectRootManagerComponent.java:298)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:419)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$100(ProjectRootManagerImpl.java:55)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.fireChange(ProjectRootManagerImpl.java:112)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:125)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:357)
        at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModel(ModuleManagerImpl.java:950)
        at com.intellij.openapi.module.impl.ModuleManagerImpl.access$1800(ModuleManagerImpl.java:71)
        at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.commitWithRunnable(ModuleManagerImpl.java:856)
        at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.access$1600(ModuleManagerImpl.java:617)
        at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModelWithRunnable(ModuleManagerImpl.java:608)
        at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:48)
        at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:37)
        at com.intellij.openapi.roots.impl.ModuleRootManagerImpl.commitModel(ModuleRootManagerImpl.java:178)
        at com.intellij.openapi.roots.impl.RootModelImpl.commit(RootModelImpl.java:338)
        at com.intellij.openapi.roots.ModuleRootModificationUtil$8.run(ModuleRootModificationUtil.java:167)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:935)
        at com.intellij.openapi.roots.ModuleRootModificationUtil$10.run(ModuleRootModificationUtil.java:208)
        at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:663)
        at com.intellij.openapi.roots.ModuleRootModificationUtil.doWriteAction(ModuleRootModificationUtil.java:205)
        at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:164)
        at org.rust.cargo.util.ModuleUtilKt.updateLibrary(ModuleUtil.kt:114)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.updateModuleDependencies(CargoProjectWorkspaceImpl.kt:133)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.access$updateModuleDependencies(CargoProjectWorkspaceImpl.kt:36)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$commitUpdate$1.invoke(CargoProjectWorkspaceImpl.kt:115)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$commitUpdate$1.invoke(CargoProjectWorkspaceImpl.kt:36)
        at org.rust.ide.utils.PlatformUtilsKt.runWriteAction(PlatformUtils.kt:18)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.commitUpdate(CargoProjectWorkspaceImpl.kt:113)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.access$commitUpdate(CargoProjectWorkspaceImpl.kt:36)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$UpdateTask.onSuccess(CargoProjectWorkspaceImpl.kt:177)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:390)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
        at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:305)
        at com.intellij.openapi.progress.Task.queue(Task.java:83)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.requestUpdateUsing(CargoProjectWorkspaceImpl.kt:88)
        at org.rust.cargo.toolchain.CargoProjectResolveTestCase.updateCargoProject(CargoProjectResolveTestCase.kt:77)
        at org.rust.cargo.toolchain.CargoProjectResolveTestCase.access$updateCargoProject(CargoProjectResolveTestCase.kt:19)
        at org.rust.cargo.toolchain.CargoProjectResolveTestCase$testModuleRelations$1.invoke(CargoProjectResolveTestCase.kt:53)
        at org.rust.cargo.toolchain.CargoProjectResolveTestCase$testModuleRelations$1.invoke(CargoProjectResolveTestCase.kt:19)
        at org.rust.cargo.RustWithToolchainTestCaseBase.withProject(RustWithToolchainTestCaseBase.kt:27)
        at org.rust.cargo.toolchain.CargoProjectResolveTestCase.testModuleRelations(CargoProjectResolveTestCase.kt:47)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:154)
        at com.intellij.testFramework.UsefulTestCase.access$001(UsefulTestCase.java:80)
        at com.intellij.testFramework.UsefulTestCase.lambda$runTest$0(UsefulTestCase.java:326)
        at com.intellij.testFramework.PlatformTestCase.lambda$invokeTestRunnable$3(PlatformTestCase.java:737)
        at com.intellij.testFramework.PlatformTestCase.invokeTestRunnable(PlatformTestCase.java:749)
        at com.intellij.testFramework.UsefulTestCase.runTest(UsefulTestCase.java:341)
        at org.rust.cargo.RustWithToolchainTestCaseBase.runTest(RustWithToolchainTestCaseBase.kt:35)
        at com.intellij.testFramework.PlatformTestCase.lambda$runBareImpl$2(PlatformTestCase.java:666)
        at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
        at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
        at com.intellij.testFramework.EdtTestUtilKt$sam$Runnable$ca4818df.run(EdtTestUtil.kt)
        at com.intellij.openapi.application.TransactionGuardImpl$7.run(TransactionGuardImpl.java:294)
        at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:156)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:828)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:663)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:393)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
    ERROR: Error while indexing /tmp/unitTest_moduleRelations/src/lib.rs
    To reindex this file IDEA has to be restarted
    java.lang.AssertionError: Index org.rust.lang.indexes.RustModulesIndex violates equals / hashCode contract for Value parameter
        at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:63)
        at com.intellij.testFramework.TestLogger.error(TestLogger.java:38)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
        at com.intellij.util.indexing.MapReduceIndex.checkValuesHaveProperEqualsAndHashCode(MapReduceIndex.java:755)
        at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:456)
        at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1656)
        at com.intellij.util.indexing.FileBasedIndexImpl$19.run(FileBasedIndexImpl.java:1586)
        at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:510)
        at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1541)
        at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1526)
        at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:108)
        at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
        at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:226)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1063)
        at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:246)
        at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:472)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:421)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
        at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:240)
        at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:472)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:421)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
        at com.intellij.openapi.project.CacheUpdateRunner.processSomeFilesWhileUserIsInactive(CacheUpdateRunner.java:125)
        at com.intellij.openapi.project.CacheUpdateRunner.processFiles(CacheUpdateRunner.java:84)
        at com.intellij.util.indexing.UnindexedFilesUpdater.indexFiles(UnindexedFilesUpdater.java:105)
        at com.intellij.util.indexing.UnindexedFilesUpdater.updateUnindexedFiles(UnindexedFilesUpdater.java:99)
        at com.intellij.util.indexing.UnindexedFilesUpdater.performInDumbMode(UnindexedFilesUpdater.java:117)
        at com.intellij.openapi.project.DumbServiceImpl.queueTask(DumbServiceImpl.java:176)
        at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.doSynchronizeRoots(ProjectRootManagerComponent.java:298)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:419)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$100(ProjectRootManagerImpl.java:55)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.fireChange(ProjectRootManagerImpl.java:112)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:125)
        at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:357)
        at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModel(ModuleManagerImpl.java:950)
        at com.intellij.openapi.module.impl.ModuleManagerImpl.access$1800(ModuleManagerImpl.java:71)
        at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.commitWithRunnable(ModuleManagerImpl.java:856)
        at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.access$1600(ModuleManagerImpl.java:617)
        at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModelWithRunnable(ModuleManagerImpl.java:608)
        at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:48)
        at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:37)
        at com.intellij.openapi.roots.impl.ModuleRootManagerImpl.commitModel(ModuleRootManagerImpl.java:178)
        at com.intellij.openapi.roots.impl.RootModelImpl.commit(RootModelImpl.java:338)
        at com.intellij.openapi.roots.ModuleRootModificationUtil$8.run(ModuleRootModificationUtil.java:167)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:935)
        at com.intellij.openapi.roots.ModuleRootModificationUtil$10.run(ModuleRootModificationUtil.java:208)
        at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:663)
        at com.intellij.openapi.roots.ModuleRootModificationUtil.doWriteAction(ModuleRootModificationUtil.java:205)
        at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:164)
        at org.rust.cargo.util.ModuleUtilKt.updateLibrary(ModuleUtil.kt:114)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.updateModuleDependencies(CargoProjectWorkspaceImpl.kt:133)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.access$updateModuleDependencies(CargoProjectWorkspaceImpl.kt:36)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$commitUpdate$1.invoke(CargoProjectWorkspaceImpl.kt:115)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$commitUpdate$1.invoke(CargoProjectWorkspaceImpl.kt:36)
        at org.rust.ide.utils.PlatformUtilsKt.runWriteAction(PlatformUtils.kt:18)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.commitUpdate(CargoProjectWorkspaceImpl.kt:113)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.access$commitUpdate(CargoProjectWorkspaceImpl.kt:36)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$UpdateTask.onSuccess(CargoProjectWorkspaceImpl.kt:177)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:390)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
        at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:305)
        at com.intellij.openapi.progress.Task.queue(Task.java:83)
        at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.requestUpdateUsing(CargoProjectWorkspaceImpl.kt:88)
        at org.rust.cargo.toolchain.CargoProjectResolveTestCase.updateCargoProject(CargoProjectResolveTestCase.kt:77)
        at org.rust.cargo.toolchain.CargoProjectResolveTestCase.access$updateCargoProject(CargoProjectResolveTestCase.kt:19)
        at org.rust.cargo.toolchain.CargoProjectResolveTestCase$testModuleRelations$1.invoke(CargoProjectResolveTestCase.kt:53)
        at org.rust.cargo.toolchain.CargoProjectResolveTestCase$testModuleRelations$1.invoke(CargoProjectResolveTestCase.kt:19)
        at org.rust.cargo.RustWithToolchainTestCaseBase.withProject(RustWithToolchainTestCaseBase.kt:27)
        at org.rust.cargo.toolchain.CargoProjectResolveTestCase.testModuleRelations(CargoProjectResolveTestCase.kt:47)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:154)
        at com.intellij.testFramework.UsefulTestCase.access$001(UsefulTestCase.java:80)
        at com.intellij.testFramework.UsefulTestCase.lambda$runTest$0(UsefulTestCase.java:326)
        at com.intellij.testFramework.PlatformTestCase.lambda$invokeTestRunnable$3(PlatformTestCase.java:737)
        at com.intellij.testFramework.PlatformTestCase.invokeTestRunnable(PlatformTestCase.java:749)
        at com.intellij.testFramework.UsefulTestCase.runTest(UsefulTestCase.java:341)
        at org.rust.cargo.RustWithToolchainTestCaseBase.runTest(RustWithToolchainTestCaseBase.kt:35)
        at com.intellij.testFramework.PlatformTestCase.lambda$runBareImpl$2(PlatformTestCase.java:666)
        at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
        at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
        at com.intellij.testFramework.EdtTestUtilKt$sam$Runnable$ca4818df.run(EdtTestUtil.kt)
        at com.intellij.openapi.application.TransactionGuardImpl$7.run(TransactionGuardImpl.java:294)
        at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:156)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:828)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:663)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:393)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

org.rust.cargo.toolchain.CargoProjectResolveTestCase > testModuleRelations FAILED
    java.lang.RuntimeException: java.lang.AssertionError

        Caused by:
        java.lang.AssertionError
            at com.intellij.openapi.roots.impl.RootModelImpl.dispose(RootModelImpl.java:619)
            at com.intellij.openapi.roots.impl.ModuleRootManagerImpl$1.dispose(ModuleRootManagerImpl.java:124)
            at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:176)
            at org.rust.cargo.util.ModuleUtilKt.updateLibrary(ModuleUtil.kt:114)
            at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.updateModuleDependencies(CargoProjectWorkspaceImpl.kt:133)
            at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.access$updateModuleDependencies(CargoProjectWorkspaceImpl.kt:36)
            at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$commitUpdate$1.invoke(CargoProjectWorkspaceImpl.kt:115)
            at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$commitUpdate$1.invoke(CargoProjectWorkspaceImpl.kt:36)
            at org.rust.ide.utils.PlatformUtilsKt.runWriteAction(PlatformUtils.kt:18)
            at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.commitUpdate(CargoProjectWorkspaceImpl.kt:113)
            at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.access$commitUpdate(CargoProjectWorkspaceImpl.kt:36)
            at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$UpdateTask.onSuccess(CargoProjectWorkspaceImpl.kt:177)
            at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:390)
            at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
            at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:305)
            at com.intellij.openapi.progress.Task.queue(Task.java:83)
            at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.requestUpdateUsing(CargoProjectWorkspaceImpl.kt:88)
            at org.rust.cargo.toolchain.CargoProjectResolveTestCase.updateCargoProject(CargoProjectResolveTestCase.kt:77)
            at org.rust.cargo.toolchain.CargoProjectResolveTestCase.access$updateCargoProject(CargoProjectResolveTestCase.kt:19)
            at org.rust.cargo.toolchain.CargoProjectResolveTestCase$testModuleRelations$1.invoke(CargoProjectResolveTestCase.kt:53)
            at org.rust.cargo.toolchain.CargoProjectResolveTestCase$testModuleRelations$1.invoke(CargoProjectResolveTestCase.kt:19)
            at org.rust.cargo.RustWithToolchainTestCaseBase.withProject(RustWithToolchainTestCaseBase.kt:27)
            at org.rust.cargo.toolchain.CargoProjectResolveTestCase.testModuleRelations(CargoProjectResolveTestCase.kt:47)

3 tests completed, 1 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/matklad/projects/intellij-rust/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 28.995 secs
```
