### ISSUE TITLE
NoSuchMethodError on Search Everywhere in CLion 2019.3 Nightly

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#4166]
## Environment

* **IntelliJ Rust plugin version:** 0.2.102.2688-192-nightly
* **Rust toolchain version:** rustc 1.36.0 (a53f9df32 2019-07-03)
* **IDE name and version:** CLion 2019.3 Nightly 193.1465
* **Operating system:** macOS 10.14.4

## Problem description

The following exception is raised by the plugin when I open Search Everywhere (double-Shift) and start typing something:

```
java.lang.NoSuchMethodError: com.intellij.ui.layout.LayoutBuilderImpl.newRow(Ljavax/swing/JLabel;Ljavax/swing/ButtonGroup;Z)Lcom/intellij/ui/layout/Row;
	at org.rust.ide.settings.RsAutoImportOptions.createComponent(RsAutoImportOptions.kt:50)
	at com.intellij.application.options.editor.AutoImportOptionsConfigurable.createComponent(AutoImportOptionsConfigurable.java:71)
	at com.intellij.ide.ui.ConfigurableOptionsTopHitProvider.getOptions(ConfigurableOptionsTopHitProvider.java:137)
	at com.intellij.ide.ui.OptionsTopHitProvider.getCachedOptions(OptionsTopHitProvider.java:89)
	at com.intellij.ide.ui.OptionsTopHitProvider.consumeTopHitsForApplicableProvider(OptionsTopHitProvider.java:130)
	at com.intellij.ide.ui.OptionsTopHitProvider.doConsumeTopHits(OptionsTopHitProvider.java:122)
	at com.intellij.ide.ui.OptionsTopHitProvider.consumeTopHits(OptionsTopHitProvider.java:111)
	at com.intellij.ide.ui.OptionsTopHitProvider.consumeTopHits(OptionsTopHitProvider.java:100)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processTopHits(GotoActionItemProvider.java:111)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:76)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchElements(ActionSearchEverywhereContributor.java:90)
	at com.intellij.ide.actions.searcheverywhere.MultiThreadSearcher$ContributorSearchTask.lambda$run$1(MultiThreadSearcher.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.ide.actions.searcheverywhere.MultiThreadSearcher$ContributorSearchTask.run(MultiThreadSearcher.java:176)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:301)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Undin** [comment]
Already fixed
