### ISSUE TITLE
NoSuchMethodError trying to create new run configuration with right-click menu

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#4171]
## Environment

* **IntelliJ Rust plugin version:** 0.2.102.2690-192-nightly
* **Rust toolchain version:** rustc 1.36.0 (a53f9df32 2019-07-03)
* **IDE name and version:** CLion 2019.3 Nightly 193.1511
* **Operating system:** macOS 10.14.4

## Problem description

There is an option in right-click menu inside the editor to create a run configuration for a given file:

<img width="567" alt="create" src="https://user-images.githubusercontent.com/2500320/61623724-e0920200-ac7f-11e9-9fe4-dc1330c16278.png">

Unfortunately, clicking it raises a `NoSuchMethodError` exception:

```
java.lang.NoSuchMethodError: com.intellij.ui.layout.LayoutBuilderImpl.newRow(Ljavax/swing/JLabel;Ljavax/swing/ButtonGroup;Z)Lcom/intellij/ui/layout/Row;
	at org.rust.cargo.runconfig.ui.CargoCommandConfigurationEditor.labeledRow(CargoCommandConfigurationEditor.kt:205)
	at org.rust.cargo.runconfig.ui.CargoCommandConfigurationEditor.createEditor(CargoCommandConfigurationEditor.kt:141)
	at com.intellij.openapi.options.SettingsEditor.getComponent(SettingsEditor.java:94)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.createEditor(ConfigurationSettingsEditor.java:298)
	at com.intellij.openapi.options.SettingsEditor.getComponent(SettingsEditor.java:94)
	at com.intellij.openapi.options.GroupSettingsBuilder.doCreateComponent(GroupSettingsBuilder.java:57)
	at com.intellij.openapi.options.GroupSettingsBuilder.createCompoundEditor(GroupSettingsBuilder.java:49)
	at com.intellij.openapi.options.CompositeSettingsEditor.createEditor(CompositeSettingsEditor.java:106)
	at com.intellij.openapi.options.SettingsEditor.getComponent(SettingsEditor.java:94)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.createEditor(ConfigurationSettingsEditorWrapper.java:86)
	at com.intellij.openapi.options.SettingsEditor.getComponent(SettingsEditor.java:94)
	at com.intellij.openapi.options.SettingsEditorConfigurable.<init>(SettingsEditorConfigurable.java:25)
	at com.intellij.execution.impl.BaseRCSettingsConfigurable.<init>(BaseRCSettingsConfigurable.java:18)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.<init>(SingleConfigurationConfigurable.java:68)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:105)
	at com.intellij.execution.impl.RunDialog.editConfiguration(RunDialog.java:103)
	at com.intellij.execution.impl.RunDialog.editConfiguration(RunDialog.java:94)
	at com.intellij.execution.actions.CreateAction$CreateAndEditPolicy.perform(CreateAction.java:76)
	at com.intellij.execution.actions.CreateAction.perform(CreateAction.java:22)
	at com.intellij.execution.actions.BaseRunConfigurationAction.lambda$perform$0(BaseRunConfigurationAction.java:167)
	at com.intellij.execution.actions.RunConfigurationProducer.onFirstRun(RunConfigurationProducer.java:180)
	at com.intellij.execution.actions.ConfigurationFromContextImpl.onFirstRun(ConfigurationFromContextImpl.java:71)
	at com.intellij.execution.actions.BaseRunConfigurationAction.perform(BaseRunConfigurationAction.java:167)
	at com.intellij.execution.actions.BaseRunConfigurationAction.actionPerformed(BaseRunConfigurationAction.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:293)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:265)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:107)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:283)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:115)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:525)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:547)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:928)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:877)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:802)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:464)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:463)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by lancelote** [comment]
Also can't edit existed Rust run configurations.

**Comment by Undin** [comment]
Already fixed
