### ISSUE TITLE
Error in the new macro expansion engine breaks syntax highlighting

### ISSUE THREAD

**Issue by dvdplm** [intellij-rust/intellij-rust#4370]
## Environment 

* **IntelliJ Rust plugin version:** 0.2.105.2732-192-nightly
* **Rust toolchain version:** rustc 1.39.0-nightly (2b8116dce 2019-09-08)
* **IDE name and version:** CLion 2019.2.1, Build #CL-192.6262.62
* **Operating system:** Macos

## Problem description
When I updated the rust plugin this morning the syntax highlighting was broken. When CLion opens the last opened active file is partially syntax highlighted but no other files are (already open or opened during the session). Only the basic highlighting works, e.g. strings and numbers. Go to definition works for all types, but no syntax highlighting.

I have tried:
- restarting the IDE
- clearing all caches and restart
- disable/enable the plugin
- switch themes to use "Default"

## Steps to reproduce

Currently working on https://github.com/paritytech/parity-ethereum/ but I doubt that is relevant. As mentioned syntax highlighting worked fine until this morning.

Screenshot: 
<img width="702" alt="image" src="https://user-images.githubusercontent.com/18515/64518067-c96fa800-d2f1-11e9-95f5-bb5d048cb4f9.png">

**Comment by vlad20012** [comment]
Could you please attach your logs collected via ctrl+shift+A "Compress Logs" action

**Comment by dvdplm** [comment]
@vlad20012 here goes: [clion-logs-20190909-121401.zip](https://github.com/intellij-rust/intellij-rust/files/3589933/clion-logs-20190909-121401.zip)

**Comment by vlad20012** [comment]
Looks like the problem is in the new macro expansion engine. "Invalidate caches & restart" should help, but if it doesn't help (as you said), I can only suggest to disable the new engine. It is experimental, so such things are expected

**Comment by dvdplm** [comment]
> disable the new engine

You are correct. With the old macro engine syntax highlighting is back.

> so such things are expected

Sure. It'd be nice to see an error ofc. ;)

Should I open a different ticket for this or is this enough?

**Comment by vlad20012** [comment]
> Should I open a different ticket for this or is this enough?

This is enough.

<details>
  <summary>Stacktrace from the logs</summary>

```
2019-09-09 11:11:59,379 [1485911]  ERROR - aemon.impl.PassExecutorService - class org.rust.lang.core.psi.impl.RsValueParameterImpl cannot be cast to class org.rust.lang.core.psi.RsMacroCall (org.rust.lang.core.psi.impl.RsValueParameterImpl and org.rust.lang.core.psi.RsMacroCall are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @697551a6) 
java.lang.ClassCastException: class org.rust.lang.core.psi.impl.RsValueParameterImpl cannot be cast to class org.rust.lang.core.psi.RsMacroCall (org.rust.lang.core.psi.impl.RsValueParameterImpl and org.rust.lang.core.psi.RsMacroCall are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @697551a6)
	at org.rust.lang.core.macros.SourceFile.stubBasedRebind(ExpandedMacroStorage.kt:362)
	at org.rust.lang.core.macros.SourceFile.access$stubBasedRebind(ExpandedMacroStorage.kt:247)
	at org.rust.lang.core.macros.SourceFile$rebind$1.run(ExpandedMacroStorage.kt:343)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:197)
	at org.rust.lang.core.macros.SourceFile.rebind(ExpandedMacroStorage.kt:336)
	at org.rust.lang.core.macros.SourceFile.rebind$default(ExpandedMacroStorage.kt:312)
	at org.rust.lang.core.macros.SourceFile.getInfoForCall(ExpandedMacroStorage.kt:459)
	at org.rust.lang.core.macros.ExpandedMacroStorage.getInfoForCall(ExpandedMacroStorage.kt:192)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.getExpansionFor(MacroExpansionManager.kt:619)
	at org.rust.lang.core.macros.MacroExpansionManagerImpl.getExpansionFor(MacroExpansionManager.kt:150)
	at org.rust.lang.core.psi.ext.RsMacroCallKt$expansion$1.compute(RsMacroCall.kt:122)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at org.rust.lang.core.psi.ext.RsMacroCallKt.getExpansion(RsMacroCall.kt:114)
	at org.rust.lang.core.psi.ext.RsMacroCallKt.processExpansionRecursively(RsMacroCall.kt:148)
	at org.rust.lang.core.psi.ext.RsMacroCallKt.processExpansionRecursively(RsMacroCall.kt:144)
	at org.rust.lang.core.psi.ext.RsItemsOwnerKt.processItem(RsItemsOwner.kt:121)
	at org.rust.lang.core.psi.ext.RsItemsOwnerKt.processExpandedItemsInternal(RsItemsOwner.kt:114)
	at org.rust.lang.core.psi.ext.RsItemsOwnerKt.access$processExpandedItemsInternal(RsItemsOwner.kt:1)
	at org.rust.lang.core.psi.ext.RsItemsOwnerKt$expandedItemsCached$1.compute(RsItemsOwner.kt:63)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at org.rust.lang.core.psi.ext.RsItemsOwnerKt.getExpandedItemsCached(RsItemsOwner.kt:59)
	at org.rust.lang.core.resolve.ItemResolutionKt.processItemDeclarations(ItemResolution.kt:62)
	at org.rust.lang.core.resolve.ItemResolutionKt$processItemDeclarationsWithCache$cached$1.compute(ItemResolution.kt:278)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at org.rust.lang.core.resolve.ItemResolutionKt.processItemDeclarationsWithCache(ItemResolution.kt:276)
	at org.rust.lang.core.resolve.NameResolutionKt.processLexicalDeclarations(NameResolution.kt:1219)
	at org.rust.lang.core.resolve.NameResolutionKt.access$processLexicalDeclarations(NameResolution.kt:1)
	at org.rust.lang.core.resolve.NameResolutionKt$processNestedScopesUpwards$stop$2.invoke(NameResolution.kt:1348)
	at org.rust.lang.core.resolve.NameResolutionKt$processNestedScopesUpwards$stop$2.invoke(NameResolution.kt)
	at org.rust.lang.core.resolve.NameResolutionKt.walkUp(NameResolution.kt:1458)
	at org.rust.lang.core.resolve.NameResolutionKt.walkUp$default(NameResolution.kt:1451)
	at org.rust.lang.core.resolve.NameResolutionKt.processNestedScopesUpwards(NameResolution.kt:1341)
	at org.rust.lang.core.resolve.NameResolutionKt.processUnqualifiedPathResolveVariants(NameResolution.kt:518)
	at org.rust.lang.core.resolve.NameResolutionKt.processPathResolveVariants(NameResolution.kt:343)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt$resolvePath$result$1.invoke(RsPathReferenceImpl.kt:85)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt$resolvePath$result$1.invoke(RsPathReferenceImpl.kt)
	at org.rust.lang.core.resolve.ProcessorsKt.collectPathResolveVariants(Processors.kt:60)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt.resolvePath(RsPathReferenceImpl.kt:84)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt.resolvePath$default(RsPathReferenceImpl.kt:83)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$Resolver.invoke(RsPathReferenceImpl.kt:72)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$Resolver.invoke(RsPathReferenceImpl.kt:70)
	at org.rust.lang.core.resolve.ref.RsResolveCache$resolveWithCaching$$inlined$run$lambda$1.invoke(RsResolveCache.kt:94)
	at org.rust.lang.core.resolve.ref.RecursionGuardWrapper$sam$com_intellij_openapi_util_Computable$0.compute(RecursionGuardWrapper.kt)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at org.rust.lang.core.resolve.ref.RecursionGuardWrapper.doPreventingRecursion(RecursionGuardWrapper.kt:15)
	at org.rust.lang.core.resolve.ref.RsResolveCache.resolveWithCaching(RsResolveCache.kt:94)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.advancedCachedMultiResolve(RsPathReferenceImpl.kt:63)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.advancedMultiResolve(RsPathReferenceImpl.kt:59)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.advancedResolve(RsPathReferenceImpl.kt:48)
	at org.rust.lang.core.psi.ext.RsTraitRefKt.resolveToBoundTrait(RsTraitRef.kt:16)
	at org.rust.lang.core.resolve.RsCachedImplItem$implementedTrait$2.invoke(RsCachedImplItem.kt:35)
	at org.rust.lang.core.resolve.RsCachedImplItem$implementedTrait$2.invoke(RsCachedImplItem.kt:30)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.rust.lang.core.resolve.RsCachedImplItem.getImplementedTrait(RsCachedImplItem.kt)
	at org.rust.lang.core.resolve.ImplLookup$assembleImplCandidates$1.invoke(ImplLookup.kt:525)
	at org.rust.lang.core.resolve.ImplLookup$assembleImplCandidates$1.invoke(ImplLookup.kt:178)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:702)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:732)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:723)
	at org.rust.lang.core.resolve.ImplLookup.assembleImplCandidates(ImplLookup.kt:520)
	at org.rust.lang.core.resolve.ImplLookup.assembleCandidates(ImplLookup.kt:503)
	at org.rust.lang.core.resolve.ImplLookup.selectCandidate(ImplLookup.kt:427)
	at org.rust.lang.core.resolve.ImplLookup.access$selectCandidate(ImplLookup.kt:178)
	at org.rust.lang.core.resolve.ImplLookup$selectWithoutConfirm$2.invoke(ImplLookup.kt:417)
	at org.rust.lang.core.resolve.ImplLookup$selectWithoutConfirm$2.invoke(ImplLookup.kt:178)
	at org.rust.stdext.Cache$Companion$fromConcurrentMap$1.getOrPut(Cache.kt:41)
	at org.rust.lang.core.resolve.ImplLookup.selectWithoutConfirm(ImplLookup.kt:417)
	at org.rust.lang.core.resolve.ImplLookup.select(ImplLookup.kt:412)
	at org.rust.lang.core.resolve.ImplLookup.selectProjection(ImplLookup.kt:660)
	at org.rust.lang.core.resolve.ImplLookup.selectProjection$default(ImplLookup.kt:658)
	at org.rust.lang.core.resolve.ImplLookup.selectProjection(ImplLookup.kt:652)
	at org.rust.lang.core.resolve.ImplLookup.access$selectProjection(ImplLookup.kt:178)
	at org.rust.lang.core.resolve.ImplLookup$asTyFunction$$inlined$run$lambda$1.invoke(ImplLookup.kt:738)
	at org.rust.lang.core.resolve.ImplLookup$asTyFunction$$inlined$run$lambda$1.invoke(ImplLookup.kt:178)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:129)
	at org.rust.lang.core.resolve.ImplLookup.asTyFunction(ImplLookup.kt:739)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferCallExprType(TypeInferenceWalker.kt:550)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:166)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferTypeCoercableTo(TypeInferenceWalker.kt:195)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferStructTypeArguments(TypeInferenceWalker.kt:516)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferStructLiteralType(TypeInferenceWalker.kt:502)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:161)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferTypeCoercableTo(TypeInferenceWalker.kt:195)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:118)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferTypeCoercableTo(TypeInferenceWalker.kt:94)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferFnBody(TypeInferenceWalker.kt:82)
	at org.rust.lang.core.types.infer.RsInferenceContext.infer(TypeInference.kt:169)
	at org.rust.lang.core.types.infer.TypeInferenceKt$inferTypesIn$1.compute(TypeInference.kt:31)
	at org.rust.lang.core.types.infer.TypeInferenceKt$inferTypesIn$1.compute(TypeInference.kt)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at org.rust.openapiext.UtilsKt.recursionGuard(utils.kt:62)
	at org.rust.lang.core.types.infer.TypeInferenceKt.inferTypesIn(TypeInference.kt:31)
	at org.rust.lang.core.types.ExtensionsKt$inference$1.compute(Extensions.kt:66)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:65)
	at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:140)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.advancedMultiResolve(RsPathReferenceImpl.kt:58)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.multiResolve(RsPathReferenceImpl.kt:51)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.resolve(RsReferenceBase.kt:28)
	at org.rust.lang.core.types.ExtensionsKt.getDeclaration(Extensions.kt:94)
	at org.rust.lang.core.types.ExtensionsKt.getDeclaration(Extensions.kt:96)
	at org.rust.ide.hints.RsInlayTypeHintsProvider$getCollectorFor$1.presentTypeForPat(RsInlayTypeHintsProvider.kt:145)
	at org.rust.ide.hints.RsInlayTypeHintsProvider$getCollectorFor$1.presentVariable(RsInlayTypeHintsProvider.kt:112)
	at org.rust.ide.hints.RsInlayTypeHintsProvider$getCollectorFor$1.collect(RsInlayTypeHintsProvider.kt:95)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:70)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation(InlayHintsPass.kt:22)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
</details>
