### ISSUE TITLE
Can't install nighlty plugin on nightly CLion 2020.1: ClassCastException

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#4637]
## Environment

* **IntelliJ Rust plugin version:** 0.2.110.2787-193-nightly
* **Rust toolchain version:** rustc 1.38.0 (625451e37 2019-09-23)
* **IDE name and version:** CLion 201.1285
* **Operating system:** macOS 10.15

## Problem description

I have `https://plugins.jetbrains.com/plugins/nightly/8182` plugin repository configured, trying to install latest Rust Plugin fails and raises the following exception

```
java.lang.ClassCastException: class com.intellij.ide.plugins.PluginNode cannot be cast to class com.intellij.ide.plugins.IdeaPluginDescriptorImpl (com.intellij.ide.plugins.PluginNode and com.intellij.ide.plugins.IdeaPluginDescriptorImpl are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @39aeed2f)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstall(PluginInstallOperation.java:241)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstall(PluginInstallOperation.java:130)
	at com.intellij.ide.plugins.PluginInstallOperation.run(PluginInstallOperation.java:67)
	at com.intellij.ide.plugins.newui.MyPluginModel.lambda$installPlugin$6(MyPluginModel.java:384)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:242)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Undin** [comment]
@lancelote Look like it's a bug in platform master. Please, file bug in IDEA tracker

**Comment by lancelote** [comment]
Thanks, done https://youtrack.jetbrains.com/issue/IDEA-226962
