### ISSUE TITLE
IllegalStateException in RustTypeInferenceEngine

### ISSUE THREAD

**Issue by jajakobyly** [intellij-rust/intellij-rust#471]
I have no idea when this has happened, build `0.0.1.667`

```
Check failed.
java.lang.IllegalStateException: Check failed.
	at org.rust.lang.core.types.visitors.RustTypeInferenceEngine.inferPatBindingTypeFrom(RustTypeInferenceEngine.kt:16)
	at org.rust.lang.core.types.visitors.RustTypificationEngine.deviseBoundPatType(RustTypificationEngine.kt:56)
	at org.rust.lang.core.types.visitors.RustTypificationEngine.typify(RustTypificationEngine.kt:38)
	at org.rust.lang.core.types.visitors.RustExprTypificationVisitor.visitPathExpr(RustTypificationEngine.kt:92)
	at org.rust.lang.core.psi.impl.RustPathExprElementImpl.accept(RustPathExprElementImpl.java:20)
	at org.rust.lang.core.psi.impl.RustPathExprElementImpl.accept(RustPathExprElementImpl.java:24)
	at org.rust.lang.core.types.visitors.RustTypificationEngine.typifyExpr(RustTypificationEngine.kt:22)
	at org.rust.lang.core.types.util.RustPsiExtensionsKt$resolvedType$1.compute(RustPsiExtensions.kt:17)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:84)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:133)
	at org.rust.lang.core.types.util.RustPsiExtensionsKt.getResolvedType(RustPsiExtensions.kt:15)
	at org.rust.lang.core.resolve.RustResolveEngine.resolveMethodCallExpr(RustResolveEngine.kt:128)
	at org.rust.lang.core.resolve.ref.RustMethodCallReferenceImpl.resolveVerbose(RustMethodCallReferenceImpl.kt:15)
	at org.rust.lang.core.resolve.ref.RustReferenceBase.resolve(RustReferenceBase.kt:24)
	at org.rust.lang.core.resolve.ref.RustReferenceBase.resolve(RustReferenceBase.kt:11)
	at com.intellij.psi.PsiReferenceBase.isReferenceTo(PsiReferenceBase.java:128)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:52)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$15.execute(PsiSearchHelperImpl.java:762)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.a(LowLevelSearchUtil.java:129)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.access$000(LowLevelSearchUtil.java:42)
	at com.intellij.psi.impl.search.LowLevelSearchUtil$1.execute(LowLevelSearchUtil.java:199)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTextOccurrences(LowLevelSearchUtil.java:242)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:195)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:199)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:187)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:31)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.JobLauncherImpl$2$1.run(JobLauncherImpl.java:148)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.JobLauncherImpl$2.run(JobLauncherImpl.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.concurrency.JobLauncherImpl.a(JobLauncherImpl.java:158)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:96)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processElementsWithWord(PsiSearchHelperImpl.java:207)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.b(PsiSearchHelperImpl.java:949)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:620)
	at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:84)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:78)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.a(IdentifierHighlighterPass.java:157)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getHighlightUsages(IdentifierHighlighterPass.java:133)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.a(IdentifierHighlighterPass.java:189)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by matklad** [comment]
Yep, I've hit this yesterday, and just about to fix it. You probably have a code like this

```
let foo = {
    if let Some(x) /* this will cause the exception */ = bar {

    }
}

```
