### ISSUE TITLE
Exception while running RsHighlightingPerformanceTest#test highlighting Cargo test

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#4965]
## Environment

* **IntelliJ Rust plugin version:**
* **Rust toolchain version:** rustc 1.41.0 (5e1a79984 2020-01-27) stable-x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2019.3.3 (IU-193.6494.35)
* **Operating system:** macOS 10.13.6

## Problem description
<details><summary>stacktrace</summary>

```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type PATH (class org.rust.lang.core.stubs.RsPathStub$Type)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:96)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:253)
	at org.rust.lang.core.resolve.ref.RsResolveCache.refineDependency(RsResolveCache.kt:110)
	at org.rust.lang.core.resolve.ref.RsResolveCache.resolveWithCaching(RsResolveCache.kt:91)
	at org.rust.lang.core.resolve.ref.RsMacroPathReferenceImpl.resolve(RsMacroPathReferenceImpl.kt:60)
	at org.rust.lang.core.resolve.ref.RsMacroPathReferenceImpl.resolve(RsMacroPathReferenceImpl.kt:39)
	at org.rustPerformanceTests.RsHighlightingPerformanceTest$highlightProjectFile$$inlined$forEach$lambda$1.invoke(RsHighlightingPerformanceTest.kt:81)
	at org.rustPerformanceTests.RsHighlightingPerformanceTest$highlightProjectFile$$inlined$forEach$lambda$1.invoke(RsHighlightingPerformanceTest.kt:21)
	at org.rust.stdext.Timings.measureInternal(Profiling.kt:32)
	at org.rust.stdext.Timings.measureAverage(Profiling.kt:28)
	at org.rustPerformanceTests.RsHighlightingPerformanceTest.highlightProjectFile(RsHighlightingPerformanceTest.kt:80)
	at org.rustPerformanceTests.RsHighlightingPerformanceTest.access$highlightProjectFile(RsHighlightingPerformanceTest.kt:21)
	at org.rustPerformanceTests.RsHighlightingPerformanceTest$test highlighting Cargo$1.invoke(RsHighlightingPerformanceTest.kt:27)
	at org.rustPerformanceTests.RsHighlightingPerformanceTest$test highlighting Cargo$1.invoke(RsHighlightingPerformanceTest.kt:21)
	at org.rustPerformanceTests.RsHighlightingPerformanceTest$repeatTest$1.invoke(RsHighlightingPerformanceTest.kt:39)
	at org.rustPerformanceTests.RsHighlightingPerformanceTest$repeatTest$1.invoke(RsHighlightingPerformanceTest.kt:21)
	at org.rust.stdext.ProfilingKt$repeatBenchmarkInternal$$inlined$repeat$lambda$1.invoke(Profiling.kt:125)
	at org.rust.stdext.ProfilingKt$repeatBenchmarkInternal$$inlined$repeat$lambda$1.invoke(Profiling.kt)
	at org.rust.stdext.ListTimings.add(Profiling.kt:66)
	at org.rust.stdext.ProfilingKt.repeatBenchmarkInternal(Profiling.kt:124)
	at org.rust.stdext.ProfilingKt.repeatBenchmark(Profiling.kt:116)
	at org.rust.stdext.ProfilingKt.repeatBenchmark$default(Profiling.kt:115)
	at org.rustPerformanceTests.RsHighlightingPerformanceTest.repeatTest(RsHighlightingPerformanceTest.kt:37)
	at org.rustPerformanceTests.RsHighlightingPerformanceTest.test highlighting Cargo(RsHighlightingPerformanceTest.kt:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.intellij.testFramework.UsefulTestCase.lambda$runTest$12(UsefulTestCase.java:337)
	at com.intellij.testFramework.UsefulTestCase.lambda$invokeTestRunnable$13(UsefulTestCase.java:374)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:44)
	at com.intellij.testFramework.UsefulTestCase.invokeTestRunnable(UsefulTestCase.java:373)
	at com.intellij.testFramework.UsefulTestCase.runTest(UsefulTestCase.java:356)
	at org.rust.cargo.RsWithToolchainTestBase.runTest(RsWithToolchainTestBase.kt:58)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:391)
	... 17 more
```
</details>

## Steps to reproduce

Just run `org.rustPerformanceTests.RsHighlightingPerformanceTest#test highlighting Cargo` test

**Comment by vlad20012** [comment]
Pls add the last commit hash of your "testData/cargo" repo

**Comment by Undin** [comment]
https://github.com/rust-lang/cargo/tree/a491aa7179bbcab817d937af33e1b91bf214c316
