### ISSUE TITLE
ISE when opened in LightEdit mode

### ISSUE THREAD

**Issue by ice1000** [intellij-rust/intellij-rust#5001]
## Environment

* **IDE name and version:** CLion 201.5616.31
* **Operating system:** Windows 10

## Problem description

<details>
<summary>
Click to see
</summary>

```
java.lang.IllegalStateException: getComponent(MacroExpansionManager::class.java) must not be null
	at org.rust.lang.core.macros.MacroExpansionManagerKt.getMacroExpansionManager(MacroExpansionManager.kt:874)
	at org.rust.lang.core.macros.RsMacroExpansionWritingAccessProvider.isPotentiallyWritable(RsMacroExpansionWritingAccessProvider.kt:21)
	at com.intellij.openapi.vcs.readOnlyHandler.ReadonlyStatusHandlerImpl.lambda$null$0(ReadonlyStatusHandlerImpl.java:89)
	at com.intellij.util.containers.ContainerUtil.findAll(ContainerUtil.java:1176)
	at com.intellij.util.containers.ContainerUtil.filter(ContainerUtil.java:1155)
	at com.intellij.openapi.vcs.readOnlyHandler.ReadonlyStatusHandlerImpl.lambda$ensureFilesWritable$1(ReadonlyStatusHandlerImpl.java:89)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:45)
	at com.intellij.openapi.extensions.ProjectExtensionPointName.computeSafeIfAny(ProjectExtensionPointName.java:58)
	at com.intellij.openapi.vcs.readOnlyHandler.ReadonlyStatusHandlerImpl.ensureFilesWritable(ReadonlyStatusHandlerImpl.java:88)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.requestWritingStatus(FileDocumentManagerImpl.java:526)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.requestWriting(FileDocumentManagerImpl.java:516)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.runProcessFile(AbstractLayoutCodeProcessor.java:283)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.run(AbstractLayoutCodeProcessor.java:221)
	at com.intellij.codeInsight.actions.FileInEditorProcessor.processCode(FileInEditorProcessor.java:123)
	at com.intellij.codeInsight.actions.ReformatCodeAction.actionPerformed(ReformatCodeAction.java:140)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:289)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:606)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:667)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:666)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:616)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:513)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:216)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:896)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:740)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:832)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>

## Steps to reproduce

+ Open a C++ file in LightEdit mode
+ Ctrl+Shift+A

**Comment by vlad20012** [comment]
I can't invoke ctrl+shift+A on the latest EAP

**Comment by ice1000** [comment]
Ok
