### ISSUE TITLE
Local history doesn't work with Intellij IDEA

### ISSUE THREAD

**Issue by mrcosta** [intellij-rust/intellij-rust#5178]
## Environment

* **IntelliJ Rust plugin version:** Rust 0.2.119.2172-193
* **Rust toolchain version:** rustc 1.42.0 (b8cedc004 2020-03-09)
* **IDE name and version:** 
IntelliJ IDEA 2019.3.4 (Community Edition)
Build #IC-193.6911.18, built on March 17, 2020
Runtime version: 11.0.6+8-b520.43 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: 
Non-Bundled Plugins: IdeaVIM, org.toml.lang, org.rust.lang
* **Operating system:** macOS 10.15.3

## Problem description
With `0.2.119.2172-193` when I go to Local History for a file, I see the entries that the file has in the left side, but the content isn't shown.

![image](https://user-images.githubusercontent.com/4819516/78235262-aa787380-74d8-11ea-9697-2b2ccb7252ba.png)

If I disable the plugin, restart IDE and try again, it shows the diff.

This is what I see in the IDE logs when doing this specific action:
```
WARN - .history.utils.LocalHistoryLog - cannot revert ContentChange->file not found: /Users/mac/workspace/leis-municipais/src/parser.rs
2020-04-02 11:57:53,967 [ 967609]  ERROR - .history.utils.LocalHistoryLog - entry '/Users/mac/workspace/leis-municipais/src/parser.rs' not found
java.lang.RuntimeException: entry '/Users/mac/workspace/leis-municipais/src/parser.rs' not found
	at com.intellij.history.core.tree.Entry.getEntry(Entry.java:200)
	at com.intellij.history.core.revisions.CurrentRevision.findEntry(CurrentRevision.java:38)
	at com.intellij.history.integration.ui.models.HistoryDialogModel.getRightEntry(HistoryDialogModel.java:135)
	at com.intellij.history.integration.ui.models.EntireFileHistoryDialogModel.getDifferenceModel(EntireFileHistoryDialogModel.java:17)
	at com.intellij.history.integration.ui.views.FileHistoryDialog.doUpdateDiffs(FileHistoryDialog.java:75)
	at com.intellij.history.integration.ui.views.FileHistoryDialog.doUpdateDiffs(FileHistoryDialog.java:38)
	at com.intellij.history.integration.ui.views.HistoryDialog.lambda$scheduleDiffUpdate$2(HistoryDialog.java:240)
	at com.intellij.history.integration.ui.views.HistoryDialog$4.run(HistoryDialog.java:266)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:324)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:314)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:264)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:278)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:233)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:371)
	at com.intellij.util.Alarm$Request.run(Alarm.java:358)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:217)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-04-02 11:57:53,967 [ 967609]  ERROR - .history.utils.LocalHistoryLog - IntelliJ IDEA 2019.3.4  Build #IC-193.6911.18
2020-04-02 11:57:53,967 [ 967609]  ERROR - .history.utils.LocalHistoryLog - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o
2020-04-02 11:57:53,967 [ 967609]  ERROR - .history.utils.LocalHistoryLog - OS: Mac OS X
2020-04-02 11:57:53,967 [ 967609]  ERROR - .history.utils.LocalHistoryLog - Last Action: LocalHistory.ShowHistory
```
## Steps to reproduce

With the described environment it should be a matter of just changing a file in the project, saving it and trying to see its local history.

Let me know if I can provide more information. Thanks a lot.

**Comment by vlad20012** [comment]
I've reproduced

**Comment by mrcosta** [comment]
I've forgotten to mention, but I revert my plugin to `0.2.117.2170-193` and then it works fine. With `0.2.118` I also had the same problem.

**Comment by vlad20012** [comment]
@mrcosta, please, try the nightly IntelliJ Rust plugin (see [instructions](https://intellij-rust.github.io/install.html)), local history should be fixed there

**Comment by mrcosta** [comment]
@vlad20012 it works well. Good job and thanks for the quick response on that =)
