### ISSUE TITLE
Save settings failed

### ISSUE THREAD

**Issue by matdehaast** [intellij-rust/intellij-rust#5403]
## Environment

* **IntelliJ Rust plugin version:** 0.2.122.3104-201
* **Rust toolchain version:** rustc 1.43.1 (8d69840ab 2020-05-04)
* **IDE name and version:** 
PhpStorm 2020.1.1
Build #PS-201.7223.96, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-46-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1937M
Cores: 16
Registry: run.processes.with.pty=TRUE, editor.distraction.free.mode=true
Non-Bundled Plugins: com.alayouni.ansiHighlight, com.intellij.ideolog, mobi.hsz.idea.gitignore, org.jetbrains.plugins.go-template, BashSupport, com.intellij.kubernetes, com.intellij.plugins.html.instantEditing, ru.adelf.idea.dotenv, intellij.prettierJS, org.toml.lang, org.rust.lang
Current Desktop: ubuntu:GNOME

## Problem description
Everytime I enable the Rust Plugin and try save a I get the error shown below. It will disable the Rust plugin. I reboot the IDE then the Rust plugin is disabled, when I reenable it the error comes again.

> 15:23	Unable to save plugin settings: The plugin org.rust.lang failed to save settings and has been disabled. Please restart PhpStorm

The logs are showing 
```
2020-05-19 15:23:23,810 [  39550]   WARN - mponents.impl.stores.StoreUtil - Save settings failed 
java.lang.NoClassDefFoundError: org/apache/commons/io/output/ByteArrayOutputStream
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner$save$2$invokeSuspend$$inlined$runReadAction$1.compute(actions.kt:79)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner$save$2.invokeSuspend(MacroExpansionManager.kt:1064)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

I have tried uninstalling and reinstalling PHPStorm and the Rust Plugin as well as deleting the .idea file. Same issue

**Comment by matdehaast** [comment]
Manually downgrading to 0.2.121.3059-201-stable has solved the issue. So it seems the newest version released today has broken something

**Comment by vlad20012** [comment]
Looks like that class `org/apache/commons/io/output/ByteArrayOutputStream` is not available in PHPStorm. We'll release a hotfix soon

**Comment by matdehaast** [comment]
@vlad20012 thanks!

**Comment by Undin** [comment]
@matdehaast build with the corresponding fix is published. Could you check that everything works for you, please?

**Comment by matdehaast** [comment]
@Undin Can confirm that 0.2.122.3105-201 has resolved the issue. You are a machine thanks for the fast turnaround :fire:

**Comment by maximelkin** [comment]
Can you please also release this fix for WebStorm?

**Comment by Undin** [comment]
@maximelkin it's published for all IDEs
Could you please check if plugin has updates?

**Comment by maximelkin** [comment]
No plugin updates (to mentioned version), but after uninstall Webstorm suggested fresh version

Thanks for help!
