### ISSUE TITLE
Trying to change standard library location freezes PHPStorm with errors

### ISSUE THREAD

**Issue by Dragonrun1** [intellij-rust/intellij-rust#549]
I've just been starting with rust and ended up with a couple of copies of rust-1.10.0-src.zip downloaded so I decided to clean up a little and try pointing all projects to one in in my downloads but when I try changing the standard library setting to use the new location it freezes PHPStorm with error dump. Here the short description that PHPStorm gives me. let me know if you want the complete dump and I can grub one to sent you. BTW setting windows won't close so I have to x out every time.

**Comment by matklad** [comment]
Ouch, that's bad :( An error dump will be helpful of course!

**Comment by Dragonrun1** [comment]
Here it is:
`loader constraint violation: when resolving method "com.intellij.openapi.application.ActionsKt.runWriteAction(Lkotlin/jvm/functions/Function0;)Ljava/lang/Object;" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, org/rust/cargo/project/configurable/RustProjectConfigurable, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, com/intellij/openapi/application/ActionsKt, have different Class objects for the type kotlin/jvm/functions/Function0 used in the signature
java.lang.LinkageError: loader constraint violation: when resolving method "com.intellij.openapi.application.ActionsKt.runWriteAction(Lkotlin/jvm/functions/Function0;)Ljava/lang/Object;" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, org/rust/cargo/project/configurable/RustProjectConfigurable, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, com/intellij/openapi/application/ActionsKt, have different Class objects for the type kotlin/jvm/functions/Function0 used in the signature
	at org.rust.cargo.project.configurable.RustProjectConfigurable.apply(RustProjectConfigurable.kt:79)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.apply(ConfigurableWrapper.java:182)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.apply(ConfigurableEditor.java:319)
	at com.intellij.openapi.options.newEditor.SettingsEditor$5.apply(SettingsEditor.java:160)
	at com.intellij.openapi.options.newEditor.SettingsEditor.apply(SettingsEditor.java:332)
	at com.intellij.openapi.options.newEditor.SettingsDialog.doOKAction(SettingsDialog.java:153)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1843)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1809)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:695)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:455)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1665)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1607)
	at com.intellij.openapi.options.newEditor.SettingsDialog.access$101(SettingsDialog.java:41)
	at com.intellij.openapi.options.newEditor.SettingsDialog.a(SettingsDialog.java:77)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:283)
	at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:77)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:94)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:62)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:188)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:154)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:325)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:695)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by Dragonrun1** [comment]
Just kind of a side comment. The reason I'm needing to do this in part is by default on Windows it dumped the zip directly into $USER_HOME$ instead of something like my docs or even into %LOCALAPPDATA% which would have been better. Really bad form in Windows to dump things like that by default directing into the home directory. Also would have been nice to know it was look for the zip and not the unzipped directory that might have at least helped keep me from downloading it twice ;)

**Comment by matklad** [comment]
>is by default on Windows it dumped the zip directly 

Hm, "download" button in the in editor notification is supposed to show a dialog where you chose the folder to download to. 

Do you see the dialog to choose the directory on windows?

**Comment by Dragonrun1** [comment]
It does but when you have no idea what it's going to download and by default it showed the user directory knowing no better it ends up there. A better default and some kind of tool tip that shows it's looking for a zip file would go a long way to making it more user friendly. I think with both project I added it because of the "infer"? popup in the editor after creating the project. I know in my case since I know about cargo etc I figured it was looking for the unzip directory it builds it index on etc. so I was going into APPDATA and trying to point it at it but of course that wasn't what it wanted so that didn't work and after a few tries I just give up and let it download it instead. When I start a new project it asked again so ended up with a couple copies. It might be useful to have it keep a app wide copy of the directory from the last download  so you don't have to set it for each project if it find it there. Might just prompt to confirm in case user want to use multiple versions of rust since it is a bit unstable and they may need to test against multiple copies but even just filling last used should help alot with confused users like me ;)

**Comment by Dragonrun1** [comment]
See you already pushed fix any idea when that should show up as update?

**Comment by matklad** [comment]
It's already published to the nightly channel. If you use nighties, just check for updates.

If you don't use nightlies, you can install this version: https://plugins.jetbrains.com/plugin/download?pr=idea&updateId=27202 (via install plugin from disk action).

I think we'll push a new alpha today.

**Comment by matklad** [comment]
I agree that the UI for std library management is mightily confusing. Ideally, we'd rather not have it at all and instead use `rustup` or `cargo` to manage stdlib sources. Unfortunately they don't support this yet, but this is being worked on.

Offering the last downloaded stdlib is a nice idea, will try to implement it, thanks!

**Comment by matklad** [comment]
https://github.com/intellij-rust/intellij-rust/commit/6fe098a04440fb87330c4ab49348168dd42be3ad <- this should automatically attach the last used standard library. It is not ideal because you may want to use different versions of stdlib with different projects, hopefully this will be fixed by cargoized standard library.
