### ISSUE TITLE
GDB pretty printer for PathBuf doesn’t work 

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#5792]
This issue is related to the ticket from Zendesk Support.

## Environment

* **IntelliJ Rust plugin version:** 0.3.126
* **Rust toolchain version:** stable-i686-pc-windows-gnu
* **IDE name and version:** CLion 2020.1.3
* **Operating system:** Windows 10 64bit

## Problem description

The contents of classes such as `std::path::PathBuf` cannot be displayed in the Variables tab. 
```
use std::path::PathBuf; 
fn main() { 
    let path = PathBuf::from(r"C:\windows\system32.dll"); 
    println!("{:?}", path); 
} 
```

If you set a breakpoint on the println line, the 
```
path = {std::path::PathBuf} 
error = Cannot instantiate printer for default visualizer 
```

This seems to occur only when using GDB, and is only possible with 
I had no problems with LLDB on the Mac. 

The GDB tab shows the following:
```
Thread 1 hit Breakpoint 1, pathbuf_test::main () at src\main.rs:4 
4 println!("{:?}", path); 
Traceback (most recent call last): 
File "C:\Users\user\AppData\Roaming\JetBrains\CLion2020.1\plugins\intellij-rust\prettyPrinters\gdb_lookup.py", line 50, in lookup 
return StdOsStringProvider(valobj) 
File "C:\Users\user\AppData\Roaming\JetBrains\CLion2020.1\plugins\intellij-rust\prettyPrinters\gdb_providers.py", line 93, in __init__ 
vec = buf[ZERO_FIELD] if is_windows else buf 
gdb.error: There is no member named __0.
```

**Comment by ortem** [comment]
Duplicate of #6046
