### ISSUE TITLE
IllegalStateException: getService(T::class.java) must not be null when executing tests.

### ISSUE THREAD

**Issue by SaarYogev** [intellij-rust/intellij-rust#5835]
## Environment

* **IntelliJ Rust plugin version:** 0.3.127.3249-202
* **Rust toolchain version:** 1.45.0 (5c1f21c3b 2020-07-13)
* **IDE name and version:**IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
* **Operating system:** Windows 10 Pro version 1909, OS build 18363.959
## Problem description
Plugin tests (for example `RsInlineFunctionTest.test inline function without parameters and a return value`) are failing with an `IllegalStateException`, caused by a missing ComponentAdapter in the `componentKeyToAdapterCache`.
This is the full stack of where this happens:
```
getFromCache:59, DefaultPicoContainer (com.intellij.util.pico)
getComponentAdapter:46, DefaultPicoContainer (com.intellij.util.pico)
getComponent:363, ComponentManagerImpl (com.intellij.serviceContainer)
getInstance:16, UltimateVerifier (com.intellij.ultimate)
verifyUltimatePlugin:27, PluginVerifier (com.intellij.ultimate)
<init>:16, AjFileType (com.intellij.lang.aspectj)
<clinit>:12, AjFileType (com.intellij.lang.aspectj)
<init>:87, InterTypeDeclarationIndex$MyInputFilter (com.intellij.lang.aspectj.index.file)
<init>:86, InterTypeDeclarationIndex$MyInputFilter (com.intellij.lang.aspectj.index.file)
<clinit>:25, InterTypeDeclarationIndex (com.intellij.lang.aspectj.index.file)
newInstance0:-1, NativeConstructorAccessorImpl (sun.reflect)
newInstance:62, NativeConstructorAccessorImpl (sun.reflect)
newInstance:45, DelegatingConstructorAccessorImpl (sun.reflect)
newInstance:423, Constructor (java.lang.reflect)
instantiateClass:613, ComponentManagerImpl (com.intellij.serviceContainer)
instantiateClass:50, ExtensionComponentAdapter (com.intellij.openapi.extensions.impl)
instantiateClass:133, XmlExtensionAdapter$SimpleConstructorInjectionAdapter (com.intellij.openapi.extensions.impl)
createInstance:42, ExtensionComponentAdapter (com.intellij.openapi.extensions.impl)
createInstance:69, XmlExtensionAdapter (com.intellij.openapi.extensions.impl)
processAdapter:455, ExtensionPointImpl (com.intellij.openapi.extensions.impl)
access$200:39, ExtensionPointImpl (com.intellij.openapi.extensions.impl)
next:353, ExtensionPointImpl$1 (com.intellij.openapi.extensions.impl)
initAssociatedDataForExtensions:60, FileBasedIndexDataInitialization (com.intellij.util.indexing)
prepare:96, FileBasedIndexDataInitialization (com.intellij.util.indexing)
call:127, IndexInfrastructure$DataInitialization (com.intellij.util.indexing)
run$$$capture:266, FutureTask (java.util.concurrent)
run:-1, FutureTask (java.util.concurrent)
 - Async stack trace
execute:-1, BoundedTaskExecutor (com.intellij.util.concurrency)
submit:134, AbstractExecutorService (java.util.concurrent)
submitGenesisTask:117, IndexInfrastructure (com.intellij.util.indexing)
<init>:52, RegisteredIndexes (com.intellij.util.indexing)
initComponent:321, FileBasedIndexImpl (com.intellij.util.indexing)
<init>:208, FileBasedIndexImpl (com.intellij.util.indexing)
newInstance0:-2, NativeConstructorAccessorImpl (sun.reflect)
newInstance:62, NativeConstructorAccessorImpl (sun.reflect)
newInstance:45, DelegatingConstructorAccessorImpl (sun.reflect)
newInstance:423, Constructor (java.lang.reflect)
instantiateUsingPicoContainer:47, ConstructorInjectionKt (com.intellij.serviceContainer)
instantiateClassWithConstructorInjection:662, ComponentManagerImpl (com.intellij.serviceContainer)
createAndInitialize:49, ServiceComponentAdapter (com.intellij.serviceContainer)
doCreateInstance:37, ServiceComponentAdapter (com.intellij.serviceContainer)
getInstanceUncached:113, BaseComponentAdapter (com.intellij.serviceContainer)
getInstance:67, BaseComponentAdapter (com.intellij.serviceContainer)
getInstance$default:60, BaseComponentAdapter (com.intellij.serviceContainer)
run:819, ComponentManagerImpl$preloadServices$future$1 (com.intellij.serviceContainer)
run$$$capture:1640, CompletableFuture$AsyncRun (java.util.concurrent)
run:-1, CompletableFuture$AsyncRun (java.util.concurrent)
 - Async stack trace
execute:-1, BoundedTaskExecutor (com.intellij.util.concurrency)
asyncRunStage:1654, CompletableFuture (java.util.concurrent)
runAsync:1871, CompletableFuture (java.util.concurrent)
preloadServices:815, ComponentManagerImpl (com.intellij.serviceContainer)
preloadServices:263, ApplicationLoader (com.intellij.idea)
preloadServices$default:259, ApplicationLoader (com.intellij.idea)
doLoadApp:69, SimpleApplicationBootstrapperKt (com.intellij)
createInstance:120, TestApplicationManager$Companion (com.intellij.testFramework)
getInstance:88, TestApplicationManager$Companion (com.intellij.testFramework)
getInstance:-1, TestApplicationManager (com.intellij.testFramework)
setUp:38, LightIdeaTestFixtureImpl (com.intellij.testFramework.fixtures.impl)
lambda$setUp$28:1195, CodeInsightTestFixtureImpl (com.intellij.testFramework.fixtures.impl)
invoke:18, EdtTestUtil$Companion$runInEdtAndWait$1 (com.intellij.testFramework)
invoke:13, EdtTestUtil$Companion$runInEdtAndWait$1 (com.intellij.testFramework)
runInEdtAndWait:63, EdtTestUtilKt (com.intellij.testFramework)
runInEdtAndWait:18, EdtTestUtil$Companion (com.intellij.testFramework)
runInEdtAndWait:-1, EdtTestUtil (com.intellij.testFramework)
setUp:1194, CodeInsightTestFixtureImpl (com.intellij.testFramework.fixtures.impl)
setUp:48, BasePlatformTestCase (com.intellij.testFramework.fixtures)
setUp:63, RsTestBase (org.rust)
defaultRunBare:390, UsefulTestCase (com.intellij.testFramework)
invoke:18, EdtTestUtil$Companion$runInEdtAndWait$1 (com.intellij.testFramework)
invoke:13, EdtTestUtil$Companion$runInEdtAndWait$1 (com.intellij.testFramework)
run:67, EdtTestUtilKt$runInEdtAndWait$3 (com.intellij.testFramework)
dispatch$$$capture:301, InvocationEvent (java.awt.event)
dispatch:-1, InvocationEvent (java.awt.event)
 - Async stack trace
<init>:284, InvocationEvent (java.awt.event)
<init>:210, InvocationEvent (java.awt.event)
invokeAndWait:1337, EventQueue (java.awt)
invokeAndWait:1324, EventQueue (java.awt)
invokeAndWait:1353, SwingUtilities (javax.swing)
runInEdtAndWait:67, EdtTestUtilKt (com.intellij.testFramework)
runInEdtAndWait:18, EdtTestUtil$Companion (com.intellij.testFramework)
runInEdtAndWait:-1, EdtTestUtil (com.intellij.testFramework)
runBare:455, UsefulTestCase (com.intellij.testFramework)
protect:122, TestResult$1 (junit.framework)
runProtected:142, TestResult (junit.framework)
run:125, TestResult (junit.framework)
run:129, TestCase (junit.framework)
runTest:252, TestSuite (junit.framework)
run:247, TestSuite (junit.framework)
run:86, JUnit38ClassRunner (org.junit.internal.runners)
run:137, JUnitCore (org.junit.runner)
startRunnerWithArgs:69, JUnit4IdeaTestRunner (com.intellij.junit4)
startRunnerWithArgs:33, IdeaTestRunner$Repeater (com.intellij.rt.junit)
prepareStreamsAndStart:220, JUnitStarter (com.intellij.rt.junit)
main:53, JUnitStarter (com.intellij.rt.junit)
```
Haven't been able to figure out how it's filled, so that's how far my debugging got.
That makes a few other things fail, like `service()` and getting a `MacroExpansionFileSystem` in the dispose, which causes the final exception I see in the test window:
```
Connected to the target VM, address: '127.0.0.1:59508', transport: 'socket'
log4j:WARN No appenders could be found for logger (#com.intellij.ui.scale.JBUIScale).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

CompositeException (2 nested):
------------------------------
[0]: java.lang.IllegalStateException: getService(T::class.java) must not be null
[1]: null cannot be cast to non-null type org.rust.lang.core.macros.MacroExpansionFileSystem
------------------------------

CompositeException (2 nested):
------------------------------
[0]: java.lang.RuntimeException: java.lang.IllegalStateException: getService(T::class.java) must not be null
	at com.intellij.testFramework.LightPlatformTestCase.initProject(LightPlatformTestCase.java:215)
	at com.intellij.testFramework.LightPlatformTestCase.lambda$doSetup$2(LightPlatformTestCase.java:270)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:462)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:480)
	at com.intellij.testFramework.LightPlatformTestCase.doSetup(LightPlatformTestCase.java:263)
	at com.intellij.testFramework.fixtures.impl.LightIdeaTestFixtureImpl.setUp(LightIdeaTestFixtureImpl.java:39)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$setUp$28(CodeInsightTestFixtureImpl.java:1195)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:18)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:13)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:63)
	at com.intellij.testFramework.EdtTestUtil$Companion.runInEdtAndWait(EdtTestUtil.kt:18)
	at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.kt)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.setUp(CodeInsightTestFixtureImpl.java:1194)
	at com.intellij.testFramework.fixtures.BasePlatformTestCase.setUp(BasePlatformTestCase.java:48)
	at org.rust.RsTestBase.setUp(RsTestBase.kt:63)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:390)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:18)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:13)
	at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$3.run(EdtTestUtil.kt:67)
	at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:301)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:417)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: getService(T::class.java) must not be null
	at org.rust.cargo.project.model.CargoProjectServiceKt.getCargoProjects(CargoProjectService.kt:165)
	at org.rust.cargo.project.model.impl.TestCargoProjectsKt.getTestCargoProjects(testCargoProjects.kt:11)
	at org.rust.RustProjectDescriptorBase.configureModule(RustProjectDescriptors.kt:63)
	at com.intellij.testFramework.LightProjectDescriptor.lambda$createContentEntry$3(LightProjectDescriptor.java:164)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.lambda$updateModel$8(ModuleRootModificationUtil.java:126)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.modifyModel(ModuleRootModificationUtil.java:134)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:125)
	at com.intellij.testFramework.LightProjectDescriptor.createContentEntry(LightProjectDescriptor.java:153)
	at com.intellij.testFramework.LightProjectDescriptor.lambda$setUpProject$0(LightProjectDescriptor.java:48)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:102)
	at com.intellij.testFramework.LightProjectDescriptor.setUpProject(LightProjectDescriptor.java:42)
	at com.intellij.testFramework.LightPlatformTestCase.initProject(LightPlatformTestCase.java:194)
	... 34 more

[1]: kotlin.TypeCastException: null cannot be cast to non-null type org.rust.lang.core.macros.MacroExpansionFileSystem
	at org.rust.lang.core.macros.MacroExpansionFileSystem$Companion.getInstance(MacroExpansionFileSystem.kt:419)
	at org.rust.CommonKt.checkMacroExpansionFileSystemAfterTest(common.kt:12)
	at org.rust.RsTestBase.tearDown(RsTestBase.kt:79)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:402)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:18)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:13)
	at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$3.run(EdtTestUtil.kt:67)
	at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:301)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:417)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

------------------------------

Disconnected from the target VM, address: '127.0.0.1:59508', transport: 'socket'

Process finished with exit code -1

```

## Steps to reproduce

1. Intall IntelliJ IDEA.
2. Install Rust plugin
3. install rust toolchain with *rustup*
4. run the test (uses `java -ea`)

**Comment by mchernyavsky** [comment]
@SaarYogev What JDK version do you have? As I know, some tests can fail if you have JDK >1.8.

**Comment by Kobzol** [comment]
A similar error happens to me sometimes, it's usually solved for me by removing build artifacts (build, out, deps, gen folders), and rebuilding the plugin from scratch (`./gradlew :assemble`).

**Comment by SaarYogev** [comment]
I did have a bad JDK installation, but I installed a # # good one, deleted all build, deps, gen folders, and retried. Unfortunately I got the same results.

**Comment by vlad20012** [comment]
Hmm, maybe it somehow related to Windows? I haven't tryed tests on windows for several years. But they work on CI btw

**Comment by Kobzol** [comment]
@SaarYogev also try to remove all caches and indices from the IntelliJ cache directory and remove/reset the .idea directory. If it worked before, there has to be some corrupted state or something that is still present.

**Comment by SaarYogev** [comment]
@Kobzol Good suggestion, I'll try it now. But I'll remark the computer is new, those tests were never run on it before. They did run on my old computer, so I assumed I knew how to setup the environment.

**Comment by SaarYogev** [comment]
@Kobzol Well, Invalidate caches/Restart did the trick! May all bugs have such easy fixes, I'm off to contribute 😄
