### ISSUE TITLE
Change directory of rust binary to another causes a fatal error

### ISSUE THREAD

**Issue by LooMaclin** [intellij-rust/intellij-rust#584]
I'm change directory from "/home/loomaclin/.multirust/..." to "/usr/bin/".
Screenshot: http://screencloud.net/v/y2JF
Error message:
```
Invalid path to cargo /cargo
```
Stacktrace:

```
Invalid path to cargo /cargo
java.lang.IllegalArgumentException: Invalid path to cargo /cargo
	at org.rust.cargo.commands.Cargo.<init>(Cargo.kt:32)
	at org.rust.cargo.toolchain.RustToolchain.nonProjectCargo(RustToolchain.kt:69)
	at org.rust.cargo.toolchain.RustToolchain.queryCargoVersion(RustToolchain.kt:35)
	at org.rust.cargo.project.settings.ui.RustProjectSettingsPanel$scheduleVersionUpdate$1.run(RustProjectSettingsPanel.kt:107)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Invalid path to cargo /usr/cargo
	at org.rust.cargo.commands.Cargo.<init>(Cargo.kt:32)
	at org.rust.cargo.toolchain.RustToolchain.nonProjectCargo(RustToolchain.kt:69)
	at org.rust.cargo.toolchain.RustToolchain.queryCargoVersion(RustToolchain.kt:35)
	at org.rust.cargo.project.settings.ui.RustProjectSettingsPanel$scheduleVersionUpdate$1.run(RustProjectSettingsPanel.kt:107)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IllegalArgumentException: Invalid path to cargo /usr/bi/cargo
	at org.rust.cargo.commands.Cargo.<init>(Cargo.kt:32)
	at org.rust.cargo.toolchain.RustToolchain.nonProjectCargo(RustToolchain.kt:69)
	at org.rust.cargo.toolchain.RustToolchain.queryCargoVersion(RustToolchain.kt:35)
	at org.rust.cargo.project.settings.ui.RustProjectSettingsPanel$scheduleVersionUpdate$1.run(RustProjectSettingsPanel.kt:107)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by matklad** [comment]
Thanks for the report!
