### ISSUE TITLE
NoSuchMethodError: com.intellij.codeInsight.hints.InlayHintsSink.addInlineElement

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#5886]
## Environment

* **IntelliJ Rust plugin version:** 0.3.129.3270-202-nightly
* **Rust toolchain version:** 1.44.0-nightly (b2e36e6c2 2020-04-22) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3 Snapshot (CL-203.1882)
* **Operating system:** macOS 10.15.4

## Problem description

I get the constant flow of exceptions in nightly - the plugin doesn't show type errors.

```
java.lang.NoSuchMethodError: 'void com.intellij.codeInsight.hints.InlayHintsSink.addInlineElement(int, boolean, com.intellij.codeInsight.hints.presentation.InlayPresentation)'
	at org.rust.ide.hints.type.RsInlayTypeHintsProvider$getCollectorFor$1.presentTypeForBinding(RsInlayTypeHintsProvider.kt:169)
	at org.rust.ide.hints.type.RsInlayTypeHintsProvider$getCollectorFor$1.presentTypeForPat(RsInlayTypeHintsProvider.kt:161)
	at org.rust.ide.hints.type.RsInlayTypeHintsProvider$getCollectorFor$1.presentVariable(RsInlayTypeHintsProvider.kt:96)
	at org.rust.ide.hints.type.RsInlayTypeHintsProvider$getCollectorFor$1.collect(RsInlayTypeHintsProvider.kt:74)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:65)
	at com.intellij.codeInsight.hints.InlayHintsPass$doCollectInformation$1.process(InlayHintsPass.kt:45)
	at com.intellij.codeInsight.hints.InlayHintsPass$doCollectInformation$1.process(InlayHintsPass.kt:25)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1112)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:653)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:605)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:62)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:99)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:57)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation(InlayHintsPass.kt:36)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1117)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:653)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:605)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

## Steps to reproduce

```rust
fn main() {
    let my = String::from("book");
    let yours = pluralize(&my);

    println!("I have one {}, you have two {}", my, yours,);
}

fn pluralize(string: u32) -> String {
    string + "s"
}
```

**Comment by Undin** [comment]
This exception happens because of binary incompatibility between 2020.2 and 2020.3. I filed [IDEA-248287](https://youtrack.jetbrains.com/issue/IDEA-248287) to fix it in platform

**Comment by Undin** [comment]
I've restored binary compatibility in IDEA master
@lancelote could you verify it, please?

**Comment by lancelote** [comment]
Works fine, thank you 👍
