### ISSUE TITLE
Downloading debugger fails: Total weight must be a positive number: 0

### ISSUE THREAD

**Issue by njam** [intellij-rust/intellij-rust#5915]
## Environment

* **IntelliJ Rust plugin version:** 0.3.128.3278-202
* **Rust toolchain version:** 1.42.0-x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2020.2  Build #IU-202.6397.94
* **Operating system:** Linux 5.7.11-arch1-1

## Problem description

Downloading the debugger fails.

Log:
```
2020-08-12 11:53:01,687 [  28457]  ERROR - pplication.impl.LaterInvocator - Total weight must be a positive number: 0 
java.lang.IllegalArgumentException: Total weight must be a positive number: 0
	at com.intellij.util.progress.ConcurrentTasksProgressManager.<init>(ConcurrentTasksProgressManager.java:24)
	at com.intellij.util.download.impl.FileDownloaderImpl.download(FileDownloaderImpl.java:201)
	at org.rust.debugger.RsDebuggerToolchainService.downloadAndUnarchive(RsDebuggerToolchainService.kt:146)
	at org.rust.debugger.RsDebuggerToolchainService.downloadDebuggerSynchronously(RsDebuggerToolchainService.kt:95)
	at org.rust.debugger.RsDebuggerToolchainService.access$downloadDebuggerSynchronously(RsDebuggerToolchainService.kt:34)
	at org.rust.debugger.RsDebuggerToolchainService$downloadDebugger$result$1.compute(RsDebuggerToolchainService.kt:67)
	at org.rust.debugger.RsDebuggerToolchainService$downloadDebugger$result$1.compute(RsDebuggerToolchainService.kt:34)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:490)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-12 11:53:01,689 [  28459]  ERROR - pplication.impl.LaterInvocator - IntelliJ IDEA 2020.2  Build #IU-202.6397.94 
2020-08-12 11:53:01,689 [  28459]  ERROR - pplication.impl.LaterInvocator - JDK: 11.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-08-12 11:53:01,689 [  28459]  ERROR - pplication.impl.LaterInvocator - OS: Linux 
2020-08-12 11:53:01,690 [  28460]  ERROR - pplication.impl.LaterInvocator - Plugin to blame: Rust version: 0.3.128.3278-202 
2020-08-12 11:53:01,690 [  28460]  ERROR - pplication.impl.LaterInvocator - Last Action: Debug 
```

## Steps to reproduce

1. Click "debug" icon
2. Prompt about downloading debugger appears, click "download"
3. Debug icon goes grey, nothing happens

**Comment by SomeoneToIgnore** [comment]
I experience the same issue, yet no prompt appears at all: after clicking the debug icon, nothing happens at all.
I observe similar logs though.
In case it's helpful, my log is here: https://github.com/intellij-rust/intellij-rust/issues/6068

**Comment by Undin** [comment]
@njam @SomeoneToIgnore sorry for delay.
Do you have some old version of LLDB (i.e. error happens on debugger update) or it's the first downloading?
You can check if you already have some old debugger version via `Preferences | Build, Execution, Deployment | Debugger` settings.
![image](https://user-images.githubusercontent.com/2539310/93070897-1b2adb00-f688-11ea-9040-677d81880df7.png)
If `LLDB path` field contains any path then the problem is in update and it would be great if you zip this directory and attach the corresponding archive to this issue to reproduce the problem

@njam Could you provide a version of `Native Debugging Support` plugin? You can check it via `Preferences | Plugins`

**Comment by njam** [comment]
I can't reproduce this anymore. I have updated both IntelliJ and the Rust plugin since opening this ticket.

My environment is:
* **IntelliJ Rust plugin version:** 0.3.129.3308-202
* **IntelliJ "Native Debugging Support" plugin version:** 202.6948.69
* **Rust toolchain version:** 1.42.0-x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2020.2.1 Build #IU-202.6948.69
