### ISSUE TITLE
Error running debugger in 2020.3 CLion

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#5947]
## Environment

* **IntelliJ Rust plugin version:** 0.3.129.3287-202-nightly
* **Rust toolchain version:** 1.47.0-nightly (6c8927b0c 2020-07-26) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3 Snapshot (CL-203.2554)
* **Operating system:** macOS 10.15.6

## Problem description

<img width="1372" alt="error" src="https://user-images.githubusercontent.com/2500320/90396377-c99a2b00-e09e-11ea-9a3f-91e6b6d169dc.png">

```stacktrace
2020-08-17 15:30:40,608 [1257009]   INFO - xecution.runners.ExecutionUtil - Error running 'Run error_chain':<br>'com.jetbrains.cidr.execution.debugger.backend.DebuggerDriverConfiguration com.jetbrains.cidr.cpp.toolchains.CPPDebuggerUtilKt.createDriverConfiguration(com.intellij.openapi.project.Project, com.jetbrains.cidr.cpp.toolchains.CPPEnvironment)' 
java.lang.NoSuchMethodError: 'com.jetbrains.cidr.execution.debugger.backend.DebuggerDriverConfiguration com.jetbrains.cidr.cpp.toolchains.CPPDebuggerUtilKt.createDriverConfiguration(com.intellij.openapi.project.Project, com.jetbrains.cidr.cpp.toolchains.CPPEnvironment)'
	at org.rust.clion.debugger.RsCLionDebuggerDriverConfigurationProvider.getDebuggerDriverConfiguration(RsCLionDebuggerDriverConfigurationProvider.kt:18)
	at org.rust.debugger.runconfig.RsDebugRunParameters.getDebuggerDriverConfiguration(RsDebugRunParameters.kt:29)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess.<init>(CidrDebugProcess.java:165)
	at com.jetbrains.cidr.execution.debugger.CidrLocalDebugProcess.<init>(CidrLocalDebugProcess.java:24)
	at com.jetbrains.cidr.execution.debugger.CidrLocalDebugProcess.<init>(CidrLocalDebugProcess.java:16)
	at org.rust.debugger.runconfig.RsLocalDebugProcess.<init>(RsLocalDebugProcess.kt:16)
	at org.rust.debugger.runconfig.RsDebugRunnerUtils$showRunContent$1.start(RsDebugRunnerUtils.kt:38)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:261)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:222)
	at org.rust.debugger.runconfig.RsDebugRunnerUtils.showRunContent(RsDebugRunnerUtils.kt:36)
	at org.rust.debugger.runconfig.RsDebugRunnerBase.showRunContent(RsDebugRunnerBase.kt:23)
	at org.rust.cargo.runconfig.RsExecutableRunner.doExecute(RsExecutableRunner.kt:85)
	at org.rust.cargo.runconfig.RsDefaultProgramRunnerBase$execute$1.invoke(RsDefaultProgramRunnerBase.kt:25)
	at org.rust.cargo.runconfig.RsDefaultProgramRunnerBase$execute$1.invoke(RsDefaultProgramRunnerBase.kt:18)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:146)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:59)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:207)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:23)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:198)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:807)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:973)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:768)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:807)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ortem** [comment]
@lancelote should be fixed on CLion `master` now

**Comment by lancelote** [comment]
It works indeed, thank you 👍
