### ISSUE TITLE
parentByStub must not be null

### ISSUE THREAD

**Issue by Riateche** [intellij-rust/intellij-rust#606]
I get this error in the Rust plugin:

```
parentByStub must not be null
java.lang.IllegalStateException: parentByStub must not be null
	at org.rust.lang.core.psi.impl.RustStubbedElementImpl.getParent(RustStubbedElementImpl.kt:18)
	at com.intellij.psi.impl.PsiElementBase.isValid(PsiElementBase.java:254)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.isValid(StubBasedPsiElementBase.java:278)
	at com.intellij.psi.impl.PsiElementBase.isValid(PsiElementBase.java:258)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.a(SmartPointerManagerImpl.java:260)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.updatePointerTargetsAfterReparse(SmartPointerManagerImpl.java:251)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:344)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:143)
	at com.intellij.psi.impl.PsiDocumentManagerBase$3.run(PsiDocumentManagerBase.java:298)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:295)
	at com.intellij.psi.impl.DocumentCommitThread$5.run(DocumentCommitThread.java:528)
	at com.intellij.psi.impl.DocumentCommitThread.commitSynchronously(DocumentCommitThread.java:424)
	at com.intellij.psi.impl.PsiDocumentManagerBase$5.run(PsiDocumentManagerBase.java:390)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.psi.impl.PsiDocumentManagerBase.b(PsiDocumentManagerBase.java:382)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitDocument(PsiDocumentManagerBase.java:284)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAllDocuments(PsiDocumentManagerBase.java:218)
	at com.intellij.codeInsight.editorActions.EnterHandler.a(EnterHandler.java:166)
	at com.intellij.codeInsight.editorActions.EnterHandler.access$000(EnterHandler.java:54)
	at com.intellij.codeInsight.editorActions.EnterHandler$1.run(EnterHandler.java:76)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect$3.compute(PostprocessReformattingAspect.java:115)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:124)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:112)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:73)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:222)
	at com.intellij.codeInsight.template.impl.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:203)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:342)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:422)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:333)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:324)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:200)
	at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This happens when editing a *.rs.in file, which is actually a Rust file, used like described here: [https://github.com/serde-rs/serde#using-serde-with-stable-rust-and-serde_codegen](https://github.com/serde-rs/serde#using-serde-with-stable-rust-and-serde_codegen).

**Comment by matklad** [comment]
So this is weird. I failed to reproduce this issue exactly, but `parentByStub` was definitely broken (#613). It is now fixed, so I hope this issue is also resolved. The fix is included in the latest nightly.

I'll close this, but please reopen if you still see the issue after the update!

**Comment by Riateche** [comment]
Now I have a different error:

```
parentByTree must not be null
java.lang.IllegalStateException: parentByTree must not be null
	at org.rust.lang.core.psi.impl.RustStubbedElementImpl.getParent(RustStubbedElementImpl.kt:18)
	at com.intellij.psi.impl.PsiElementBase.isValid(PsiElementBase.java:254)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.isValid(StubBasedPsiElementBase.java:278)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.a(SmartPointerManagerImpl.java:260)
(...)
```
Turns out it has nothing to do with rs.in files. I now have this error even in a fresh project created with "cargo new --bin". As long as I type "struct A {" above main function, I have the error.

I can't reopen the issue.

**Comment by matklad** [comment]
Can you report the versions of the IDE (`Help > About`), plugin ('Plugins > Rust'), and OS that you are using? 

Also, have you tried using **Invalidate caches and restart** action? Does it help?

Sorry for this guesswork questions, but I have not seen this issue myself yet :(

**Comment by Riateche** [comment]
Sure. 

IntelliJ IDEA 15.0.6
Build #IU-143.2370, built on April 28, 2016
JRE: 1.8.0_74-b02 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Rust plugin: Version: 0.0.1.950-nightly

OS - Debian Jessie
uname -a
Linux 4.0.0-2-amd64 #1 SMP Debian 4.0.8-1 (2015-07-11) x86_64 GNU/Linux

"Invalidate caches and restart" does not help.

**Comment by matklad** [comment]
Yay, I've reproduced it! The version of the IDE seems to matter. 15 and 2016.1 are affected, 2016.2 works fine.

I'll fix this for the older versions.

**Comment by Riateche** [comment]
Works fine now. Thanks a lot.
