### ISSUE TITLE
Unable to run the debugger in Intellij Idea on macOs

### ISSUE THREAD

**Issue by SomeoneToIgnore** [intellij-rust/intellij-rust#6068]
## Environment

* **IntelliJ Rust plugin version:** 0.3.131.3329-202-nightly
* **Rust toolchain version:** 1.46.0 (04488afe3 2020-08-24) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.2.2 Preview Ultimate Edition (IU-202.7319.5)
* **Operating system:** macOS 10.15.6

## Problem description

Create a new project with `cargo new`, open it in the Intellij Idea, run the project to ensure that it works.
Try to debug the project.
Expected: the debugging starts
Actual: nothing happens

Natide Debugging plugin is installed:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/2690773/92242058-e8365980-eec7-11ea-8b9e-a33d864d70f6.png">

idea.log contents:
```
2020-09-04 15:56:55,583 [  30575]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=local_test, containerState=ACTIVE, componentStore=/Users/someonetoignore/Dropbox (Personal)/pet_projects/rust/local_test)RunManager took 25 ms 
2020-09-04 15:57:24,626 [  59618]   INFO - rust.openapiext.CommandLineExt - Executing `/Users/someonetoignore/.cargo/bin/rustc --version --verbose` 
2020-09-04 15:57:24,649 [  59641]  ERROR - til.concurrency.QueueProcessor - Total weight must be a positive number: 0 
java.lang.IllegalArgumentException: Total weight must be a positive number: 0
	at com.intellij.util.progress.ConcurrentTasksProgressManager.<init>(ConcurrentTasksProgressManager.java:24)
	at com.intellij.util.download.impl.FileDownloaderImpl.download(FileDownloaderImpl.java:201)
	at org.rust.debugger.RsDebuggerToolchainService.downloadAndUnarchive(RsDebuggerToolchainService.kt:146)
	at org.rust.debugger.RsDebuggerToolchainService.downloadDebuggerSynchronously(RsDebuggerToolchainService.kt:95)
	at org.rust.debugger.RsDebuggerToolchainService.access$downloadDebuggerSynchronously(RsDebuggerToolchainService.kt:34)
	at org.rust.debugger.RsDebuggerToolchainService$downloadDebugger$result$1.compute(RsDebuggerToolchainService.kt:67)
	at org.rust.debugger.RsDebuggerToolchainService$downloadDebugger$result$1.compute(RsDebuggerToolchainService.kt:34)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:490)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-04 15:57:24,650 [  59642]  ERROR - til.concurrency.QueueProcessor - IntelliJ IDEA 2020.2.2 Preview  Build #IU-202.7319.5 
2020-09-04 15:57:24,650 [  59642]  ERROR - til.concurrency.QueueProcessor - JDK: 11.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-09-04 15:57:24,650 [  59642]  ERROR - til.concurrency.QueueProcessor - OS: Mac OS X 
2020-09-04 15:57:24,650 [  59642]  ERROR - til.concurrency.QueueProcessor - Plugin to blame: Rust version: 0.3.131.3329-202-nightly 
```

**Comment by SomeoneToIgnore** [comment]
Oh, looks like a duplicate of https://github.com/intellij-rust/intellij-rust/issues/5915, sorry.
