### ISSUE TITLE
"Executable is not specified" running profiler

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#6173]
## Environment

* **IntelliJ Rust plugin version:** 0.3.132.3379-203-nightly
* **Rust toolchain version:** 1.46.0 (04488afe3 2020-08-24) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3 EAP (CL-203.3645.37)
* **Operating system:** Linux 5.4.0-42-generic

## Problem description

I created a new binary project and on attempt to profile `main.rs` CLion complains

> Error running ...
> Executable is not specified

<img width="320" alt="Screen Shot 2020-09-28 at 22 24 50" src="https://user-images.githubusercontent.com/2500320/94477008-f121fe80-01d9-11eb-85a6-113af4f73f83.png">

Did I miss some setting? Which executable should I specify?

```
2020-09-28 12:27:12,670 [ 253463]   INFO - xecution.runners.ExecutionUtil - Error running 'Run test_6152':<br>Executable is not specified 
com.intellij.execution.ExecutionException: Executable is not specified
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:385)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:100)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:48)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:37)
	at org.rust.cargo.runconfig.RsKillableColoredProcessHandler.<init>(RsKillableColoredProcessHandler.kt:17)
	at org.rust.cargo.runconfig.RsExecutableRunner.executeCommandLine(RsExecutableRunner.kt:106)
	at org.rust.cargo.runconfig.RsExecutableRunner.showRunContent(RsExecutableRunner.kt:92)
	at org.rust.cargo.runconfig.RsExecutableRunner.doExecute(RsExecutableRunner.kt:85)
	at org.rust.cargo.runconfig.RsDefaultProgramRunnerBase$execute$1.invoke(RsDefaultProgramRunnerBase.kt:25)
	at org.rust.cargo.runconfig.RsDefaultProgramRunnerBase$execute$1.invoke(RsDefaultProgramRunnerBase.kt:18)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:146)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:57)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:207)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:823)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:973)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:823)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ortem** [comment]
Cannot reproduce on CLion 2020.3 EAP (CL-203.4203.24) with IJ Rust 0.3.132.3395-203 and stable Rust 1.47

**Comment by lancelote** [comment]
@ortem Did you test it on Linux? I still suffer this problem there with the same setup as you.

**Comment by ortem** [comment]
@lancelote Sorry for the long reply. Yes, I tested it on Ubuntu

**Comment by esemeniuc** [comment]
I have the same issue. I am running on Arch with Rust 1.47 (via rustup) with Clion 2020.2.4 and plugin version 0.3.133.3426-202. I have tried reinstalling Clion (reset the CLion2020.2 folder) as well as the `.idea` folder in my repository

**Comment by esemeniuc** [comment]
@ortem any thoughts on a workaround?

**Comment by ortem** [comment]
@esemeniuc Please check your CLion profiler settings in `Preferences | Build, Execution, Deployment | Dynamic Analysis Tools | Profiler`. Do you have `Perf executable` path specified like in the screenshot below? If no, try to use `/usr/bin/perf` or your perf location.

<img width="907" alt="Screenshot 2020-10-29 at 17 41 08" src="https://user-images.githubusercontent.com/4854600/97588831-ef806c00-1a0d-11eb-9c84-05c306442723.png">

**Comment by esemeniuc** [comment]
Fixed for me, thank you @ortem

**Comment by larsw** [comment]
Experiencing this problem in the latest RustRover EAP. What profiler should I use?

**Comment by lancelote** [comment]
@larsw Report the problem to the RustRover issue tracker https://youtrack.jetbrains.com/issues/RUST
