### ISSUE TITLE
IntelliJ hangs if project closed while IDE is starting up

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [intellij-rust/intellij-rust#6185]
## Environment

* **IntelliJ Rust plugin version:** `0.3.133.3383-202-nightly`
* **Rust toolchain version:** 1.46 stable
* **IDE name and version:** IntelliJ IDEA 2020.2.2 Ultimate
* **Operating system:** Windows 10 x64 2004

## Problem description
If a project is closed while IDE is starting up it will hang forever on "Saving Project".

## Steps to reproduce
1. Have multiple Rust projects open (e.g. 8)
2. Close IDE
3. Start IDE
4. While IDE is opening project windows, close one of them
5. IDE hangs forever on "Saving Project". Other projects show "Reloading Cargo Projects" or "Cleaning outdated macros" (in status bar). Input not possible in any window. Task manager shows near-zero CPU use and memory use almost unchanging. End Task works.

**Comment by chansonzhang** [comment]
same problem, any way to fix or workaround?

**Comment by vemod** [comment]
same happens also on multiple java and nodejs projects are in use. so not only rust issue. Stuck on "Saving xxxx project settings". 
I even waited until all projects are finally open (not during startup). And trying to close any of them. Gets stuck. SIGTERM works but not always. `kill -USR1`  terminates Idea. 

The system: 
Connected to internet. No vpn. No remote folders
nvme disk. 
fedora 40 with kde wayland
jdk 17 and 21

This is really annoying. Its ok that a project takes time to save settings or whatever it does. But why other windows (projects in separate windows) get stuck and no way to cancel, terminate etc.. have to kill the app

may be something related to this?
```
WARN - #c.i.u.t.AbstractTreeNodeVisitor - unexpected component class com.intellij.ide.util.treeView.CachedTreePresentationNode
```
```
WARN - #c.i.u.x.Binding - No accessors for com.intellij.docker.view.DockerTreeFilter. This means that state class cannotbe serialized properly. Please see https://jb.gg/ij-psoc
Warning: Not allowed as a service: com.jetbrains.RoundedCornersManager
at com.jetbrains.JBR$RoundedCornersManager__Holder.<clinit>(JBR.java:514)
at com.jetbrains.JBR.isRoundedCornersManagerSupported(JBR.java:524)
at com.intellij.ui.WindowRoundedCornersManager.isAvailable(WindowRoundedCornersManager.java:36)
at com.intellij.ide.ui.laf.OurPopupFactory.getPopup(LafManagerImpl.kt:1125)
at java.desktop/javax.swing.plaf.PopupMenuUI.getPopup(PopupMenuUI.java:71)
at java.desktop/javax.swing.JPopupMenu.showPopup(JPopupMenu.java:881)
at java.desktop/javax.swing.JPopupMenu.setVisible(JPopupMenu.java:829)
at java.desktop/javax.swing.JPopupMenu.show(JPopupMenu.java:1003)
at java.desktop/javax.swing.JMenu.setPopupMenuVisible(JMenu.java:339)
```
