### ISSUE TITLE
Error during macro expansion: `NoSuchMethodError` on `org.rust.lang.core.macros.RangeMap`

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#6322]
## Environment

* **IntelliJ Rust plugin version:** 0.3.133.3389-203-nightly
* **Rust toolchain version:** 1.49.0-nightly (a9cd294cf 2020-10-22) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.3 EAP Ultimate Edition (IU-203.4203.26)
* **Operating system:** macOS 10.15.7

## Problem description
See `EA-242185` report

```
Error during macro expansion

java.lang.NoSuchMethodError: 'org.rust.lang.core.macros.RangeMap org.rust.lang.core.macros.RangeMap$Companion.readFrom(java.io.DataInputStream)'
    at org.rust.lang.core.macros.ExpandedMacroStorageKt.loadRangeMap(ExpandedMacroStorage.kt:997)
    at org.rust.lang.core.macros.MacroExpansionKt.getRanges(MacroExpansion.kt:136)
    at org.rust.lang.core.macros.RsExpandedElementKt.mapOffsetFromExpansionToCallBodyRelative(RsExpandedElement.kt:170)
    at org.rust.lang.core.macros.RsExpandedElementKt.cameFromMacroCall(RsExpandedElement.kt:176)
    at org.rust.lang.core.resolve.NameResolutionKt.processMacroCallPathResolveVariants(NameResolution.kt:805)
    at org.rust.lang.core.resolve.ref.RsMacroPathReferenceImpl$Resolver$invoke$1.invoke(RsMacroPathReferenceImpl.kt:69)
    at org.rust.lang.core.resolve.ref.RsMacroPathReferenceImpl$Resolver$invoke$1.invoke(RsMacroPathReferenceImpl.kt:66)
    at org.rust.lang.core.resolve.ProcessorsKt.pickFirstResolveVariant(Processors.kt:156)
    at org.rust.lang.core.resolve.ref.RsMacroPathReferenceImpl$Resolver.invoke(RsMacroPathReferenceImpl.kt:68)
    at org.rust.lang.core.resolve.ref.RsMacroPathReferenceImpl$Resolver.invoke(RsMacroPathReferenceImpl.kt:66)
    at org.rust.lang.core.resolve.ref.RsResolveCache$resolveWithCaching$$inlined$run$lambda$1.compute(RsResolveCache.kt:100)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
    at org.rust.lang.core.resolve.ref.RsResolveCache.resolveWithCaching(RsResolveCache.kt:100)
    at org.rust.lang.core.resolve.ref.RsMacroPathReferenceImpl.resolve(RsMacroPathReferenceImpl.kt:55)
    at org.rust.lang.core.resolve.ref.RsMacroPathReferenceImpl.resolve(RsMacroPathReferenceImpl.kt:38)
    at org.rust.lang.core.psi.ext.RsMacroCallKt.resolveToMacro(RsMacroCall.kt:149)
    at org.rust.lang.core.macros.ExpansionPipeline$Stage1.expand(MacroExpansionTask.kt:406)
    at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1$stages2$1$result$1$1.invoke(MacroExpansionTask.kt:213)
    at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1$stages2$1$result$1$1.invoke(MacroExpansionTask.kt:48)
    at org.rust.openapiext.UtilsKt$runReadActionInSmartMode$1.compute(utils.kt:275)
    at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:103)
    at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:147)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:889)
    at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
    at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:140)
    at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:103)
    at org.rust.openapiext.UtilsKt.runReadActionInSmartMode(utils.kt:273)
    at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1$stages2$1$result$1.invoke(MacroExpansionTask.kt:211)
    at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1$stages2$1$result$1.invoke(MacroExpansionTask.kt:48)
    at org.rust.openapiext.UtilsKt$executeUnderProgressWithWriteActionPriorityWithRetries$success$1.invoke(utils.kt:285)
    at org.rust.openapiext.UtilsKt$executeUnderProgressWithWriteActionPriorityWithRetries$success$1.invoke(utils.kt)
    at org.rust.openapiext.UtilsKt$sam$java_lang_Runnable$0.run(utils.kt)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:152)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:113)
    at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:59)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:110)
    at org.rust.openapiext.UtilsKt.runWithWriteActionPriority(utils.kt:297)
    at org.rust.openapiext.UtilsKt.executeUnderProgressWithWriteActionPriorityWithRetries(utils.kt:284)
    at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1$stages2$1.apply(MacroExpansionTask.kt:209)
    at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1$stages2$1.apply(MacroExpansionTask.kt:48)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
    at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
    at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
    at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
    at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
    at kotlin.streams.jdk8.StreamsKt.toList(Streams.kt:60)
    at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1.invoke(MacroExpansionTask.kt:224)
    at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1.invoke(MacroExpansionTask.kt:48)
    at org.rust.stdext.CompletableFutureKt$supplyAsync$1.get(CompletableFuture.kt:18)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by Undin** [comment]
Looks like everything is fine with the latest plugin builds and the latest 2020.3 EAPs
