### ISSUE TITLE
IDE Fatal error in Cargo.toml edit

### ISSUE THREAD

**Issue by LooMaclin** [intellij-rust/intellij-rust#643]
When i'm edit the cargo.toml, ide show fatal error:
![Image](https://sc-cdn.scaleengine.net/i/bb36597e17e62fa35fce5460c3e8c192.png)

With this stacktrace:
>`cargo metadata` reported a package which does not exist at `/home/loomaclin/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.3.14/Cargo.toml`
java.lang.IllegalStateException: `cargo metadata` reported a package which does not exist at `/home/loomaclin/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.3.14/Cargo.toml`
	at org.rust.cargo.commands.impl.CargoMetadata.clean(CargoMetadata.kt:122)
	at org.rust.cargo.commands.impl.CargoMetadata.clean(CargoMetadata.kt:111)
	at org.rust.cargo.commands.Cargo.fullProjectDescription(Cargo.kt:51)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$UpdateTask.run(CargoProjectWorkspaceImpl.kt:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by matklad** [comment]
Thanks for the report, should be fixed now!

**Comment by darkdarkfruit** [comment]
Same problem re-appears with latest itellij-rust plugin while working with rust-1.49, althoug rust-1.48 is ok.

**Comment by Undin** [comment]
@darkdarkfruit I doubt that it's the same issue so could you create a new one and attach your logs (`Find Action | Collect logs and Diagnostic data`), please?

**Comment by darkdarkfruit** [comment]
Sure(Note: with org.rust.cargo.fetch.actual.stdlib.metadata on)


`
2021-01-03 11:44:34,410 [2578225]  ERROR - intellij.openapi.progress.Task - `cargo metadata` reported a package which does not exist at `/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/vendor/rustc-std-workspace-core/Cargo.toml` 
java.lang.IllegalStateException: `cargo metadata` reported a package which does not exist at `/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/vendor/rustc-std-workspace-core/Cargo.toml`
	at org.rust.cargo.toolchain.impl.CargoMetadata.clean(CargoMetadata.kt:368)
	at org.rust.cargo.toolchain.impl.CargoMetadata.clean(CargoMetadata.kt:340)
	at org.rust.cargo.toolchain.impl.CargoMetadata.clean$default(CargoMetadata.kt:325)
	at org.rust.cargo.project.workspace.StdlibDataFetcher.fetchStdlibData(StandardLibrary.kt:181)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib(StandardLibrary.kt:84)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromFile(StandardLibrary.kt:74)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromFile$default(StandardLibrary.kt:56)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.fetchStdlib(CargoSyncTask.kt:268)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$fetchStdlib(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:260)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:288)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$runWithChildProgress(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$SyncContext.runWithChildProgress(CargoSyncTask.kt:167)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.fetchStdlib(CargoSyncTask.kt:232)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$fetchStdlib(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$$inlined$map$lambda$1.invoke(CargoSyncTask.kt:113)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$$inlined$map$lambda$1.invoke(CargoSyncTask.kt:50)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:288)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress$default(CargoSyncTask.kt:283)
	at org.rust.cargo.project.model.impl.CargoSyncTask.doRun(CargoSyncTask.kt:100)
	at org.rust.cargo.project.model.impl.CargoSyncTask.run(CargoSyncTask.kt:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-03 11:44:34,411 [2578226]  ERROR - intellij.openapi.progress.Task - CLion 2020.3.1  Build #CL-203.6682.181 
2021-01-03 11:44:34,411 [2578226]  ERROR - intellij.openapi.progress.Task - JDK: 11.0.9.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-01-03 11:44:34,411 [2578226]  ERROR - intellij.openapi.progress.Task - OS: Linux 
2021-01-03 11:44:34,411 [2578226]  ERROR - intellij.openapi.progress.Task - Plugin to blame: Rust version: 0.3.138.3572-203
 `

**Comment by Undin** [comment]
@darkdarkfruit Thank you!
Looks like it's the same as #6603. See https://github.com/intellij-rust/intellij-rust/issues/6603#issuecomment-753478878 about possible workarounds

**Comment by darkdarkfruit** [comment]
Thanks for your quick response.
