### ISSUE TITLE
Cannot download debugger in IDEA 2020.3.1 - 404 error

### ISSUE THREAD

**Issue by ramosbugs** [intellij-rust/intellij-rust#6593]
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.3.1 Ultimate Edition (IU-203.6682.168)
* **Operating system:** macOS 10.15.7
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description

It looks like #5921 was reintroduced with the most recent release. The logs show the following when I attempt to install the Rust debugger:
```
2020-12-30 14:21:01,448 [3201534]   WARN - ger.RsDebuggerToolchainService - Can't download debugger 
java.io.IOException: Failed to download 'https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-third-party-dependencies/org/jetbrains/intellij/deps/cidr/lldb/7bd069dd5430f43ea3e0737aa2f9d082efb21c9e/lldb-7bd069dd5430f43ea3e0737aa2f9d082efb21c9e-mac-x64.tar.gz':
Request failed with status code 404
	at com.intellij.util.download.impl.FileDownloaderImpl.lambda$download$1(FileDownloaderImpl.java:236)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 404. Status=404, Url=https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-third-party-dependencies/org/jetbrains/intellij/deps/cidr/lldb/7bd069dd5430f43ea3e0737aa2f9d082efb21c9e/lldb-7bd069dd5430f43ea3e0737aa2f9d082efb21c9e-mac-x64.tar.gz
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:671)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:649)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:381)
	at com.intellij.util.download.impl.FileDownloaderImpl$2.process(FileDownloaderImpl.java:339)
	at com.intellij.util.download.impl.FileDownloaderImpl$2.process(FileDownloaderImpl.java:336)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:541)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:355)
	at com.intellij.util.download.impl.FileDownloaderImpl.downloadFile(FileDownloaderImpl.java:336)
	at com.intellij.util.download.impl.FileDownloaderImpl.lambda$download$1(FileDownloaderImpl.java:233)
	... 13 more
```

## Steps to reproduce

1. Attempt to run a Rust unit test with the debugger.
2. IntelliJ prompts to download the debugger
3. Clicking "Download" results in the error above.

**Comment by kevleyski** [comment]
(having same issue I think - bit annoying, if there is a quick win happy to try it)

**Comment by Undin** [comment]
Should be fixed now

**Comment by ramosbugs** [comment]
works now, thank you!
