### ISSUE TITLE
Unable to debug with Apple M1

### ISSUE THREAD

**Issue by bastien-solutions** [intellij-rust/intellij-rust#6616]
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.49.0
* **IDE name and version:** Intellij 2020.3.1
* **Operating system:**: OSX Big Sur

## Problem description

No problem with code run but when I try to debug it, I got the following error :

```
/Users/xxx/IdeaProjects/testrust/target/debug/testrust
process exited with status -1 (Error 1)

Process finished with exit code 0
```

Nothing special in IJ logs : 

```
2021-01-04 14:18:23,373 [  31192]   INFO - rust.openapiext.CommandLineExt - Executing `/Users/xxx/.cargo/bin/rustc --version --verbose` 
2021-01-04 14:18:24,028 [  31847]   INFO - rust.openapiext.CommandLineExt - Executing `/Users/xxx/.cargo/bin/rustc --print sysroot` 
```

## Steps to reproduce

Just try to debug any rust program with a Mac M1.

**Comment by Undin** [comment]
@bastien-solutions could you enable additional logs for debugger (I mean `#com.jetbrains.cidr.execution.debugger` logs. See https://intellij-support.jetbrains.com/hc/en-us/articles/360001436079-Collecting-additional-logs-in-CLion- for more details), try again and provide logs, please?

Also, could you provide target of your toolchain? I suppose it's `x86_64-apple-darwin`

**Comment by bastien-solutions** [comment]
Please find attached requested log.

For toolchain, here is ones installed on my machine : 
```
stable-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin
1.49.0-aarch64-apple-darwin
```

`stable-aarch64-apple-darwin` is the one selected by IntelliJ Rust plugin.

[log.txt](https://github.com/intellij-rust/intellij-rust/files/5767221/log.txt)

**Comment by Undin** [comment]
@bastien-solutions could you also provide version of Native Debugging Support plugin?

**Comment by bastien-solutions** [comment]
Sure it is 203.6682.168.

**Comment by bastien-solutions** [comment]
Hello @Undin any update regarding this issue ?

**Comment by ortem** [comment]
@bastien-solutions Thank you for the logs and sorry for the long wait. We are working on this and will let you know when we find out something useful.

**Comment by bastien-solutions** [comment]
Thank you guys, let me know if you need anything.

**Comment by ortem** [comment]
@bastien-solutions Currently, we are unable to reproduce the bug: Rust debugging seems to work fine on our M1 machines. But we are still working on that.

It might be helpful for us to investigate the problem if you also provide:
* `idea.log` file (can be found using `Show Log in Finder` action available via `Cmd + Shift + A` menu)
* Minimal reproducible example to check the issue: source code with a binary if possible

**Comment by bastien-solutions** [comment]
What ???
That a good news anyway even if this is not the case for me.
Do you confirm this should work with IntelliJ arm64 and Rust toolchain on darwin-arm64 ?

To reply to yours questions @ortem :

- on idea.log, nothing more than what I have provided 
- For the minimum reproductible project, see below.

```rust main.rs
fn main() {
    let a = 1+1;
    println!("{}",a);   // breakpoint here
}
```

```toml cargo.toml
[package]
name = "testrustdebug"
version = "0.1.0"
authors = ["xxxx <xxxx@xxxx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```


Console log : 

```
/Users/xxxx/IdeaProjects/testrustdebug/target/debug/testrustdebug
process exited with status -1 (Error 1)

Process finished with exit code 0
```

**Comment by bastien-solutions** [comment]
P.S. I think the most promising index is in the detailed logs provided above:

```
2021-01-05 00:20:17,848 [  92321]  DEBUG - brains.cidr.execution.debugger -  
com.jetbrains.cidr.execution.debugger.backend.lldb.LLDBDriverException: process exited with status -1 (Error 1)
	at com.jetbrains.cidr.execution.debugger.backend.lldb.LLDBDriver$ThrowIfNotValid.throwError(LLDBDriver.java:272)
	at com.jetbrains.cidr.execution.debugger.backend.lldb.LLDBDriver$ResponseMessageConsumer.throwIfNeeded(LLDBDriver.java:237)
	at com.jetbrains.cidr.execution.debugger.backend.lldb.LLDBDriver$ThrowIfNotValid.throwIfNeeded(LLDBDriver.java:267)
	at com.jetbrains.cidr.execution.debugger.backend.lldb.LLDBDriver.doLaunch(LLDBDriver.java:828)
	at com.jetbrains.cidr.execution.debugger.backend.lldb.LLDBDriver$6.startImpl(LLDBDriver.java:493)
	at com.jetbrains.cidr.execution.debugger.backend.DebuggerDriver$Inferior.start(DebuggerDriver.java:807)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess.doStartTarget(CidrDebugProcess.java:634)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess.lambda$sessionInitialized$2(CidrDebugProcess.java:627)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$VoidDebuggerCommand.call(CidrDebugProcess.java:981)
	at com.jetbrains.cidr.execution.debugger.CidrDebugProcess$VoidDebuggerCommand.call(CidrDebugProcess.java:975)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor$executeCommand$3.invokeSuspend(CidrDebuggerCommandExecutor.kt:84)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor$executeCommand$3.invoke(CidrDebuggerCommandExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor.executeCommand(CidrDebuggerCommandExecutor.kt:77)
	at com.jetbrains.cidr.execution.debugger.CidrDebuggerCommandExecutor$executeCommandAsync$1.invokeSuspend(CidrDebuggerCommandExecutor.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ortem** [comment]
@bastien-solutions Thank you for providing the example! However, your project seems to debug fine on our machine. 

Since `LLDBDriverException` is not really informative in our case, let's also try to collect the LLDB trace log. Please enable `#com.jetbrains.cidr.execution.debugger:trace` in `Help | Diagnostic Tools | Debug Log Settings`, reproduce the issue, and then post both `idea.log` and `lldb.log` (both are available via `Show Log in Finder`).

**Comment by bastien-solutions** [comment]
Please find attached the requested files.

[idea.log](https://github.com/intellij-rust/intellij-rust/files/5809895/idea.log)
[lldb.log](https://github.com/intellij-rust/intellij-rust/files/5809896/lldb.log)

**Comment by bastien-solutions** [comment]
Hello @ortem ,

Any update considering the provided logs ?

**Comment by ortem** [comment]
Hi @bastien-solutions,

Finally, we have managed to reproduce the issue!

We found out that on Apple M1, Rust debugging works only in CLion, but not in IntelliJ IDEA Ultimate. The reason is that some of debugger binaries for IntelliJ IDEA are compiled only for x86_64, but not for ARM64. So now we are working on providing the proper binaries. I will let you know when they are done and explain how to finally fix the problem.

**Comment by bastien-solutions** [comment]
Great news !
Did you have an idea of the fix availability date ?

**Comment by ortem** [comment]
@bastien-solutions Actually, the fix is almost done! Although the new binary is not available through the IDE yet, it is possible to download them from the server. Please use `curl` to download instead of your web browser to avoid potential quarantine by macOS security:
```
$ cd ~/Library/Caches/JetBrains/IntelliJIdea2020.3.1/intellij-rust/lldb
$ rm ./LLDBFrontend
$ curl -sL 'https://bintray.com/jetbrains/intellij-third-party-dependencies/download_file?file_path=org%2Fjetbrains%2Fintellij%2Fdeps%2Fcidr%2Flldbfrontend%2F2d5d4c8af0f50c4f66581b735cf1ed7b5fcc01ae%2Flldbfrontend-2d5d4c8af0f50c4f66581b735cf1ed7b5fcc01ae-mac-x64.tar.gz' | tar xzf - -C .
```
These commands download and extract the new `LLDBFrontend` binary and replace the old one with it.
Note, your path might be different, and you can find the exact path in `Preferences | Build, Execution, Deployment | Debugger | Rust`

**Comment by bastien-solutions** [comment]
It works perfectly
You're doing great!

**Comment by qiujiangkun** [comment]
> @bastien-solutions Actually, the fix is almost done! Although the new binary is not available through the IDE yet, it is possible to download them from the server. Please use `curl` to download instead of your web browser to avoid potential quarantine by macOS security:
> 
> ```
> $ cd ~/Library/Caches/JetBrains/IntelliJIdea2020.3.1/intellij-rust/lldb
> $ rm ./LLDBFrontend
> $ curl -sL 'https://bintray.com/jetbrains/intellij-third-party-dependencies/download_file?file_path=org%2Fjetbrains%2Fintellij%2Fdeps%2Fcidr%2Flldbfrontend%2F2d5d4c8af0f50c4f66581b735cf1ed7b5fcc01ae%2Flldbfrontend-2d5d4c8af0f50c4f66581b735cf1ed7b5fcc01ae-mac-x64.tar.gz' | tar xzf - -C .
> ```
> 
> These commands download and extract the new `LLDBFrontend` binary and replace the old one with it.
> Note, your path might be different, and you can find the exact path in `Preferences | Build, Execution, Deployment | Debugger | Rust`

I don't have such folder. `locate LLDBFrontend` gives me nothing

**Comment by qiujiangkun** [comment]
My error message is `NSUnbufferedIO is not set, output may be delayed`, not sure why or if it's related to M1

**Comment by justprosh** [comment]
## Environment

* **IntelliJ Rust plugin version:** 0.3.142.3705-203
* **Rust toolchain version:** 1.52.0-nightly (4f20caa62 2021-03-01) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** macOS 11.2.2
* **Macro expansion engine:** new
* **Name resolution engine:** old

Debugging hello_world cause `Exception: EXC_BAD_ACCESS (code=1, address=0x90)` on `ldrb   w23, [x0]`
same with stable toolchain 
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/24271614/110620173-c1741b00-81a9-11eb-868f-4ea4653f187d.png">

**Comment by Undin** [comment]
@justprosh It's known [problem](https://youtrack.jetbrains.com/issue/CPP-23531). Try to use `aarch64-apple-darwin` target instead of `x86_64-apple-darwin`

**Comment by Undin** [comment]
@ortem since this issue is completely different from the original one, consider opening new issue (if you need it, for example, for tracking purposes) or just close since the fix should be done by CLion team and the corresponding issue already exists in youtrack

**Comment by ortem** [comment]
@Undin Thank you for the information! I agree that we can follow the existing CLion's issue
