### ISSUE TITLE
Build View doesn't show full output when build script fails

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#6698]
The output looks like: 
```

error: failed to run custom build command for `recorder v0.1.0 (/Users/user/dev/packages/android)`

Caused by:
  process didn't exit successfully: `/Users/user/rust_target/debug/build/recorder-f97f70973f2f8aeb/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'a `libclang` shared library is not loaded on this thread', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.29.3/src/lib.rs:1659:1
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/core/src/panicking.rs:92:14
     2: core::option::expect_failed
               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/core/src/option.rs:1260:5
     3: core::option::Option<T>::expect
               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:349:21
     4: clang_sys::clang_createIndex
               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.29.3/src/link.rs:156:25
     5: clang::Index::new
               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-0.24.0/src/lib.rs:2655:34
     6: dart_bindgen::Codegen::generate
               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/dart-bindgen-0.1.8/src/lib.rs:98:21
     7: build_script_build::main
               at ./build.rs:18:20
     8: core::ops::function::FnOnce::call_once
               at /Users/user/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed

Process finished with exit code 101
```

![image](https://user-images.githubusercontent.com/436625/105181290-aafffa80-5b3c-11eb-8ec7-2cf77bff9963.png)

![image](https://user-images.githubusercontent.com/436625/105181324-b6ebbc80-5b3c-11eb-8d28-68310ea0ce8c.png)

I guess this is a typical output for errors in __build.rs__

_Originally posted by @chertov in https://github.com/intellij-rust/intellij-rust/issues/6697#issuecomment-763609477_

**Comment by zoombinis** [comment]
In my case, not even a multi-line error is shown, just the first line is shown: `error: failed to run custom build command for...`

**Comment by zoombinis** [comment]
if I run my unit tests in the terminal, I can see the full error:
`~/.cargo/bin/cargo test --color=always --message-format=json-diagnostic-rendered-ansi --no-run --package app --bin app test1`

**Comment by jonay2000** [comment]
I am still experiencing this same issue

**Comment by paulora2405** [comment]
I'm also experiencing the same issue.
Only the first line is presented in the build window.

**Comment by avl** [comment]
Anyone found a workaround? We're using a build.rs script in our project. I just spent a lot of time making sure it gives good errors when it fails. Not everyone on the team is an build.rs expert, so now I'm looking for a way for them to actually see the good errors we produce. Is it possible to output something that CLion will 'scrape' successfullly?
