### ISSUE TITLE
IDE Fatal error when i'm write quotes in argument

### ISSUE THREAD

**Issue by LooMaclin** [intellij-rust/intellij-rust#670]
I'm write next code:
```rust

let mut child_shell = Command::new("xvfb-run")
        .arg("--server-args=\"-screen 0, 1024x768x24\"")

```

And get fatal error with stacktrace:

>Invalid range specified: (57,0); 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:222)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:217)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:213)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:43)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:32)
	at com.intellij.spellchecker.tokenizer.EscapeSequenceTokenizer.getHighlightingRange(EscapeSequenceTokenizer.java:45)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection.createProblemDescriptor(SpellCheckingInspection.java:164)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection.addRegularDescriptor(SpellCheckingInspection.java:154)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection.access$000(SpellCheckingInspection.java:40)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$MyTokenConsumer.consume(SpellCheckingInspection.java:253)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$MyTokenConsumer.consume(SpellCheckingInspection.java:201)
	at com.intellij.spellchecker.inspections.BaseSplitter.addWord(BaseSplitter.java:46)
	at com.intellij.spellchecker.inspections.IdentifierSplitter.split(IdentifierSplitter.java:61)
	at com.intellij.spellchecker.inspections.WordSplitter.split(WordSplitter.java:49)
	at com.intellij.spellchecker.inspections.TextSplitter.doSplit(TextSplitter.java:50)
	at com.intellij.spellchecker.inspections.TextSplitter.split(TextSplitter.java:41)
	at com.intellij.spellchecker.inspections.PlainTextSplitter.split(PlainTextSplitter.java:95)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$MyTokenConsumer.consumeToken(SpellCheckingInspection.java:228)
	at com.intellij.spellchecker.tokenizer.EscapeSequenceTokenizer.processTextWithOffsets(EscapeSequenceTokenizer.java:34)
	at org.rust.ide.spelling.StringLiteralTokenizer.processTextWithEscapeSequences(StringLiteralTokenizer.kt:25)
	at org.rust.ide.spelling.StringLiteralTokenizer.tokenize(StringLiteralTokenizer.kt:17)
	at org.rust.ide.spelling.StringLiteralTokenizer.tokenize(StringLiteralTokenizer.kt:9)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection.tokenize(SpellCheckingInspection.java:133)
	at com.intellij.spellchecker.inspections.SpellCheckingInspection$1.visitElement(SpellCheckingInspection.java:117)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.accept(LeafPsiElement.java:215)
	at org.rust.lang.core.psi.impl.RustTextLiteralImplBase.accept(RustTextLiteralImplBase.kt:17)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:286)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$1(LocalInspectionsPass.java:254)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$0(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:60)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:256)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:228)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:136)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:427)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by LooMaclin** [comment]
В итоге там и не нужны кавычки с экранированием вообще...ну это я так к слову. =)

**Comment by matklad** [comment]
А когда они нужны, то удобнее `r#"quotes "in" raw string"#`.

**Comment by LooMaclin** [comment]
@matklad спасибо, теперь буду знать
