### ISSUE TITLE
Exception in Move Line Up action

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#6709]
## Environment

* **IntelliJ Rust plugin version:** 0.3.140.3613-203-nightly
* **Rust toolchain version:** 1.48.0 (7eac88abb 2020-11-16) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3.1 (CL-203.6682.181)
* **Operating system:** macOS 10.16
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description

Exception stack trace:
```
Cannot perform move

com.intellij.diagnostic.PluginException: Wrong move ranges requested by org.rust.ide.actions.mover.RsCommaListElementUpDownMover@2b81a946 53:138 vs 53:71 [Plugin: org.rust.lang]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:337)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:59)
	at com.intellij.codeInsight.editorActions.moveUpDown.MoverWrapper.move(MoverWrapper.java:92)
	at com.intellij.codeInsight.editorActions.moveUpDown.BaseMoveHandler.executeWriteAction(BaseMoveHandler.java:57)
```

## Steps to reproduce
```Rust
fn foo(x: i32, v: Vec<i32>) {}

fn main() {
    foo(
        42, vec![
            1,
            2, // <caret> Move Up
            3,
        ],
    );
}
```

**Comment by dima74** [comment]
@ortem looks like it was fixed some time ago
