### ISSUE TITLE
Macro Expansion Fails on IntelliJ 2021.1 EAP 1

### ISSUE THREAD

**Issue by HTG-YT** [intellij-rust/intellij-rust#6759]
## Environment

* **IntelliJ Rust plugin version:** 0.3.139.3615-203
* **Rust toolchain version:** 1.51.0-nightly (c0b64d97b 2021-01-28) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2021.1 EAP Ultimate Edition (IU-211.4961.33)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description

When I initially load up my project, everything works and when the plugin goes into the "Expanding Rust macros" stage, this error occurred:

```
Error during macro expansion

com.intellij.diagnostic.PluginException: Cannot create class org.rust.lang.core.macros.MacroExpansionSharedCache (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Rust, id=org.rust.lang, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2021.1\plugins\intellij-rust, version=0.3.139.3615-203, package=null), packagePrefix=null, instanceId=184, state=active))
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:300)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:81)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:760)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:699)
	at com.intellij.serviceContainer.ComponentManagerImpl.access$createLightService(ComponentManagerImpl.kt:55)
	at com.intellij.serviceContainer.ComponentManagerImpl$getOrCreateLightService$1.run(ComponentManagerImpl.kt:596)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:612)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:220)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:595)
	at com.intellij.serviceContainer.ComponentManagerImpl.getLightService$intellij_platform_serviceContainer(ComponentManagerImpl.kt:566)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:478)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
	at org.rust.lang.core.macros.MacroExpansionSharedCache$Companion.getInstance(MacroExpansionSharedCache.kt:361)
	at org.rust.lang.core.macros.ExpansionPipeline$Stage1.expand(MacroExpansionTask.kt:427)
	at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1$stages2$1$result$1$1.invoke(MacroExpansionTask.kt:225)
	at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1$stages2$1$result$1$1.invoke(MacroExpansionTask.kt:50)
	at org.rust.openapiext.UtilsKt$runReadActionInSmartMode$1.compute(utils.kt:275)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:106)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:866)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:143)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:106)
	at org.rust.openapiext.UtilsKt.runReadActionInSmartMode(utils.kt:273)
	at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1$stages2$1$result$1.invoke(MacroExpansionTask.kt:223)
	at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1$stages2$1$result$1.invoke(MacroExpansionTask.kt:50)
	at org.rust.openapiext.UtilsKt$executeUnderProgressWithWriteActionPriorityWithRetries$success$1.invoke(utils.kt:285)
	at org.rust.openapiext.UtilsKt$executeUnderProgressWithWriteActionPriorityWithRetries$success$1.invoke(utils.kt)
	at org.rust.openapiext.UtilsKt$sam$java_lang_Runnable$0.run(utils.kt)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:154)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:56)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:612)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:167)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:56)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at org.rust.openapiext.UtilsKt.runWithWriteActionPriority(utils.kt:297)
	at org.rust.openapiext.UtilsKt.executeUnderProgressWithWriteActionPriorityWithRetries(utils.kt:284)
	at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1$stages2$1.apply(MacroExpansionTask.kt:221)
	at org.rust.lang.core.macros.MacroExpansionTaskBase$submitExpansionTask$1$stages2$1.apply(MacroExpansionTask.kt:50)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:722)
	... 55 more
Caused by: java.lang.NoSuchMethodError: 'void com.intellij.psi.stubs.SerializedStubTreeDataExternalizer.<init>(com.intellij.psi.stubs.SerializationManagerEx, com.intellij.psi.stubs.StubForwardIndexExternalizer)'
	at org.rust.lang.core.macros.CompatUtilsKt.newSerializedStubTreeDataExternalizer(compatUtils.kt:24)
	at org.rust.lang.core.macros.PersistentCacheData$Companion.tryCreate(MacroExpansionSharedCache.kt:263)
	at org.rust.lang.core.macros.MacroExpansionSharedCache.tryCreateData(MacroExpansionSharedCache.kt:79)
	at org.rust.lang.core.macros.MacroExpansionSharedCache.<init>(MacroExpansionSharedCache.kt:61)
	... 60 more
```

## Steps to reproduce

I believe this is reproducible on all Rust projects on IntelliJ 2021.1 EAPs.

**Comment by Undin** [comment]
Fixed by #6741
You can try nightly plugin builds where this fix is already available. See https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly how to do it
