### ISSUE TITLE
StackOverflowError while analyzing `capnp-rpc/src/rpc.rs`

### ISSUE THREAD

**Issue by dima74** [intellij-rust/intellij-rust#6783]
## Environment

* **IntelliJ Rust plugin version:** 0.3.141.SNAPSHOT-203-dev
* **Rust toolchain version:** 1.51.0-nightly (1d0d76f8d 2021-01-24) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2020.3.2 Ultimate Edition (IU-203.7148.57)
* **Operating system:** Linux 5.10.11-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description
```
java.lang.StackOverflowError
	at com.intellij.util.BitUtil.assertOneBitMask(BitUtil.java:58)
	at com.intellij.util.BitUtil.isSet(BitUtil.java:14)
	at org.rust.lang.core.types.infer.HasTypeFlagVisitor.visitTy(Fold.kt:218)
	at org.rust.lang.core.types.ty.Ty.visitWith(Ty.kt:34)
	at org.rust.lang.core.types.infer.FoldKt.getHasTyInfer(Fold.kt:234)
	at org.rust.lang.core.types.infer.FoldKt.getNeedsInfer(Fold.kt:255)
	at org.rust.lang.core.types.infer.RsInferenceContext$OpportunisticVarResolver.foldTy(TypeInference.kt:563)
	at org.rust.lang.core.types.ty.Ty.foldWith(Ty.kt:30)
	at org.rust.lang.core.types.ty.TyFunction.superFoldWith(TyFunction.kt:15)
	at org.rust.lang.core.types.infer.RsInferenceContext$OpportunisticVarResolver.foldTy(TypeInference.kt:565)
	at org.rust.lang.core.types.ty.Ty.foldWith(Ty.kt:30)
	at org.rust.lang.core.types.ty.TyAdt.superFoldWith(TyAdt.kt:58)
	at org.rust.lang.core.types.ty.TyAdt.superFoldWith(TyAdt.kt:32)
	at org.rust.lang.core.types.infer.RsInferenceContext$OpportunisticVarResolver.foldTy(TypeInference.kt:565)
...
```

## Steps to reproduce
Add `capnp-rpc = "0.14.0"` to `Cargo.toml` and open `capnp-rpc/src/rpc.rs` file

**Comment by ramosbugs** [comment]
are there any workarounds for this issue? I've been running into constant StackOverflowErrors since upgrading the plugin to 0.3.143.3737-203 (on rustc 1.50.0).

I'm not 100% sure that it's due to the upgrade and not recent changes to my code, but I can confirm that increasing the stack space to `-Xss8192k` didn't help, so this may be an infinite recursion bug.

**Comment by ramosbugs** [comment]
update: the issue reproed even after downgrading the plugin to 0.3.140.3644-203

**Comment by vlad20012** [comment]
Cannot reproduce this on the latest plugin version
