### ISSUE TITLE
Throwable RustModulesIndex: crate failing to index, no autocomplete available

### ISSUE THREAD

**Issue by ZainlessBrombie** [intellij-rust/intellij-rust#6800]
The module qt_gui 0.5.0 can't be indexed in my setup.
The following Cargo.toml reproduces the issue, the main.rs is just a hello world:

```
[package]
name = "reproduce_1"
version = "0.1.0"
authors = ["ZainlessBrombie"]
edition = "2018"

[dependencies]
qt_core = "0.5.0"
qt_qml = "0.5.0"
qt_gui = "0.5.0"
syn = "=1.0.56"
serde = { version = "1.0.118", features = ["derive"] }
```

## Environment

* **IntelliJ Rust plugin version: 0.3.140.3644-203**
* **Rust toolchain version: stable rustc 1.49.0 (e1884a8e3 2020-12-29); rustup 1.23.1**
* **IDE name and version: clion 2020.3.2; Build #CL-203.7148.70, built on January 26, 2021**
* **Operating system: Ubuntu 20.04.2 LTS; Kernel 5.4.0-65-generic**

## Problem description
The module mentioned above cannot be indexed. The following exception is being thrown, possibly related:

```
2021-02-04 14:19:53,100 [  15884]   INFO - il.indexing.FileBasedIndexImpl - Rebuild requested for index Stubs 
java.lang.Throwable: org.rust.lang.core.stubs.index.RustModulesIndex(index version : 232 -> 234),org.rust.lang.core.stubs.index.RustNamedElementIndex(index version : 232 -> 234),org.rust.lang.core.stubs.index.RustGotoClassIndex(index version : 232 -> 234),org.rust.lang.core.stubs.index.RsReexportIndex(index version : 232 -> 234),org.rust.lang.core.stubs.index.RsExternCrateReexportIndex(index version : 232 -> 234),org.rust.lang.core.stubs.index.RsFeatureIndex(index version : 232 -> 234),org.rust.lang.core.stubs.index.RsCfgIndex(index version : 232 -> 234),org.rust.lang.core.stubs.index.RsIncludeMacroIndex(index version : 232 -> 234),org.rust.lang.core.stubs.index.RustImplIndex.TraitImpls(index version : 232 -> 234),org.rust.lang.core.stubs.index.RsTypeAliasIndex(index version : 232 -> 234),org.rust.lang.core.resolve.indexes.RsLangItemIndex(index version : 232 -> 234),org.rust.lang.core.resolve.indexes.RsMacroIndex(index version : 232 -> 234),org.rust.lang.core.resolve.indexes.RsMacroCallIndex(index version : 232 -> 234)
	at com.intellij.psi.stubs.StubIndexImpl$StubIndexInitialization.finish(StubIndexImpl.java:688)
	at com.intellij.psi.stubs.StubIndexImpl$StubIndexInitialization.finish(StubIndexImpl.java:650)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.call(IndexInfrastructure.java:124)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## Steps to reproduce
Use the Cargo.toml above. Use a struct such as qt_gui::QGuiApplication in main.rs. qt_gui cannot be indexed and context actions are unavailable.

**Comment by Undin** [comment]
@ZainlessBrombie Thanks for the report!
> The module qt_gui 0.5.0 can't be indexed in my setup.

It's expected behavior since `lib.rs` file has more than 17 MB size. By default, files that exceed 2.5 MB size are not indexed by IntelliJ-based IDEs to avoid performance issues. As a result, name resolution, completion and other code insight features may not work as expected.
![image](https://user-images.githubusercontent.com/2539310/107922977-d9c59100-6f81-11eb-944f-bd2c4b0fe496.png)


You can increase the default limit to make it work. It's required changing value of `idea.max.intellisense.filesize` property, for example, to `20000`. See description of common platform properties [here](https://www.jetbrains.com/help/idea/tuning-the-ide.html#common-platform-properties). To configure necessary property, see [instruction](https://www.jetbrains.com/help/idea/tuning-the-ide.html#procedure-platform-properties)

Note, this change may affect IDE performance.

Also, probably, it makes sense to create an issue in `qt_gui` repo not to generate such large files and make the library more IDE-friendly

**Comment by ZainlessBrombie** [comment]
Oh! Thanks
