### ISSUE TITLE
Can not create rust project and open rust settings

### ISSUE THREAD

**Issue by BanqiJane** [intellij-rust/intellij-rust#7202]
## Environment

* **IntelliJ Rust plugin version: 0.3.146.3826-211**
* **Rust toolchain version: 1.51.0 (2fd73fabe 2021-03-23) x86_64-pc-windows-gnu**
* **IDE name and version:  CLion 2021.1.1  Build #CL-211.7142.21**
* **Operating system: Windows 10**
* **Macro expansion engine: new**
* **Name resolution engine: old**

## Problem description
Can not create rust project and open rust settings
![image](https://user-images.githubusercontent.com/44255558/117016255-1bfea300-ad25-11eb-850d-d61ddc46362a.png)
[idea.log](https://github.com/intellij-rust/intellij-rust/files/6421609/idea.log)

```java
2021-05-04 21:47:40,674 [  38263]  ERROR - tions.ex.ConfigurableCardPanel - CLion 2021.1.1  Build #CL-211.7142.21 
2021-05-04 21:47:40,674 [  38263]  ERROR - tions.ex.ConfigurableCardPanel - JDK: 11.0.10; VM: Dynamic Code Evolution 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-05-04 21:47:40,674 [  38263]  ERROR - tions.ex.ConfigurableCardPanel - OS: Windows 10 
2021-05-04 21:47:40,674 [  38263]  ERROR - tions.ex.ConfigurableCardPanel - Plugin to blame: Rust version: 0.3.146.3826-211 
2021-05-04 21:47:40,674 [  38263]  ERROR - tions.ex.ConfigurableCardPanel - Last Action: ShowLog 
2021-05-04 21:47:40,674 [  38263]  ERROR - pplication.impl.LaterInvocator - Illegal char <"> at index 0: " 
java.nio.file.InvalidPathException: Illegal char <"> at index 0: "
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.rust.stdext.UtilsKt.toPath(Utils.kt:43)
	at org.rust.cargo.toolchain.flavors.RsSysPathToolchainFlavor.getHomePathCandidates(RsSysPathToolchainFlavor.kt:19)
	at org.rust.cargo.toolchain.flavors.RsToolchainFlavor.suggestHomePaths(RsToolchainFlavor.kt:17)
	at org.rust.cargo.toolchain.RsToolchain$Companion$suggest$1.invoke(RsToolchain.kt:77)
	at org.rust.cargo.toolchain.RsToolchain$Companion$suggest$1.invoke(RsToolchain.kt:63)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:133)
	at org.rust.cargo.toolchain.RsToolchain$Companion.suggest(RsToolchain.kt:79)
	at org.rust.cargo.project.settings.ui.RustProjectSettingsPanel.attachTo(RustProjectSettingsPanel.kt:94)
	at org.rust.cargo.project.configurable.RsProjectConfigurable.createPanel(RsProjectConfigurable.kt:33)
	at com.intellij.openapi.options.DslConfigurableBase$panel$1.compute(BoundConfigurable.kt:35)
	at com.intellij.openapi.options.DslConfigurableBase$panel$1.compute(BoundConfigurable.kt:30)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:39)
	at com.intellij.openapi.options.DslConfigurableBase.isModified(BoundConfigurable.kt:45)
	at org.rust.cargo.project.configurable.RsProjectConfigurable.isModified(RsProjectConfigurable.kt:78)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.isModified(ConfigurableWrapper.java:174)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedInternal(SettingsEditor.java:461)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModifiedForItem(SettingsEditor.java:455)
	at com.intellij.openapi.options.newEditor.SettingsEditor.checkModified(SettingsEditor.java:443)
	at com.intellij.openapi.options.newEditor.SettingsEditor$5.updateCurrent(SettingsEditor.java:210)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.lambda$select$1(ConfigurableEditor.java:246)
	at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:44)
	at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:116)
	at com.intellij.ui.CardLayoutPanel.lambda$selectLater$0(CardLayoutPanel.java:127)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:797)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:436)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1702)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1661)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:134)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:107)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:99)
	at org.rust.cargo.project.settings.impl.RustProjectSettingsServiceImpl.configureToolchain(RustProjectSettingsServiceImpl.kt:96)
	at org.rust.ide.notifications.MissingToolchainNotificationProvider$createBadToolchainPanel$$inlined$apply$lambda$1.run(MissingToolchainNotificationProvider.kt:91)
	at com.intellij.ui.EditorNotificationPanel$1.handlePanelActionClick(EditorNotificationPanel.java:241)
	at com.intellij.ui.EditorNotificationPanel$ActionHyperlinkLabel$1.hyperlinkActivated(EditorNotificationPanel.java:287)
	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:11)
	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:240)
	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:162)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-05-04 21:47:40,674 [  38263]  ERROR - pplication.impl.LaterInvocator - CLion 2021.1.1  Build #CL-211.7142.21 
2021-05-04 21:47:40,674 [  38263]  ERROR - pplication.impl.LaterInvocator - JDK: 11.0.10; VM: Dynamic Code Evolution 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-05-04 21:47:40,674 [  38263]  ERROR - pplication.impl.LaterInvocator - OS: Windows 10 
2021-05-04 21:47:40,674 [  38263]  ERROR - pplication.impl.LaterInvocator - Plugin to blame: Rust version: 0.3.146.3826-211 
2021-05-04 21:47:40,674 [  38263]  ERROR - pplication.impl.LaterInvocator - Last Action: ShowLog 
```

**Comment by mchernyavsky** [comment]
Hi! Can you please show your `PATH` variable?

```rust
fn main() {
    let key = "PATH";
    match std::env::var_os(key) {
        Some(paths) => {
            for path in std::env::split_paths(&paths) {
                println!("'{}'", path.display());
            }
        }
        None => println!("{} is not defined in the environment.", key)
    }
}
```

**Comment by BanqiJane** [comment]
```
E:\WorkSpace\workspace to rust\tr\greeting>cargo build
   Compiling greeting v0.1.0 (E:\WorkSpace\workspace to rust\tr\greeting)
    Finished dev [unoptimized + debuginfo] target(s) in 2.89s

E:\WorkSpace\workspace to rust\tr\greeting>cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target\debug\greeting.exe`
'E:\WorkSpace\workspace to rust\tr\greeting\target\debug\deps'
'E:\WorkSpace\workspace to rust\tr\greeting\target\debug'
'E:\web\rust\rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib'
'E:\web\rust\cargo\bin'
'E:\web\rust\rustup\toolchains\stable-x86_64-pc-windows-gnu\bin'
'C:\Program Files (x86)\Common Files\Oracle\Java\javapath'
'C:\Program Files\Java\jdk1.8.0_251\bin'
'C:\Program Files\Java\jdk1.8.0_251\jre\bin'
'C:\Windows\system32'
'C:\Windows'
'C:\Windows\System32\Wbem'
'C:\Windows\System32\WindowsPowerShell\v1.0\'
'C:\Windows\System32\OpenSSH\'
'C:\Program Files\Intel\WiFi\bin\'
'C:\Program Files\Common Files\Intel\WirelessCommon\'
'E:\web\apache-maven-3.6.0\bin'
'E:\web\nodejs\'
'E:\web\php-7.3.1'
'E:\web\php-7.3.1\ext'
'E:\web\gradle-6.5.1\bin'
'E:\web\Git\cmd'
'E:\web\nodejs\npm_global'
'C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common'
'E:\web\Go\bin'
'D:\Program Files\Xhell7\'
'C:\Program Files\Docker\Docker\resources\bin'
'C:\ProgramData\DockerDesktop\version-bin'
'E:\web\msys64\usr\bin'
'E:\web\rust\cargo\bin'
'C:\Users\zjian\AppData\Local\Microsoft\WindowsApps'
'C:\Program Files\Java\jdk1.8.0_251\bin'
';C:\Program Files\Java\jdk1.8.0_251\jre\bin'
'C:\Program Files\Intel\WiFi\bin\'
'C:\Program Files\Common Files\Intel\WirelessCommon\'
'C:\Users\zjian\AppData\Local\GitHubDesktop\bin'
'C:\Users\zjian\go\bin'
'E:\Program Files\Fiddler'

E:\WorkSpace\workspace to rust\tr\greeting>
```

**Comment by BanqiJane** [comment]
Thanks you！ I found the problem. This comes from the users jre path error.
