### ISSUE TITLE
Opening a project inside a workspace results in CLion being unable to attach the Cargo project.

### ISSUE THREAD

**Issue by d0nut-grapl** [intellij-rust/intellij-rust#7222]
## Environment

* **IntelliJ Rust plugin version:** 0.3.146.3826-211
* **Rust toolchain version:** 1.52.1 (9bc8c42bb 2021-05-09) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.1.1 (CL-211.7142.21)
* **Operating system:** Linux 5.4.99-12983-g8b7876ab9f5e
* **Macro expansion engine:** new
* **Name resolution engine:** old

## Problem description

When opening a project that is inside of a workspace, CLion notes that "No Cargo projects found". Additionally, when attempting to manually attach to a Cargo project, CLion silently fails with the following exception.

```
2021-05-13 14:25:42,469 [ 118599]   INFO - oject.model.impl.CargoSyncTask - CargoSyncTask started 
2021-05-13 14:25:42,471 [ 118601]   INFO - rust.openapiext.CommandLineExt - Executing `/home/nlattimer/.cargo/bin/rustc --print sysroot` 
2021-05-13 14:25:42,595 [ 118725]   INFO - rust.openapiext.CommandLineExt - Executing `/home/nlattimer/.cargo/bin/rustc --version --verbose` 
2021-05-13 14:25:42,837 [ 118967]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=node-identifier, containerState=COMPONENT_CREATED, componentStore=/home/nlattimer/src/grapl/src/rust/node-identifier)RunManager took 19 ms 
2021-05-13 14:25:44,974 [ 121104]   INFO - rust.openapiext.CommandLineExt - Executing `/home/nlattimer/.cargo/bin/rustup component list` 
2021-05-13 14:25:45,098 [ 121228]   INFO - rust.openapiext.CommandLineExt - Executing `/home/nlattimer/.cargo/bin/rustc --print sysroot` 
2021-05-13 14:25:45,193 [ 121323]   INFO - t.cargo.toolchain.tools.Rustup - stdlib path: /home/nlattimer/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust 
2021-05-13 14:25:45,235 [ 121365]  ERROR -    #org.rust.stdext.AsyncValue - java.lang.RuntimeException: java.lang.IllegalStateException: Source folder file:///home/nlattimer/src/grapl/src/rust/target/debug/build/memchr-bd435ecf4cb3b273/out must be under content entry file:///home/nlattimer/src/grapl/src/rust/node-identifier 
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.IllegalStateException: Source folder file:///home/nlattimer/src/grapl/src/rust/target/debug/build/memchr-bd435ecf4cb3b273/out must be under content entry file:///home/nlattimer/src/grapl/src/rust/node-identifier
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.rust.cargo.project.model.impl.CargoSyncTask.run(CargoSyncTask.kt:90)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Source folder file:///home/nlattimer/src/grapl/src/rust/target/debug/build/memchr-bd435ecf4cb3b273/out must be under content entry file:///home/nlattimer/src/grapl/src/rust/node-identifier
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:428)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded(actions.kt:34)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded$default(actions.kt:27)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt.setupProjectRoots(CargoProjectImpl.kt:568)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt.access$setupProjectRoots(CargoProjectImpl.kt:1)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$doRefresh$1.apply(CargoProjectImpl.kt:553)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$doRefresh$1.apply(CargoProjectImpl.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 20 more
```  

## Steps to reproduce

Relevant link to repository: https://github.com/grapl-security/grapl/tree/main/src/rust

1. Open a project within a Cargo workspace with CLion. (e.g. node-identifier)
2. Observe that CLion reports that "No Cargo projects found"
3. Attempt to manually attach a Cargo project via Cargo menu on the right side.
4. Observe that CLion begins work on this task but exits quietly.
5. Open the logs via Help -> "Show Log in Visual Studio Code" 
6. Observe cited exception above

## Workaround

The current workaround I've been using is just opening the whole workspace in CLion instead of an inner project.

**Comment by Undin** [comment]
@d0nut-grapl Thanks for the report!
Opening of a single workspace crate is not supposed to work at all because we use Cargo to retrieve data about project structure and Cargo checks the corresponding manifest files in parent directories and, if it exists, Cargo analyzes the whole workspace.
So, actually, the plugin should explicitly say something user-friendly in such cases to inform about unsupported configuration.

In addition to your workaround, I can also suggest excluding the crate from the workspace manifest (for example, via [`exclude`](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspace-section) field) if it's important for you to open a crate without workspace

**Comment by Undin** [comment]
Related to #6844

**Comment by d0nut-grapl** [comment]
Oh that's odd. It's a regression in behavior as opening a crate within a workspace used to work fine. I'm assuming that was an unintended "feature"? :P

**Comment by Undin** [comment]
> Oh that's odd. It's a regression in behavior as opening a crate within a workspace used to work fine. I'm assuming that was an unintended "feature"? :P

I don't consider it as "an unintended "feature"". From Cargo point of view, workspace member is a workspace part even if you  run commands inside member directory. I think it's possible to implement such behavior and open a workspace members as an independent cargo project in the plugin, but it will require some non-obvious work that we don't plan to do, at least in the nearest future, only user-friendly error messages
