### ISSUE TITLE
Cannot profile in 212-213: Class DTraceProfilerSettings must be not requested from main classloader of com.intellij.clion plugin

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#7448]
## Environment

* **IntelliJ Rust plugin version:** 0.4.151.3964-212-nightly
* **Rust toolchain version:** 1.52.0-nightly (b3e19a221 2021-03-12) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.3 EAP (CL-213.777)
* **Operating system:** macOS 10.15.7
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Error trying to profile a simple Rust binary

<img width="1075" alt="error" src="https://user-images.githubusercontent.com/2500320/124388034-87470000-dce9-11eb-8b2d-a2e38622848f.png">

## Steps to reproduce

1. Create a binary Rust project
2. Try to profile `main.rs`

```
2021-07-04 16:59:05,980 [ 135831]   INFO - xecution.runners.ExecutionUtil - Error running 'Run':<br>Class com.intellij.profiler.clion.dtrace.DTraceProfilerSettings must be not requested from main classloader of com.intellij.clion plugin [Plugin: org.rust.lang] 
com.intellij.diagnostic.PluginException: Class com.intellij.profiler.clion.dtrace.DTraceProfilerSettings must be not requested from main classloader of com.intellij.clion plugin [Plugin: org.rust.lang]
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:299)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:251)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.rust.clion.profiler.dtrace.CompatUtilsKt.getDTraceSettings(compatUtils.kt:24)
	at org.rust.clion.profiler.dtrace.CompatUtilsKt.validateDTraceSettings(compatUtils.kt:18)
	at org.rust.clion.profiler.dtrace.RsDTraceConfigurationExtension.patchCommandLine(RsDTraceConfigurationExtension.kt:43)
	at org.rust.cargo.runconfig.RsRunConfigurationExtensionManager.patchCommandLine(RsRunConfigurationExtensionManager.kt:35)
	at org.rust.cargo.runconfig.UtilsKt.executeCommandLine(Utils.kt:196)
	at org.rust.cargo.runconfig.RsExecutableRunner.executeCommandLine(RsExecutableRunner.kt:118)
	at org.rust.cargo.runconfig.RsExecutableRunner.showRunContent(RsExecutableRunner.kt:112)
	at org.rust.cargo.runconfig.RsExecutableRunner.doExecute(RsExecutableRunner.kt:92)
	at org.rust.cargo.runconfig.RsDefaultProgramRunnerBase$execute$1.invoke(RsDefaultProgramRunnerBase.kt:25)
	at org.rust.cargo.runconfig.RsDefaultProgramRunnerBase$execute$1.invoke(RsDefaultProgramRunnerBase.kt:18)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:171)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:70)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:232)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:817)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Undin** [comment]
@lancelote is it true that it cannot be reproduced with 212 EAPs?

**Comment by lancelote** [comment]
@Undin No, sorry, my mistake. 212 EAPs are also affected. Only 2021.1 is working correctly.

**Comment by Undin** [comment]
Should be fixed in the latest CLion EAP.
@lancelote could you verify it, please?

**Comment by lancelote** [comment]
Works fine in CLion 2021.2 EAP Build #CL-212.4638.8, built on July 6, 2021.
Thank you.
