### ISSUE TITLE
IndexNotReadyException in RsAsyncParameterInfoHandler

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#7477]
## Environment

* **IntelliJ Rust plugin version:** 0.4.149.3903-211-nightly
* **Rust toolchain version:** 1.52.1 (9bc8c42bb 2021-05-09) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.1.2 Ultimate Edition (IU-211.7442.40)
* **Operating system:** macOS 11.2.3
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
`RsAsyncParameterInfoHandler` does not check dumb mode and this leads to `IndexNotReadyException`

<details>
  <summary>Exception</summary>

```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
    at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
    at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:62)
    at org.rust.openapiext.UtilsKt.checkIsSmartMode(utils.kt:103)
    at org.rust.lang.core.resolve2.FacadeUpdateDefMapKt.getOrUpdateIfNeeded(FacadeUpdateDefMap.kt:39)
    at org.rust.lang.core.resolve2.FacadeResolveKt.findModDataFor(FacadeResolve.kt:629)
    at org.rust.lang.core.psi.RsFile.doGetCachedData(RsFile.kt:103)
    at org.rust.lang.core.psi.RsFile.access$doGetCachedData(RsFile.kt:68)
    at org.rust.lang.core.psi.RsFile$cachedData$1$value$1.compute(RsFile.kt:93)
    at org.rust.lang.core.psi.RsFile$cachedData$1$value$1.compute(RsFile.kt:68)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at org.rust.openapiext.UtilsKt.recursionGuard(utils.kt:67)
    at org.rust.openapiext.UtilsKt.recursionGuard$default(utils.kt:66)
    at org.rust.lang.core.psi.RsFile$cachedData$1.compute(RsFile.kt:93)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
    at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
    at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
    at org.rust.lang.core.psi.RsFile.getCachedData(RsFile.kt:92)
    at org.rust.lang.core.psi.RsFile.getCargoProject(RsFile.kt:74)
    at org.rust.lang.core.psi.ext.RsElementKt.getCargoProject(RsElement.kt:40)
    at org.rust.lang.core.resolve.KnownItemsKt.getKnownItems(KnownItems.kt:41)
    at org.rust.lang.core.types.infer.TypeInferenceKt.inferTypesIn(TypeInference.kt:30)
    at org.rust.lang.core.types.ExtensionsKt$inference$1.compute(Extensions.kt:75)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
    at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
    at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
    at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:74)
    at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:165)
    at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.advancedMultiresolveUsingInferenceCache(RsPathReferenceImpl.kt:92)
    at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.advancedMultiResolve(RsPathReferenceImpl.kt:88)
    at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.multiResolve(RsPathReferenceImpl.kt:76)
    at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
    at org.rust.lang.core.resolve.ref.RsReferenceBase.resolve(RsReferenceBase.kt:28)
    at org.rust.ide.utils.CallInfo$Companion.resolve(CallInfo.kt:33)
    at org.rust.ide.hints.parameter.RsArgumentsDescription$Companion.findDescription(RsParameterInfoHandler.kt:80)
    at org.rust.ide.hints.parameter.RsParameterInfoHandler.calculateParameterInfo(RsParameterInfoHandler.kt:30)
    at org.rust.ide.hints.parameter.RsParameterInfoHandler.calculateParameterInfo(RsParameterInfoHandler.kt:25)
    at org.rust.ide.hints.parameter.RsAsyncParameterInfoHandler$findElementForParameterInfo$1.call(RsAsyncParameterInfoHandler.kt:43)
    at org.rust.ide.hints.parameter.RsAsyncParameterInfoHandler$findElementForParameterInfo$1.call(RsAsyncParameterInfoHandler.kt:25)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
    at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
    at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
    at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

**Comment by mili-l** [comment]
the same for

## Environment

* **IntelliJ Rust plugin version:** 0.4.179.4874-222-nightly
* **Rust toolchain version:** 1.65.0-nightly (78a891d36 2022-09-06) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.2.2 RC Ultimate Edition (IU-222.4167.21)
* **Operating system:** macOS 11.5.1
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal
