### ISSUE TITLE
Code coverage not shown, java.lang.NumberFormatException thrown in console

### ISSUE THREAD

**Issue by werner291** [intellij-rust/intellij-rust#7580]
## Environment

* **IntelliJ Rust plugin version:** 0.4.151.3997-211
* **Rust toolchain version:** 1.55.0-nightly (cebef2951 2021-07-22)
* **IDE name and version:** CLion 2021.1.2  Build #CL-211.7442.42
* **Operating system:** NixOS 21.05

## Problem description

Hello, I'm getting the following issue after running my tests with coverage:

```
java.lang.NumberFormatException: For input string: "3747759300"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at org.rust.coverage.LcovCoverageReport$Serialization$readLcov$1.invoke(LcovCoverageReport.kt:65)
        at org.rust.coverage.LcovCoverageReport$Serialization$readLcov$1.invoke(LcovCoverageReport.kt:51)
        at kotlin.io.TextStreamsKt.forEachLine(ReadWrite.kt:155)
        at kotlin.io.FilesKt__FileReadWriteKt.forEachLine(FileReadWrite.kt:190)
        at kotlin.io.FilesKt__FileReadWriteKt.forEachLine$default(FileReadWrite.kt:188)
        at org.rust.coverage.LcovCoverageReport$Serialization.readLcov(LcovCoverageReport.kt:51)
        at org.rust.coverage.RsCoverageRunner$Companion.readProjectData(RsCoverageRunner.kt:67)
        at org.rust.coverage.RsCoverageRunner$Companion.access$readProjectData(RsCoverageRunner.kt:47)
        at org.rust.coverage.RsCoverageRunner$loadCoverageData$1.invoke(RsCoverageRunner.kt:36)
        at org.rust.coverage.RsCoverageRunner$loadCoverageData$1.invoke(RsCoverageRunner.kt:35)
        at org.rust.openapiext.UtilsKt.computeWithCancelableProgress$lambda-8(utils.kt:242)
        at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:275)
        at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
        at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:545)
        at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:78)
        at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
        at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
        at java.base/java.lang.Thread.run(Thread.java:834)
2021-07-26 14:30:14,683 [3164262]  ERROR - llij.ide.plugins.PluginManager - CLion 2021.1.2  Build #CL-211.7442.42 
2021-07-26 14:30:14,683 [3164262]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: Oracle Corporation 
2021-07-26 14:30:14,683 [3164262]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2021-07-26 14:30:14,684 [3164263]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Rust version: 0.4.151.3997-211 
2021-07-26 14:30:14,684 [3164263]  ERROR - llij.ide.plugins.PluginManager - Last Action: SwitchCoverage 
```

I cannot open the coverage data for my project.

## Steps to reproduce

(Note about this: see my post lower down about a minimal working example to reproduce the exception.)

- Run tests with coverage
- Go to Run > Show coverage data...
- Select one of the coverage data entries
- Observe that nothing happens, but the above exception is thrown.

**Comment by werner291** [comment]
Looks like the number is just too large to be parsed as an integer.

**Comment by werner291** [comment]
Ok, this looks to be project-specific, coverage simply works on a tiny, one-file test project.

**Comment by werner291** [comment]
Actually, it's specific to only some tests... Some tests seem to produce coverage data just fine.

**Comment by werner291** [comment]
Never mind, wiping caches and recompiling everything fixed it. Perhaps it was due to some of the caches still being around from before I upgraded my IDE.

**Comment by werner291** [comment]
Nope, it's back: it appears to be related to my use of the `proptest` crate.

That would explain the source of the huge number: Proptest will likely run my code a far larger number of times than average test cases would. I'm still not quite sure where exactly the large number is coming from, though.

**Comment by werner291** [comment]
So, looks like just cranking up the numbers does the trick, here's a working minimal example:

```
use proptest::prelude::*;

proptest! {
    #[test]
    fn foo(_a in  -1000..=1000,
        _b in  -1000..=1000,
        _c in  -1000.0..=1000.0) {

        let mut i = 0;
        for _ in 0..10000000 {
            i+=1;
        }
        assert_eq!(i, 10000000);
    }
}
```

This only uses `proptest="1.0.0"` as a dependency.

Of course, that example here is a bit contrived, but it appears I've actually run into a similar issue in an actual project I'm working on.

**Comment by mchernyavsky** [comment]
I have fixed the exception in https://github.com/intellij-rust/intellij-rust/pull/7587, but unfortunately, the code coverage tool for Rust doesn't support macros. You can generate a coverage report by grcov and see the result. See "Example: How to generate .gcda files for a Rust project" - https://github.com/mozilla/grcov.

**Comment by werner291** [comment]
Do you mean it won't show coverage inside the macro? Or that coverage isn't registered when the method calls originate from within a macro?

If its the latter I don't really care, since I don't really care about coverage of the test suite itself.

**Comment by mchernyavsky** [comment]
> Do you mean it won't show coverage inside the macro?

this

<img width="1334" alt="Screenshot 2021-07-27 at 12 20 16" src="https://user-images.githubusercontent.com/6079006/127129825-3171744e-b9b5-4e92-a546-04f409c33fb0.png">

**Comment by werner291** [comment]
Then there is no problem as far as I can tell, unless someone enters a strange scenario where they'd have to assess the coverage of the test suite itself.

Thanks for the fix, looking forward to seeing it appear in my update queue!
