### ISSUE TITLE
Sometimes random IllegalStateException when CARGO_TARGET_DIR ist set

### ISSUE THREAD

**Issue by kellerkindt** [intellij-rust/intellij-rust#7583]
## Environment

* **IntelliJ Rust plugin version:** Rust version: 0.4.151.3997-211
* **Rust toolchain version:** rustc 1.53.0 (53cb7b09b 2021-06-17) stable-x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.1.3  Build #CL-211.7628.27 
* **Operating system:** Ubuntu 20.04, Linux Kernel 5.11

## Problem description
When the environment variable `CARGO_TARGET_DIR` is set (in this case to a temp-directory), IllegalStateExceptions start to arise at some point (maybe when there are too many crates in the local workspace?). It then proceeds to complain that some crate's (which excatly changes sometimes after a `cargo clean` and restart with cache invalidation) out directory... is in the wrong place? I had this for libc, tokio and syn (stacktrace below). Once the exceptions start to arise, the crates list in the cargo view does no longer updates on changes to the workspace `Cargo.toml`. Manually reloading the project does not work. Removing the workspace works, adding it afterwards (in its broken state) doesn't work. This means that newly added crates are treat as detached crates - and therefore have no proper auto-complete and package resolution.
```
2021-07-26 17:52:16,901 [  31110]  ERROR -    #org.rust.stdext.AsyncValue - java.lang.RuntimeException: java.lang.IllegalStateException: Source folder file:///tmp/cargo-target/debug/build/syn-af7adf8301d34a6b/out must be under content entry file:///home/.../projects/lukas/rust 
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.IllegalStateException: Source folder file:///tmp/cargo-target/debug/build/syn-af7adf8301d34a6b/out must be under content entry file:///home/.../projects/lukas/rust
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.rust.cargo.project.model.impl.CargoSyncTask.run(CargoSyncTask.kt:91)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Source folder file:///tmp/cargo-target/debug/build/syn-af7adf8301d34a6b/out must be under content entry file:///home/.../projects/lukas/rust
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:428)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded(actions.kt:34)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded$default(actions.kt:27)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt.setupProjectRoots(CargoProjectImpl.kt:576)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt.doRefresh$lambda-7(CargoProjectImpl.kt:561)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 20 more
Caused by: java.lang.IllegalStateException: Source folder file:///tmp/cargo-target/debug/build/syn-af7adf8301d34a6b/out must be under content entry file:///home/.../projects/lukas/rust
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableContentEntryBridge.addSourceFolder(ModifiableContentEntryBridge.kt:46)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableContentEntryBridge.addSourceFolder(ModifiableContentEntryBridge.kt:204)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableContentEntryBridge.addSourceFolder(ModifiableContentEntryBridge.kt:195)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableContentEntryBridge.addSourceFolder(ModifiableContentEntryBridge.kt:192)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableContentEntryBridge.addSourceFolder(ModifiableContentEntryBridge.kt:189)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$setupProjectRoots$1$1$1$setupPackage$2.consume(CargoProjectImpl.kt:608)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$setupProjectRoots$1$1$1$setupPackage$2.consume(CargoProjectImpl.kt:606)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.lambda$updateModel$8(ModuleRootModificationUtil.java:128)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.modifyModel(ModuleRootModificationUtil.java:136)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:127)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$setupProjectRoots$1$1$1.run$setupPackage(CargoProjectImpl.kt:606)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$setupProjectRoots$1$1$1.run$setupPackage(CargoProjectImpl.kt:612)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$setupProjectRoots$1$1$1.run$setupPackage(CargoProjectImpl.kt:612)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$setupProjectRoots$1$1$1.run$setupPackage(CargoProjectImpl.kt:612)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$setupProjectRoots$1$1$1.run(CargoProjectImpl.kt:623)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.mergeRootsChangesDuring(ProjectRootManagerImpl.java:402)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$setupProjectRoots$1$invoke$$inlined$runWriteAction$1.compute(actions.kt:62)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$15(ApplicationImpl.java:968)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:947)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:968)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$setupProjectRoots$1.invoke(CargoProjectImpl.kt:642)
	at org.rust.cargo.project.model.impl.CargoProjectImplKt$setupProjectRoots$1.invoke(CargoProjectImpl.kt:576)
	at com.intellij.openapi.application.ActionsKt$invokeAndWaitIfNeeded$$inlined$computeDelegated$lambda$1.run(actions.kt:34)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:428)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-07-26 17:52:16,904 [  31113]  ERROR -    #org.rust.stdext.AsyncValue - CLion 2021.1.3  Build #CL-211.7628.27 
2021-07-26 17:52:16,904 [  31113]  ERROR -    #org.rust.stdext.AsyncValue - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-07-26 17:52:16,904 [  31113]  ERROR -    #org.rust.stdext.AsyncValue - OS: Linux 
2021-07-26 17:52:16,904 [  31113]  ERROR -    #org.rust.stdext.AsyncValue - Plugin to blame: Rust version: 0.4.151.3997-211 
2021-07-26 17:52:16,904 [  31113]  ERROR -    #org.rust.stdext.AsyncValue - Last Action: WelcomeScreen.OpenDirectoryProject 

```

## Steps to reproduce
Sorry, but I cannot share the workspace. I just started to split a big crate into many smaller ones, when the exceptions suddenly started. Before that it worked fine. I couldn't figure out what exactly caused the exceptions to appear. FWIW, my workspace currently hosts 28 crates. Unsetting the environment variable results in an expected behavior of the IDE.

**Comment by kellerkindt** [comment]
So apparently a symlink from `$workspace/target` to wherever `$CARGO_TARGET_DIR` is also causing this issue (in CLion 2021.2??)?
