### ISSUE TITLE
Exception in `Trust Project` dialog when cloning a project from VCS

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#7599]
## Environment

* **IntelliJ Rust plugin version:** 0.4.153.4014-212-nightly
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2 (CL-212.4746.61), CLion 2021.3 (CL-213.1557)
* **Operating system:** macOS 11.2.3
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

<details>
<summary>Exception</summary>

```
java.lang.Throwable: Assertion failed: Do not use API that changes roots from roots events. Try using invoke later or something else.
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:218)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireBeforeRootsChanged(ProjectRootManagerImpl.java:430)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.beforeRootsChanged(ProjectRootManagerImpl.java:102)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:417)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl$modifyProjects$1$1$invoke$$inlined$runWriteAction$1.compute(actions.kt:78)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$15(ApplicationImpl.java:945)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:924)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:945)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl$modifyProjects$1$1.invoke(CargoProjectImpl.kt:642)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl$modifyProjects$1$1.invoke(CargoProjectImpl.kt:316)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded(actions.kt:29)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded$default(actions.kt:26)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl.modifyProjects$lambda-8(CargoProjectImpl.kt:316)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl.modifyProjects(CargoProjectImpl.kt:315)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl.refreshAllProjects(CargoProjectImpl.kt:201)
	at org.rust.ide.security.RsTrustChangeNotifier.projectTrusted(RsTrustChangeNotifier.kt:19)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:386)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:172)
	at com.sun.proxy.$Proxy144.beforeRootsChange(Unknown Source)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.fireBeforeRootsChangeEvent(ProjectRootManagerComponent.java:221)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireBeforeRootsChanged(ProjectRootManagerImpl.java:432)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.beforeRootsChanged(ProjectRootManagerImpl.java:102)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:417)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl$modifyProjects$1$1$invoke$$inlined$runWriteAction$1.compute(actions.kt:78)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$15(ApplicationImpl.java:945)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:924)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:945)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl$modifyProjects$1$1.invoke(CargoProjectImpl.kt:642)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl$modifyProjects$1$1.invoke(CargoProjectImpl.kt:316)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded(actions.kt:29)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded$default(actions.kt:26)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl.modifyProjects$lambda-8(CargoProjectImpl.kt:316)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl.modifyProjects(CargoProjectImpl.kt:315)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl.refreshAllProjects(CargoProjectImpl.kt:201)
	at org.rust.ide.security.RsTrustChangeNotifier.projectTrusted(RsTrustChangeNotifier.kt:19)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy207.projectTrusted(Unknown Source)
	at com.intellij.ide.impl.TrustedProjects.setTrusted(TrustedProjects.kt:124)
	at org.rust.cargo.project.CargoProjectOpenProcessor.doOpenProject(CargoProjectOpenProcessor.kt:40)
	at com.intellij.ide.impl.ProjectUtil.lambda$chooseProcessorAndOpen$9(ProjectUtil.java:329)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:456)
	at com.intellij.ide.impl.ProjectUtil.chooseProcessorAndOpen(ProjectUtil.java:328)
	at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:195)
	at com.intellij.openapi.vcs.checkout.PlatformProjectCheckoutListener.processCheckedOutDirectory(PlatformProjectCheckoutListener.java:17)
	at com.intellij.openapi.vcs.checkout.CompositeCheckoutListener.notifyCheckoutListeners(CompositeCheckoutListener.java:48)
	at com.intellij.openapi.vcs.checkout.CompositeCheckoutListener.checkoutCompleted(CompositeCheckoutListener.java:75)
	at git4idea.checkout.GitCheckoutProvider$1.onSuccess(GitCheckoutProvider.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:600)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.finishTask(ProgressManagerImpl.java:162)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$6(CoreProgressManager.java:523)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:881)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:817)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:482)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>

## Steps to reproduce

1. Open any project in CLion
2. Open `Git | Clone...` dialog (or `VCS | Get from Version Control...` if the project is not under git) and clone any Rust project
3. Choose `Trust Project` in dialog introduced in #7432
4. The exception is thrown

**Comment by ortem** [comment]
The same exception when clicking `Trust project...` in editor notification after adding a new Rust file to a non-Rust project

<details>
<summary>Exception</summary>

```
java.lang.Throwable: Assertion failed: Do not use API that changes roots from roots events. Try using invoke later or something else.
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:218)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireBeforeRootsChanged(ProjectRootManagerImpl.java:430)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.beforeRootsChanged(ProjectRootManagerImpl.java:102)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:417)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl$modifyProjects$1$1$invoke$$inlined$runWriteAction$1.compute(actions.kt:78)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$15(ApplicationImpl.java:945)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:924)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:945)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl$modifyProjects$1$1.invoke(CargoProjectImpl.kt:642)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl$modifyProjects$1$1.invoke(CargoProjectImpl.kt:316)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded(actions.kt:29)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded$default(actions.kt:26)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl.modifyProjects$lambda-8(CargoProjectImpl.kt:316)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl.modifyProjects(CargoProjectImpl.kt:315)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl.refreshAllProjects(CargoProjectImpl.kt:201)
	at org.rust.ide.security.RsTrustChangeNotifier.projectTrusted(RsTrustChangeNotifier.kt:19)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:386)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:172)
	at com.sun.proxy.$Proxy68.beforeRootsChange(Unknown Source)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.fireBeforeRootsChangeEvent(ProjectRootManagerComponent.java:221)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireBeforeRootsChanged(ProjectRootManagerImpl.java:432)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.beforeRootsChanged(ProjectRootManagerImpl.java:102)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:417)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl$modifyProjects$1$1$invoke$$inlined$runWriteAction$1.compute(actions.kt:78)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$15(ApplicationImpl.java:945)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:924)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:945)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl$modifyProjects$1$1.invoke(CargoProjectImpl.kt:642)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl$modifyProjects$1$1.invoke(CargoProjectImpl.kt:316)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded(actions.kt:29)
	at com.intellij.openapi.application.ActionsKt.invokeAndWaitIfNeeded$default(actions.kt:26)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl.modifyProjects$lambda-8(CargoProjectImpl.kt:316)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl.modifyProjects(CargoProjectImpl.kt:315)
	at org.rust.cargo.project.model.impl.CargoProjectsServiceImpl.refreshAllProjects(CargoProjectImpl.kt:201)
	at org.rust.ide.security.RsTrustChangeNotifier.projectTrusted(RsTrustChangeNotifier.kt:19)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy209.projectTrusted(Unknown Source)
	at com.intellij.ide.impl.TrustedProjects.setTrusted(TrustedProjects.kt:125)
	at org.rust.ide.notifications.RsUntrustedNotificationProvider$createNotificationPanel$1.invoke(RsUntrustedNotificationProvider.kt:35)
	at org.rust.ide.notifications.RsUntrustedNotificationProvider$createNotificationPanel$1.invoke(RsUntrustedNotificationProvider.kt:34)
	at com.intellij.ide.impl.UntrustedProjectEditorNotificationPanel$1.run(UntrustedProjectEditorNotificationPanel.kt:17)
	at com.intellij.ui.EditorNotificationPanel$2.handlePanelActionClick(EditorNotificationPanel.java:276)
	at com.intellij.ui.EditorNotificationPanel$ActionHyperlinkLabel$1.hyperlinkActivated(EditorNotificationPanel.java:322)
	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:11)
	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:240)
	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:162)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:816)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:494)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>
