### ISSUE TITLE
Can't attach Cargo project to a workspace with WSL

### ISSUE THREAD

**Issue by toml01** [intellij-rust/intellij-rust#7641]
## Environment

* **IntelliJ Rust plugin version:** 0.4.152.4026-212
* **Rust toolchain version:** null
* **IDE name and version:** CLion 2021.2 (CL-212.4746.93)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
I'm trying to use Rust on CLion with the WSL experimental feature.
Attaching a Cargo project fails, thus all of the analyzing features and auto complete are not working.
When I'm switching to the Rust toolchain on windows, everything works.

Notice the `null` I got above for `Rust toolchain **version**`. On the GUI all looks fine:
![image](https://user-images.githubusercontent.com/7473870/128632932-173d2d4b-7377-4662-8e27-5ad8f7950cb4.png)

Logs:
```
2021-08-08 15:54:45,845 [  11530]  ERROR - intellij.openapi.progress.Task - \\wsl$\Ubuntu-20.04\mnt\c\Users\lange\Dev\project-name 
java.nio.file.AccessDeniedException: \\wsl$\Ubuntu-20.04\mnt\c\Users\lange\Dev\project-name
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.isSameFile(WindowsFileSystemProvider.java:445)
	at java.base/java.nio.file.Files.isSameFile(Files.java:1531)
	at org.rust.cargo.toolchain.tools.Cargo.replacePathsSymlinkIfNeeded(Cargo.kt:244)
	at org.rust.cargo.toolchain.tools.Cargo.fullProjectDescription(Cargo.kt:140)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchCargoWorkspace$1.invoke(CargoSyncTask.kt:316)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchCargoWorkspace$1.invoke(CargoSyncTask.kt:306)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:409)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$runWithChildProgress(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$SyncContext.runWithChildProgress(CargoSyncTask.kt:178)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.fetchCargoWorkspace(CargoSyncTask.kt:306)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$fetchCargoWorkspace(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:118)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:109)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:409)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress$default(CargoSyncTask.kt:400)
	at org.rust.cargo.project.model.impl.CargoSyncTask.doRun(CargoSyncTask.kt:106)
	at org.rust.cargo.project.model.impl.CargoSyncTask.run(CargoSyncTask.kt:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-08-08 15:54:45,845 [  11530]  ERROR - intellij.openapi.progress.Task - CLion 2021.2  Build #CL-212.4746.93 
2021-08-08 15:54:45,845 [  11530]  ERROR - intellij.openapi.progress.Task - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-08-08 15:54:45,845 [  11530]  ERROR - intellij.openapi.progress.Task - OS: Windows 10 
2021-08-08 15:54:45,846 [  11531]  ERROR - intellij.openapi.progress.Task - Plugin to blame: Rust version: 0.4.152.4026-212 
2021-08-08 15:54:45,846 [  11531]  ERROR - intellij.openapi.progress.Task - Last Action:  
```

## Steps to reproduce
Opening any Rust project and trying to sync/build/attach Cargo.toml, while using WSL toolchain

**Comment by mchernyavsky** [comment]
@toml01 Does your Windows support `\\wsl$\` paths? It requires version 1903.
