### ISSUE TITLE
PluginException: org.rust.grazie.RsGrammarCheckingStrategy@48ae7e6b produced invalid stealthy ranges

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#7680]
## Environment

* **IntelliJ Rust plugin version:** 0.4.154.4050-212-nightly
* **Rust toolchain version:** 1.56.0-nightly (492723897 2021-07-29) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.3 EAP (CL-213.2388)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

```stacktrace
com.intellij.diagnostic.PluginException: org.rust.grazie.RsGrammarCheckingStrategy@48ae7e6b produced invalid stealthy ranges [0..0, 4..3] in a text of length 4 [Plugin: org.rust.lang]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:268)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:91)
	at com.intellij.diagnostic.PluginException.logPluginError(PluginException.java:108)
	at com.intellij.grazie.text.StrategyTextExtractor.buildTextContent(StrategyTextExtractor.kt:59)
	at com.intellij.grazie.text.StrategyTextExtractor.extractText(StrategyTextExtractor.kt:19)
	at com.intellij.grazie.text.TextExtractor.doExtract(TextExtractor.java:158)
	at com.intellij.grazie.text.TextExtractor.findTextAt(TextExtractor.java:82)
	at com.intellij.grazie.text.TextExtractor.findUniqueTextAt(TextExtractor.java:136)
	at com.intellij.grazie.ide.inspection.detection.LanguageDetectionInspection$buildVisitor$1.visitElement(LanguageDetectionInspection.kt:49)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.accept(LeafPsiElement.java:208)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$processInOrder$8(LocalInspectionsPass.java:398)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1074)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$processInOrder$9(LocalInspectionsPass.java:377)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$processInOrder$10(LocalInspectionsPass.java:376)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$processInOrder$11(LocalInspectionsPass.java:374)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$processInOrder$12(LocalInspectionsPass.java:374)
	at com.intellij.concurrency.JobLauncherImpl$1MyTask.lambda$call$0(JobLauncherImpl.java:295)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:631)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:653)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:630)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.JobLauncherImpl$1MyTask.call(JobLauncherImpl.java:282)
	at com.intellij.concurrency.JobLauncherImpl$1MyTask.call(JobLauncherImpl.java:272)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

## Steps to reproduce

- Make sure **Settings | Editor | Natural Languages | Grammar** is enabled for Rust including "String literals"
- Copy-paste the following code in some Rust file

```rust
#[derive(Debug)]
enum Event {
    Update,
    Delete,
    Unknown,
}

type Message = String;

fn parse_log(line: &str) -> (Event, Message) {
    let parts: Vec<_> = line.splitn(2, "").collect();
    if parts.len() == 1 {
        return (Event::Unknown, String::from(line))
    }

    let event = parts[0];
    let rest = String::from(parts[1]);

    match event {
        "UPDATE" | "update" => (Event::Update, rest),
        "DELETE" | "delete" => (Event::Delete, rest),
        _ => (Event::Unknown, String::from(line)),
    }
}

fn main() {
    let log = "BEGIN Transaction XK324"

    
}
```

- Type `";"` on the last line of the `main`
- Remove last `"` typed
- Exception should be raised at this point

https://user-images.githubusercontent.com/2500320/129455832-a5b39c3d-9b27-47ec-8fff-53ceb67c5c1c.mov

**Comment by Undin** [comment]
Fixed by #10671
