### ISSUE TITLE
Converting from function to closure eats comments

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#7741]
## Environment

* **IntelliJ Rust plugin version:** 0.4.155.4071-212-nightly
* **Rust toolchain version:** 1.53.0 (53cb7b09b 2021-06-17) x86_64-apple-darwin
* **IDE name and version:** CLion 2021.2 (CL-212.4746.93)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
Сomments above the function disappear: 

https://user-images.githubusercontent.com/49211026/130996505-5b45467f-0198-4006-aa36-4da05b6ba56c.mov

Converting from closure to function works normally.

## Steps to reproduce
```rust
fn main() {
    //fn foo(x: i32) -> i32 { x + 1 }
    //fn foo(x: i32) -> i32 { x + 1 }
    let a = 7;
    //comment 1
    //comment 2
    
    ///comment 3
    //comment 4
    fn foo(x: i32) -> i32 { x + 1 } //convert from function to closure 
}
```

**Comment by Kobzol** [comment]
@nschoellhorn Do you want to try fixing this bug?

**Comment by nschoellhorn** [comment]
@Kobzol Sure, thanks for letting me know! I'll try to prepare a failing test + fix this evening.

**Comment by nschoellhorn** [comment]
@Kobzol I'm not quite done with this, but I'm getting there. It feels weird that the comments that are outside of the function are parsed as children of the `RsFunction`. This is why the comments were lost when I replaced the `RsFunction` element. My idea was to do something like getting all comments that belong to the function via `ctx.targetFunction.childrenOfType<PsiComment>()` and then re-insert them above the generated lambda via `addBefore()`.

This seems to work for doc comments, but it inserts additional whitespace:
![grafik](https://user-images.githubusercontent.com/3925180/133328746-eabae100-ee65-4696-b1a8-b50b94f3cd0f.png)

For normal line comments it gets even worse, it throws an exception that I can't get behind:
<details>
<summary>invalidated at: see attachment; com.intellij.psi.impl.source.tree.PsiCommentImpl:<EOL_COMMENT></summary>
<pre><code>Element: class com.intellij.psi.impl.source.tree.PsiCommentImpl #Rust  because: different providers: com.intellij.psi.DummyHolderViewProvider{vFile=LightVirtualFile: \DummyHolder, content=VirtualFileContent{size=0}, eventSystemEnabled=false}(1073f4f3); com.intellij.psi.SingleRootFileViewProvider{vFile=LightVirtualFile: \DummyHolder, content=VirtualFileContent{size=0}, eventSystemEnabled=true}(6830f0e7)
invalidated at: see attachment; com.intellij.psi.impl.source.tree.PsiCommentImpl:<EOL_COMMENT> / com.intellij.psi.impl.source.tree.CompositeElement:FUNCTION / com.intellij.psi.impl.source.tree.FileElement:DUMMY_HOLDER
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.PsiCommentImpl #Rust  because: different providers: com.intellij.psi.DummyHolderViewProvider{vFile=LightVirtualFile: \DummyHolder, content=VirtualFileContent{size=0}, eventSystemEnabled=false}(1073f4f3); com.intellij.psi.SingleRootFileViewProvider{vFile=LightVirtualFile: \DummyHolder, content=VirtualFileContent{size=0}, eventSystemEnabled=true}(6830f0e7)
invalidated at: see attachment; com.intellij.psi.impl.source.tree.PsiCommentImpl:<EOL_COMMENT> / com.intellij.psi.impl.source.tree.CompositeElement:FUNCTION / com.intellij.psi.impl.source.tree.FileElement:DUMMY_HOLDER
	at com.intellij.psi.impl.source.tree.LeafPsiElement.invalid(LeafPsiElement.java:102)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.getContainingFile(LeafPsiElement.java:86)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.saveWhitespacesInfo(CodeEditUtil.java:107)
	at com.intellij.psi.impl.source.tree.ChangeUtil.saveIndentationToCopy(ChangeUtil.java:104)
	at com.intellij.psi.impl.source.tree.ChangeUtil.copyElement(ChangeUtil.java:97)
	at com.intellij.psi.impl.source.tree.ChangeUtil.copyElement(ChangeUtil.java:87)
	at com.intellij.psi.impl.source.tree.TreeElement.copyElement(TreeElement.java:58)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.copy(LeafPsiElement.java:117)
	at org.rust.ide.intentions.ConvertFunctionToClosureIntention.invoke(ConvertFunctionToClosureIntention.kt:55)
	at org.rust.ide.intentions.ConvertFunctionToClosureIntention.invoke(ConvertFunctionToClosureIntention.kt:19)
	at org.rust.ide.intentions.RsElementBaseIntentionAction.invoke(RsElementBaseIntentionAction.kt:49)
	at com.intellij.codeInsight.intention.BaseElementAtCaretIntentionAction.invoke(BaseElementAtCaretIntentionAction.java:76)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.invoke(IntentionActionWrapper.java:66)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$4(ShowIntentionActionsHandler.java:263)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:94)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:924)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:950)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:93)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:263)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$3(ShowIntentionActionsHandler.java:239)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:238)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:222)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$invokeIntention$54(CodeInsightTestFixtureImpl.java:1998)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at com.intellij.util.ui.EdtInvocationManager.dispatchAllInvocationEvents(EdtInvocationManager.java:65)
	at com.intellij.util.ui.UIUtil.dispatchAllInvocationEvents(UIUtil.java:1686)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$invokeIntention$55(CodeInsightTestFixtureImpl.java:2004)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.withReadOnlyFile(CodeInsightTestFixtureImpl.java:2025)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.invokeIntention(CodeInsightTestFixtureImpl.java:1994)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$launchAction$14(CodeInsightTestFixtureImpl.java:708)
	at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.java:33)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.launchAction(CodeInsightTestFixtureImpl.java:708)
	at org.rust.ide.intentions.RsIntentionTestBase.launchAction(RsIntentionTestBase.kt:88)
	at org.rust.ide.intentions.RsIntentionTestBase.doAvailableTest(RsIntentionTestBase.kt:48)
	at org.rust.ide.intentions.RsIntentionTestBase.doAvailableTest$default(RsIntentionTestBase.kt:42)
	at org.rust.ide.intentions.ConvertFunctionToClosureIntentionTest.test keeps line comments(ConvertFunctionToClosureIntentionTest.kt:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at com.intellij.testFramework.UsefulTestCase.lambda$runBare$11(UsefulTestCase.java:533)
	at com.intellij.testFramework.UsefulTestCase.lambda$wrapTestRunnable$13(UsefulTestCase.java:553)
	at com.intellij.testFramework.UsefulTestCase.runTestRunnable(UsefulTestCase.java:465)
	at com.intellij.testFramework.fixtures.BasePlatformTestCase.runTestRunnable(BasePlatformTestCase.java:106)
	at org.rust.RsTestBase.runTestRunnable(RsTestBase.kt:217)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:481)
	at com.intellij.testFramework.UsefulTestCase.lambda$runBare$12(UsefulTestCase.java:541)
	at com.intellij.testFramework.EdtTestUtil.lambda$runInEdtAndWait$1(EdtTestUtil.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:451)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</code></pre>
</details>

My code currently looks like this: https://github.com/nschoellhorn/intellij-rust/commit/c889745f030acf468f4ada5472d6cf6ab5356ef7

Do you have any tips to point me in the right direction? I am not really sure what is failing here. The most interesting thing is that it works totally fine for block comments, since those are not parsed as children of the `RsFunction` but instead are just separate elements that are before the actual function. Is this intentional or does that point to a parser issue here?

**Comment by Kobzol** [comment]
When you replace the function, you invalidate the previously collected comments. So you should copy them before you replace the function, not after. However, I noticed that copying whitespace (which is probably needed to avoid removing/adding spaces) does not work.

I tried something like this:
```kotlin
val functionComments = ctx.targetFunction.childrenWithLeaves.filter {
    (it is PsiComment || it is PsiWhiteSpace) && it.startOffset <= ctx.targetFunction.fn.startOffset
}

val lambda = factory.createLambda("|$parametersText| $returnText $bodyText")
val declaration = factory.createLetDeclaration(ctx.targetFunction.identifier.text, lambda)

val replaced = ctx.targetFunction.parent.addAfter(declaration, ctx.targetFunction) as RsLetDecl
functionComments.forEach { comment ->
    replaced.parent.addBefore(comment, replaced)
}
replaced.semicolon?.endOffset?.let {
    editor.caretModel.moveToOffset(it)
}
ctx.targetFunction.delete()
```
but there's still some problem with the whitespace.

**Comment by Kobzol** [comment]
It seems to work when it's treated as text instead:
```kotlin
val text = ctx.targetFunction.childrenWithLeaves.filter {
    (it is PsiComment || it is PsiWhiteSpace) && it.startOffset <= ctx.targetFunction.fn.startOffset
}.map { it.text }.joinToString(separator = "")

val lambda = factory.createLambda("|$parametersText| $returnText $bodyText")
val declaration = factory.createLetDeclaration(ctx.targetFunction.identifier.text, lambda)

val replaced = ctx.targetFunction.replace(declaration) as RsLetDecl
replaced.semicolon?.endOffset?.let {
    editor.caretModel.moveToOffset(it)
}
PsiDocumentManager.getInstance(project).doPostponedOperationsAndUnblockDocument(editor.document)
editor.document.insertString(replaced.startOffset, text)
```
Not sure if that's acceptable here though. CC @vlad20012

**Comment by nschoellhorn** [comment]
Interesting. I fixed the copy and I tried if it works when we manually call the formatter on the replaced part, but it still messes up the indentation of the follow-up comment. I don't really understand why it works when inserting text only. Now all tests are green except for the line comment test.
