### ISSUE TITLE
AWT thread freezes when performing editing

### ISSUE THREAD

**Issue by xxDark** [intellij-rust/intellij-rust#7830]
## Environment

* **IntelliJ Rust plugin version:** 0.4.154.4085-212
* **Rust toolchain version:** 1.55.0
* **IDE name and version:** IntelliJ IDEA 2021.2
* **Operating system:** Windows 10, x64

## Problem description
Performing an edit provided by IDEA's hint causing whole IDE to hang.
AWT thread dump:
```Java
"AWT-EventQueue-0" #26 prio=6 os_prio=0 cpu=813312.50ms elapsed=5733.67s tid=0x0000000049db1000 nid=0x2498 runnable  [0x000000004db59000]
   java.lang.Thread.State: RUNNABLE
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.11/AbstractQueuedSynchronizer.java:1239)
        at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.11/ReentrantLock.java:267)
        at java.util.concurrent.DelayQueue.remove(java.base@11.0.11/DelayQueue.java:465)
        at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.cancel(SchedulingWrapper.java:158)
        at com.intellij.util.Alarm$Request.cancel(Alarm.java:421)
        at com.intellij.util.Alarm.cancelAllRequests(Alarm.java:274)
        at com.intellij.util.Alarm.cancelAllRequests(Alarm.java:267)
        - locked <0x0000000507f30488> (a java.lang.Object)
        at com.intellij.util.ui.update.MergingUpdateQueue.clearWaiter(MergingUpdateQueue.java:422)
        at com.intellij.util.ui.update.MergingUpdateQueue.restart(MergingUpdateQueue.java:229)
        at com.intellij.util.ui.update.MergingUpdateQueue.restartTimer(MergingUpdateQueue.java:223)
        at com.intellij.util.ui.update.MergingUpdateQueue.queue(MergingUpdateQueue.java:361)
        - locked <0x0000000507f30258> (a it.unimi.dsi.fastutil.ints.Int2ObjectRBTreeMap)
        at com.intellij.xml.breadcrumbs.BreadcrumbsPanel.queueUpdate(BreadcrumbsPanel.java:212)
        at com.intellij.xml.breadcrumbs.BreadcrumbsPanel.lambda$findCollectorFor$6(BreadcrumbsPanel.java:335)
        at com.intellij.xml.breadcrumbs.BreadcrumbsPanel$$Lambda$2495/0x00000008018f6040.run(Unknown Source)
        at com.intellij.xml.breadcrumbs.PsiFileBreadcrumbsCollector$1.modelChanged(PsiFileBreadcrumbsCollector.java:74)
        at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$1(PomModelImpl.java:137)
        at com.intellij.pom.core.impl.PomModelImpl$$Lambda$3893/0x000000080265e840.run(Unknown Source)
        at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
        at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:104)
        at com.intellij.pom.core.impl.PomModelImpl$$Lambda$3890/0x000000080265dc40.run(Unknown Source)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
        at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:93)
        at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:142)
        at com.intellij.psi.impl.source.tree.CompositeElement.removeChildrenInner(CompositeElement.java:833)
        at com.intellij.psi.impl.source.tree.CompositeElement.removeRange(CompositeElement.java:611)
        at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.removeChildren(CodeEditUtil.java:132)
        at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.removeChild(CodeEditUtil.java:35)
        at com.intellij.psi.impl.source.tree.CompositeElement.deleteChildInternal(CompositeElement.java:451)
        at com.intellij.psi.impl.source.tree.LeafPsiElement.delete(LeafPsiElement.java:182)
        at org.rust.lang.core.psi.ext.RsElementKt.deleteWithSurroundingCommaAndWhitespace(RsElement.kt:186)
        at org.rust.ide.annotator.fixes.RemoveRedundantFunctionArgumentsFix.invoke(RemoveRedundantFunctionArgumentsFix.kt:32)
        at com.intellij.codeInspection.LocalQuickFixAndIntentionActionOnPsiElement.invoke(LocalQuickFixAndIntentionActionOnPsiElement.java:42)
        at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$4(ShowIntentionActionsHandler.java:263)
        at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler$$Lambda$6083/0x0000000803314040.run(Unknown Source)
        at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:94)
        at com.intellij.openapi.application.WriteAction$$Lambda$2262/0x0000000801733040.compute(Unknown Source)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:924)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:950)
        at com.intellij.openapi.application.WriteAction.run(WriteAction.java:93)
        at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:263)
        at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$3(ShowIntentionActionsHandler.java:239)
        at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler$$Lambda$6082/0x0000000803314c40.run(Unknown Source)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
        at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:238)
        at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:222)
        at com.intellij.codeInsight.daemon.impl.DaemonTooltipAction.execute(DaemonTooltipActionProvider.kt:54)
        at com.intellij.codeInsight.daemon.impl.DaemonTooltipWithActionRenderer$addActionsRow$runFixAction$1.invoke(DaemonTooltipWithActionRenderer.kt:148)
        at com.intellij.codeInsight.daemon.impl.DaemonTooltipWithActionRenderer$addActionsRow$runFixAction$1.invoke(DaemonTooltipWithActionRenderer.kt:50)
        at com.intellij.codeInsight.daemon.impl.DaemonTooltipWithActionRendererKt$createActionLabel$1.hyperlinkActivated(DaemonTooltipWithActionRenderer.kt:372)
        at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:11)
        at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:240)
        at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:162)
        at java.awt.Component.processEvent(java.desktop@11.0.11/Component.java:6417)
        at java.awt.Container.processEvent(java.desktop@11.0.11/Container.java:2263)
        at java.awt.Component.dispatchEventImpl(java.desktop@11.0.11/Component.java:5027)
        at java.awt.Container.dispatchEventImpl(java.desktop@11.0.11/Container.java:2321)
        at java.awt.Component.dispatchEvent(java.desktop@11.0.11/Component.java:4859)
        at java.awt.LightweightDispatcher.retargetMouseEvent(java.desktop@11.0.11/Container.java:4918)
        at java.awt.LightweightDispatcher.processMouseEvent(java.desktop@11.0.11/Container.java:4547)
        at java.awt.LightweightDispatcher.dispatchEvent(java.desktop@11.0.11/Container.java:4488)
        at java.awt.Container.dispatchEventImpl(java.desktop@11.0.11/Container.java:2307)
        at java.awt.Window.dispatchEventImpl(java.desktop@11.0.11/Window.java:2784)
        at java.awt.Component.dispatchEvent(java.desktop@11.0.11/Component.java:4859)
        at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.11/EventQueue.java:778)
        at java.awt.EventQueue$4.run(java.desktop@11.0.11/EventQueue.java:727)
        at java.awt.EventQueue$4.run(java.desktop@11.0.11/EventQueue.java:721)
        at java.security.AccessController.doPrivileged(java.base@11.0.11/Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.11/ProtectionDomain.java:85)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.11/ProtectionDomain.java:95)
        at java.awt.EventQueue$5.run(java.desktop@11.0.11/EventQueue.java:751)
        at java.awt.EventQueue$5.run(java.desktop@11.0.11/EventQueue.java:749)
        at java.security.AccessController.doPrivileged(java.base@11.0.11/Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.11/ProtectionDomain.java:85)
        at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.11/EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:815)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:752)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
        at com.intellij.ide.IdeEventQueue$$Lambda$404/0x00000008005bcc40.compute(Unknown Source)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
        at com.intellij.ide.IdeEventQueue$$Lambda$399/0x00000008005bec40.run(Unknown Source)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.11/EventDispatchThread.java:203)
        at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.11/EventDispatchThread.java:124)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.11/EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.11/EventDispatchThread.java:109)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.11/EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.run(java.desktop@11.0.11/EventDispatchThread.java:90)
```

## Steps to reproduce
```Rust
foo(Some(&'static o))
```
IDE will suggest to remove the lifetime and freeze.

**Comment by Kobzol** [comment]
@xxDark Thanks for the MCVE! The code contains a syntax error, which interacts badly with code for deleting the extra argument and it results in an infinite loop inside the IDE. I created a [PR](https://github.com/intellij-rust/intellij-rust/pull/7841) that should fix this.
