### ISSUE TITLE
IDE internal error

### ISSUE THREAD

**Issue by alexbool** [intellij-rust/intellij-rust#790]
Plugin version: 0.1.0.1194-nightly

```
null
java.lang.NullPointerException
	at org.rust.lang.core.psi.visitors.RustComputingVisitor.compute(RustComputingVisitor.kt:30)
	at org.rust.lang.core.resolve.RustResolveEngineKt$declarations$$inlined$Sequence$1.iterator(Sequences.kt:591)
	at kotlin.sequences.SequencesKt___SequencesKt$flatMap$1.invoke(_Sequences.kt:594)
	at kotlin.sequences.SequencesKt___SequencesKt$flatMap$1.invoke(_Sequences.kt)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:241)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:229)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:141)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:97)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:141)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:97)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:536)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:560)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:553)
	at org.rust.lang.core.completion.RustCompletionEngineKt.completionsFromScopeEntries(RustCompletionEngine.kt:62)
	at org.rust.lang.core.completion.RustCompletionEngineKt.access$completionsFromScopeEntries(RustCompletionEngine.kt:1)
	at org.rust.lang.core.completion.RustCompletionEngine.completePath(RustCompletionEngine.kt:28)
	at org.rust.lang.core.resolve.ref.RustPathReferenceImpl.getVariants(RustPathReferenceImpl.kt:35)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:292)
	at com.intellij.codeInsight.completion.CompletionVariant.addReferenceCompletions(CompletionVariant.java:164)
	at com.intellij.codeInsight.completion.CompletionData.completeReference(CompletionData.java:97)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.lambda$completeReference$0(LegacyCompletionContributor.java:71)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReference(LegacyCompletionContributor.java:125)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:108)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:69)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:52)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:773)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:91)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:755)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:877)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

As for now I cannot help you with reproduction steps, but will post it if I understand.

**Comment by matklad** [comment]
That does seem strange, Kotlin usually produces Kotlin-flavored NPE if there are `!!` or platform types...

**Comment by matklad** [comment]
Closing this: this particular part of the plugin was changed drastically, so it's unlikely that the stack trace is still relevant.
