### ISSUE TITLE
stdlib is not added to a project dependencies if rust toolchain installed to read-only location (e.g. Nix store)

### ISSUE THREAD

**Issue by zaytsev** [intellij-rust/intellij-rust#7912]
## Environment

* **IntelliJ Rust plugin version:** 0.4.156.4145-212
* **Rust toolchain version:** 1.55.0
* **IDE name and version:**  IntelliJ IDEA 2021.2.1  Build #IU-212.5080.55
* **Operating system:** Linux 5.10.68 NixOS SMP x86_64 GNU/Linux

## Problem description

1. No 'stdlib' entry in External Libraries
2. Code completion doesn't work for `std` namespace
3. Go-To Type Definition doesn't work for types from `std` namespace 

```
com.intellij.execution.ExecutionException: Execution failed (exit code 101).
/nix/store/q4pprd3l90ssvcz0hky3k59rqk5pmsma-rust-default-1.55.0/bin/cargo metadata --verbose --format-version 1 --all-features
stdout :     Updating crates.io index
error: failed to write /nix/store/q4pprd3l90ssvcz0hky3k59rqk5pmsma-rust-default-1.55.0/lib/rustlib/src/rust/library/std/Cargo.lock

Caused by:
  failed to open: /nix/store/q4pprd3l90ssvcz0hky3k59rqk5pmsma-rust-default-1.55.0/lib/rustlib/src/rust/library/std/Cargo.lock

Caused by:
  Read-only file system (os error 30)

stderr : 
	at org.rust.openapiext.CommandLineExtKt.execute(CommandLineExt.kt:109)
	at org.rust.openapiext.CommandLineExtKt.execute$default(CommandLineExt.kt:56)
	at org.rust.cargo.toolchain.tools.Cargo.execute(Cargo.kt:418)
	at org.rust.cargo.toolchain.tools.Cargo.execute$default(Cargo.kt:412)
	at org.rust.cargo.toolchain.tools.Cargo.fetchMetadata(Cargo.kt:152)
	at org.rust.cargo.project.workspace.StdlibDataFetcher.collectPackageMetadata(StandardLibrary.kt:297)
	at org.rust.cargo.project.workspace.StdlibDataFetcher.fetchStdlibData(StandardLibrary.kt:210)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib(StandardLibrary.kt:114)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib$default(StandardLibrary.kt:106)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromFile(StandardLibrary.kt:83)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromPath(StandardLibrary.kt:59)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromPath$default(StandardLibrary.kt:52)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:364)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:344)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:400)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$runWithChildProgress(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$SyncContext.runWithChildProgress(CargoSyncTask.kt:178)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.fetchStdlib(CargoSyncTask.kt:344)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$fetchStdlib(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:120)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:108)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:400)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress$default(CargoSyncTask.kt:391)
	at org.rust.cargo.project.model.impl.CargoSyncTask.doRun(CargoSyncTask.kt:105)
	at org.rust.cargo.project.model.impl.CargoSyncTask.run(CargoSyncTask.kt:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-09-29 15:53:34,327 [1214268]  ERROR - ct.workspace.StdlibDataFetcher - IntelliJ IDEA 2021.2.1  Build #IU-212.5080.55 
2021-09-29 15:53:34,327 [1214268]  ERROR - ct.workspace.StdlibDataFetcher - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: Oracle Corporation 
2021-09-29 15:53:34,327 [1214268]  ERROR - ct.workspace.StdlibDataFetcher - OS: Linux 
2021-09-29 15:53:34,327 [1214268]  ERROR - ct.workspace.StdlibDataFetcher - Plugin to blame: Rust version: 0.4.156.4145-212 
2021-09-29 15:53:34,666 [1214607]  ERROR - ct.workspace.StdlibDataFetcher - Execution failed (exit code 101).
```

## Steps to reproduce

requires latest [Nix](https://nixos.org/manual/nix/stable/#chap-quick-start) with [flakes](https://nixos.wiki/wiki/Flakes#Installing_flakes) support enabled

```
git clone https://github.com/zaytsev/idea-rust-nix.git
cd idea-rust-nix
nix develop
idea-ultimate .
```

**Comment by im-0** [comment]
Same happens on Fedora 35 with IDEA installed from official tar.gz and rust (including stdlib source code) installed from Fedora's repositories.

```
2021-10-21 23:16:07,404 [  13283]  ERROR - ct.workspace.StdlibDataFetcher - Execution failed (exit code 101).
/usr/bin/cargo metadata --verbose --format-version 1 --all-features
stdout :     Updating crates.io index
error: failed to write /usr/lib/rustlib/src/rust/library/panic_unwind/Cargo.lock

Caused by:
  failed to open: /usr/lib/rustlib/src/rust/library/panic_unwind/Cargo.lock

Caused by:
  Permission denied (os error 13)

stderr :  
com.intellij.execution.ExecutionException: Execution failed (exit code 101).
/usr/bin/cargo metadata --verbose --format-version 1 --all-features
stdout :     Updating crates.io index
error: failed to write /usr/lib/rustlib/src/rust/library/panic_unwind/Cargo.lock

Caused by:
  failed to open: /usr/lib/rustlib/src/rust/library/panic_unwind/Cargo.lock

Caused by:
  Permission denied (os error 13)

stderr : 
	at org.rust.openapiext.CommandLineExtKt.execute(CommandLineExt.kt:109)
	at org.rust.openapiext.CommandLineExtKt.execute$default(CommandLineExt.kt:56)
	at org.rust.cargo.toolchain.tools.Cargo.execute(Cargo.kt:428)
	at org.rust.cargo.toolchain.tools.Cargo.execute$default(Cargo.kt:422)
	at org.rust.cargo.toolchain.tools.Cargo.fetchMetadata(Cargo.kt:161)
	at org.rust.cargo.project.workspace.StdlibDataFetcher.collectPackageMetadata(StandardLibrary.kt:297)
	at org.rust.cargo.project.workspace.StdlibDataFetcher.fetchStdlibData(StandardLibrary.kt:210)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib(StandardLibrary.kt:114)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib$default(StandardLibrary.kt:106)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromFile(StandardLibrary.kt:83)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromPath(StandardLibrary.kt:59)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromPath$default(StandardLibrary.kt:52)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:390)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:370)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:426)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$runWithChildProgress(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$SyncContext.runWithChildProgress(CargoSyncTask.kt:184)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.fetchStdlib(CargoSyncTask.kt:370)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$fetchStdlib(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:122)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:110)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:426)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress$default(CargoSyncTask.kt:417)
	at org.rust.cargo.project.model.impl.CargoSyncTask.doRun(CargoSyncTask.kt:107)
	at org.rust.cargo.project.model.impl.CargoSyncTask.run(CargoSyncTask.kt:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-10-21 23:16:07,405 [  13284]  ERROR - ct.workspace.StdlibDataFetcher - IntelliJ IDEA 2021.2.3  Build #IC-212.5457.46 
2021-10-21 23:16:07,407 [  13286]  ERROR - ct.workspace.StdlibDataFetcher - JDK: 11.0.12; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-10-21 23:16:07,407 [  13286]  ERROR - ct.workspace.StdlibDataFetcher - OS: Linux 
2021-10-21 23:16:07,407 [  13286]  ERROR - ct.workspace.StdlibDataFetcher - Plugin to blame: Rust version: 0.4.157.4174-212 
2021-10-21 23:16:07,407 [  13286]  ERROR - ct.workspace.StdlibDataFetcher - Last Action:  
2021-10-21 23:16:07,760 [  13639]  ERROR - ct.workspace.StdlibDataFetcher - Execution failed (exit code 101).
```

**Comment by 2xsaiko** [comment]
Getting the same with the Gentoo rust package (sources installed to /usr/lib/rustlib/src/rust as in the comment above). Weirdly, it was working before I added another project to my workspace...

**Comment by mhthies** [comment]
The underlying problem seems to be https://github.com/rust-lang/cargo/issues/10096

**Comment by jvdsn** [comment]
Also the case for Arch Linux with the `rust` and `rust-src` package, sources installed in `/usr/lib/rustlib/src/rust/library/`.

**Comment by JB-Dmitry** [comment]
Same problem on Slackware 15.0, where Rust (and its standard library) comes as part of full OS installation.
Looks like it can be workarounded, at least to a certain extent, by disabling `org.rust.cargo.fetch.actual.stdlib.metadata` experimental feature (mentioned in https://github.com/intellij-rust/intellij-rust/pull/7782).

**Comment by tribunsky-kir** [comment]
One more Gentoo here! 

I've just copied stdlib and make it writeable as dirty workaround. Works fine, but after the next rust version bump in distro I will be forced to repeat. 

I can imagine two possible solutions for this problem:

1. the plugin could do the same thing by itself, just copying system's stdlib in some local temporary place and creating it's index. I'm pretty new to rust, are there any hidden problems with this?
2. is it possibly to build shareable index once and for all? this should help much, especially since shareable indexes are available for python packages in other Jetbrains IDE.

Are any of these approaches viable?

Also it looks like there some duplicates of the same problem here https://github.com/intellij-rust/intellij-rust/issues/5363 and https://github.com/intellij-rust/intellij-rust/issues/8213

**Comment by stevenxxiu** [comment]
Copying sources seem like a waste of space, so doesn't seem ideal.

**Comment by powerboat9** [comment]
I've written the following patch for Gentoo

```
--- a/src/tools/cargo/src/cargo/ops/lockfile.rs
+++ b/src/tools/cargo/src/cargo/ops/lockfile.rs
@@ -36,6 +36,11 @@ pub fn resolve_to_string(ws: &Workspace<'_>, resolve: &mut Resolve) -> CargoResu
 }
 
 pub fn write_pkg_lockfile(ws: &Workspace<'_>, resolve: &mut Resolve) -> CargoResult<()> {
+    // prevent lock file write failures
+    if ws.root_manifest().starts_with("/usr/lib/rust/") {
+        return Ok(())
+    }
+
     let (orig, mut out, ws_root) = resolve_to_string_orig(ws, resolve);
 
     // If the lock file contents haven't changed so don't rewrite it. This is
```

While it's a bit of a hack, it works

**Comment by dulatello08** [comment]
Any updates on this issue?

**Comment by maxammann** [comment]
Experiencing the same issue I beleive. I can see the following: 


```
nix/store/52mq23zilq1jj9fq5ngd4r2pdj1c176b-rust-default-1.76.0/bin/cargo vendor --respect-source-config /home/max/.cache/JetBrains/RustRover2024.1/intellij-rust/stdlib/1.76.0-0adf3adfad6aa9b2c71d14d41e792aff5fdfc317/vendor
stdout :     Updating crates.io index
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  failed to write /nix/store/52mq23zilq1jj9fq5ngd4r2pdj1c176b-rust-default-1.76.0/lib/rustlib/src/rust/library/test/Cargo.lock

Caused by:
  failed to open: /nix/store/52mq23zilq1jj9fq5ngd4r2pdj1c176b-rust-default-1.76.0/lib/rustlib/src/rust/library/test/Cargo.lock

Caused by:
  Read-only file system (os error 30)
``

**Comment by maxammann** [comment]
> org.rust.cargo.fetch.actual.stdlib.metadata

After disabling this feature I can still see the "Cargo failed" when refreshing my project.

I think the reason is:

> 2024-07-22 15:44:51,969 [ 464397]   WARN - #org.rust.cargo.project.workspace.StandardLibrary - Failed to fetch up-to-date stdlib info. The hardcoded stdlib structure will be used instead.

**Comment by maxammann** [comment]
related:
* https://youtrack.jetbrains.com/issue/RUST-7912/stdlib-is-not-added-to-a-project-dependencies-if-rust-toolchain-installed-to-read-only-location-e.g.-Nix-store
* https://youtrack.jetbrains.com/issue/RUST-14477

**Comment by maxammann** [comment]
there seems to be movement now with this feature: https://github.com/rust-lang/cargo/issues/5707

**Comment by powerboat9** [comment]
Up-to-date patch, if anyone wants it. Could probably be reworked for nix
```
--- a/src/tools/cargo/src/cargo/ops/lockfile.rs
+++ b/src/tools/cargo/src/cargo/ops/lockfile.rs
@@ -38,6 +38,11 @@
 /// Returns `true` if the lockfile changed
 #[tracing::instrument(skip_all)]
 pub fn write_pkg_lockfile(ws: &Workspace<'_>, resolve: &mut Resolve) -> CargoResult<bool> {
+    // prevent lock file write failures
+    if ws.root_manifest().starts_with("/usr/lib/rust/") {
+        return Ok(false)
+    }
+
     let (orig, mut out, lock_root) = resolve_to_string_orig(ws, resolve);
 
     // If the lock file contents haven't changed so don't rewrite it. This is
```

**Comment by ifropc** [comment]
I think `--lockfile-path` is more clean long-term solution, but would require changes on rust-rover side as well. I believe for now you can also just copy stdlib sources into a writable location for it to be indexed, as mentioned issues above

**Comment by dulatello08** [comment]
+1. I copied /usr/lib/rustlib/src/rust/library to my project's root and added it to .gitignore. Then, I set the standard library path in rustrover to this new location. Works perfectly on Arch Linux!
