### ISSUE TITLE
Cannot install "Native Debugging Support" plugin on 221 nightly PyCharm

### ISSUE THREAD

**Issue by lancelote** [intellij-rust/intellij-rust#8032]
## Environment

* **IntelliJ Rust plugin version:** 0.4.159.4210-213-nightly
* **Rust toolchain version:** 1.54.0 (a178d0322 2021-07-26) x86_64-unknown-linux-gnu
* **IDE name and version:** PyCharm 2022.1 EAP Professional Edition (PY-221.435)
* **Operating system:** Linux 5.11.0-38-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Attempt to install the plugin raises the following exception and doesn't succeed

```stacktrace
java.util.NoSuchElementException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1495)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
	at com.intellij.openapi.updateSettings.impl.pluginsAdvertisement.PluginsAdvertiserDialog.createCenterPanel(PluginsAdvertiserDialog.java:58)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1309)
	at com.intellij.openapi.updateSettings.impl.pluginsAdvertisement.PluginsAdvertiserDialog.<init>(PluginsAdvertiserDialog.java:45)
	at com.intellij.openapi.updateSettings.impl.pluginsAdvertisement.InstallAndEnableTask.onSuccess(InstallAndEnableTask.java:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:601)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.finishTask(ProgressManagerImpl.java:167)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:563)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:437)
	at com.intellij.openapi.application.ex.ApplicationUtil.invokeAndWaitSomewhere(ApplicationUtil.java:145)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:561)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:91)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:384)
	at com.intellij.openapi.updateSettings.impl.pluginsAdvertisement.PluginsAdvertiser.installAndEnable(PluginsAdvertiser.kt:66)
	at org.rust.debugger.runconfig.RsDebugAdvertisingRunner$Action$INSTALL.doOkAction(RsDebugAdvertisingRunner.kt:86)
	at org.rust.debugger.runconfig.RsDebugAdvertisingRunner.execute(RsDebugAdvertisingRunner.kt:61)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:737)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$executeConfiguration(ExecutionManagerImpl.kt:71)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$2.accept(ExecutionManagerImpl.kt:673)
	at com.intellij.execution.impl.ExecutionManagerImpl$executeConfiguration$2.accept(ExecutionManagerImpl.kt:71)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$6(NonBlockingReadActionImpl.java:577)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

## Steps to reproduce

1. Debug some script
2. Popup suggesting "Native Debugging Support" plugin installation appears
3. Agree to install it

**Comment by Undin** [comment]
It looks like a platform bug that's already fixed
@intellij-rust/qa could you verify it?

**Comment by neonaot** [comment]
For 
* **IntelliJ Rust plugin version:** 0.4.168.4555-221
* **Rust toolchain version:** 1.59.0 (9d1b2106e 2022-02-23) x86_64-unknown-linux-gnu
* **IDE name and version:** PyCharm 2022.1 Professional Edition (PY-221.5080.212)
* **Operating system:** Linux 4.19.0-17-amd64
Installation and debugging work fine
