### ISSUE TITLE
Using intellij-rust heavily, daily for 3 months. Finally got my first exception. 

### ISSUE THREAD

**Issue by nathanaeljones** [intellij-rust/intellij-rust#808]
I'm guessing my clumsy test code managed to expose an unexpected state in the language parser. It never reoccurred, and I have no need for resolution. I'm posting this in case it can help troubleshoot something already under investigation.  

Feel free to close immediately and use for reference later if a similar issue becomes more common. 

Using build `0.1.0.1196`
 

```{
                        let fname = format!("{)
                        let new_path = directory.join();
                        
                    }
                    s::IoEnum::Url(url) => {}
                    other => other
                }
            }else{
                match e{
                    s::IoEnum::Filename(path) => {

                    }
                    other => other
                }
            };
            s::IoObject{
                direction: obj.direction,
                io: new_enum,
                io_id: obj.io_id
            }
        })
    }

    // Write new invocation to STDOUT, for execution in 'directory'.
    // Will write recipe and dependencies into directory
    pub fn bundle_to(self, directory: &Path) -> i32{

    }

    pub fn build_maybe(self) -> CmdBuild {

        if self.job.is_ok() {

            let mut result = Err(CmdError::Incomplete);
            {
                if let Ok(ref b) = self.job {
                    result = CmdBuild::build(&b);
                }
            }
            CmdBuild { response: Some(result), ..self }
        } else {
            self
        }
    }

//    pub fn get_modified_recipe<'a>(&'a self) -> &'a Result<s::Build001>{
//        &self.job
//    }

    ///
    /// Write the JSON response (if present) to the given file or STDOUT
    pub fn write_response_maybe(&self, response_file: Option<&str>) -> std::io::Result<()> {
        if let Some(ref rr) = self.response {
            if let &Ok(ref r) = rr {
                if let Some(ref filename) = response_file {
                    let mut file = BufWriter::new(File::create(filename).unwrap());
                    file.write(&r.response_json)?;
                } else {
                    std::io::stdout().write(&r.response_json)?;
                }
            }
        }
        Ok(())
    }

    pub fn write_errors_maybe(&self) -> std::io::Result<()> {
        let err = &mut std::io::stderr();

        if let Err(ref e) = self.job {
            writeln!(err, "{:?}", e)?;
        }

        if let Some(ref rr) = self.response {
            match *rr {
                Err(ref e) => {
                    writeln!(err, "{:?}", e)?;
                }
                Ok(ref response) => {
                    let happy_json = response.status_code >= 200 && response.status_code < 300;
                    if !happy_json {
                        writeln!(err,
                                 "Job failed with status code {}. Response:\n",
                                 response.status_code)?;
                        std::io::stderr().write(&response.response_json)?;
                    }
                }
            }
        }
        Ok(())
    }

    pub fn get_exit_code(&self) -> Option<i32> {
        if let Err(ref e) = self.job {
            return Some(e.exit_code());
        }
        if let Some(ref rr) = self.response {
            match *rr {
                Err(ref err) => Some(err.exit_code()),
                Ok(ref response) => {
                    match response.status_code {
                        s if s >= 200 && s < 300 => Some(0),
                        s if s >= 400 && s < 500 => Some(65), //user error, bad data
                        _ => Some(70), //internal error
                    }
                }
            }
        } else {
            None
        }
    }

    fn build<'a, 'b>(data: &'a s::Build001) -> Result<fc::JsonResponse> {
        let mut context = fc::Context::create()?;
        Ok(context.message("v0.1/build", &serde_json::to_vec(data).unwrap())?)
    }
}

 parent={
                        let fname = format!("{)
                        let new_path = directory.join();
                        
                    }
                    s::IoEnum::Url(url) => {}
                    other => other
                }
            }else{
                match e{
                    s::IoEnum::Filename(path) => {

                    }
                    other => other
                }
            };
            s::IoObject{
                direction: obj.direction,
                io: new_enum,
                io_id: obj.io_id
            }
        })
    }

    // Write new invocation to STDOUT, for execution in 'directory'.
    // Will write recipe and dependencies into directory
    pub fn bundle_to(self, directory: &Path) -> i32{

    }

    pub fn build_maybe(self) -> CmdBuild {

        if self.job.is_ok() {

            let mut result = Err(CmdError::Incomplete);
            {
                if let Ok(ref b) = self.job {
                    result = CmdBuild::build(&b);
                }
            }
            CmdBuild { response: Some(result), ..self }
        } else {
            self
        }
    }

//    pub fn get_modified_recipe<'a>(&'a self) -> &'a Result<s::Build001>{
//        &self.job
//    }

    ///
    /// Write the JSON response (if present) to the given file or STDOUT
    pub fn write_response_maybe(&self, response_file: Option<&str>) -> std::io::Result<()> {
        if let Some(ref rr) = self.response {
            if let &Ok(ref r) = rr {
                if let Some(ref filename) = response_file {
                    let mut file = BufWriter::new(File::create(filename).unwrap());
                    file.write(&r.response_json)?;
                } else {
                    std::io::stdout().write(&r.response_json)?;
                }
            }
        }
        Ok(())
    }

    pub fn write_errors_maybe(&self) -> std::io::Result<()> {
        let err = &mut std::io::stderr();

        if let Err(ref e) = self.job {
            writeln!(err, "{:?}", e)?;
        }

        if let Some(ref rr) = self.response {
            match *rr {
                Err(ref e) => {
                    writeln!(err, "{:?}", e)?;
                }
                Ok(ref response) => {
                    let happy_json = response.status_code >= 200 && response.status_code < 300;
                    if !happy_json {
                        writeln!(err,
                                 "Job failed with status code {}. Response:\n",
                                 response.status_code)?;
                        std::io::stderr().write(&response.response_json)?;
                    }
                }
            }
        }
        Ok(())
    }

    pub fn get_exit_code(&self) -> Option<i32> {
        if let Err(ref e) = self.job {
            return Some(e.exit_code());
        }
        if let Some(ref rr) = self.response {
            match *rr {
                Err(ref err) => Some(err.exit_code()),
                Ok(ref response) => {
                    match response.status_code {
                        s if s >= 200 && s < 300 => Some(0),
                        s if s >= 400 && s < 500 => Some(65), //user error, bad data
                        _ => Some(70), //internal error
                    }
                }
            }
        } else {
            None
        }
    }

    fn build<'a, 'b>(data: &'a s::Build001) -> Result<fc::JsonResponse> {
        let mut context = fc::Context::create()?;
        Ok(context.message("v0.1/build", &serde_json::to_vec(data).unwrap())?)
    }
}

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:285)
	at org.rust.lang.core.psi.impl.RustBlockElementImpl.getRbrace(RustBlockElementImpl.java:146)
	at org.rust.ide.intentions.MatchToIfLetIntention.isVoid(MatchToIfLetIntention.kt:52)
	at org.rust.ide.intentions.MatchToIfLetIntention.findMathExpr(MatchToIfLetIntention.kt:40)
	at org.rust.ide.intentions.MatchToIfLetIntention.isAvailable(MatchToIfLetIntention.kt:16)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.isAvailable(PsiElementBaseIntentionAction.java:64)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:132)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$2(ShowIntentionsPass.java:312)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:311)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:219)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:285)
	at org.rust.lang.core.psi.impl.RustBlockElementImpl.getRbrace(RustBlockElementImpl.java:146)
	at org.rust.ide.intentions.MatchToIfLetIntention.isVoid(MatchToIfLetIntention.kt:52)
	at org.rust.ide.intentions.MatchToIfLetIntention.findMathExpr(MatchToIfLetIntention.kt:40)
	at org.rust.ide.intentions.MatchToIfLetIntention.isAvailable(MatchToIfLetIntention.kt:16)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.isAvailable(PsiElementBaseIntentionAction.java:64)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:132)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$2(ShowIntentionsPass.java:312)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:311)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:219)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:285)
	at org.rust.lang.core.psi.impl.RustBlockElementImpl.getRbrace(RustBlockElementImpl.java:146)
	at org.rust.ide.intentions.MatchToIfLetIntention.isVoid(MatchToIfLetIntention.kt:52)
	at org.rust.ide.intentions.MatchToIfLetIntention.findMathExpr(MatchToIfLetIntention.kt:40)
	at org.rust.ide.intentions.MatchToIfLetIntention.isAvailable(MatchToIfLetIntention.kt:16)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.isAvailable(PsiElementBaseIntentionAction.java:64)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:132)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$2(ShowIntentionsPass.java:312)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:311)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:219)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.IllegalStateException: @NotNull method com/intellij/psi/impl/PsiElementBase.notNullChild must not return null
	at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:287)
	at org.rust.lang.core.psi.impl.RustBlockElementImpl.getRbrace(RustBlockElementImpl.java:146)
	at org.rust.ide.intentions.MatchToIfLetIntention.isVoid(MatchToIfLetIntention.kt:52)
	at org.rust.ide.intentions.MatchToIfLetIntention.findMathExpr(MatchToIfLetIntention.kt:40)
	at org.rust.ide.intentions.MatchToIfLetIntention.isAvailable(MatchToIfLetIntention.kt:16)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.isAvailable(PsiElementBaseIntentionAction.java:64)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:132)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$2(ShowIntentionsPass.java:312)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:311)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:219)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.IllegalStateException: @NotNull method com/intellij/psi/impl/PsiElementBase.notNullChild must not return null
	at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:287)
	at org.rust.lang.core.psi.impl.RustBlockElementImpl.getRbrace(RustBlockElementImpl.java:146)
	at org.rust.ide.intentions.MatchToIfLetIntention.isVoid(MatchToIfLetIntention.kt:52)
	at org.rust.ide.intentions.MatchToIfLetIntention.findMathExpr(MatchToIfLetIntention.kt:40)
	at org.rust.ide.intentions.MatchToIfLetIntention.isAvailable(MatchToIfLetIntention.kt:16)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.isAvailable(PsiElementBaseIntentionAction.java:64)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:132)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$2(ShowIntentionsPass.java:312)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:311)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:219)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.IllegalStateException: @NotNull method com/intellij/psi/impl/PsiElementBase.notNullChild must not return null
	at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:287)
	at org.rust.lang.core.psi.impl.RustBlockElementImpl.getRbrace(RustBlockElementImpl.java:146)
	at org.rust.ide.intentions.MatchToIfLetIntention.isVoid(MatchToIfLetIntention.kt:52)
	at org.rust.ide.intentions.MatchToIfLetIntention.findMathExpr(MatchToIfLetIntention.kt:40)
	at org.rust.ide.intentions.MatchToIfLetIntention.isAvailable(MatchToIfLetIntention.kt:16)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.isAvailable(PsiElementBaseIntentionAction.java:64)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:132)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$2(ShowIntentionsPass.java:312)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:311)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:219)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


``

**Comment by matklad** [comment]
Wow, that was a subtle bug! Thanks a bunch for the report!
