### ISSUE TITLE
testResolveExternalLibrary fail

### ISSUE THREAD

**Issue by la10736** [intellij-rust/intellij-rust#809]
Test regression after last update:

```
michele@DartVader:~/intellij-rust$ git log -1
commit 2bb8ee0c4f3620c2227503ff077d0dc4f9d9fbe7
Merge: bebb9c8 218211c
Author: Aleksey Kladov <aleksey.kladov@gmail.com>
Date:   Fri Dec 2 18:04:27 2016 +0300

    Merge pull request #803 from alygin/params-hint
    
    (HINT): Functions/methods arguments hint
```

`testResolveExternalLibrary` fail :

```
org.rust.cargo.toolchain.CargoProjectResolveTest
.X
org.rust.cargo.toolchain.CargoProjectResolveTest > testResolveExternalLibrary FAILED
    java.lang.RuntimeException: java.lang.IllegalStateException: Unresolved reference in src/main.rs

        Caused by:
        java.lang.IllegalStateException: Unresolved reference in src/main.rs
            at org.rust.cargo.toolchain.CargoProjectResolveTest$resolveRefInFile$1.invoke(CargoProjectResolveTest.kt:53)
            at org.rust.cargo.toolchain.CargoProjectResolveTest$resolveRefInFile$1.invoke(CargoProjectResolveTest.kt:21)
            at org.rust.cargo.RustWithToolchainTestBase.withProject(RustWithToolchainTestBase.kt:27)
            at org.rust.cargo.toolchain.CargoProjectResolveTest.resolveRefInFile(CargoProjectResolveTest.kt:38)
            at org.rust.cargo.toolchain.CargoProjectResolveTest.resolveRefInFile$default(CargoProjectResolveTest.kt:37)
            at org.rust.cargo.toolchain.CargoProjectResolveTest.testResolveExternalLibrary(CargoProjectResolveTest.kt:27)
....

org.rust.cargo.commands.CargoFmtTest
.



1132 tests completed, 1 failed
:test FAILED

FAILURE: Build failed with an exception.
```
This morning I run test on updated source at office and I didn't notice any failure.

**Comment by la10736** [comment]
By last update after (necessary) clean the project the issue disappeared. I'm closing it.

**Comment by matklad** [comment]
I've found a dependency between tests, which might have caused similar issues: https://github.com/intellij-rust/intellij-rust/commit/d4a77d2bbdd86cad15bbfa82178a444a4e081a7f
