### ISSUE TITLE
Write-safe context error on startup

### ISSUE THREAD

**Issue by paulirotta** [intellij-rust/intellij-rust#816]
Windows 10, appeared on first start after reboot

Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities={ModalityState.NON_MODAL=true}
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:246)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.fireEvent(PsiModificationTrackerImpl.java:74)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.treeChanged(PsiModificationTrackerImpl.java:92)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:362)
	at com.intellij.psi.impl.PsiManagerImpl.beforePropertyChange(PsiManagerImpl.java:278)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$MyModuleRootListener$1.run(PsiVFSListener.java:642)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:927)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$MyModuleRootListener.beforeRootsChange(PsiVFSListener.java:629)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:381)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:368)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:354)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
	at com.sun.proxy.$Proxy100.beforeRootsChange(Unknown Source)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.fireBeforeRootsChangeEvent(ProjectRootManagerComponent.java:190)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireBeforeRootsChanged(ProjectRootManagerImpl.java:376)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$200(ProjectRootManagerImpl.java:55)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.beforeRootsChanged(ProjectRootManagerImpl.java:117)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:348)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$RootProviderChangeListener.rootSetChanged(ProjectRootManagerImpl.java:642)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy43.rootSetChanged(Unknown Source)
	at com.intellij.openapi.roots.impl.RootProviderBaseImpl.fireRootSetChanged(RootProviderBaseImpl.java:45)
	at com.intellij.openapi.roots.impl.libraries.LibraryImpl.commit(LibraryImpl.java:614)
	at com.intellij.openapi.roots.impl.libraries.LibraryImpl.commit(LibraryImpl.java:592)
	at org.rust.cargo.util.ModuleUtilKt.fillLibrary(ModuleUtil.kt:140)
	at org.rust.cargo.util.ModuleUtilKt.updateLibrary(ModuleUtil.kt:117)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.updateModuleDependencies(CargoProjectWorkspaceImpl.kt:164)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.access$updateModuleDependencies(CargoProjectWorkspaceImpl.kt:52)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$commitUpdate$1.invoke(CargoProjectWorkspaceImpl.kt:146)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$commitUpdate$1.invoke(CargoProjectWorkspaceImpl.kt:52)
	at org.rust.ide.utils.PlatformUtilsKt$runWriteAction$1.compute(PlatformUtils.kt:21)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:939)
	at org.rust.ide.utils.PlatformUtilsKt.runWriteAction(PlatformUtils.kt:21)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.commitUpdate(CargoProjectWorkspaceImpl.kt:144)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl.access$commitUpdate(CargoProjectWorkspaceImpl.kt:52)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$UpdateTask.onSuccess(CargoProjectWorkspaceImpl.kt:208)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.lambda$run$0(ProgressManagerImpl.java:152)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by matklad** [comment]
Could you please say what version of the IDE are you using `Help > About`?

**Comment by matklad** [comment]
>Could you please say what version of the IDE are you using Help > About?

Ah, looks like this affects the EAP version. Thanks for the report!
