### ISSUE TITLE
IDEA 2016.3: Could not initialize class com.intellij.codeInsight.completion.CompletionUtil

### ISSUE THREAD

**Issue by rx80** [intellij-rust/intellij-rust#818]
```
Could not initialize class com.intellij.codeInsight.completion.CompletionUtil
java.lang.NoClassDefFoundError: Could not initialize class com.intellij.codeInsight.completion.CompletionUtil
	at org.rust.lang.core.types.RustEnumType.<init>(RustEnumType.kt:9)
	at org.rust.lang.core.types.visitors.impl.RustItemTypificationVisitor$visitEnumItem$1.invoke(RustTypificationEngine.kt:177)
	at org.rust.lang.core.types.visitors.impl.RustItemTypificationVisitor$visitEnumItem$1.invoke(RustTypificationEngine.kt:162)
	at org.rust.lang.core.psi.visitors.RustComputingVisitor.set(RustComputingVisitor.kt:36)
	at org.rust.lang.core.types.visitors.impl.RustItemTypificationVisitor.visitEnumItem(RustTypificationEngine.kt:176)
	at org.rust.lang.core.psi.impl.RustEnumItemElementImpl.accept(RustEnumItemElementImpl.java:28)
	at org.rust.lang.core.psi.impl.RustEnumItemElementImpl.accept(RustEnumItemElementImpl.java:32)
	at org.rust.lang.core.psi.visitors.RustComputingVisitor.compute(RustComputingVisitor.kt:27)
	at org.rust.lang.core.types.visitors.impl.RustTypificationEngine.typifyItem(RustTypificationEngine.kt:28)
	at org.rust.lang.core.types.visitors.impl.RustTypificationEngine.typify(RustTypificationEngine.kt:32)
	at org.rust.lang.core.types.util.RustPsiExtensionsKt$resolvedType$3.compute(RustPsiExtensions.kt:43)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
	at org.rust.lang.core.types.util.RustPsiExtensionsKt.getResolvedType(RustPsiExtensions.kt:41)
	at org.rust.lang.core.resolve.RustScopeVisitor.staticMethods(RustResolveEngine.kt:390)
	at org.rust.lang.core.resolve.RustScopeVisitor.access$staticMethods(RustResolveEngine.kt:226)
	at org.rust.lang.core.resolve.RustScopeVisitor$visitEnumItem$1.invoke(RustResolveEngine.kt:289)
	at org.rust.lang.core.resolve.RustScopeVisitor$visitEnumItem$1.invoke(RustResolveEngine.kt:226)
	at org.rust.lang.core.psi.visitors.RustComputingVisitor.set(RustComputingVisitor.kt:36)
	at org.rust.lang.core.resolve.RustScopeVisitor.visitEnumItem(RustResolveEngine.kt:288)
	at org.rust.lang.core.psi.impl.RustEnumItemElementImpl.accept(RustEnumItemElementImpl.java:28)
	at org.rust.lang.core.psi.impl.RustEnumItemElementImpl.accept(RustEnumItemElementImpl.java:32)
	at org.rust.lang.core.psi.visitors.RustComputingVisitor.compute(RustComputingVisitor.kt:27)
	at org.rust.lang.core.resolve.RustResolveEngineKt$declarations$$inlined$Sequence$1.iterator(Sequences.kt:591)
	at kotlin.sequences.SequencesKt___SequencesKt$flatMap$1.invoke(_Sequences.kt:594)
	at kotlin.sequences.SequencesKt___SequencesKt$flatMap$1.invoke(_Sequences.kt)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:241)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:229)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:97)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:141)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:97)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
	at kotlin.sequences.TakeSequence$iterator$1.hasNext(Sequences.kt:338)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:141)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:97)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:536)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:560)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:553)
	at org.rust.lang.core.resolve.RustResolveEngine.resolve(RustResolveEngine.kt:42)
	at org.rust.lang.core.resolve.ref.RustPathReferenceImpl.resolveInner(RustPathReferenceImpl.kt:24)
	at org.rust.lang.core.resolve.ref.RustPathReferenceImpl$resolve$1.resolve(RustPathReferenceImpl.kt:30)
	at org.rust.lang.core.resolve.ref.RustPathReferenceImpl$resolve$1.resolve(RustPathReferenceImpl.kt:15)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:213)
	at org.rust.lang.core.resolve.ref.RustPathReferenceImpl.resolve(RustPathReferenceImpl.kt:28)
	at org.rust.ide.annotator.RustHighlightingAnnotator.annotate(RustHighlightingAnnotator.kt:34)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:363)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:322)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:237)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.NoClassDefFoundError: Could not initialize class com.intellij.codeInsight.completion.CompletionUtil
	at org.rust.lang.core.types.RustEnumType.<init>(RustEnumType.kt:9)
	at org.rust.lang.core.types.visitors.impl.RustItemTypificationVisitor$visitEnumItem$1.invoke(RustTypificationEngine.kt:177)
	at org.rust.lang.core.types.visitors.impl.RustItemTypificationVisitor$visitEnumItem$1.invoke(RustTypificationEngine.kt:162)
	at org.rust.lang.core.psi.visitors.RustComputingVisitor.set(RustComputingVisitor.kt:36)
	at org.rust.lang.core.types.visitors.impl.RustItemTypificationVisitor.visitEnumItem(RustTypificationEngine.kt:176)
	at org.rust.lang.core.psi.impl.RustEnumItemElementImpl.accept(RustEnumItemElementImpl.java:28)
	at org.rust.lang.core.psi.impl.RustEnumItemElementImpl.accept(RustEnumItemElementImpl.java:32)
	at org.rust.lang.core.psi.visitors.RustComputingVisitor.compute(RustComputingVisitor.kt:27)
	at org.rust.lang.core.types.visitors.impl.RustTypificationEngine.typifyItem(RustTypificationEngine.kt:28)
	at org.rust.lang.core.types.visitors.impl.RustTypificationEngine.typify(RustTypificationEngine.kt:32)
	at org.rust.lang.core.types.util.RustPsiExtensionsKt$resolvedType$3.compute(RustPsiExtensions.kt:43)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
	at org.rust.lang.core.types.util.RustPsiExtensionsKt.getResolvedType(RustPsiExtensions.kt:41)
	at org.rust.lang.core.resolve.RustScopeVisitor.staticMethods(RustResolveEngine.kt:390)
	at org.rust.lang.core.resolve.RustScopeVisitor.access$staticMethods(RustResolveEngine.kt:226)
	at org.rust.lang.core.resolve.RustScopeVisitor$visitEnumItem$1.invoke(RustResolveEngine.kt:289)
	at org.rust.lang.core.resolve.RustScopeVisitor$visitEnumItem$1.invoke(RustResolveEngine.kt:226)
	at org.rust.lang.core.psi.visitors.RustComputingVisitor.set(RustComputingVisitor.kt:36)
	at org.rust.lang.core.resolve.RustScopeVisitor.visitEnumItem(RustResolveEngine.kt:288)
	at org.rust.lang.core.psi.impl.RustEnumItemElementImpl.accept(RustEnumItemElementImpl.java:28)
	at org.rust.lang.core.psi.impl.RustEnumItemElementImpl.accept(RustEnumItemElementImpl.java:32)
	at org.rust.lang.core.psi.visitors.RustComputingVisitor.compute(RustComputingVisitor.kt:27)
	at org.rust.lang.core.resolve.RustResolveEngineKt$declarations$$inlined$Sequence$1.iterator(Sequences.kt:591)
	at kotlin.sequences.SequencesKt___SequencesKt$flatMap$1.invoke(_Sequences.kt:594)
	at kotlin.sequences.SequencesKt___SequencesKt$flatMap$1.invoke(_Sequences.kt)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:241)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:229)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:97)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:141)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:97)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
	at kotlin.sequences.TakeSequence$iterator$1.hasNext(Sequences.kt:338)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:141)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:97)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:121)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:536)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:560)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:553)
	at org.rust.lang.core.resolve.RustResolveEngine.resolve(RustResolveEngine.kt:42)
	at org.rust.lang.core.resolve.ref.RustPathReferenceImpl.resolveInner(RustPathReferenceImpl.kt:24)
	at org.rust.lang.core.resolve.ref.RustPathReferenceImpl$resolve$1.resolve(RustPathReferenceImpl.kt:30)
	at org.rust.lang.core.resolve.ref.RustPathReferenceImpl$resolve$1.resolve(RustPathReferenceImpl.kt:15)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:213)
	at org.rust.lang.core.resolve.ref.RustPathReferenceImpl.resolve(RustPathReferenceImpl.kt:28)
	at org.rust.ide.annotator.RustHighlightingAnnotator.annotate(RustHighlightingAnnotator.kt:34)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:363)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:322)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:325)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:237)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:433)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:426)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:425)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:405)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:155)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by matklad** [comment]
Hm, what is the precise version of the IDE you are using (`Help > About`)?

**Comment by rx80** [comment]
@matklad Sorry for late reply, holidays and stuff. Sadly  i can't answer because the issue sorted itself out with next update, so this issue can be closed.

**Comment by matklad** [comment]
Glad to hear that the issue is fixed, thanks!
