### ISSUE TITLE
компилятор не распознает свежую версию webassembly rust, выдает ошибку и предлагает обновиться.

### ISSUE THREAD

**Issue by Evgene-Kopylov** [intellij-rust/intellij-rust#8599]
## Environment

* **IntelliJ Rust plugin version:** 0.4.165.4438-213
* **Rust toolchain version:** 1.58.1 (db9d1b20b 2022-01-20) x86_64-pc-windows-msvc
* **IDE name and version:** IntelliJ IDEA 2021.3.2 Community Edition (IC-213.6777.52)
* **Operating system:** Windows 11 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Получил ошибку при попытке скомпилировать шаблон для wasm проекта
wasm-pack is not installed
Need at least wasm-pack 0.9.1

Стоит свежий wasm
wasm-pack -V
wasm-pack 0.10.2

компилятор не распознает свежую версию webassembly rust, выдает ошибку и предлагает обновиться.

## Steps to reproduce

создать новый webassembly rust проект в IntelliJ, нажать Build

**Comment by avrong** [comment]
Hi. Thanks for the report.

I cannot reproduce this issue on macOS 11.5.2 with `wasm-pack` 0.10.2 installed through `cargo install`.

Can you specify, please:
1. How did you install `wasm-pack`?
2. Is `wasm-pack` available in the IDEA terminal? (`Alt+F12` for standard Windows keymap)
3. What happens if you will install it using the prompt that says `wasm-pack is not installed`?

**Comment by Evgene-Kopylov** [comment]
У меня винда.
проект билдится через консольную команду
wasm-pack build
через shift+f10 не билдится, выдаёт описанную ошибку

вт, 1 мар. 2022 г., 12:38 Aleksei Trifonov ***@***.***>:

**Comment by avrong** [comment]
What specific way did you install `wasm-pack`?

**Comment by Evgene-Kopylov** [comment]
через окошко ошибки. там гиперссылка "install"

сб, 12 мар. 2022 г. в 20:29, Aleksei Trifonov ***@***.***>:

**Comment by huhlig** [comment]
I'm having the same issue. If you install wasm-pack on windows you must do it via the installer (not cargo) due to an openssl-sys issue. See https://rustwasm.github.io/wasm-pack/installer/ for the installer. Due to this, it does not show up in `cargo install --list` and thus the plugin doesn't find it. However, if you use cargo on the terminal it has no issues using it. A simple fix for this is likely just to run `wasm-pack --version` and parse the resulting version string.

**Comment by Evgene-Kopylov** [comment]
after reinstalling rust and intellij, while installing wasm-pack encounter same issue

```
error: failed to run custom build command for `openssl-sys v0.9.72`

Caused by:
  process didn't exit successfully: `C:\Temp\cargo-installCEtjuT\release\build\openssl-sys-fc52b967695c062a\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\Temp\\cargo-installCEtjuT\\release\\build\\openssl-sys-02c2e34762025e69\\out\\openssl-build\\install" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', C:\Users\Death\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.18.0+1.1.1n\src\lib.rs:477:39
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\panicking.rs:584
     1: core::panicking::panic_fmt
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\panicking.rs:143
     2: core::result::unwrap_failed
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\result.rs:1749
     3: core::result::Result<T,E>::unwrap
     4: openssl_src::Build::build
     5: openssl_src::Build::build
     6: build_script_main::find_vendored::get_openssl
     7: build_script_main::env::{{closure}}
     8: build_script_main::find_openssl::{{closure}}
     9: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasm-pack v0.10.2`, intermediate artifacts can be found at `C:\Temp\cargo-installCEtjuT`

Caused by:
  build failed

Process finished with exit code 101
```

**Comment by huhlig** [comment]
A workaround until wasm-pack fixes it's installer, or intellij-rust fixes it's detection.

1) Install wasm-pack via installer at https://rustwasm.github.io/wasm-pack/installer/
2) open $CARGO_HOME/.crates.toml
3) Add following line between blocks for `wasm-bindgen-cli` and `wasm-server-runner`
`"wasm-pack 0.10.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-pack.exe"]`
4) CLion should now recognise and run wasm-pack properly.

**Comment by Kage-Yami** [comment]
I'm puzzled why IntelliJ Rust does not just use `wasm-pack` if it is available on the `PATH`? 

In my case, I've installed `wasm-pack` using Arch Linux's package - which then IntelliJ Rust is not picking up on. From the sounds of things though, even if I install `wasm-pack` using the official installer, it _still_ won't work.

**Comment by huhlig** [comment]
> I'm puzzled why IntelliJ Rust does not just use `wasm-pack` if it is available on the `PATH`?
> 
> In my case, I've installed `wasm-pack` using Arch Linux's package - which then IntelliJ Rust is not picking up on. From the sounds of things though, even if I install `wasm-pack` using the official installer, it _still_ won't work.

You should be able to use the same workaround until JetBrains fixes this issue.

**Comment by max-sixty** [comment]
> open $CARGO_HOME/.crates.toml

What is `.crates.toml`? When I google for it, this issue comes up...
