### ISSUE TITLE
`Build` button in Rider does not work

### ISSUE THREAD

**Issue by neonaot** [intellij-rust/intellij-rust#8751]
## Environment

* **IntelliJ Rust plugin version:** 0.4.169.4558-221-nightly
* **Rust toolchain version:** 1.61.0-nightly (f0c4da499 2022-03-01) x86_64-apple-darwin
* **IDE name and version:** JetBrains Rider 2022.1 EAP 10 (RD-221.5080.209)
* **Operating system:** macOS 11.4
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
There is a familiar hammer button that is expected to build a project, but it does nothing except exception :(

https://user-images.githubusercontent.com/49211026/163411007-487f2a73-eebf-4199-9fe2-7e24fb906e14.mov

I remember that a run configuration with the `build` command can be added, but button is still annoyed.

 
<details>

```

com.jetbrains.rdclient.util.BackendException: Toolset is null

--- EXCEPTION #1/1 [LoggerException]
Message = “Toolset is null”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogMessage(ILogger this, LoggingLevel level, String message)
     at JetBrains.Util.ILoggerEx.Error(ILogger this, String message)
     at JetBrains.ReSharper.Features.SolBuilderDuo.ConsoleRunner.MsBuildExeBuildRunner.ExecuteBuildRequestCore(SolutionBuilderRequest builderRequest, Lifetime lifetime)
     at JetBrains.ReSharper.Features.SolBuilderDuo.ConsoleRunner.MsBuildExeBuildRunner.ExecuteBuildRequest(SolutionBuilderRequest builderRequest)
     at JetBrains.ProjectModel.Features.SolutionBuilders.SolutionBuilder.<>c__DisplayClass27_0.<ExecuteBuildRequest>g__ExecuteBuildRequest|2()
     at JetBrains.ProjectModel.Features.SolutionBuilders.SolutionBuilder.<>c__DisplayClass27_0.<ExecuteBuildRequest>b__4()
     at JetBrains.DataFlow.IPropertyEx.WhenEqualsOnce[T](IProperty`1 property, Lifetime lifetime, Action FHandler, T value)
     at JetBrains.DataFlow.IPropertyEx.WhenTrueOnce(IProperty`1 property, Lifetime lifetime, Action FHandler)
     at JetBrains.ProjectModel.Features.SolutionBuilders.SolutionBuilder.<>c__DisplayClass27_0.<ExecuteBuildRequest>b__1()
     at JetBrains.Application.Threading.IShellLocksEx.ExecuteWithReadLock(IShellLocks thіs, Action F)
     at JetBrains.Application.Threading.IShellLocksEx.<>c__DisplayClass8_0.<ExecuteOrQueueReadLockEx>b__0()
     at JetBrains.Threading.ReentrancyGuardEx.<>c__DisplayClass4_1.<ExecuteOrQueueOrRunSync>b__2()
     at JetBrains.Util.Concurrency.ExecutionContextEx.<>c__DisplayClass0_0.<Run>b__0(Object _)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
     at JetBrains.Util.Concurrency.ExecutionContextEx.Run(ExecutionContext context, ContextCallback callback, Object state)
     at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     at JetBrains.Threading.ReentrancyGuard.ExecutePendingActions()
     at JetBrains.Util.Concurrency.ExecutionContextEx.<>c__DisplayClass0_0.<Run>b__0(Object _)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
     at JetBrains.Util.Concurrency.ExecutionContextEx.Run(ExecutionContext context, ContextCallback callback, Object state)
     at JetBrains.Threading.JetDispatcher.Closure.Execute()
     at JetBrains.Threading.JetDispatcher.Run()
     at JetBrains.Rider.Backend.Product.RiderMain.Main(Lifetime lifetime, IRiderSettings settings, ILogger logger, ProtocolComponent protocol, RdShellModel shellModel, ApplicationShutdownRequests shutdownRequests)
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at JetBrains.Application.Environment.RunsPublicStaticIntMain.<>c__DisplayClass0_0.<.ctor>b__0()
     at JetBrains.Application.Environment.RunsPublicStaticIntMain.<>c__DisplayClass0_2.<.ctor>b__5()
     at JetBrains.Util.Logging.Logger.Catch(Action action)
     at JetBrains.Application.Threading.IThreadingEx.<>c__DisplayClass18_1.<ExecuteOrQueueWhenNotGuarded>b__4()
     at JetBrains.Util.Concurrency.ExecutionContextEx.<>c__DisplayClass1_0.<Run>b__0(Object _)
     at JetBrains.Util.Concurrency.ExecutionContextEx.<>c__DisplayClass0_0.<Run>b__0(Object _)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at JetBrains.Util.Concurrency.ExecutionContextEx.Run(ExecutionContext context, ContextCallback callback, Object state)
     at JetBrains.Util.Concurrency.ExecutionContextEx.Run(ExecutionContext context, Action action)
     at JetBrains.Threading.JetDispatcher.Closure.<>c__DisplayClass10_1.<.ctor>b__0()
     at JetBrains.Threading.JetDispatcher.Closure.Execute()
     at JetBrains.Threading.JetDispatcher.Run(Func`1 condition, TimeSpan timeout, Boolean bThrowOnTimeout)
     at JetBrains.Application.Environment.IJetHostEx.RunHostMessageLoop(IComponentContainer containerEnv)
     at JetBrains.Application.Environment.HostParameters.MessagePumpMainLoopHostMixin.JetBrains.Application.Environment.HostParameters.IRunMainLoopHostMixin.RunMainLoop(ComponentContainer containerEnv)
     at JetBrains.Application.Environment.HostParameters.JetHostParametersCaller.RunMainLoop(ComponentContainer containerEnv)
     at JetBrains.Application.Environment.JetEnvironment.InternalRun(JetHostParametersCaller host, ComponentContainer containerEnv)
     at JetBrains.Application.Environment.JetEnvironment.CreateAndRun(Full hostparams)
     at JetBrains.Application.Environment.JetHostItems.CreateAndRun(Full input)
     at JetBrains.Rider.Backend.Product.RiderBackendProgram.MainX(Assembly assembly, HostInfo hostInfo, String[] args)
     at JetBrains.Rider.Backend.Product.RiderBackendProgram.<>c.<Main>b__3_0(Lifetime lifetime)
     at JetBrains.Lifetimes.Lifetime.Using[T](Func`2 action)
     at JetBrains.Rider.Backend.Product.RiderBackendProgram.Main()
”

	at com.jetbrains.rdclient.protocol.components.RdClientProtocolComponent$2.invoke(RdClientProtocolComponent.kt:47)
	at com.jetbrains.rdclient.protocol.components.RdClientProtocolComponent$2.invoke(RdClientProtocolComponent.kt:22)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.framework.impl.RdSignal.onWireReceived(RdSignal.kt:42)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:97)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:18)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:23)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```
</details>

**Comment by jamsoft** [comment]
On my windows machine, it kicks off MSBuild which promptly fails with:

```
Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

**Comment by rfvgyhn** [comment]
I have the same issue as @jamsoft on linux. Is this a misconfiguration on my end or an issue with the plugin?

```
JetBrains Rider 2022.3.1
Build #RD-223.8214.53, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.1.6-arch1-3
.NET 7.0.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Registry:
    ide.intellij.laf.enable.animation=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    indexing.enable.entity.provider.based.indexing=false
    vcs.empty.toolwindow.show=false
    rdclient.asyncActions=false
    ide.workspace.model.rbs.as.tree=false
    platform.projectModel.workspace.model.file.index=false
    ide.new.project.model.index.case.sensitivity=true
    database.show.search.tab=false

Non-Bundled Plugins:
    com.sburlyaev.terminal.plugin (0.4.5)
    com.intellij.resharper.HeapAllocationsViewer (2022.3.1)
    org.rust.lang (0.4.186.5143-223)
    org.toml.lang (223.8214.6)
    com.mallowigi.idea (20.0.0)
    com.intellij.resharper.StructuredLogging (2022.3.1.280)
    com.intellij.plugin.adernov.powershell (2.0.10)
    GrepConsole (12.15.211.6693.1)
    com.mallowigi (85.1.0)

Current Desktop: KDE
```

**Comment by MrGaribaldi** [comment]
Similar issue here, has been going on for a long time. Hope you can acknowledge issue, and either block the build option, as happens on Jetbrains Client when working remotely or fix it. 

JetBrains Rider 2022.2.4
Build #RD-222.4459.9, built on November 4, 2022
Runtime version: 17.0.5+7-b469.67 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
.NET 6.0.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    rdclient.asyncActions=false
    ide.new.project.model.index.case.sensitivity=true
    indexing.enable.entity.provider.based.indexing=false

Non-Bundled Plugins:
    org.toml.lang (222.4459.17)
    org.rust.lang (0.4.186.5143-222)
    izhangzhihao.rainbow.brackets (6.26)

**Comment by wakuflair** [comment]
> On my windows machine, it kicks off MSBuild which promptly fails with:
> 
> ```
> Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
> Copyright (C) Microsoft Corporation. All rights reserved.
> MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
> ```

+1

**Comment by AlexEndris** [comment]
> On my windows machine, it kicks off MSBuild which promptly fails with:
> 
> ```
> Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
> Copyright (C) Microsoft Corporation. All rights reserved.
> MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
> ```

+1
