### ISSUE TITLE
Exception in c.i.e.p.BaseOSProcessHandler

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#8765]
## Environment

* **IntelliJ Rust plugin version:** 0.4.170.4570-221-nightly
* **Rust toolchain version:** 1.62.0-nightly (60e50fc1c 2022-04-04) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.1 RC (CL-221.5080.169)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
```
2022-04-19 10:06:21,620 [ 305170]   WARN - #c.i.e.p.BaseOSProcessHandler - Process hasn't generated any output for a long time.
If it's a long-running mostly idle daemon process, consider overriding OSProcessHandler#readerOptions with 'BaseOutputReader.Options.forMostlySilentProcess()' to reduce CPU usage.
```

<details>
   
```
    2022-04-19 **10:05:26,211** [ 249761]   WARN - #c.i.o.a.i.ActionUpdater - 107 ms to call on EDT RefreshCargoProjectsAction#update (org.rust.ide.actions.RefreshCargoProjectsAction). Use `UpdateInBackground`.
2022-04-19 **10:06:21,620** [ 305170]   WARN - #c.i.e.p.BaseOSProcessHandler - Process hasn't generated any output for a long time.
If it's a long-running mostly idle daemon process, consider overriding OSProcessHandler#readerOptions with 'BaseOutputReader.Options.forMostlySilentProcess()' to reduce CPU usage.
Command line: C:\Windows\system32\wsl.exe --distribution Ubuntu-20.04 --exec /bin/sh -c "export PATH=\"/home/user/.cargo/bin:$PATH\" && export RUST_BACKTRACE=short && export CARGO_CRATE_NAME=TestProfilerRust && export CARGO_PKG_VERSION_MINOR=1 && export TERM=ansi && export CARGO=cargo && export CARGO_PKG_VERSION_PATCH=0 && export CARGO_PKG_REPOSITORY='' && export CARGO_PKG_AUTHORS='' && export CARGO_PKG_VERSION=0.1.0 && export CARGO_PKG_LICENSE_FILE='' && export CARGO_PKG_LICENSE='' && export CARGO_PKG_NAME=TestProfilerRust && export CARGO_PKG_VERSION_MAJOR=0 && export CARGO_MANIFEST_DIR=/home/user/runstProjects/TestProfiler/TestProfilerRust && export CARGO_PKG_VERSION_PRE='' && export CARGO_PKG_DESCRIPTION='' && cd /home/user/runstProjects/TestProfiler/TestProfilerRust && /usr/bin/valgrind --tool=memcheck --xml=yes --xml-file=/mnt/c/Users/user/AppData/Local/Temp/valgrind --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no /home/user/runstProjects/TestPr ...

java.lang.Throwable: Process creation:
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:33)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:41)
	at org.rust.cargo.runconfig.RsProcessHandler.<init>(RsProcessHandler.kt:20)
	at org.rust.cargo.runconfig.RsProcessHandler.<init>(RsProcessHandler.kt:20)
	at org.rust.cargo.runconfig.target.UtilsKt.startProcess(Utils.kt:64)
	at org.rust.cargo.runconfig.UtilsKt.executeCommandLine(Utils.kt:199)
	at org.rust.cargo.runconfig.RsExecutableRunner.executeCommandLine(RsExecutableRunner.kt:123)
	at org.rust.cargo.runconfig.RsExecutableRunner.showRunContent(RsExecutableRunner.kt:117)
	at org.rust.cargo.runconfig.RsExecutableRunner.doExecute(RsExecutableRunner.kt:110)
	at org.rust.cargo.runconfig.RsDefaultProgramRunnerBase$execute$1.invoke(RsDefaultProgramRunnerBase.kt:25)
	at org.rust.cargo.runconfig.RsDefaultProgramRunnerBase$execute$1.invoke(RsDefaultProgramRunnerBase.kt:24)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:173)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:72)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:234)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```
</details>

**Comment by mchernyavsky** [comment]
The same exception on macOS:

<details>
```
2022-04-05 16:01:38,574 [1416324]   WARN - #c.i.e.p.BaseOSProcessHandler - Process hasn't generated any output for a long time.
If it's a long-running mostly idle daemon process, consider overriding OSProcessHandler#readerOptions with 'BaseOutputReader.Options.forMostlySilentProcess()' to reduce CPU usage.
Command line: /usr/local/Cellar/valgrind/HEAD-6ff08b6/bin/valgrind --tool=memcheck --xml=yes --xml-file=/private/var/folders/3h/84f9f09s3m1g29j5d685wds00000gn/T/valgrind2 --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no /Users/jamilya.shurukhova/IdeaProjects/pr_verify_projects/TestProfiler/TestProfilerRust/target/debug/TestProfilerRust
java.lang.Throwable: Process creation:
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:33)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:41)
	at org.rust.cargo.runconfig.RsProcessHandler.<init>(RsProcessHandler.kt:19)
	at org.rust.cargo.runconfig.RsProcessHandler.<init>(RsProcessHandler.kt:16)
	at org.rust.cargo.runconfig.UtilsKt.executeCommandLine(Utils.kt:198)
	at org.rust.cargo.runconfig.RsExecutableRunner.executeCommandLine(RsExecutableRunner.kt:121)
	at org.rust.cargo.runconfig.RsExecutableRunner.showRunContent(RsExecutableRunner.kt:115)
	at org.rust.cargo.runconfig.RsExecutableRunner.doExecute(RsExecutableRunner.kt:108)
	at org.rust.cargo.runconfig.RsDefaultProgramRunnerBase$execute$1.invoke(RsDefaultProgramRunnerBase.kt:25)
	at org.rust.cargo.runconfig.RsDefaultProgramRunnerBase$execute$1.invoke(RsDefaultProgramRunnerBase.kt:24)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:173)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:72)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:234)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2022-04-05 16:03:19,080 [1516830]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=TestProfilerRust, containerState=COMPONENT_CREATED, componentStore=/Users/jamilya.shurukhova/IdeaProjects/pr_verify_projects/TestProfiler/TestProfilerRust)RunManager took 22 ms
```
</details>
