### ISSUE TITLE
Synchronous execution on EDT: rustfmt

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#8774]
## Environment

* **IntelliJ Rust plugin version:** 0.4.170.4570-221-nightly
* **Rust toolchain version:** 1.61.0-nightly (461e80780 2022-03-16) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.1 Ultimate Edition (IU-221.5080.210)
* **Operating system:** macOS 11.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
Exception occured 
```
2022-04-21 09:37:19,639 [155388043] SEVERE - #c.i.e.p.OSProcessHandler - Synchronous execution on EDT: /Users/jamilya.shurukhova/.cargo/bin/rustfmt --unstable-features --emit=stdout --edition=2018, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions
java.lang.Throwable: Synchronous execution on EDT: /Users/jamilya.shurukhova/.cargo/bin/rustfmt --unstable-features --emit=stdout --edition=2018, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions

```

## Steps to reproduce
1. Add additional argument to rustfmt
<img width="1045" alt="Screenshot 2022-04-21 at 09 53 22" src="https://user-images.githubusercontent.com/1213122/164406800-4fbffe42-4efb-463b-9f04-c70a404651d0.png">
2. Open file with a piece of code
```rust
struct F{   }
```
3. Save

## Actual Results
There is an exception in logs

<details>

```
2022-04-21 09:37:19,639 [155388043] SEVERE - #c.i.e.p.OSProcessHandler - Synchronous execution on EDT: /Users/jamilya.shurukhova/.cargo/bin/rustfmt --unstable-features --emit=stdout --edition=2018, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions
java.lang.Throwable: Synchronous execution on EDT: /Users/jamilya.shurukhova/.cargo/bin/rustfmt --unstable-features --emit=stdout --edition=2018, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions
   at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
   at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:171)
   at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:102)
   at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:39)
   at com.intellij.execution.process.CapturingProcessHandler.runProcess(CapturingProcessHandler.java:43)
   at org.rust.openapiext.CommandLineExtKt.runProcess(CommandLineExt.kt:131)
   at org.rust.openapiext.CommandLineExtKt.runProcessWithGlobalProgress(CommandLineExt.kt:118)
   at org.rust.openapiext.CommandLineExtKt.access$runProcessWithGlobalProgress(CommandLineExt.kt:1)
   at org.rust.openapiext.CommandLineExtKt$execute$1.invoke(CommandLineExt.kt:58)
   at org.rust.openapiext.CommandLineExtKt$execute$1.invoke(CommandLineExt.kt:58)
   at org.rust.openapiext.CommandLineExtKt.execute(CommandLineExt.kt:104)
   at org.rust.openapiext.CommandLineExtKt.execute$default(CommandLineExt.kt:55)
   at org.rust.cargo.toolchain.tools.Rustfmt.reformatDocumentTextOrNull(Rustfmt.kt:41)
   at org.rust.cargo.RustfmtWatcher$Companion.reformatDocument(RustfmtWatcher.kt:113)
   at org.rust.cargo.RustfmtWatcher$Companion.reformatDocuments(RustfmtWatcher.kt:106)
   at org.rust.cargo.RustfmtWatcher$Companion.access$reformatDocuments(RustfmtWatcher.kt:89)
   at org.rust.cargo.RustfmtWatcher$RustfmtListener.beforeDocumentSaving(RustfmtWatcher.kt:79)
   at jdk.internal.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.multiCast(FileDocumentManagerImpl.java:185)
   at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$new$0(FileDocumentManagerImpl.java:128)
   at com.sun.proxy.$Proxy18.beforeDocumentSaving(Unknown Source)
   at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocumentInWriteAction$4(FileDocumentManagerImpl.java:407)
   at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:326)
   at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocumentInWriteAction(FileDocumentManagerImpl.java:406)
   at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocument$2(FileDocumentManagerImpl.java:367)
   at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:86)
   at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1003)
   at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1029)
   at com.intellij.openapi.application.WriteAction.run(WriteAction.java:85)
   at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocument(FileDocumentManagerImpl.java:367)
   at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocuments(FileDocumentManagerImpl.java:287)
   at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:262)
   at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:255)
   at com.intellij.ide.actions.SaveAllAction.actionPerformed(SaveAllAction.kt:24)
   at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
   at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:579)
   at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:704)
   at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
   at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
   at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$11(IdeKeyEventDispatcher.java:704)
   at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
   at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:701)
   at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
   at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:590)
   at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:473)
   at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:462)
   at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:227)
   at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
   at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:740)
   at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
   at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
   at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
   at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
   at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
   at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
   at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
   at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
   at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
   at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
   at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
   at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
   at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
   at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2022-04-21 09:37:19,640 [155388044] SEVERE - #c.i.e.p.OSProcessHandler - IntelliJ IDEA 2022.1  Build #IU-221.5080.210
2022-04-21 09:37:19,640 [155388044] SEVERE - #c.i.e.p.OSProcessHandler - JDK: 11.0.14.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-04-21 09:37:19,640 [155388044] SEVERE - #c.i.e.p.OSProcessHandler - OS: Mac OS X
2022-04-21 09:37:19,640 [155388044] SEVERE - #c.i.e.p.OSProcessHandler - Plugin to blame: Rust version: 0.4.170.4570-221-nightly
2022-04-21 09:37:20,250 [155388654]   INFO - #c.i.o.u.LowMemoryWatcher - Low memory signal received: afterGc=false
```

</details>

**Comment by mili-l** [comment]
Run rustfmt from IDE leads to exception

<details>

<summary> Exception </summary>

```
java.lang.Throwable: Synchronous execution on EDT: /Users/jamilya.shurukhova/.cargo/bin/rustup component list, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:171)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:109)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:61)
	at com.intellij.execution.process.CapturingProcessRunner.runProcess(CapturingProcessRunner.java:50)
	at com.intellij.execution.process.CapturingProcessHandler.runProcess(CapturingProcessHandler.java:52)
	at org.rust.openapiext.CommandLineExtKt.runProcess(CommandLineExt.kt:130)
	at org.rust.openapiext.CommandLineExtKt.runProcessWithGlobalProgress(CommandLineExt.kt:118)
	at org.rust.openapiext.CommandLineExtKt.execute(CommandLineExt.kt:46)
	at org.rust.cargo.toolchain.tools.Rustup.listComponents(Rustup.kt:63)
	at org.rust.cargo.toolchain.tools.Rustup.needInstallComponent(Rustup.kt:133)
	at org.rust.cargo.toolchain.tools.Rustup.access$needInstallComponent(Rustup.kt:37)
	at org.rust.cargo.toolchain.tools.Rustup$Companion.checkNeedInstallComponent(Rustup.kt:172)
	at org.rust.cargo.toolchain.tools.Rustup$Companion.checkNeedInstallRustfmt(Rustup.kt:157)
	at org.rust.cargo.RustfmtWatcher$Companion.reformatDocuments(RustfmtWatcher.kt:105)
	at org.rust.cargo.RustfmtWatcher$Companion.access$reformatDocuments(RustfmtWatcher.kt:89)
	at org.rust.cargo.RustfmtWatcher$RustfmtListener.beforeDocumentSaving(RustfmtWatcher.kt:79)
	at jdk.internal.reflect.GeneratedMethodAccessor2914.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.multiCast(FileDocumentManagerImpl.java:185)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$new$0(FileDocumentManagerImpl.java:128)
	at jdk.proxy1/jdk.proxy1.$Proxy21.beforeDocumentSaving(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocumentInWriteAction$4(FileDocumentManagerImpl.java:407)
	at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:326)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocumentInWriteAction(FileDocumentManagerImpl.java:406)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocument$2(FileDocumentManagerImpl.java:367)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1011)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1037)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:85)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocument(FileDocumentManagerImpl.java:367)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocument(FileDocumentManagerImpl.java:318)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocument(FileDocumentManagerImpl.java:308)
	at com.intellij.formatting.service.AsyncDocumentFormattingService$FormattingRequestImpl.<init>(AsyncDocumentFormattingService.java:170)
	at com.intellij.formatting.service.AsyncDocumentFormattingService.formatDocument(AsyncDocumentFormattingService.java:69)
	at com.intellij.formatting.service.AbstractDocumentFormattingService.formatRanges(AbstractDocumentFormattingService.java:67)
	at com.intellij.formatting.service.FormattingServiceUtil.formatRanges(FormattingServiceUtil.java:93)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:167)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:132)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:114)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$doReformat$5(ReformatCodeProcessor.java:196)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:149)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$doReformat$6(ReformatCodeProcessor.java:186)
	at com.intellij.openapi.editor.ex.util.EditorScrollingPositionKeeper.perform(EditorScrollingPositionKeeper.java:100)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.doReformat(ReformatCodeProcessor.java:186)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$2(ReformatCodeProcessor.java:134)
	at com.intellij.application.options.CodeStyle.doWithTemporarySettings(CodeStyle.java:338)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$3(ReformatCodeProcessor.java:130)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ProcessingTask.lambda$performFileProcessing$5(AbstractLayoutCodeProcessor.java:459)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:148)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:184)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:157)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:124)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ProcessingTask.lambda$performFileProcessing$6(AbstractLayoutCodeProcessor.java:459)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:95)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)


```

</details>
