### ISSUE TITLE
cargo check has no ability to specify target, and the build.rs throws an exception because the library can not be compiled for the default target

### ISSUE THREAD

**Issue by mutantbob** [intellij-rust/intellij-rust#8781]
## Environment

rust plugin 0.4.168.4555-221
cargo 1.60.0 (d1fd9fe 2022-03-01)
rust toolchain nightly-2021-01-07
IDEA 2022.1 CE
Linux herakleion 5.4.72-gentoo https://github.com/intellij-rust/intellij-rust/pull/1 SMP Fri Nov 13 19:51:13 EST 2020 x86_64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz GenuineIntel GNU/Linux

## Problem description

I have a library that wraps around Arduino C++ libraries.  It has a `build.rs` that uses bindgen.  `build.rs` will panic if invoked for an unknown target, and the list of known targets is quite short.

When intellij runs `cargo check --message-format json --workspace --all-targets`, it triggers a panic:

```
thread 'main' panicked at 'I do not know how to compile arduino libraries for TARGET=x86_64-unknown-linux-gnu', /home/thoth/.cargo/git/checkouts/rust-arduino-helpers-fafe45f17f4c9d7c/211d2a6/arduino-build-helpers/src/lib.rs:44:18
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
     2: arduino_build_helpers::ArduinoCompileFlags::new
               at /home/thoth/.cargo/git/checkouts/rust-arduino-helpers-fafe45f17f4c9d7c/211d2a6/arduino-build-helpers/src/lib.rs:44:18
     3: <bindgen::Builder as arduino_build_helpers::ArduinoBindgen>::rig_arduino_uno
               at /home/thoth/.cargo/git/checkouts/rust-arduino-helpers-fafe45f17f4c9d7c/211d2a6/arduino-build-helpers/src/lib.rs:135:37
     4: build_script_build::generate_bindings_rs
               at ./build.rs:48:20
     5: build_script_build::main
               at ./build.rs:66:5
     6: core::ops::function::FnOnce::call_once
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
```

Based on https://github.com/intellij-rust/intellij-rust/pull/3380 it seems there were options to deal with this in the past, but they might have been culled.

## Steps to reproduce

https://github.com/mutantbob/rust-arduino-wrappers contains a number of rust wrappers for Arduino libraries that trigger this problem.

The closest I can come to getting `cargo check` to succeed is
`cargo +nightly-2021-01-07 check -Z build-std=core -Z build-std-features=compiler-builtins-mangled-names  --workspace --all-targets --features atmega328p --target ~/src/rust-arduino-blink-3/avr-specs/avr-atmega328p.json`

There is still an error  caused by https://github.com/japaric/cty/issues/20 which will probably remain until https://github.com/japaric/cty/pull/21 or an equivalent gets merged.  This particular problem is fixed at the application layer in `Cargo.toml` with the following clause.
```
[patch.crates-io]
cty = { git="https://github.com/mutantbob/cty.git", branch="2022-Feb-avr" }
```
I have no idea how you would supply that to a `cargo check` of the library without the application.

**Comment by mutantbob** [comment]
I was poking around trying to figure out how to disable `cargo check` and came across the Languages&Frameworks > Rust > External Linters.  It appears I already customized this and forgot about it.

In Additional arguments I have supplied `-Z build-std=core -Z build-std-features=compiler-builtins-mangled-names --target $HOME/src/rust-arduino-blink-3/avr-specs/avr-atmega328p.json` , but evidently this is not supplied to the Build scripts evaluation.
