### ISSUE TITLE
IntelliSense no longer working for the standard library

### ISSUE THREAD

**Issue by Fryuni** [intellij-rust/intellij-rust#8782]
## Environment

* **Rust toolchain version:** 1.60.0 (stable as of 2022-04-22)
* **Operating system:** PopOS 21.10
* **IntelliJ Rust plugin version + IDE name and version:**
```text
GoLand 2022.1
Build #GO-221.5080.224, built on April 13, 2022
Licensed to Luiz Ferraz
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.16.19-76051619-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1962M
Cores: 12
Registry:
    suggest.all.run.configurations.from.context=true
    ide.completion.variant.limit=500

Non-Bundled Plugins:
    monokai-pro (1.8.1)
    com.intellij.nativeDebug (221.5080.218)
    org.rust.lang (0.4.168.4555-221)
    izhangzhihao.rainbow.brackets (6.21)

Current Desktop: pop:GNOME
```

## Problem description

It's been almost two months since I last opened a Rust project and there were lots of updates since then (both from the system, the IDE and the plugin). So I started a new project from scratch to reproduce the error.

There is no more code completion or any sort of IntelliSense or type information regarding the standard library

Even when the type is explicitly declared it shows `unknown` and has no autocompletion of the methods:
![image](https://user-images.githubusercontent.com/11063910/164814121-6f534b6a-6c12-4848-adfa-ec51de213a4c.png)
![image](https://user-images.githubusercontent.com/11063910/164814186-7fe1ca9b-e765-4295-a5da-50a3317682ba.png)

The code itself works:
![image](https://user-images.githubusercontent.com/11063910/164814072-0534ca14-7c00-4f26-81d3-617ae70a8273.png)

I noticed that the std library doesn't appear on the "External Libraries" anymore, I think it used to, not sure.

If the type is part of my code it works fine, notice that it recognizes `Foo`, but not `String`:
![image](https://user-images.githubusercontent.com/11063910/164814309-2af9b27c-1376-4812-b159-05032b2bb294.png)

My rust installation was made with rustup and I did include the `rust-src` component, in the settings is is being correctly recognized:
![image](https://user-images.githubusercontent.com/11063910/164814435-0caa5672-e292-4561-a990-d7098b093a4b.png)
And the stdlib source is there:
![image](https://user-images.githubusercontent.com/11063910/164814708-51991405-5d3e-44c2-98b6-d2d9354d45cf.png)

## Steps to reproduce

I just created a new project, no extra steps

**Comment by Fryuni** [comment]
I tried invalidating the caches and restarting as suggested on #6016 without success. Nothing seems to have changed

**Comment by vlad20012** [comment]
1. Could you please attach your IDE logs? You can do it by `Help` | `Collect Logs and Diagnostic Data`
2. Could you please take a look at the Cargo toolwindow (located at the right-hand side). There should be a list of Cargo projects (i.e. one "sample-test" project).
![image](https://user-images.githubusercontent.com/3221931/164886256-7128514f-bdc5-4f90-9406-6ec2f63641e0.png)

**Comment by Fryuni** [comment]
I never noticed that option on Help. I just went through the logs and found the problem:
```
2022-04-23 11:53:04,969 [  11966]   INFO - o.r.o.CommandLineExt - Executing `/opt/rust/bin/cargo +stable-x86_64-unknown-linux-gnu metadata --verbose --format-version 1 --all-features`
2022-04-23 11:53:05,079 [  12076] SEVERE - #o.r.c.p.w.StdlibDataFetcher - Execution failed (exit code 101).
/opt/rust/bin/cargo +stable-x86_64-unknown-linux-gnu metadata --verbose --format-version 1 --all-features
stdout :     Updating crates.io index
error: failed to write /opt/rust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/Cargo.lock

Caused by:
  failed to open: /opt/rust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/Cargo.lock

Caused by:
  Permission denied (os error 13)

stderr : 
org.rust.openapiext.RsProcessExecutionException$ProcessAborted: Execution failed (exit code 101).
/opt/rust/bin/cargo +stable-x86_64-unknown-linux-gnu metadata --verbose --format-version 1 --all-features
stdout :     Updating crates.io index
error: failed to write /opt/rust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/Cargo.lock

Caused by:
  failed to open: /opt/rust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/Cargo.lock

Caused by:
  Permission denied (os error 13)

stderr : 
	at org.rust.openapiext.CommandLineExtKt.execute(CommandLineExt.kt:112)
	at org.rust.openapiext.CommandLineExtKt.execute$default(CommandLineExt.kt:55)
	at org.rust.cargo.toolchain.tools.Cargo.execute(Cargo.kt:428)
	at org.rust.cargo.toolchain.tools.Cargo.execute$default(Cargo.kt:422)
	at org.rust.cargo.toolchain.tools.Cargo.fetchMetadata(Cargo.kt:168)
	at org.rust.cargo.project.workspace.StdlibDataFetcher.collectPackageMetadata(StandardLibrary.kt:298)
	at org.rust.cargo.project.workspace.StdlibDataFetcher.fetchStdlibData(StandardLibrary.kt:212)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib(StandardLibrary.kt:115)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib$default(StandardLibrary.kt:106)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromFile(StandardLibrary.kt:83)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromFile$default(StandardLibrary.kt:62)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.fetchStdlib(CargoSyncTask.kt:415)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$fetchStdlib(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:407)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:379)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:435)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$runWithChildProgress(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$SyncContext.runWithChildProgress(CargoSyncTask.kt:188)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.fetchStdlib(CargoSyncTask.kt:379)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$fetchStdlib(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:126)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:111)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:435)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress$default(CargoSyncTask.kt:426)
	at org.rust.cargo.project.model.impl.CargoSyncTask.doRun(CargoSyncTask.kt:111)
	at org.rust.cargo.project.model.impl.CargoSyncTask.run(CargoSyncTask.kt:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I thought I only needed _read_ access to the standard library source folder, but it also tries to write to the Cargo.lock file. I think there is a way to tell cargo to not write anything, but I'm not sure. If there isn't, there could be some visual indication that this is the problem.

Executing the cargo commands by hand to create the lock files and giving my user permission to write on those files fixed the problem 

Thanks for the help! 😄
