### ISSUE TITLE
Very slow code completion and syntax highlighting

### ISSUE THREAD

**Issue by TobiasDeBruijn** [intellij-rust/intellij-rust#8920]
## Environment

CLion is managed by snapd.

* **IntelliJ Rust plugin version:** 0.4.171.4656-221
* **Rust toolchain version:** 1.62.0-beta.2 (daf68b1f7 2022-05-19) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.1.2 (CL-221.5787.29)
* **Operating system:** Linux 5.15.0-33-generic
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
Code completion and syntax highlighting are quite slow (4-5 seconds wait time before dialog even opens). Problem only seems to appear on large repos. Problem appears with and without Cargo Check (on the fly).

CPU: Ryzen 9 5900X
Memory: 64GB at 3200Mhz
Project is stored on a WD Blue M.2 SSD. CLion has a max heap of 7GB. 

## Steps to reproduce
1. Clone the [project](https://github.com/MrFriendly-B-V/smartbathroom-server)
2. Open it in CLion
3. Observe code completion and syntax highlighting being slow (after indexing has finished)

**Comment by TobiasDeBruijn** [comment]
Autocompletion appears to be a little bit faster, though still taking 1-2 seconds. Syntax highlighting is worse though:
![image](https://user-images.githubusercontent.com/28569170/175272430-6e640119-c228-4ba6-a3eb-f2553f1432a8.png)

This is with CLion 2022.1.2 build CL-221.5787.29, Rust `1.62.0-beta.2`

**Comment by TobiasDeBruijn** [comment]
I've noticed something else, when a proc macro is applied to a function, syntax highlighting in that function becomes way slower, I think. In this case it's the `api_v2_operation` from the Paperclip crate

**Comment by vlad20012** [comment]
I've checked all rust files in the project. The highlighting speed seems perfect to me. The only exception is functions under proc macro attributes. I can't say it's acceptable, but, unfortunately, it's expected for now. I think that the most significant issue is that any code modification in any macro (including functions under a proc macro attribute) drops almost all in-memory caches.
Macro highlighting also has performance issues.

**Comment by TobiasDeBruijn** [comment]
That might explain why I've got such isuses primarily in the rest/ subcrate, as almost every function there has a proc macro on it.

**Comment by nickb937** [comment]
This seems to explain why I have a problem with performance too. Practically all functions in my project would have the proc macro #[instrument] to facilitate tracing.

**Comment by TobiasDeBruijn** [comment]
> This seems to explain why I have a problem with performance too. Practically all functions in my project would have the proc macro #[instrument] to facilitate tracing.

Yep this too

**Comment by vlad20012** [comment]
@nickb937
> This seems to explain why I have a problem with performance too. Practically all functions in my project would have the proc macro #[instrument] to facilitate tracing.

`#[instrument]` is specially hardcoded in IntelliJ Rust, so it shouldn't be counted as a proc macro. Your case seems to be something different

**Comment by ForsakenHarmony** [comment]
> I think that the most significant issue is that any code modification in any macro (including functions under a proc macro attribute) drops almost all in-memory caches.
> Macro highlighting also has performance issues.

Any chance you could add some (temporary) setting to ignore the contents of the functions to help with indexing?
I'm pretty sure it would be good enough for most proc macros because they generally only look at type signatures?

I think I'm seeing that exact issue, every single keystroke causes an indexing operation

**Comment by TobiasDeBruijn** [comment]
Another possible solution: Ignore the proc macro when it is applied to a function, for me that'd solve basically all problems, as the transformation done by the proc macro I've got issues with aren't useful to me, but only for Actix/Paperclip.

**Comment by vlad20012** [comment]
Hello! Could you please try the latest nightly IntelliJ Rust plugin (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly))

We just landed #8977 and #8978 which should help a bit with performance in the case of typing inside an attribute macro (and we also landed #8985, but it's about function-like macros).

Also, I'm working on #8986 that should finally fix your case and also should fix highlighting blinking during typing inside an attribute macro.

**Comment by TobiasDeBruijn** [comment]
The latest nightly (`0.4.174.4721-221-nightly`) feels **a lot** smoother. Whatever magic you pulled, it paid off.

It's not as smooth as functions without any attribute macros on them, but definitely miles better than what the latest stable can do! I'll await #8986, curious what that does for performance.

**Comment by nickb937** [comment]
Similarly, I have experienced a dramatic improvement in usability of the plugin. I'm no longer experiencing the periods of no syntax highlighting and previous code completion pop-ups have reduced in time to around 1.5 seconds, from over 5 seconds.

**Comment by luxalpa** [comment]
I am having this problem with a small code base (one file with about 500 lines) using `ash` and `winit` libraries. Turning off macro expansion speeds up auto complete significantly (even though I am not using any macros), memory usage on my system is quite small (749 of 2000M it says). Most other languages including Typescript (in IntelliJ and Webstorm) and Unreal C++ (in Rider) work fine on my system. It takes about 3~5 seconds (without macro expansion) to update the error checks. `cargo check` in the command line takes 0.09s.

Something is clearly wrong :/ My guess is that it doesn't cache library code (I think ash and winit are fairly big) and that's why it is so slow.

Would love to see some suggestion on how I can profile the performance of the plugin, because I would love to at least understand what it is that is making it so slow.

**Comment by luxalpa** [comment]
I had a look at the IDE CPU profile with the YourKit profiler which sort of seems to support my suspicion. If I understand the profile right (which I might not, I never used this tool before), it strongly looks like the bottle neck is that it takes a very long time (3000ms) for parsing the code. Considering this code is only 500 lines, that seems extremely weird, especially since I only touched a single file.

So to me this seems to suggest that it does not save any information about external libraries and instead parses and typechecks them over and over again.

Anyway, I might be wrong, so here's the profile: [CL-221.5921.27_Luxalpa_11.07.2022_12.55.25.zip](https://github.com/intellij-rust/intellij-rust/files/9083374/CL-221.5921.27_Luxalpa_11.07.2022_12.55.25.zip)

The context of this profile is me deleting the return type declaration on an empty function and then waiting until the red error marker disappears.

Turning this:

```rs
fn init(&mut self) -> Result<(), Box<dyn Error>> {}
```

into this:

```rs
fn init(&mut self) {}
```

**Comment by vlad20012** [comment]
@luxalpa Hello! Could you please try out today's release of the plugin (we released it just an hour ago)

**Comment by luxalpa** [comment]
@vlad20012 Thanks! I confirm this fixed the issue for me! :)

**Comment by ForsakenHarmony** [comment]
It has definitely gotten a lot better, thanks 🙏 

Any chance we'll get parameter/type hints in functions with a proc macro soon as well?

**Comment by TobiasDeBruijn** [comment]
Of course! I'll be able to tomorrow morning.

**Comment by ForsakenHarmony** [comment]
Hmm, I feel like the indexing problem has gotten worse again, but maybe I'm just misremembering

<details>
<summary>Also keep getting the error <code>com.intellij.psi.stubs.ManyProjectsStubIndexMismatch: PSI and index do not match.</code> now</summary>

```java
com.intellij.psi.stubs.ManyProjectsStubIndexMismatch: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=FILE, file.class=class org.rust.lang.core.psi.RsFile, file.lang=Language: Rust, modStamp=3
 tree consistent
 stub debugInfo=created in getStubTree(), with AST = false; with backReference
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=RsFileStub}1850729679
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=rust-macros:///rust_expanded_macros/feejmada/2848/4/e/4ea632692ce7fcbb65cd958448f43ce641271388_1_24.rs, vFileId=137237, content=VirtualFileContent{size=33}, eventSystemEnabled=true}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1658201468095; file length: 33
 doc saved: true; doc stamp: 0; doc size: 33; committed: false
indexing info: indexing timestamp = 1658201468095, binary = false, byte size = 33, char size = 0
	at com.intellij.psi.stubs.StubTreeLoader.handleManyProjectsMismatch(StubTreeLoader.java:140)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:65)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:193)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:141)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:215)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:734)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:937)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:118)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitAsynchronously$0(DocumentCommitThread.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.AssertionError: Stub count doesn't match stubbed node length
	at com.intellij.psi.impl.source.FileTrees.lambda$reconcilePsi$4(FileTrees.java:181)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:494)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:174)
	... 37 more
```

</details>

**Comment by TobiasDeBruijn** [comment]
> @TobiasDeBruijn We released #8986 just in today's nightly plugin, so could you please try it?
Apologies for the late reply. It's been a very busy weekend.

While I don't have exact measurements, it does feel a lot smoother and faster. I have seen an increase in memory usage reported by the IDE of about 0.5GB, but that's not much of an issue considering the performance improvements.

**Comment by vlad20012** [comment]
I think the issue can be closed. @TobiasDeBruijn thank you very much for your comments!

Btw all related changes has been landed in the yesterday's plugin release.

**Comment by ObjectAssign** [comment]
I bought another 16GB of ram because PHP storm + Sail/Docker were killing my machine... now it runs even slower, idk what the fk is up with this stupid ass ide... i really am considering ditching the crappy Java code editor and go back to WS code
