### ISSUE TITLE
MismatchedInputException occurred on project opening 

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#8939]
## Environment

* **IntelliJ Rust plugin version:** 0.4.173.4688-222-nightly
* **Rust toolchain version:** 1.63.0-nightly (50b00252a 2022-06-06) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.2 EAP (CL-222.2964.48)
* **Operating system:** macOS 11.5.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
`com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (END_OBJECT), expected FIELD_NAME
 at [Source: (BufferedReader); line: 1, column: 2]`

## Steps to reproduce
1. Open a rust project in IDE (CLion)
2. Invalidate cash -> ide is restarted and project is reopened 

## Actual Results
Error occured:
```
Error communicating with `intellij-rust-native-helper` process

com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (END_OBJECT), expected FIELD_NAME
 at [Source: (BufferedReader); line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1948)
	at com.fasterxml.jackson.databind.DeserializationContext.reportWrongTokenException(DeserializationContext.java:1691)
	at org.rust.util.RsJacksonDeserializer.wrongToken(RsJacksonDeserializer.kt:59)
	at org.rust.util.RsJacksonDeserializer.expectNextFieldName(RsJacksonDeserializer.kt:55)
	at org.rust.util.RsJacksonDeserializer.access$expectNextFieldName(RsJacksonDeserializer.kt:12)
	at org.rust.lang.core.macros.proc.ResponseJsonDeserializer.deserialize(Response.kt:46)
	at org.rust.lang.core.macros.proc.ResponseJsonDeserializer.deserialize(Response.kt:24)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3642)
	at org.rust.lang.core.macros.proc.ProcMacroServerProcess.writeAndRead(ProcMacroServerPool.kt:278)
	at org.rust.lang.core.macros.proc.ProcMacroServerProcess.run(ProcMacroServerPool.kt:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by vlad20012** [comment]
It looks like proc macro expansion does not work on nightly Rust for now

**Comment by vlad20012** [comment]
In you case this error means that you use `println!` in a proc macro, but this error can also mean that something went very wrong during the expansion. Currently it's impossible to reliably distinguish these cases, unfortunately
