### ISSUE TITLE
the plugin can not work with linux distribution offered rust toolchain.

### ISSUE THREAD

**Issue by abadcafe** [intellij-rust/intellij-rust#9002]
## Environment

* **IntelliJ Rust plugin version:** 0.4.173.4714-221
* **Rust toolchain version:** 1.62.0 (os package, not rustup)
* **IDE name and version:** clion 2022 1.3
* **Operating system:** archlinux

## Problem description
the plugin throws exception:

2022-07-03 10:28:12,965 [  23683] SEVERE - #o.r.c.p.w.StdlibDataFetcher - Plugin to blame: Rust version: 0.4.173.4714-221
2022-07-03 10:28:12,965 [  23683] SEVERE - #o.r.c.p.w.StdlibDataFetcher - OS: Linux
2022-07-03 10:28:12,965 [  23683] SEVERE - #o.r.c.p.w.StdlibDataFetcher - JDK: 11.0.15; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-07-03 10:28:12,964 [  23682] SEVERE - #o.r.c.p.w.StdlibDataFetcher - CLion 2022.1.3  Build #CL-221.5921.27
        at java.base/java.lang.Thread.run(Thread.java:829)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
        at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
        at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
        at org.rust.cargo.project.model.impl.CargoSyncTask.run(CargoSyncTask.kt:81)
        at org.rust.cargo.project.model.impl.CargoSyncTask.doRun(CargoSyncTask.kt:116)
        at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress$default(CargoSyncTask.kt:451)
        at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:460)
        at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:116)
        at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:131)
        at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$fetchStdlib(CargoSyncTask.kt:1)
        at org.rust.cargo.project.model.impl.CargoSyncTaskKt.fetchStdlib(CargoSyncTask.kt:404)
        at org.rust.cargo.project.model.impl.CargoSyncTask$SyncContext.runWithChildProgress(CargoSyncTask.kt:193)
        at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$runWithChildProgress(CargoSyncTask.kt:1)
        at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:460)
        at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:404)
        at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:424)
        at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromPath$default(StandardLibrary.kt:52)
        at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromPath(StandardLibrary.kt:59)
        at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromFile(StandardLibrary.kt:83)
        at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib$default(StandardLibrary.kt:106)
        at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib(StandardLibrary.kt:115)
        at org.rust.cargo.project.workspace.StdlibDataFetcher.fetchStdlibData(StandardLibrary.kt:212)
        at org.rust.cargo.project.workspace.StdlibDataFetcher.collectPackageMetadata(StandardLibrary.kt:298)
        at org.rust.cargo.toolchain.tools.Cargo.fetchMetadata(Cargo.kt:171)
        at org.rust.cargo.toolchain.tools.Cargo.execute$default(Cargo.kt:467)
        at org.rust.cargo.toolchain.tools.Cargo.execute(Cargo.kt:473)
        at org.rust.openapiext.CommandLineExtKt.execute$default(CommandLineExt.kt:55)
        at org.rust.openapiext.CommandLineExtKt.execute(CommandLineExt.kt:112)
stderr :
  Permission denied (os error 13)
Caused by:
  failed to open: /usr/lib/rustlib/src/rust/library/unwind/Cargo.lock
Caused by:
error: failed to write /usr/lib/rustlib/src/rust/library/unwind/Cargo.lock
stdout :     Updating crates.io index
/usr/bin/cargo metadata --verbose --format-version 1 --all-features
org.rust.openapiext.RsProcessExecutionException$ProcessAborted: Execution failed (exit code 101).
stderr :
  Permission denied (os error 13)
Caused by:
  failed to open: /usr/lib/rustlib/src/rust/library/unwind/Cargo.lock
Caused by:
error: failed to write /usr/lib/rustlib/src/rust/library/unwind/Cargo.lock
stdout :     Updating crates.io index
/usr/bin/cargo metadata --verbose --format-version 1 --all-features

## Steps to reproduce
just run clion and see journalctl -r -l.

**Comment by ortem** [comment]
@abadcafe Thanks for reporting. It is a known problem that the plugin is unable to work when the Rust toolchain was installed without `rustup`, because the plugin relies significantly on `rustup` to resolve certain file paths, versions, and so on. Moreover, alternative distributions are often incomplete or broken (for example, providing certain files without necessary permissions or wrongly located). So we strongly recommend installing Rust via `rustup`.

Related issues: #5315, #5363, 7912, #8213.

**Comment by abadcafe** [comment]
@ortem OK, I see it. But rust-analyzer works with distribution's toolchain quite well, maybe you can consider improve this case.
