### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by msiemens** [intellij-rust/intellij-rust#916]
Hey there,

I get a NullPointerException from the intellij-rust plugin:

```
null
java.lang.NullPointerException
	at org.rust.cargo.toolchain.impl.CargoMetadata.clean(CargoMetadata.kt:116)
	at org.rust.cargo.toolchain.Cargo.fullProjectDescription(Cargo.kt:52)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$UpdateTask.run(CargoProjectWorkspaceImpl.kt:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The error happens every time I open a Rust project in IntelliJ.

I'm using Rustup v1.0.0 and with an override setting the project's Rust version to 1.12.0 and Cargo 0.13.0-nightly (109cb7c 2016-08-19).

**Comment by msiemens** [comment]
Interestingly, it seems to work when updating cargo to a more recent version (simply replacing the binary), it works with cargo 0.16.0-nightly (3568be9 2016-11-26)

**Comment by matklad** [comment]
Yeah, we don't support that old cargo anymore. Although the error could be improved!

**Comment by matklad** [comment]
Fixed in https://github.com/intellij-rust/intellij-rust/commit/e3291076921103d76ef7e90a9635d7b25cae15f2, thanks for the report!
