### ISSUE TITLE
NPE on first run (MacOS)

### ISSUE THREAD

**Issue by mechkg** [intellij-rust/intellij-rust#918]
MacOS 10.12.2
Rust 1.12.1
Cargo 0.13.0

```
null
java.lang.NullPointerException
	at org.rust.cargo.toolchain.impl.CargoMetadata.clean(CargoMetadata.kt:116)
	at org.rust.cargo.toolchain.Cargo.fullProjectDescription(Cargo.kt:52)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$UpdateTask.run(CargoProjectWorkspaceImpl.kt:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mkaput** [comment]
Hi!

What version of Cargo do you use? Recently very similar issue was reported: #916

**Comment by matklad** [comment]
And will it be acceptable to you to just upgrade the Cargo? Or you need to work with an older one? Perhaps we should handle this more gracefully? cc @alygin

**Comment by matklad** [comment]
>What version of Cargo do you use?

It's from Rust 12.1, as is stated at the top of the issue ;)

**Comment by matklad** [comment]
cc #919

**Comment by mechkg** [comment]
Updating to a newer version or Cargo solves the issue.

**Comment by matklad** [comment]
@mechkg thanks! I think we'll close this issue then, and work out a more solid back compat strategy!

**Comment by alygin** [comment]
@matklad, I think you're right, we could make metadata parsing more robust.
I'm overburden a bit at work now, but I'll get back to this issue when time allows.

**Comment by matklad** [comment]
>we could make metadata parsing more robust.

I think there's no need to handle this specific case: so far nobody said that they are stuck with Rust 1.12.0, and reminders to upgrade Rust are actually good, the last couple of releases saw some sweet performance improvements!

But I think we can make a more general fix here: the underling problem is that after parsing with GSON some field is `null` (which is totally fine from Java's POW), but its Kotlin type is not nullable. So I think that we should make GSON to throw errors in such cases. Perhaps there are some annotations? I haven't work with GSON a lot myself.

**Comment by alygin** [comment]
As far as I remember, GSON doesn't support such validation.
Though, it supports the `@Since` attribute that makes transition between json versions smoother. Cargo emits the `version` property in the json output that we could leverage, but I'm not sure it's properly maintained. This question needs some investigation.

**Comment by matklad** [comment]
Yep, you are right :( https://github.com/google/gson/issues/61

**Comment by matklad** [comment]
We can also try https://github.com/yole/jkid instead of Gson.
