### ISSUE TITLE
Stuck on "Getting Rust stdlib"

### ISSUE THREAD

**Issue by pavel-cernohorsky** [intellij-rust/intellij-rust#9204]
## Environment

* **IntelliJ Rust plugin version:** 0.4.176.4815-222
* **Rust toolchain version:** rustc 1.63.0 (4b91a6ea7 2022-08-08), cargo 1.63.0 (fd9c4297c 2022-07-01)
* **IDE name and version and OS:** CL-222.3345.126, JRE 17.0.3+7-b469.32x64 JetBrains s.r.o., OS Linux(amd64) v5.15.52-gentoo, screens 1920.0x1080.0

## Steps to reproduce

After creating new Rust project from CLion (licensed), I get message saying "No Cargo projects found". There is an option to "Attach". When I do so and try to attach project's Cargo.toml, the process gets stuck on "Getting Rust stdlib". When I give up and cancel the process, I get following error messages:
```
2022-08-16 19:46:49,971 [1376242] SEVERE - #o.r.c.p.w.StdlibDataFetcher - Execution failed (exit code 137).
/home/pavel/Dokumenty/Programování/Rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo metadata --verbose --format-version 1 --all-features
stdout :     Updating crates.io index

stderr : 
org.rust.openapiext.RsProcessExecutionException$Canceled: Execution failed (exit code 137).
/home/pavel/Dokumenty/Programování/Rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo metadata --verbose --format-version 1 --all-features
stdout :     Updating crates.io index

stderr : 
	at org.rust.openapiext.CommandLineExtKt.execute(CommandLineExt.kt:110)
	at org.rust.openapiext.CommandLineExtKt.execute$default(CommandLineExt.kt:55)
	at org.rust.cargo.toolchain.tools.Cargo.execute(Cargo.kt:474)
	at org.rust.cargo.toolchain.tools.Cargo.execute$default(Cargo.kt:468)
	at org.rust.cargo.toolchain.tools.Cargo.fetchMetadata(Cargo.kt:171)
	at org.rust.cargo.project.workspace.StdlibDataFetcher.collectPackageMetadata(StandardLibrary.kt:298)
	at org.rust.cargo.project.workspace.StdlibDataFetcher.fetchStdlibData(StandardLibrary.kt:201)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib(StandardLibrary.kt:115)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib$default(StandardLibrary.kt:106)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromFile(StandardLibrary.kt:83)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromPath(StandardLibrary.kt:59)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromPath$default(StandardLibrary.kt:52)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:424)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:404)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:460)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$runWithChildProgress(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$SyncContext.runWithChildProgress(CargoSyncTask.kt:193)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.fetchStdlib(CargoSyncTask.kt:404)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$fetchStdlib(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:131)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:116)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:460)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress$default(CargoSyncTask.kt:451)
	at org.rust.cargo.project.model.impl.CargoSyncTask.doRun(CargoSyncTask.kt:116)
	at org.rust.cargo.project.model.impl.CargoSyncTask.run(CargoSyncTask.kt:81)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-08-16 19:46:49,973 [1376244] SEVERE - #o.r.c.p.w.StdlibDataFetcher - CLion 2022.2  Build #CL-222.3345.126
2022-08-16 19:46:49,974 [1376245] SEVERE - #o.r.c.p.w.StdlibDataFetcher - JDK: 17.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-08-16 19:46:49,974 [1376245] SEVERE - #o.r.c.p.w.StdlibDataFetcher - OS: Linux
2022-08-16 19:46:49,974 [1376245] SEVERE - #o.r.c.p.w.StdlibDataFetcher - Plugin to blame: Rust version: 0.4.176.4815-222
2022-08-16 19:46:49,976 [1376247] SEVERE - #o.r.c.p.w.StandardLibrary - null
java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged: ignore for explicitly started processes or rethrow to handle on the outer process level
	at com.intellij.openapi.diagnostic.Logger.ensureNotControlFlow(Logger.java:264)
	at com.intellij.idea.IdeaLogger.doLogError(IdeaLogger.java:151)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:142)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:210)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib(StandardLibrary.kt:119)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib$default(StandardLibrary.kt:106)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromFile(StandardLibrary.kt:83)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromPath(StandardLibrary.kt:59)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fromPath$default(StandardLibrary.kt:52)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:424)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt$fetchStdlib$1.invoke(CargoSyncTask.kt:404)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:460)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$runWithChildProgress(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$SyncContext.runWithChildProgress(CargoSyncTask.kt:193)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.fetchStdlib(CargoSyncTask.kt:404)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.access$fetchStdlib(CargoSyncTask.kt:1)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:131)
	at org.rust.cargo.project.model.impl.CargoSyncTask$doRun$refreshedProjects$1$2.invoke(CargoSyncTask.kt:116)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress(CargoSyncTask.kt:460)
	at org.rust.cargo.project.model.impl.CargoSyncTaskKt.runWithChildProgress$default(CargoSyncTask.kt:451)
	at org.rust.cargo.project.model.impl.CargoSyncTask.doRun(CargoSyncTask.kt:116)
	at org.rust.cargo.project.model.impl.CargoSyncTask.run(CargoSyncTask.kt:81)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:157)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:147)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:103)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.checkCancelledEvenWithPCEDisabled(ProgressIndicatorUtils.java:407)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:359)
	at com.intellij.openapi.vfs.DiskQueryRelay.accessDiskWithCheckCanceled(DiskQueryRelay.java:52)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.getAttributes(LocalFileSystemBase.java:754)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getChildData(PersistentFSImpl.java:1633)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.lambda$findChildInfo$4(PersistentFSImpl.java:421)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.update(FSRecords.java:349)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findChildInfo(PersistentFSImpl.java:453)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findInPersistence(VirtualDirectoryImpl.java:150)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:132)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:78)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:538)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:45)
	at com.intellij.openapi.vfs.VirtualFile.findFileByRelativePath(VirtualFile.java:384)
	at org.rust.cargo.project.workspace.StandardLibraryKt.findFirstFileByRelativePaths(StandardLibrary.kt:402)
	at org.rust.cargo.project.workspace.StandardLibraryKt.access$findFirstFileByRelativePaths(StandardLibrary.kt:1)
	at org.rust.cargo.project.workspace.StdlibDataFetcher.fetchStdlibData(StandardLibrary.kt:207)
	at org.rust.cargo.project.workspace.StandardLibrary$Companion.fetchActualStdlib(StandardLibrary.kt:115)
	... 37 more

```
but when I try to manually execute the command mentioned above, I normally get result without any problems:
```
pavel@anita ~/Dokumenty/Programování/deleteme $ /home/pavel/Dokumenty/Programování/Rust/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo metadata --verbose --format-version 1 --all-features
{"packages":[{"name":"deleteme","version":"0.1.0","id":"deleteme 0.1.0 (path+file:///home/pavel/Dokumenty/Programov%C3%A1n%C3%AD/deleteme)","license":null,"license_file":null,"description":null,"source":null,"dependencies":[],"targets":[{"kind":["bin"],"crate_types":["bin"],"name":"deleteme","src_path":"/home/pavel/Dokumenty/Programování/deleteme/src/main.rs","edition":"2021","doc":true,"doctest":false,"test":true}],"features":{},"manifest_path":"/home/pavel/Dokumenty/Programování/deleteme/Cargo.toml","metadata":null,"publish":null,"authors":[],"categories":[],"keywords":[],"readme":null,"repository":null,"homepage":null,"documentation":null,"edition":"2021","links":null,"default_run":null,"rust_version":null}],"workspace_members":["deleteme 0.1.0 (path+file:///home/pavel/Dokumenty/Programov%C3%A1n%C3%AD/deleteme)"],"resolve":{"nodes":[{"id":"deleteme 0.1.0 (path+file:///home/pavel/Dokumenty/Programov%C3%A1n%C3%AD/deleteme)","dependencies":[],"deps":[],"features":[]}],"root":"deleteme 0.1.0 (path+file:///home/pavel/Dokumenty/Programov%C3%A1n%C3%AD/deleteme)"},"target_directory":"/home/pavel/Dokumenty/Programování/deleteme/target","version":1,"workspace_root":"/home/pavel/Dokumenty/Programování/deleteme","metadata":null}
```

**Comment by ssh352** [comment]
waiting a few minutes fixed it.

**Comment by ningmingxiao** [comment]
> waiting a few minutes fixed it.
If use it offline, it will show folow error
```
Download failed: rustup failed: `info: downloading component 'rust-src'
info: retrying download for 'https://static.rust-lang.org/dist/2023-08-24/rust-src-1.72.0.tar.xz'
info: retrying download for 'https://static.rust-lang.org/dist/2023-08-24/rust-src-1.72.0.tar.xz'
info: retrying download for 'https://static.rust-lang.org/dist/2023-08-24/rust-src-1.72.0.tar.xz'
info: retrying download for 'https://static.rust-lang.org/dist/2023-08-24/rust-src-1.72.0.tar.xz'
error: component download failed for rust-src: could not download file from 'https://static.rust-lang.org/dist/2023-08-24/rust-src-1.72.0.tar.xz' to '/root/.rustup/downloads/b21a44e3cb46a73d2e2d0441a92c401396d4ba6e11d798e5adec4d3b8fc423e6.partial'
`
```
