### ISSUE TITLE
NPE when loading Rust project

### ISSUE THREAD

**Issue by stephanstross** [intellij-rust/intellij-rust#921]
I have IntelliJ IDE, and every time I load a cargo project with it, I get the following error:
`null
java.lang.NullPointerException
	at org.rust.cargo.toolchain.impl.CargoMetadata.clean(CargoMetadata.kt:116)
	at org.rust.cargo.toolchain.Cargo.fullProjectDescription(Cargo.kt:52)
	at org.rust.cargo.project.workspace.impl.CargoProjectWorkspaceImpl$UpdateTask.run(CargoProjectWorkspaceImpl.kt:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

And, I've noticed as this error has occurred, it has also stopped any sort of autocompletion from modules outside of the one I'm working on (Such as looking at the methods on &str, for exaample)

**Comment by matklad** [comment]
Yep, this is a known issue! You need to update your Cargo version! Or is it not convenient for you?

Sorry for the NPE: the next release will have a somewhat better error message :)

**Comment by stephanstross** [comment]
Yup, that's fixed it. Thanks!
