### ISSUE TITLE
Syntax highlighting issues with macro expansion

### ISSUE THREAD

**Issue by HolgerGottChristensen** [intellij-rust/intellij-rust#9291]
## Environment

* **IntelliJ Rust plugin version:** 0.4.178.4851-222-nightly
* **Rust toolchain version:** 1.62.0 (a8314ef7d 2022-06-27) aarch64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.2.1 Ultimate Edition (IU-222.3739.54)
* **Operating system:** macOS 12.4
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
This issue is written as a follow up of: https://github.com/intellij-rust/intellij-rust/issues/8966#issuecomment-1230092324 
and the corresponding fix: https://github.com/intellij-rust/intellij-rust/pull/9280#issue-1357657160

The issue is about highlighting in files using proc-macros. 
It seems to affect versions after 0.4.167.

As written in the comment linked above it, syntax highlighting fails in some, but not all files.

The fix above fixed the syntax highlighting for the specific file mentioned in the comment above, but it seems the hot fix does not fix the whole issue.

An example of a file that fails is:
carbide_core/src/widget/clip.rs

<img width="802" alt="Screenshot 2022-09-02 at 22 07 32" src="https://user-images.githubusercontent.com/11473146/188230238-a2efee0a-a994-474a-b5f8-b5f22327ca2d.png">

## Steps to reproduce
1. Clone the repository https://github.com/HolgerGottChristensen/carbide
2. Locate the file: carbide_core/src/widget/clip.rs

When you open the file it will say "Analyzing" but it does not finish, and the highlighting is broken as in the screenshot above.

Some of the syntax highlighting shows up after 1-2min, but most of the file is still not highlighted.

**Comment by HolgerGottChristensen** [comment]
It seems like after another restart of IntelliJ, after the restart forced by plugin installation, there was no problem anymore.

**Comment by HolgerGottChristensen** [comment]
After more investigation, the syntax highlighting works in most cases now, but one example of a case where it fails, is:
carbide/examples/syntax.rs

At the start of the file is a pretty advanced function like proc macro.
In version 0.4.167 the highlighting look like this:
<img width="794" alt="Screenshot 2022-09-02 at 23 06 30" src="https://user-images.githubusercontent.com/11473146/188235258-f9658b34-71f6-46a9-94fe-46838fb347ca.png">

and sometimes behaved a bit funky(in 0.4.167):
https://user-images.githubusercontent.com/11473146/188235498-53f980f6-a3e8-4a0a-8121-c1dcc2ac88e4.mov

and in 0.4.178 it looks like this:
<img width="845" alt="Screenshot 2022-09-02 at 22 57 17" src="https://user-images.githubusercontent.com/11473146/188234212-e3532e3c-8b85-4089-bd2e-2d5dbb62fe88.png">

This also seems to break syntax highlighting in a declarative macro below.
In version 0.4.167 the highlighting look like this:
<img width="663" alt="Screenshot 2022-09-02 at 23 05 31" src="https://user-images.githubusercontent.com/11473146/188235140-50c18e83-3dc7-45aa-9eec-e75a420dc361.png">


and in 0.4.178 looks like this, when the proc macro above in the file is not commented out.
<img width="695" alt="Screenshot 2022-09-02 at 23 02 16" src="https://user-images.githubusercontent.com/11473146/188234775-49ba1e4a-f256-496a-b91a-1b5704a58a0e.png">


When the proc macro is commented out, and (optionally) re-added to the file it keeps the correct highlighting:
<img width="701" alt="Screenshot 2022-09-02 at 23 00 05" src="https://user-images.githubusercontent.com/11473146/188234504-24312bc6-4e63-4cf1-9b98-3e99be497960.png">

**Comment by mili-l** [comment]
<details>

<summary> Exception </summary>

```
java.lang.ClassCastException
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor164.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:672)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:357)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:293)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:268)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$5(InspectionRunner.java:121)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:226)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:109)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:131)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassCastException: class com.intellij.testFramework.LightVirtualFile cannot be cast to class com.intellij.openapi.vfs.VirtualFileWithId (com.intellij.testFramework.LightVirtualFile and com.intellij.openapi.vfs.VirtualFileWithId are in unnamed module of loader com.intellij.util.lang.PathClassLoader @6979e8cb)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getFileId(PersistentFSImpl.java:377)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.readAttribute(PersistentFSImpl.java:269)
	at com.intellij.openapi.vfs.newvfs.FileAttribute.readFileAttribute(FileAttribute.java:66)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readSavedIndexingStampInfo(StubTreeLoaderImpl.java:308)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.getIndexingStampInfo(StubTreeLoaderImpl.java:277)
	at com.intellij.psi.stubs.StubTreeLoader.lambda$stubTreeAndIndexDoNotMatch$0(StubTreeLoader.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:65)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:193)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:141)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:215)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:734)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:128)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getFirstChild(ASTDelegatePsiElement.java:99)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:46)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:28)
	at com.intellij.util.WalkingState.next(WalkingState.java:70)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:58)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:76)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at org.rust.openapiext.RsWithMacrosRecursiveElementWalkingVisitor.visitElement(psi.kt:117)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.rust.lang.core.psi.impl.RsImplItemImpl.accept(RsImplItemImpl.java:33)
	at org.rust.openapiext.RsWithMacrosRecursiveElementWalkingVisitor.processMacro(psi.kt:144)
	at org.rust.openapiext.RsWithMacrosRecursiveElementWalkingVisitor.tryProcessDeriveProcMacro(psi.kt:158)
	at org.rust.openapiext.RsWithMacrosRecursiveElementWalkingVisitor.visitElement(psi.kt:119)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.rust.lang.core.psi.impl.RsStructItemImpl.accept(RsStructItemImpl.java:33)
	at org.rust.openapiext.RsWithMacrosRecursiveElementWalkingVisitor.processMacro(psi.kt:144)
	at org.rust.openapiext.RsWithMacrosRecursiveElementWalkingVisitor.visitElement(psi.kt:115)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.rust.lang.core.psi.impl.RsMacroCallImpl.accept(RsMacroCallImpl.java:33)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:67)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:24)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:62)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:76)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at org.rust.openapiext.RsWithMacrosRecursiveElementWalkingVisitor.visitElement(psi.kt:117)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.rust.lang.core.psi.impl.RsFunctionImpl.accept(RsFunctionImpl.java:33)
	at org.rust.openapiext.PsiKt.processElementsWithMacros(psi.kt:95)
	at org.rust.ide.inspections.lints.RsPathUsageAnalysisKt.handleSubtree(RsPathUsageAnalysis.kt:72)
	at org.rust.ide.inspections.lints.RsPathUsageAnalysisKt.calculatePathUsages(RsPathUsageAnalysis.kt:66)
	at org.rust.ide.inspections.lints.RsPathUsageAnalysisKt._get_pathUsage_$lambda-0(RsPathUsageAnalysis.kt:55)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.rust.ide.inspections.lints.RsPathUsageAnalysisKt.getPathUsage(RsPathUsageAnalysis.kt:54)
	at org.rust.ide.inspections.lints.RsUnusedImportInspection$buildVisitor$1.visitUseItem(RsUnusedImportInspection.kt:48)
	at org.rust.lang.core.psi.impl.RsUseItemImpl.accept(RsUseItemImpl.java:27)
	at org.rust.lang.core.psi.impl.RsUseItemImpl.accept(RsUseItemImpl.java:32)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:317)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:325)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:331)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:159)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:151)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:294)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:294)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:297)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:282)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:270)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	... 5 more

```

</details>

**Comment by ForsakenHarmony** [comment]
Having similar issues with whole files losing highlighting and the only way to fix it is reindexing + reopening the project

Also,intermittently having issues with std code no longer being properly resolved when there's a proc macro error (I think) leading to CLion telling me `&str` doesn't implement `Display`

Didn't have this issue in the past, wondering if it could be related to #9176
