### ISSUE TITLE
Failed to expand the macro: internal error: expansion file not found, but cache has valid expansion

### ISSUE THREAD

**Issue by ForsakenHarmony** [intellij-rust/intellij-rust#9539]
## Environment

* **IntelliJ Rust plugin version:** 0.4.181.4939-223-nightly
* **Rust toolchain version:** 1.66.0-nightly (e7119a030 2022-09-22) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2022.3 EAP (CL-223.6646.99)
* **Operating system:** Windows 10 10.0
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.emulate.terminal, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
Proc macro expansion (and highlighting anything inside the macro) stops working and manually expanding I get the error `Failed to expand the macro: internal error: expansion file not found, but cache has valid expansion`

Using the `Re-Expand All Rust Macros` actions also doesn't do anything. I have to re-open the project.

I get this error
<details>
<summary>Error Stacktrace</summary>

```java
In file: file://something/in/my/project.rs

com.intellij.psi.PsiInvalidElementAccessException: Element: class org.rust.lang.core.psi.RsFile
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:121)
	at com.intellij.psi.PsiInvalidElementAccessException.getPsiInvalidationTrace(PsiInvalidElementAccessException.java:98)
	at com.intellij.psi.PsiInvalidElementAccessException.<init>(PsiInvalidElementAccessException.java:61)
	at com.intellij.psi.PsiInvalidElementAccessException.<init>(PsiInvalidElementAccessException.java:33)
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:483)
	at org.rust.lang.core.resolve.ref.RsResolveCacheKt.ensureValidPsi(RsResolveCache.kt:316)
	at org.rust.lang.core.resolve.ref.RsResolveCacheKt.ensureValidResult(RsResolveCache.kt:300)
	at org.rust.lang.core.resolve.ref.RsResolveCacheKt.ensureValidResults(RsResolveCache.kt:311)
	at org.rust.lang.core.resolve.ref.RsResolveCacheKt.ensureValidResult(RsResolveCache.kt:302)
	at org.rust.lang.core.resolve.ref.RsResolveCacheKt.access$ensureValidResult(RsResolveCache.kt:1)
	at org.rust.lang.core.resolve.ref.RsResolveCache.resolveWithCaching(RsResolveCache.kt:97)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$Companion.resolveAllNestedPathsInternal(RsPathReferenceImpl.kt:271)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$Companion.resolveAllNestedPaths(RsPathReferenceImpl.kt:276)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.advancedResolve(RsPathReferenceImpl.kt:87)
	at org.rust.lang.core.psi.ext.RsTraitRefKt.resolveToBoundTrait(RsTraitRef.kt:16)
	at org.rust.lang.core.resolve.RsCachedImplItem$implementedTrait$2.invoke(RsCachedImplItem.kt:48)
	at org.rust.lang.core.resolve.RsCachedImplItem$implementedTrait$2.invoke(RsCachedImplItem.kt:48)
	at com.intellij.util.RecursionPreventingSafePublicationLazy$initializer$1.invoke(RecursionPreventingSafePublicationLazy.kt:13)
	at com.intellij.util.RecursionPreventingSafePublicationLazy._get_value_$lambda-0(RecursionPreventingSafePublicationLazy.kt:31)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.util.RecursionPreventingSafePublicationLazy.getValue(RecursionPreventingSafePublicationLazy.kt:31)
	at org.rust.lang.core.resolve.RsCachedImplItem.getImplementedTrait(RsCachedImplItem.kt:48)
	at org.rust.lang.core.resolve.ImplLookup.trySelectCandidate(ImplLookup.kt:804)
	at org.rust.lang.core.resolve.ImplLookup.assembleImplCandidatesWithoutAliases(ImplLookup.kt:798)
	at org.rust.lang.core.resolve.ImplLookup.access$assembleImplCandidatesWithoutAliases(ImplLookup.kt:234)
	at org.rust.lang.core.resolve.ImplLookup$assembleCandidatesFromImpls$2.invoke(ImplLookup.kt:791)
	at org.rust.lang.core.resolve.ImplLookup$assembleCandidatesFromImpls$2.invoke(ImplLookup.kt:790)
	at org.rust.lang.core.resolve.ImplLookup.processTyFingerprintsWithAliases(ImplLookup.kt:370)
	at org.rust.lang.core.resolve.ImplLookup.assembleCandidatesFromImpls(ImplLookup.kt:790)
	at org.rust.lang.core.resolve.ImplLookup.assembleCandidatesFromImpls(ImplLookup.kt:783)
	at org.rust.lang.core.resolve.ImplLookup.assembleCandidates(ImplLookup.kt:655)
	at org.rust.lang.core.resolve.ImplLookup.selectCandidate(ImplLookup.kt:483)
	at org.rust.lang.core.resolve.ImplLookup.selectWithoutConfirm(ImplLookup.kt:470)
	at org.rust.lang.core.resolve.ImplLookup.select(ImplLookup.kt:451)
	at org.rust.lang.core.resolve.ImplLookup.select(ImplLookup.kt:442)
	at org.rust.lang.core.resolve.ImplLookup.selectProjection(ImplLookup.kt:1147)
	at org.rust.lang.core.resolve.ImplLookup.selectProjection$default(ImplLookup.kt:1142)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.lookupRawFutureOutputTy(TypeInferenceWalker.kt:1519)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.lookupFutureOutputTy(TypeInferenceWalker.kt:1511)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferFieldExprType(TypeInferenceWalker.kt:883)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferDotExprType(TypeInferenceWalker.kt:914)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:188)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType$default(TypeInferenceWalker.kt:170)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferTryExprType(TypeInferenceWalker.kt:1170)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:198)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.processStatement(TypeInferenceWalker.kt:149)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:117)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferTypeCoercableTo(TypeInferenceWalker.kt:111)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferFnBody(TypeInferenceWalker.kt:106)
	at org.rust.lang.core.types.infer.RsInferenceContext.infer(TypeInference.kt:214)
	at org.rust.lang.core.types.infer.TypeInferenceKt.inferTypesIn$lambda$0(TypeInference.kt:40)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at org.rust.openapiext.UtilsKt.recursionGuard(utils.kt:94)
	at org.rust.lang.core.types.infer.TypeInferenceKt.inferTypesIn(TypeInference.kt:40)
	at org.rust.lang.core.types.ExtensionsKt._get_inference_$lambda$0(Extensions.kt:111)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:110)
	at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:117)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.rawMultiResolveUsingInferenceCache(RsPathReferenceImpl.kt:117)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.rawMultiResolve(RsPathReferenceImpl.kt:113)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl.resolve(RsPathReferenceImpl.kt:98)
	at org.rust.ide.annotator.RsHighlightingAnnotator.highlightReference(RsHighlightingAnnotator.kt:130)
	at org.rust.ide.annotator.RsHighlightingAnnotator.highlightIdentifier(RsHighlightingAnnotator.kt:85)
	at org.rust.ide.annotator.RsHighlightingAnnotator.highlightLeaf(RsHighlightingAnnotator.kt:55)
	at org.rust.ide.annotator.RsHighlightingAnnotator.annotateInternal(RsHighlightingAnnotator.kt:32)
	at org.rust.ide.annotator.AnnotatorBase.annotate(AnnotatorBase.kt:21)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:344)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:304)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:307)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:222)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:396)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:372)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:370)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
</details>

## Steps to reproduce

Don't know exactly yet, but very similar to #9417

**Comment by vlad20012** [comment]
Could you please attach your IDE logs? Maybe I can find more errors there. You can collect logs by `Help` | `Collect Logs and Diagnostic Data`

**Comment by vlad20012** [comment]
Oh I think I know what's wrong
