### ISSUE TITLE
StackOverflowError in type inference and resolve in `diesel` crate

### ISSUE THREAD

**Issue by dima74** [intellij-rust/intellij-rust#9565]
## Environment

* **IntelliJ Rust plugin version:** 0.4.182.SNAPSHOT-222-dev
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-unknown-linux-gnu
* **IDE name and version:** IntelliJ IDEA 2022.2.2 Ultimate Edition (IU-222.4167.29)
* **Operating system:** Linux 6.0.1-zen2-1-zen
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal

## Problem description

<details>

```kotlin
java.lang.StackOverflowError
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:163)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.isReadLockedByThisThread(ReadMostlyRWLock.java:89)
	at com.intellij.openapi.application.impl.ApplicationImpl.isReadAccessAllowed(ApplicationImpl.java:1087)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1055)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:184)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:621)
	at com.intellij.psi.impl.source.SpineRef.getStub(SpineRef.java:32)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getStub(StubBasedPsiElementBase.java:340)
	at com.intellij.psi.util.PsiTreeUtil.getStubChildrenOfTypeAsList(PsiTreeUtil.java:450)
	at org.rust.lang.core.psi.ext.RsTypeParameterListKt.getGenericParameters(RsTypeParameterList.kt:47)
	at org.rust.lang.core.psi.ext.RsGenericDeclarationKt.getGenericParameters(RsGenericDeclaration.kt:27)
	at org.rust.lang.core.psi.ext.RsGenericDeclarationKt.getGenericParameters$default(RsGenericDeclaration.kt:23)
	at org.rust.lang.core.types.infer.TyLowering.instantiatePathGenerics(TyLowering.kt:193)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:149)
	at org.rust.lang.core.types.infer.TyLowering.instantiatePathGenerics(TyLowering.kt:212)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:65)
	at org.rust.lang.core.types.infer.TyLowering.instantiatePathGenerics(TyLowering.kt:212)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:65)
	at org.rust.lang.core.types.infer.TyLowering.instantiatePathGenerics(TyLowering.kt:212)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:65)
	at org.rust.lang.core.types.infer.TyLowering.access$lowerTy(TyLowering.kt:38)
	at org.rust.lang.core.types.infer.TyLowering$Companion.lowerTypeReference(TyLowering.kt:276)
	at org.rust.lang.core.types.ExtensionsKt.getRawType(Extensions.kt:74)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt$pathPsiSubst$typeOrConstSubst$1.invoke(RsPathReferenceImpl.kt:379)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt$pathPsiSubst$typeOrConstSubst$1.invoke(RsPathReferenceImpl.kt:372)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt.associateSubst(RsPathReferenceImpl.kt:475)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt.pathPsiSubst(RsPathReferenceImpl.kt:372)
	at org.rust.lang.core.types.infer.TyLowering.instantiatePathGenerics(TyLowering.kt:194)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:149)
	at org.rust.lang.core.types.infer.TyLowering.instantiatePathGenerics(TyLowering.kt:212)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:65)
	at org.rust.lang.core.types.infer.TyLowering.instantiatePathGenerics(TyLowering.kt:212)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:65)
	at org.rust.lang.core.types.infer.TyLowering.instantiatePathGenerics(TyLowering.kt:212)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:65)
	at org.rust.lang.core.types.infer.TyLowering.access$lowerTy(TyLowering.kt:38)
	at org.rust.lang.core.types.infer.TyLowering$Companion.lowerTypeReference(TyLowering.kt:276)
	at org.rust.lang.core.types.ExtensionsKt.getRawType(Extensions.kt:74)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt$pathPsiSubst$typeOrConstSubst$1.invoke(RsPathReferenceImpl.kt:379)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt$pathPsiSubst$typeOrConstSubst$1.invoke(RsPathReferenceImpl.kt:372)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt.associateSubst(RsPathReferenceImpl.kt:475)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt.pathPsiSubst(RsPathReferenceImpl.kt:372)
	at org.rust.lang.core.types.infer.TyLowering.instantiatePathGenerics(TyLowering.kt:194)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:149)
	at org.rust.lang.core.types.infer.TyLowering.instantiatePathGenerics(TyLowering.kt:212)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:65)
	at org.rust.lang.core.types.infer.TyLowering.instantiatePathGenerics(TyLowering.kt:212)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:65)
	at org.rust.lang.core.types.infer.TyLowering.instantiatePathGenerics(TyLowering.kt:212)
	at org.rust.lang.core.types.infer.TyLowering.lowerTy(TyLowering.kt:65)
	at org.rust.lang.core.types.infer.TyLowering.access$lowerTy(TyLowering.kt:38)
	at org.rust.lang.core.types.infer.TyLowering$Companion.lowerTypeReference(TyLowering.kt:276)
	at org.rust.lang.core.types.ExtensionsKt.getRawType(Extensions.kt:74)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt$pathPsiSubst$typeOrConstSubst$1.invoke(RsPathReferenceImpl.kt:379)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt$pathPsiSubst$typeOrConstSubst$1.invoke(RsPathReferenceImpl.kt:372)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt.associateSubst(RsPathReferenceImpl.kt:475)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImplKt.pathPsiSubst(RsPathReferenceImpl.kt:372)
```

</details>

## Steps to reproduce
* 
  ```
  git clone https://github.com/diesel-rs/diesel
  git checkout 5dc6b2a9e681c2bf0880b9b75c84edd784e8f221
  ```

* Open `diesel/src/query_builder/select_statement/boxed.rs`

**Comment by vlad20012** [comment]
Minimal example:

```rust
trait Foo<T = ()> {}
trait Bar {}
fn foo<T>() where dyn Foo: Bar {}
```
