### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Sequence doesn't contain element at index 0

### ISSUE THREAD

**Issue by mili-l** [intellij-rust/intellij-rust#9655]
## Environment

* **IntelliJ Rust plugin version:** 0.4.183.4982-223-nightly
* **Rust toolchain version:** 1.64.0 x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2022.3 EAP Ultimate Edition (IU-223.7126.7)
* **Operating system:** macOS 12.6
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal, org.rust.macros.proc.function-like, org.rust.macros.proc

## Problem description
```
java.lang.IndexOutOfBoundsException: Sequence doesn't contain element at index 0.
	at kotlin.sequences.SequencesKt___SequencesKt$elementAt$1.invoke(_Sequences.kt:35)
	at kotlin.sequences.SequencesKt___SequencesKt$elementAt$1.invoke(_Sequences.kt:35)
	at kotlin.sequences.SequencesKt___SequencesKt.elementAtOrElse(_Sequences.kt:55)
	at kotlin.sequences.SequencesKt___SequencesKt.elementAt(_Sequences.kt:35)
	at org.rust.lang.core.resolve2.FacadeResolveKt.findItemWithMacroIndex(FacadeResolve.kt:323)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.findMacroCall-sVsatjs(MacroExpansionManager.kt:788)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.doGetExpandedFromForExpansionFile(MacroExpansionManager.kt:758)
```

## Steps to reproduce
1. Open [file](https://github.com/apache/arrow-rs/blob/f812d2cda1379933fca22d9979e3df5be19792fa/arrow/src/compute/kernels/comparison.rs) 

=> Exception occured

<details>

<summary>Exception</summary>

```
java.lang.IndexOutOfBoundsException: Sequence doesn't contain element at index 0.
	at kotlin.sequences.SequencesKt___SequencesKt$elementAt$1.invoke(_Sequences.kt:35)
	at kotlin.sequences.SequencesKt___SequencesKt$elementAt$1.invoke(_Sequences.kt:35)
	at kotlin.sequences.SequencesKt___SequencesKt.elementAtOrElse(_Sequences.kt:55)
	at kotlin.sequences.SequencesKt___SequencesKt.elementAt(_Sequences.kt:35)
	at org.rust.lang.core.resolve2.FacadeResolveKt.findItemWithMacroIndex(FacadeResolve.kt:323)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.findMacroCall-sVsatjs(MacroExpansionManager.kt:788)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.doGetExpandedFromForExpansionFile(MacroExpansionManager.kt:758)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.getExpandedFrom$lambda$1(MacroExpansionManager.kt:747)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.getExpandedFrom(MacroExpansionManager.kt:745)
	at org.rust.lang.core.macros.MacroExpansionManagerImpl.getExpandedFrom(MacroExpansionManager.kt:238)
	at org.rust.lang.core.macros.RsExpandedElementKt.getExpandedFrom(RsExpandedElement.kt:70)
	at org.rust.lang.core.macros.RsExpandedElementKt.getExpandedOrIncludedFrom(RsExpandedElement.kt:96)
	at org.rust.lang.core.resolve2.FacadeResolveKt.getMacroIndex(FacadeResolve.kt:279)
	at org.rust.lang.core.resolve2.FacadeResolveKt.getMacroIndex(FacadeResolve.kt:281)
	at org.rust.lang.core.resolve2.FacadeResolveKt.getMacroIndex(FacadeResolve.kt:281)
	at org.rust.lang.core.resolve2.FacadeResolveKt.getMacroIndex(FacadeResolve.kt:281)
	at org.rust.lang.core.resolve2.FacadeResolveKt.getMacroIndex(FacadeResolve.kt:281)
	at org.rust.lang.core.resolve2.FacadeResolveKt.getMacroIndex(FacadeResolve.kt:281)
	at org.rust.lang.core.resolve2.FacadeResolveKt.getMacroIndex(FacadeResolve.kt:281)
	at org.rust.lang.core.resolve2.FacadeResolveKt.getMacroIndex(FacadeResolve.kt:281)
	at org.rust.lang.core.resolve2.FacadeResolveKt.getMacroIndex(FacadeResolve.kt:281)
	at org.rust.lang.core.macros.MacroExpansionServiceImplInner.getExpansionFor(MacroExpansionManager.kt:726)
	at org.rust.lang.core.macros.MacroExpansionManagerImpl.getExpansionFor(MacroExpansionManager.kt:213)
	at org.rust.lang.core.psi.ext.RsPossibleMacroCallKt._get_expansionResult_$lambda$16(RsPossibleMacroCall.kt:428)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.rust.lang.core.psi.ext.RsPossibleMacroCallKt.getExpansionResult(RsPossibleMacroCall.kt:422)
	at org.rust.lang.core.psi.ext.RsPossibleMacroCallKt.getExpansion(RsPossibleMacroCall.kt:418)
	at org.rust.lang.core.resolve2.HangingModDataKt.createDollarCrateHelper(HangingModData.kt:133)
	at org.rust.lang.core.resolve2.HangingModDataKt.createHangingModData(HangingModData.kt:109)
	at org.rust.lang.core.resolve2.HangingModDataKt.access$createHangingModData(HangingModData.kt:1)
	at org.rust.lang.core.resolve2.HangingModDataKt$getHangingModInfo$hangingModData$1.invoke(HangingModData.kt:61)
	at org.rust.lang.core.resolve2.HangingModDataKt$getHangingModInfo$hangingModData$1.invoke(HangingModData.kt:60)
	at org.rust.openapiext.UtilsKt.getCachedOrCompute(utils.kt:443)
	at org.rust.lang.core.resolve2.HangingModDataKt.getHangingModInfo(HangingModData.kt:60)
	at org.rust.lang.core.resolve2.HangingModDataKt.getHangingModInfo(HangingModData.kt:46)
	at org.rust.lang.core.resolve2.FacadeResolveKt.getModInfo(FacadeResolve.kt:409)
	at org.rust.lang.core.resolve2.FacadeResolveKt.processItemDeclarations(FacadeResolve.kt:44)
	at org.rust.lang.core.resolve.NameResolutionKt.processLexicalDeclarations(NameResolution.kt:1625)
	at org.rust.lang.core.resolve.NameResolutionKt.access$processLexicalDeclarations(NameResolution.kt:1)
	at org.rust.lang.core.resolve.NameResolutionKt$processNestedScopesUpwards$2.invoke(NameResolution.kt:1696)
	at org.rust.lang.core.resolve.NameResolutionKt$processNestedScopesUpwards$2.invoke(NameResolution.kt:1692)
	at org.rust.lang.core.resolve.NameResolutionKt.walkUp(NameResolution.kt:1833)
	at org.rust.lang.core.resolve.NameResolutionKt.walkUp$default(NameResolution.kt:1823)
	at org.rust.lang.core.resolve.NameResolutionKt.processNestedScopesUpwards(NameResolution.kt:1692)
	at org.rust.lang.core.resolve.NameResolutionKt.processPathResolveVariants(NameResolution.kt:351)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$Resolver$invoke$4.invoke(RsPathReferenceImpl.kt:194)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$Resolver$invoke$4.invoke(RsPathReferenceImpl.kt:193)
	at org.rust.lang.core.resolve.ProcessorsKt.collectMultiplePathResolveVariants(Processors.kt:121)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$Resolver.invoke(RsPathReferenceImpl.kt:193)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$Resolver.invoke(RsPathReferenceImpl.kt:171)
	at org.rust.lang.core.resolve.ref.RsResolveCache.resolveWithCaching$lambda$1$lambda$0(RsResolveCache.kt:96)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at org.rust.lang.core.resolve.ref.RsResolveCache.resolveWithCaching(RsResolveCache.kt:96)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$Companion.resolveAllNestedPathsInternal(RsPathReferenceImpl.kt:271)
	at org.rust.lang.core.resolve.ref.RsPathReferenceImpl$Companion.resolveAllNestedPaths(RsPathReferenceImpl.kt:276)
	at org.rust.lang.core.types.infer.TyLowering$Companion.lowerTypeReference(TyLowering.kt:272)
	at org.rust.lang.core.types.ExtensionsKt.getRawType(Extensions.kt:75)
	at org.rust.lang.core.resolve.RsCachedImplItem$typeAndGenerics$2.invoke(RsCachedImplItem.kt:50)
	at org.rust.lang.core.resolve.RsCachedImplItem$typeAndGenerics$2.invoke(RsCachedImplItem.kt:49)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.rust.lang.core.resolve.RsCachedImplItem.getTypeAndGenerics(RsCachedImplItem.kt:49)
	at org.rust.lang.core.resolve.ImplLookup.findExplicitImplsWithoutAliases(ImplLookup.kt:344)
	at org.rust.lang.core.resolve.ImplLookup.access$findExplicitImplsWithoutAliases(ImplLookup.kt:234)
	at org.rust.lang.core.resolve.ImplLookup$findExplicitImpls$1.invoke(ImplLookup.kt:336)
	at org.rust.lang.core.resolve.ImplLookup$findExplicitImpls$1.invoke(ImplLookup.kt:335)
	at org.rust.lang.core.resolve.ImplLookup.processTyFingerprintsWithAliases(ImplLookup.kt:357)
	at org.rust.lang.core.resolve.ImplLookup.findExplicitImpls(ImplLookup.kt:335)
	at org.rust.lang.core.resolve.ImplLookup.rawFindImplsAndTraits(ImplLookup.kt:315)
	at org.rust.lang.core.resolve.ImplLookup.findImplsAndTraits(ImplLookup.kt:273)
	at org.rust.lang.core.resolve.NameResolutionKt.processAssociatedItems(NameResolution.kt:1408)
	at org.rust.lang.core.resolve.NameResolutionKt.processMethodDeclarationsWithDeref(NameResolution.kt:1378)
	at org.rust.lang.core.resolve.NameResolutionKt.processMethodCallExprResolveVariants(NameResolution.kt:155)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImplKt$resolveMethodCallReferenceWithReceiverType$1.invoke(RsMethodCallReferenceImpl.kt:55)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImplKt$resolveMethodCallReferenceWithReceiverType$1.invoke(RsMethodCallReferenceImpl.kt:54)
	at org.rust.lang.core.resolve.ProcessorsKt.collectResolveVariantsAsScopeEntries(Processors.kt:189)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImplKt.resolveMethodCallReferenceWithReceiverType(RsMethodCallReferenceImpl.kt:54)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferMethodCallExprType(TypeInferenceWalker.kt:659)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferDotExprType(TypeInferenceWalker.kt:915)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:189)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.processStatement(TypeInferenceWalker.kt:150)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:118)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferTypeCoercableTo(TypeInferenceWalker.kt:112)
	at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferFnBody(TypeInferenceWalker.kt:107)
	at org.rust.lang.core.types.infer.RsInferenceContext.infer(TypeInference.kt:214)
	at org.rust.lang.core.types.infer.TypeInferenceKt.inferTypesIn$lambda$0(TypeInference.kt:40)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at org.rust.openapiext.UtilsKt.recursionGuard(utils.kt:94)
	at org.rust.lang.core.types.infer.TypeInferenceKt.inferTypesIn(TypeInference.kt:40)
	at org.rust.lang.core.types.ExtensionsKt._get_inference_$lambda$0(Extensions.kt:112)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:231)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:41)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:231)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:232)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:111)
	at org.rust.lang.core.types.ExtensionsKt.getInference(Extensions.kt:126)
	at org.rust.lang.core.resolve.ref.RsMethodCallReferenceImpl.multiResolve(RsMethodCallReferenceImpl.kt:26)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.multiResolve(RsReferenceBase.kt:30)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:47)
	at org.rust.lang.core.resolve.ref.RsReferenceBase.resolve(RsReferenceBase.kt:27)
	at org.rust.ide.lineMarkers.RsRecursiveCallLineMarkerProvider.isRecursive(RsRecursiveCallLineMarkerProvider.kt:58)
	at org.rust.ide.lineMarkers.RsRecursiveCallLineMarkerProvider.collectSlowLineMarkers(RsRecursiveCallLineMarkerProvider.kt:33)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:222)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:112)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:98)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:396)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:372)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:370)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

</details>

**Comment by vlad20012** [comment]
Duplicate #9533
