### ISSUE TITLE
`Add definition to trait` quick-fix throws `IncorrectOperationException`

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#9693]
## Environment

* **IntelliJ Rust plugin version:** 0.4.183.4994-223-nightly
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.3 EAP (CL-223.7401.10)
* **Operating system:** macOS 11.1
* **Macro expansion:** enabled

## Problem description
`AddDefinitionToTraitFix` introduced in #7134 tries to modify the PSI without using `WriteCommandAction`, which leads to the exception:
```
com.intellij.util.IncorrectOperationException: Must not change PSI outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
	at com.intellij.pom.core.impl.PomModelImpl.startTransaction(PomModelImpl.java:270)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:226)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:234)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:234)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:225)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:93)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:142)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:579)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:673)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:53)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.addInternal(ASTDelegatePsiElement.java:306)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.addAfter(ASTDelegatePsiElement.java:293)
	at org.rust.ide.inspections.fixes.AddDefinitionToTraitFix.invoke(AddDefinitionToTraitFix.kt:42)
        ...
```

## Steps to reproduce
```Rust
struct MyStruct;

trait MyTrait {
    fn foo() {}
}

impl MyTrait for MyStruct {
    fn foo() {}
    
    fn bar() {} // Invoke `Add definition to trait` quick-fix
}
```

**Comment by dima74** [comment]
This is related to intention preview (#9561)
