### ISSUE TITLE
Unable to save settings:  Failed to save settings.  Please restart PyCharm

### ISSUE THREAD

**Issue by RomHartmann** [intellij-rust/intellij-rust#974]
Almost identical to https://github.com/intellij-rust/intellij-rust/issues/297, and also [here on SO](http://stackoverflow.com/questions/37511590/pycharm-unable-to-save-settings-failed-to-save-settings-please-restart-pych)

My idea.log:  
Started from fresh, then reapplied the same settings I always have to (but with many INFOs removed):

```
2017-01-30 14:35:29,997 [   1232]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2017-01-30 14:35:30,022 [   1257]   INFO -        #com.intellij.idea.Main - IDE: PyCharm (build #PY-143.2371.1, 18 Oct 2016 00:00) 
2017-01-30 14:35:30,022 [   1257]   INFO -        #com.intellij.idea.Main - OS: Linux (4.4.0-59-generic, amd64) 
2017-01-30 14:35:30,023 [   1258]   INFO -        #com.intellij.idea.Main - JRE: 1.8.0_101-b13 (Oracle Corporation) 
2017-01-30 14:35:30,023 [   1258]   INFO -        #com.intellij.idea.Main - JVM: 25.101-b13 (Java HotSpot(TM) 64-Bit Server VM) 
2017-01-30 14:35:30,038 [   1273]   INFO -        #com.intellij.idea.Main - JVM Args: -Xbootclasspath/a:/home/roman/ProgramFiles/pycharm/bin/../lib/boot.jar -Xms128m -Xmx750m -XX:MaxPermSize=350m -XX:ReservedCodeCacheSize=240m -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Dawt.useSystemAAFontSettings=lcd -Djb.vmOptionsFile=/home/roman/ProgramFiles/pycharm/bin/pycharm64.vmoptions -XX:ErrorFile=/home/roman/java_error_in_PYCHARM_%p.log -Djb.restart.code=88 -Didea.paths.selector=PyCharm50 -Didea.platform.prefix=Python -Didea.no.jre.check=true 
2017-01-30 14:35:30,038 [   1273]   INFO -        #com.intellij.idea.Main - ext: /usr/lib/jvm/java-8-oracle/jre/lib/ext: [jfxrt.jar, sunec.jar, sunpkcs11.jar, meta-index, jaccess.jar, dnsns.jar, nashorn.jar, sunjce_provider.jar, cldrdata.jar, zipfs.jar, localedata.jar] 
2017-01-30 14:35:30,124 [   1359]   INFO -        #com.intellij.idea.Main - JNA library loaded (64-bit) in 85 ms 
2017-01-30 14:35:32,109 [   3344]   INFO - .intellij.idea.IdeaApplication - WM detected: Compiz 
2017-01-30 14:35:33,549 [   4784]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor plugin-intelliLang.xml 
2017-01-30 14:35:33,754 [   4989]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor uml-java-support.xml 
2017-01-30 14:35:33,856 [   5091]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor uml-properties-support.xml 
2017-01-30 14:35:34,522 [   5757]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor js-nashorn-support.xml 
2017-01-30 14:35:35,524 [   6759]   INFO - llij.ide.plugins.PluginManager - 52 plugins initialized in 2418 ms 
2017-01-30 14:35:35,525 [   6760]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: AngularJS (999.999), CSS Support (143.SNAPSHOT), CVS Integration (11), CoffeeScript (2.0), Concurrency Visualiser (0.1), Database Tools and SQL (1.0), Django Database Support Integration (1.0), Docker for Python (0.1), EditorConfig (1.0), File Watchers (999.999), GNU GetText files support (*.po) (136.SNAPSHOT), Gherkin (999.999), Git Integration (8.1), GitHub (143.2371.1), HAML (143.SNAPSHOT), HTML Tools (2.0), IDEA CORE (143.SNAPSHOT), IPython Notebook (0.1), Ini4Idea (999.999), IntelliLang (8.0), JavaScript Debugger (1.0), JavaScript Intention Power Pack (0.9.4), JavaScript Support (1.0), LESS support (143.SNAPSHOT), Perforce Integration (2.0), Puppet Support (VERSION), Python BDD support for engines, based on Gherkin (cucumber, lettuce, behave) (0.1), Python IntelliLang (VERSION), Python JavaScript Debugger Integration (VERSION), Python Localization Integration (VERSION), Python Profiler (0.1), Python ReStructureText Integration (1.0), Python Remote Interpreter (VERSION), Python UML Diagrams (VERSION), REST Client (143.SNAPSHOT), ReStructuredText Support (136.SNAPSHOT), Remote Hosts Access (0.1), SASS support (143.SNAPSHOT), SSH Remote Run (0.1), Stylus support (999.999), Subversion Integration (1.1), Task Management (1.0), Terminal (0.1), TextMate bundles support (VERSION), UML Support (1.0), Vagrant (0.6.VERSION), hg4idea (10.0) 
2017-01-30 14:35:35,526 [   6761]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: .ignore (1.6), BashSupport (1.5.8.143), Docker integration (1.7.6), LaTeX (0.2), Markdown support (2016.1.20160405.143) 
2017-01-30 14:35:38,540 [   9775]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=500; buffer=10; max=739246080 
2017-01-30 14:35:38,874 [  10109]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: /home/roman/ProgramFiles/pycharm/bin/fsnotifier64 
2017-01-30 14:35:38,890 [  10125]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2017-01-30 14:35:46,055 [  17290]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2017-01-30 14:35:59,918 [  31153]   INFO - plication.impl.ApplicationImpl - 80 application components initialized in 26814 ms 
2017-01-30 14:35:59,950 [  31185]   INFO - .intellij.idea.IdeaApplication - App initialization took 39301 ms 
2017-01-30 14:36:01,117 [  32352]   INFO - ellij.concurrency.JobScheduler - 50 ms execution limit failed for: com.intellij.a.g.a.a$b@2c175e50; elapsed time was 57ms 
2017-01-30 14:36:07,918 [  39153]   INFO - ellij.project.impl.ProjectImpl - 115 project components initialized in 5772 ms 
2017-01-30 14:36:09,279 [  40514]   INFO - le.impl.ModuleManagerComponent - 12 module(s) loaded in 1360 ms 
...
2017-01-30 14:39:10,658 [ 221893]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: editor for id: editor.preferences.import 
..
2017-01-30 14:44:04,814 [ 516049]  ERROR - rationStore.ComponentStoreImpl - String index out of range: 0 
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.intellij.configurationStore.ApplicationStorageManager.expandMacros(ApplicationStoreImpl.kt:108)
	at com.intellij.configurationStore.StateStorageManagerImpl.createStateStorage(StateStorageManagerImpl.kt:194)
	at com.intellij.configurationStore.StateStorageManagerImpl.getOrCreateStorage(StateStorageManagerImpl.kt:150)
	at com.intellij.configurationStore.StateStorageManagerImpl.getStateStorage(StateStorageManagerImpl.kt:133)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:269)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:237)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
	at org.intellij.plugins.markdown.settings.MarkdownApplicationSettings.getInstance(MarkdownApplicationSettings.java:39)
	at org.intellij.plugins.markdown.ui.preview.MarkdownPreviewFileEditor.<init>(MarkdownPreviewFileEditor.java:96)
	at org.intellij.plugins.markdown.ui.preview.MarkdownPreviewFileEditorProvider.createEditor(MarkdownPreviewFileEditorProvider.java:23)
	at org.intellij.plugins.markdown.ui.split.SplitTextEditorProvider$2.build(SplitTextEditorProvider.java:139)
	at org.intellij.plugins.markdown.ui.split.SplitTextEditorProvider$1.build(SplitTextEditorProvider.java:64)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13.run(FileEditorManagerImpl.java:873)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2382)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:855)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:789)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$10.run(FileEditorManagerImpl.java:769)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:117)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:766)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:707)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:151)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$16.run(FileEditorManagerImpl.java:1143)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditor(FileEditorManagerImpl.java:1139)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInAnyFileEditor(OpenFileDescriptor.java:146)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditor(OpenFileDescriptor.java:132)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditorOrNativeApp(OpenFileDescriptor.java:128)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:115)
	at com.intellij.psi.impl.source.PsiFileImpl.navigate(PsiFileImpl.java:958)
	at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:179)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:207)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:217)
	at com.intellij.ide.projectView.impl.nodes.PsiFileNode.navigate(PsiFileNode.java:132)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:53)
	at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:31)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:130)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:122)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:410)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2017-01-30 14:44:04,841 [ 516076]  ERROR - rationStore.ComponentStoreImpl - PyCharm 5.0.6  Build #PY-143.2371.1 
2017-01-30 14:44:04,841 [ 516076]  ERROR - rationStore.ComponentStoreImpl - JDK: 1.8.0_101 
2017-01-30 14:44:04,841 [ 516076]  ERROR - rationStore.ComponentStoreImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
2017-01-30 14:44:04,842 [ 516077]  ERROR - rationStore.ComponentStoreImpl - Vendor: Oracle Corporation 
2017-01-30 14:44:04,842 [ 516077]  ERROR - rationStore.ComponentStoreImpl - OS: Linux 
2017-01-30 14:44:04,842 [ 516077]  ERROR - rationStore.ComponentStoreImpl - Current Command:  
2017-01-30 14:44:18,450 [ 529685]   WARN - mponents.impl.stores.StoreUtil - Save settings failed 
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.intellij.configurationStore.ApplicationStorageManager.expandMacros(ApplicationStoreImpl.kt:108)
	at com.intellij.configurationStore.StateStorageManagerImpl.createStateStorage(StateStorageManagerImpl.kt:194)
	at com.intellij.configurationStore.StateStorageManagerImpl.getOrCreateStorage(StateStorageManagerImpl.kt:150)
	at com.intellij.configurationStore.StateStorageManagerImpl.getStateStorage(StateStorageManagerImpl.kt:133)
	at com.intellij.configurationStore.StateStorageManagerImpl$startExternalization$1.setState(StateStorageManagerImpl.kt:342)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:199)
	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:124)
	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl.saveSettings(ApplicationImpl.java:1433)
	at com.intellij.ide.SaveAndSyncHandlerImpl.doSaveDocumentsAndProjectsAndApp(SaveAndSyncHandlerImpl.java:150)
	at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:134)
	at com.intellij.ide.SaveAndSyncHandlerImpl$4.onFrameDeactivated(SaveAndSyncHandlerImpl.java:104)
	at com.intellij.ide.FrameStateManagerImpl.a(FrameStateManagerImpl.java:87)
	at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:32)
	at com.intellij.ide.FrameStateManagerImpl$2$1.run(FrameStateManagerImpl.java:72)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2017-01-30 14:45:31,551 [ 602786]   INFO - ellij.concurrency.JobScheduler - 50 ms execution limit failed for: com.intellij.ide.a.f.C$c@7f9729fd; elapsed time was 120ms 
```

**Comment by matklad** [comment]
Hm, do you have the Rust language plugin installed? It's not listed in the "Loaded custom plugins".

**Comment by RomHartmann** [comment]
Nope.  I don't use Rust.

**Comment by matklad** [comment]
This is the issue tracker for the Rust plugin (btw, check the Rust out, it's an awesome language :) ). Given the stack trace, I think the problem is caused by the `Markdown` plugin. Could you open the issue on the PyCharm issue tracker https://youtrack.jetbrains.com/issues/PY ?

**Comment by RomHartmann** [comment]
Oh, my bad!  I just followed a trail here from the similar issue I linked.  Apologies, and thanks for your time

**Comment by RomHartmann** [comment]
Ha!  You were right!  Uninstalled it and it went away.  Thanks!

**Comment by matklad** [comment]
Glad to here that!
