### ISSUE TITLE
 Cannot download debugger in IDEA #IU-223.8617.9 - 404 error

### ISSUE THREAD

**Issue by Miuler** [intellij-rust/intellij-rust#9994]
# Environment

* IntelliJ Rust plugin version: 0.4.186.5143-223
* Rust toolchain version: rustc 1.66.1 (90743e729 2023-01-10)
* IDE name and version:  Build #IU-223.8617.9, built on January 11, 2023
* Operating system: **ArchLinux**

# Problem description

It looks like https://github.com/intellij-rust/intellij-rust/issues/5921 was reintroduced with the most recent release. The logs show the following when I attempt to install the Rust debugger:

```
  2023-01-17 09:25:30,330 [60568127]   WARN - #org.rust.debugger.RsDebuggerToolchainService - Can't download debugger
  java.io.IOException: Failed to download 'https://cache-redirector.jetbrains.com/intellij-dependencies/org/jetbrains/intellij/deps/cidr/lldb/023ca6547ee9a966c05e195ee9e3b7927bd28d36/lldb-023ca6547ee9a966c05e195ee9e3b7927bd28d36-linux-x64.tar.gz':
  Request failed with status code 404
      at com.intellij.util.download.impl.FileDownloaderImpl.lambda$download$1(FileDownloaderImpl.java:233)
      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
      at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
      at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
      at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
      at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
      at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
      at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
      at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
      at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
      at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 404. Status=404, Url=https://cache-redirector.jetbrains.com/intellij-dependencies/org/jetbrains/intellij/deps/cidr/lldb/023ca6547ee9a966c05e195ee9e3b7927bd2
  8d36/lldb-023ca6547ee9a966c05e195ee9e3b7927bd28d36-linux-x64.tar.gz
      at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:657)
      at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:635)
      at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:360)
      at com.intellij.util.download.impl.FileDownloaderImpl$2.process(FileDownloaderImpl.java:336)
      at com.intellij.util.download.impl.FileDownloaderImpl$2.process(FileDownloaderImpl.java:333)
      at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
      at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
      at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:334)
      at com.intellij.util.download.impl.FileDownloaderImpl.downloadFile(FileDownloaderImpl.java:333)
      at com.intellij.util.download.impl.FileDownloaderImpl.lambda$download$1(FileDownloaderImpl.java:230)
      ... 13 more
```

# Steps to reproduce

    Attempt to run a Rust unit test with the debugger.
    IntelliJ prompts to download the debugger
    Clicking "Download" results in the error above.

**Comment by neonaot** [comment]
Hi! 
This problem should be fixed now, missed files were uploaded. 
Updating of IDE or Rust plugin is not required.
